jubatus_core: jubatus::core::driver::recommender Class Reference
jubatus::core::driver::recommender Class Reference
#include <recommender.hpp>
Public Member Functions
float calc_l2norm (const fv_converter::datum &q)
float calc_similality (const fv_converter::datum &l, const fv_converter::datum &r)
void clear ()
void clear_row (const std::string &id)
fv_converter::datum complete_row_from_datum (const fv_converter::datum &dat)
fv_converter::datum complete_row_from_id (const std::string &id)
fv_converter::datum decode_row (const std::string &id)
std::vector< std::string > get_all_rows ()
void pack (framework::packer &pk) const
recommender (jubatus::util::lang::shared_ptr< core::recommender::recommender_base > method, jubatus::util::lang::shared_ptr< fv_converter::datum_to_fv_converter > converter)
std::vector< std::pair< std::string, float > > similar_row_from_datum (const fv_converter::datum &data, size_t size)
std::vector< std::pair< std::string, float > > similar_row_from_id (const std::string &id, size_t ret_num)
void unpack (msgpack::object o)
void update_row (const std::string &id, const fv_converter::datum &dat)
virtual ~recommender ()
Public Member Functions inherited from jubatus::core::driver::driver_base
driver_base ()
virtual framework::mixable * get_mixable ()
std::vector< storage::version > get_versions () const
virtual ~driver_base ()
Private Attributes
jubatus::util::lang::shared_ptr< fv_converter::datum_to_fv_converter > converter_
jubatus::util::lang::shared_ptr< core::recommender::recommender_base > recommender_
fv_converter::mixable_weight_manager wm_
Additional Inherited Members
Protected Member Functions inherited from jubatus::core::driver::driver_base
void register_mixable (framework::mixable *mixable)
Protected Attributes inherited from jubatus::core::driver::driver_base
mixable_holder holder_
Detailed Description
Definition at line 42 of file recommender.hpp.
Constructor & Destructor Documentation
jubatus::core::driver::recommender::recommender (jubatus::util::lang::shared_ptr< core::recommender::recommender_base > method, jubatus::util::lang::shared_ptr< fv_converter::datum_to_fv_converter > converter)
Definition at line 44 of file recommender.cpp.
References converter_, jubatus::core::framework::linear_mixable_helper< Model, Diff >::get_model(), recommender_, jubatus::core::driver::driver_base::register_mixable(), and wm_.
     : converter_(converter),
       recommender_(recommender_method),
       wm_(mixable_weight_manager::model_ptr(new weight_manager)) {
   register_mixable(recommender_->get_mixable());
   register_mixable(&wm_);
   converter_->set_weight_manager(wm_.get_model());
 }
jubatus::core::driver::recommender::~recommender () virtual
Definition at line 56 of file recommender.cpp.
{
 }
Member Function Documentation
float jubatus::core::driver::recommender::calc_l2norm (const fv_converter::datum & q)
Definition at line 125 of file recommender.cpp.
References jubatus::core::recommender::recommender_base::calc_l2norm(), and converter_.
{
   common::sfv_t v0;
   converter_->convert(q, v0);
   return jubatus::core::recommender::recommender_base::calc_l2norm(v0);
 }
float jubatus::core::driver::recommender::calc_similality (const fv_converter::datum & l, const fv_converter::datum & r)
Definition at line 116 of file recommender.cpp.
References jubatus::core::recommender::recommender_base::calc_similality(), and converter_.
{
   common::sfv_t v0, v1;
   converter_->convert(l, v0);
   converter_->convert(r, v1);
   return jubatus::core::recommender::recommender_base::calc_similality(v0, v1);
 }
void jubatus::core::driver::recommender::clear () virtual
Implements jubatus::core::driver::driver_base.
Definition at line 71 of file recommender.cpp.
References converter_, and recommender_.
{
   recommender_->clear();
   converter_->clear_weights();
 }
void jubatus::core::driver::recommender::clear_row (const std::string & id)
Definition at line 59 of file recommender.cpp.
References recommender_.
{
   recommender_->clear_row(id);
 }
fv_converter::datum jubatus::core::driver::recommender::complete_row_from_datum (const fv_converter::datum & dat)
Definition at line 85 of file recommender.cpp.
References converter_, recommender_, jubatus::core::fv_converter::revert_feature(), and jubatus::core::common::jsonconfig::v().
{
   common::sfv_t u, v;
   converter_->convert(dat, u);
   recommender_->complete_row(u, v);
   fv_converter::datum ret;
   fv_converter::revert_feature(v, ret);
   return ret;
 }
fv_converter::datum jubatus::core::driver::recommender::complete_row_from_id (const std::string & id)
Definition at line 76 of file recommender.cpp.
References recommender_, jubatus::core::fv_converter::revert_feature(), and jubatus::core::common::jsonconfig::v().
{
   common::sfv_t v;
   recommender_->complete_row(id, v);
   fv_converter::datum ret;
   fv_converter::revert_feature(v, ret);
   return ret;
 }
fv_converter::datum jubatus::core::driver::recommender::decode_row (const std::string & id)
Definition at line 131 of file recommender.cpp.
References recommender_, jubatus::core::fv_converter::revert_feature(), and jubatus::core::common::jsonconfig::v().
{
   common::sfv_t v;
   recommender_->decode_row(id, v);
   fv_converter::datum ret;
   fv_converter::revert_feature(v, ret);
   return ret;
 }
std::vector< std::string > jubatus::core::driver::recommender::get_all_rows ()
Definition at line 140 of file recommender.cpp.
References recommender_.
{
   std::vector<std::string> ret;
   recommender_->get_all_row_ids(ret);
   return ret;
 }
void jubatus::core::driver::recommender::pack (framework::packer & pk) const virtual
Implements jubatus::core::driver::driver_base.
Definition at line 146 of file recommender.cpp.
References jubatus::core::framework::linear_mixable_helper< Model, Diff >::get_model(), recommender_, and wm_.
{
   pk.pack_array(2);
   recommender_->pack(pk);
   wm_.get_model()->pack(pk);
 }
std::vector< std::pair< std::string, float > > jubatus::core::driver::recommender::similar_row_from_datum (const fv_converter::datum & data, size_t size)
Definition at line 105 of file recommender.cpp.
References converter_, recommender_, and jubatus::core::common::jsonconfig::v().
                  {
   common::sfv_t v;
   converter_->convert(data, v);
   std::vector<std::pair<std::string, float> > ret;
   recommender_->similar_row(v, ret, size);
   return ret;
 }
std::vector< std::pair< std::string, float > > jubatus::core::driver::recommender::similar_row_from_id (const std::string & id, size_t ret_num)
Definition at line 96 of file recommender.cpp.
References recommender_.
                     {
   std::vector<std::pair<std::string, float> > ret;
   recommender_->similar_row(id, ret, ret_num);
   return ret;
 }
void jubatus::core::driver::recommender::unpack (msgpack::object o) virtual
Implements jubatus::core::driver::driver_base.
Definition at line 152 of file recommender.cpp.
References converter_, jubatus::core::framework::linear_mixable_helper< Model, Diff >::get_model(), recommender_, and wm_.
{
   if (o.type != msgpack::type::ARRAY || o.via.array.size != 2) {
     throw msgpack::type_error();
   }
   // clear before load
   recommender_->clear();
   converter_->clear_weights();
   recommender_->unpack(o.via.array.ptr[0]);
   wm_.get_model()->unpack(o.via.array.ptr[1]);
 }
void jubatus::core::driver::recommender::update_row (const std::string & id, const fv_converter::datum & dat)
Definition at line 63 of file recommender.cpp.
References converter_, recommender_, and jubatus::core::common::jsonconfig::v().
{
   core::recommender::sfv_diff_t v;
   converter_->convert_and_update_weight(dat, v);
   recommender_->update_row(id, v);
 }
Member Data Documentation
jubatus::util::lang::shared_ptr<fv_converter::datum_to_fv_converter> jubatus::core::driver::recommender::converter_ private
Definition at line 76 of file recommender.hpp.
Referenced by calc_l2norm(), calc_similality(), clear(), complete_row_from_datum(), recommender(), similar_row_from_datum(), unpack(), and update_row().
jubatus::util::lang::shared_ptr<core::recommender::recommender_base> jubatus::core::driver::recommender::recommender_ private
Definition at line 78 of file recommender.hpp.
Referenced by clear(), clear_row(), complete_row_from_datum(), complete_row_from_id(), decode_row(), get_all_rows(), pack(), recommender(), similar_row_from_datum(), similar_row_from_id(), unpack(), and update_row().
fv_converter::mixable_weight_manager jubatus::core::driver::recommender::wm_ private
Definition at line 79 of file recommender.hpp.
Referenced by pack(), recommender(), and unpack().
The documentation for this class was generated from the following files:
jubatus/core/driver/recommender.hpp
jubatus/core/driver/recommender.cpp