jubatus_core: jubatus::core::fv_converter::counter< T > Class Template Reference
jubatus::core::fv_converter::counter< T > Class Template Reference
#include <counter.hpp>
Public Types
typedef jubatus::util::data::unordered_map< T, double >::const_iterator const_iterator
typedef jubatus::util::data::unordered_map< T, double >::iterator iterator
typedef jubatus::util::data::unordered_map< T, double > map_t
Public Member Functions
void add (const counter< T > &counts)
const_iterator begin () const
iterator begin ()
void clear ()
bool contains (const T &key) const
const_iterator end () const
iterator end ()
MSGPACK_DEFINE (data_)
double operator[] (const T &key) const
double & operator[] (const T &key)
Private Attributes
jubatus::util::data::unordered_map< T, double > data_
Friends
std::ostream & operator<< (std::ostream &os, const counter< T > &c)
Detailed Description
template<class T>
class jubatus::core::fv_converter::counter< T >
Definition at line 31 of file counter.hpp.
Member Typedef Documentation
template<class T> typedef jubatus::util::data::unordered_map<T, double>::const_iterator jubatus::core::fv_converter::counter< T >::const_iterator
Definition at line 35 of file counter.hpp.
template<class T> typedef jubatus::util::data::unordered_map<T, double>::iterator jubatus::core::fv_converter::counter< T >::iterator
Definition at line 37 of file counter.hpp.
template<class T> typedef jubatus::util::data::unordered_map<T, double> jubatus::core::fv_converter::counter< T >::map_t
Definition at line 33 of file counter.hpp.
Member Function Documentation
template<class T> void jubatus::core::fv_converter::counter< T >::add (const counter< T > & counts) inline
Definition at line 79 of file counter.hpp.
Referenced by jubatus::core::fv_converter::keyword_weights::merge().
{
     for (const_iterator it = counts.begin(); it != counts.end(); ++it) {
       (*this)[it->first] += it->second;
     }
   }
template<class T> const_iterator jubatus::core::fv_converter::counter< T >::begin () const inline
Definition at line 59 of file counter.hpp.
Referenced by jubatus::core::fv_converter::counter< std::string >::add(), and jubatus::core::fv_converter::datum_to_fv_converter_impl::make_string_features().
{
     return data_.begin();
   }
template<class T> iterator jubatus::core::fv_converter::counter< T >::begin () inline
Definition at line 63 of file counter.hpp.
                    {
     return data_.begin();
   }
template<class T> void jubatus::core::fv_converter::counter< T >::clear () inline
Definition at line 75 of file counter.hpp.
Referenced by jubatus::core::fv_converter::keyword_weights::clear().
                {
     jubatus::util::data::unordered_map<T, double>().swap(data_);
   }
template<class T> bool jubatus::core::fv_converter::counter< T >::contains (const T & key) const inline
Definition at line 39 of file counter.hpp.
{
     return data_.count(key) != 0;
   }
template<class T> const_iterator jubatus::core::fv_converter::counter< T >::end () const inline
Definition at line 67 of file counter.hpp.
Referenced by jubatus::core::fv_converter::counter< std::string >::add(), and jubatus::core::fv_converter::datum_to_fv_converter_impl::make_string_features().
{
     return data_.end();
   }
template<class T> iterator jubatus::core::fv_converter::counter< T >::end () inline
Definition at line 71 of file counter.hpp.
                  {
     return data_.end();
   }
template<class T> jubatus::core::fv_converter::counter< T >::MSGPACK_DEFINE (data_)
template<class T> double jubatus::core::fv_converter::counter< T >::operator[] (const T & key) const inline
Definition at line 43 of file counter.hpp.
{
     const_iterator it = data_.find(key);
     if (it == data_.end()) {
       return 0;
     } else {
       return it->second;
     }
   }
template<class T> double& jubatus::core::fv_converter::counter< T >::operator[] (const T & key) inline
Definition at line 52 of file counter.hpp.
{
     if (data_.count(key) == 0) {
       data_[key] = 0;
     }
     return data_[key];
   }
Friends And Related Function Documentation
template<class T> std::ostream& operator<< (std::ostream & os, const counter< T > & c) friend
Definition at line 87 of file counter.hpp.
{
     os << "{";
     for (typename
              jubatus::util::data::unordered_map<T, double>::const_iterator it
                  = c.data_.begin();
          it != c.data_.end();
          ++it) {
       os << it->first << ":" << it->second << ", ";
     }
     os << "}";
     return os;
   }
Member Data Documentation
template<class T> jubatus::util::data::unordered_map<T, double> jubatus::core::fv_converter::counter< T >::data_ private
Definition at line 101 of file counter.hpp.
Referenced by jubatus::core::fv_converter::counter< std::string >::begin(), jubatus::core::fv_converter::counter< std::string >::clear(), jubatus::core::fv_converter::counter< std::string >::contains(), jubatus::core::fv_converter::counter< std::string >::end(), and jubatus::core::fv_converter::counter< std::string >::operator[]().
The documentation for this class was generated from the following file:
jubatus/core/fv_converter/counter.hpp