jubatus_core: jubatus::core::framework::linear_mixable_helper< Model, Diff > Class Template Reference
jubatus::core::framework::linear_mixable_helper< Model, Diff > Class Template Reference
#include <mixable_helper.hpp>
Classes
struct internal_diff_object
Public Types
typedef Diff diff_type
typedef jubatus::util::lang::shared_ptr< Model > model_ptr
typedef Model model_type
Public Member Functions
diff_object convert_diff_object (const msgpack::object &obj) const
void get_diff (packer &pk) const
model_ptr get_model () const
storage::version get_version () const
linear_mixable_helper (model_ptr model)
void mix (const msgpack::object &obj, diff_object ptr) const
bool put_diff (const diff_object &ptr)
void set_model (model_ptr m)
virtual ~linear_mixable_helper ()
Public Member Functions inherited from jubatus::core::framework::linear_mixable
linear_mixable ()
virtual ~linear_mixable ()
Public Member Functions inherited from jubatus::core::framework::mixable
mixable ()
mixable (const std::string &name)
virtual std::set< std::string > mixables () const
virtual ~mixable ()
Private Attributes
model_ptr model_
Additional Inherited Members
Protected Attributes inherited from jubatus::core::framework::mixable
std::set< std::string > mixables_
Detailed Description
template<typename Model, typename Diff>
class jubatus::core::framework::linear_mixable_helper< Model, Diff >
Definition at line 39 of file mixable_helper.hpp.
Member Typedef Documentation
template<typename Model, typename Diff> typedef Diff jubatus::core::framework::linear_mixable_helper< Model, Diff >::diff_type
Definition at line 42 of file mixable_helper.hpp.
template<typename Model, typename Diff> typedef jubatus::util::lang::shared_ptr<Model> jubatus::core::framework::linear_mixable_helper< Model, Diff >::model_ptr
Definition at line 43 of file mixable_helper.hpp.
template<typename Model, typename Diff> typedef Model jubatus::core::framework::linear_mixable_helper< Model, Diff >::model_type
Definition at line 41 of file mixable_helper.hpp.
Constructor & Destructor Documentation
template<typename Model, typename Diff> jubatus::core::framework::linear_mixable_helper< Model, Diff >::linear_mixable_helper (model_ptr model) inline explicit
Definition at line 45 of file mixable_helper.hpp.
     : model_(model) {
     if (!model) {
       throw JUBATUS_EXCEPTION(common::config_not_set());
     }
   }
template<typename Model, typename Diff> virtual jubatus::core::framework::linear_mixable_helper< Model, Diff >::~linear_mixable_helper () inline virtual
Definition at line 59 of file mixable_helper.hpp.
{
   }
Member Function Documentation
template<typename Model, typename Diff> diff_object jubatus::core::framework::linear_mixable_helper< Model, Diff >::convert_diff_object (const msgpack::object & obj) const inline virtual
Implements jubatus::core::framework::linear_mixable.
Definition at line 66 of file mixable_helper.hpp.
{
     internal_diff_object* diff = new internal_diff_object;
     diff_object diff_obj(diff);
     obj.convert(&diff->diff_);
     return diff_obj;
   }
template<typename Model, typename Diff> void jubatus::core::framework::linear_mixable_helper< Model, Diff >::get_diff (packer & pk) const inline virtual
Implements jubatus::core::framework::linear_mixable.
Definition at line 85 of file mixable_helper.hpp.
{
     Diff diff;
     model_->get_diff(diff);
     pk.pack(diff);
   }
template<typename Model, typename Diff> model_ptr jubatus::core::framework::linear_mixable_helper< Model, Diff >::get_model () const inline
Definition at line 62 of file mixable_helper.hpp.
Referenced by jubatus::core::driver::anomaly::anomaly(), jubatus::core::driver::classifier::classifier(), jubatus::core::driver::recommender::pack(), jubatus::core::driver::regression::pack(), jubatus::core::driver::anomaly::pack(), jubatus::core::driver::classifier::pack(), jubatus::core::driver::nearest_neighbor::pack(), jubatus::core::driver::recommender::recommender(), jubatus::core::driver::regression::regression(), jubatus::core::driver::recommender::unpack(), jubatus::core::driver::regression::unpack(), jubatus::core::driver::classifier::unpack(), jubatus::core::driver::anomaly::unpack(), and jubatus::core::driver::nearest_neighbor::unpack().
{
     return model_;
   }
template<typename Model, typename Diff> storage::version jubatus::core::framework::linear_mixable_helper< Model, Diff >::get_version () const inline virtual
Reimplemented from jubatus::core::framework::mixable.
Definition at line 101 of file mixable_helper.hpp.
{
     return model_->get_version();
   }
template<typename Model, typename Diff> void jubatus::core::framework::linear_mixable_helper< Model, Diff >::mix (const msgpack::object & obj, diff_object ptr) const inline virtual
Implements jubatus::core::framework::linear_mixable.
Definition at line 73 of file mixable_helper.hpp.
{
     Diff diff;
     internal_diff_object* diff_obj =
       dynamic_cast<internal_diff_object*>(ptr.get());
     if (!diff_obj) {
       throw JUBATUS_EXCEPTION(
           core::common::exception::runtime_error("bad diff_object"));
     }
     obj.convert(&diff);
     model_->mix(diff, diff_obj->diff_);
   }
template<typename Model, typename Diff> bool jubatus::core::framework::linear_mixable_helper< Model, Diff >::put_diff (const diff_object & ptr) inline virtual
Implements jubatus::core::framework::linear_mixable.
Definition at line 91 of file mixable_helper.hpp.
{
     internal_diff_object* diff_obj =
       dynamic_cast<internal_diff_object*>(ptr.get());
     if (!diff_obj) {
       throw JUBATUS_EXCEPTION(
           core::common::exception::runtime_error("bad diff_object"));
     }
     return model_->put_diff(diff_obj->diff_);
   }
template<typename Model, typename Diff> void jubatus::core::framework::linear_mixable_helper< Model, Diff >::set_model (model_ptr m) inline
Definition at line 52 of file mixable_helper.hpp.
{
     if (!m) {
       throw JUBATUS_EXCEPTION(common::config_not_set());
     }
     model_ = m;
   }
Member Data Documentation
template<typename Model, typename Diff> model_ptr jubatus::core::framework::linear_mixable_helper< Model, Diff >::model_ private
Definition at line 114 of file mixable_helper.hpp.
Referenced by jubatus::core::framework::linear_mixable_helper< jubatus::core::bandit::bandit_base, jubatus::core::bandit::bandit_base::diff_t >::get_diff(), jubatus::core::framework::linear_mixable_helper< jubatus::core::bandit::bandit_base, jubatus::core::bandit::bandit_base::diff_t >::get_model(), jubatus::core::framework::linear_mixable_helper< jubatus::core::bandit::bandit_base, jubatus::core::bandit::bandit_base::diff_t >::get_version(), jubatus::core::framework::linear_mixable_helper< jubatus::core::bandit::bandit_base, jubatus::core::bandit::bandit_base::diff_t >::mix(), jubatus::core::framework::linear_mixable_helper< jubatus::core::bandit::bandit_base, jubatus::core::bandit::bandit_base::diff_t >::put_diff(), and jubatus::core::framework::linear_mixable_helper< jubatus::core::bandit::bandit_base, jubatus::core::bandit::bandit_base::diff_t >::set_model().
The documentation for this class was generated from the following file:
jubatus/core/framework/mixable_helper.hpp