jubatus_core: jubatus::core::storage::lsh_vector Class Reference
jubatus::core::storage::lsh_vector Class Reference
#include <lsh_vector.hpp>
Public Member Functions
lsh_vector cut (size_t from, size_t len) const
void debug_print (std::ostream &os) const
int get (size_t pos) const
lsh_vector ()
lsh_vector (const lsh_vector &lv)
lsh_vector (size_t len)
lsh_vector (const std::vector< int > &v)
bool operator!= (const lsh_vector &lv) const
bool operator== (const lsh_vector &lv) const
void push_back (int value)
void resize_and_clear (size_t sz)
void set (size_t pos, int value)
size_t size () const
lsh_vector slice (size_t from, size_t len) const
void swap (lsh_vector &lv)
~lsh_vector ()
Private Attributes
std::vector< int > values_
Friends
class jubatus::util::data::hash< lsh_vector >
Detailed Description
Definition at line 30 of file lsh_vector.hpp.
Constructor & Destructor Documentation
jubatus::core::storage::lsh_vector::lsh_vector ()
Definition at line 30 of file lsh_vector.cpp.
{
 }
jubatus::core::storage::lsh_vector::lsh_vector (const lsh_vector & lv)
Definition at line 33 of file lsh_vector.cpp.
     : values_(lv.values_) {
 }
jubatus::core::storage::lsh_vector::lsh_vector (size_t len) explicit
Definition at line 37 of file lsh_vector.cpp.
     : values_(len) {
 }
jubatus::core::storage::lsh_vector::lsh_vector (const std::vector< int > & v) explicit
jubatus::core::storage::lsh_vector::~lsh_vector ()
Definition at line 45 of file lsh_vector.cpp.
{
 }
Member Function Documentation
lsh_vector jubatus::core::storage::lsh_vector::cut (size_t from, size_t len) const
Definition at line 88 of file lsh_vector.cpp.
References values_.
{
   if (from + len > values_.size()) {
     throw out_of_range("cut range is out of size");
   }
   lsh_vector lv(values_.size() - len);
   copy(values_.begin(), values_.begin() + from, lv.values_.begin());
   copy(values_.begin() + from + len, values_.end(), lv.values_.begin() + from);
   return lv;
 }
void jubatus::core::storage::lsh_vector::debug_print (std::ostream & os) const
Definition at line 100 of file lsh_vector.cpp.
References values_.
Referenced by jubatus::core::storage::operator<<().
{
   for (size_t i = 0; i < values_.size(); ++i) {
     if (i > 0) {
       os << ' ';
     }
     os << values_[i];
   }
 }
int jubatus::core::storage::lsh_vector::get (size_t pos) const
Definition at line 56 of file lsh_vector.cpp.
References values_.
{
   return values_[pos];
 }
bool jubatus::core::storage::lsh_vector::operator!= (const lsh_vector & lv) const
Definition at line 52 of file lsh_vector.cpp.
References operator==().
{
   return !operator==(lv);
 }
bool jubatus::core::storage::lsh_vector::operator== (const lsh_vector & lv) const
Definition at line 48 of file lsh_vector.cpp.
References values_.
Referenced by operator!=().
{
   return values_ == lv.values_;
 }
void jubatus::core::storage::lsh_vector::push_back (int value)
Definition at line 64 of file lsh_vector.cpp.
References values_.
Referenced by jubatus::core::storage::lsh_index_storage::make_entry().
{
   values_.push_back(value);
 }
void jubatus::core::storage::lsh_vector::resize_and_clear (size_t sz)
Definition at line 68 of file lsh_vector.cpp.
References values_.
{
   values_.reserve(sz);
   values_.clear();
   values_.resize(sz);
 }
void jubatus::core::storage::lsh_vector::set (size_t pos, int value)
Definition at line 60 of file lsh_vector.cpp.
References values_.
Referenced by jubatus::core::storage::lsh_probe_generator::base_all().
{
   values_[pos] = value;
 }
size_t jubatus::core::storage::lsh_vector::size () const
Definition at line 74 of file lsh_vector.cpp.
References values_.
Referenced by jubatus::util::data::hash< jubatus::core::storage::lsh_vector >::operator()().
{
   return values_.size();
 }
lsh_vector jubatus::core::storage::lsh_vector::slice (size_t from, size_t len) const
Definition at line 78 of file lsh_vector.cpp.
References values_.
{
   if (from + len > values_.size()) {
     throw out_of_range("slice range is out of size");
   }
   lsh_vector lv;
   lv.values_.assign(values_.begin() + from, values_.begin() + from + len);
   return lv;
 }
void jubatus::core::storage::lsh_vector::swap (lsh_vector & lv)
Definition at line 109 of file lsh_vector.cpp.
References values_.
Referenced by jubatus::core::storage::swap().
{
   values_.swap(lv.values_);
 }
Friends And Related Function Documentation
friend class jubatus::util::data::hash< lsh_vector > friend
Definition at line 56 of file lsh_vector.hpp.
Member Data Documentation
std::vector<int> jubatus::core::storage::lsh_vector::values_ private
Definition at line 58 of file lsh_vector.hpp.
Referenced by cut(), debug_print(), get(), jubatus::util::data::hash< jubatus::core::storage::lsh_vector >::operator()(), operator==(), push_back(), resize_and_clear(), set(), size(), slice(), and swap().
The documentation for this class was generated from the following files:
jubatus/core/storage/lsh_vector.hpp
jubatus/core/storage/lsh_vector.cpp