jubatus_core: jubatus::core::storage::sparse_matrix_storage Class Reference
jubatus::core::storage::sparse_matrix_storage Class Reference
#include <sparse_matrix_storage.hpp>
Public Member Functions
float calc_l2norm (const std::string &row) const
void clear ()
float get (const std::string &row, const std::string &column) const
void get_all_row_ids (std::vector< std::string > &ids) const
void get_row (const std::string &row, std::vector< std::pair< std::string, float > > &columns) const
storage::version get_version () const
MSGPACK_DEFINE (tbl_, column2id_)
sparse_matrix_storage & operator= (const sparse_matrix_storage &)
void pack (framework::packer &packer) const
void remove (const std::string &row, const std::string &column)
void remove_row (const std::string &row)
void set (const std::string &row, const std::string &column, float val)
void set_row (const std::string &row, const std::vector< std::pair< std::string, float > > &columns)
sparse_matrix_storage ()
void unpack (msgpack::object o)
~sparse_matrix_storage ()
Public Member Functions inherited from jubatus::core::framework::model
virtual ~model ()
Private Attributes
common::key_manager column2id_
tbl_t tbl_
storage::version version_
Detailed Description
Definition at line 34 of file sparse_matrix_storage.hpp.
Constructor & Destructor Documentation
jubatus::core::storage::sparse_matrix_storage::sparse_matrix_storage ()
Definition at line 37 of file sparse_matrix_storage.cpp.
{
 }
jubatus::core::storage::sparse_matrix_storage::~sparse_matrix_storage ()
Definition at line 40 of file sparse_matrix_storage.cpp.
{
 }
Member Function Documentation
float jubatus::core::storage::sparse_matrix_storage::calc_l2norm (const std::string & row) const
Definition at line 104 of file sparse_matrix_storage.cpp.
References jubatus::core::common::assoc_vector< K, V >::begin(), jubatus::core::common::assoc_vector< K, V >::end(), and tbl_.
{
   tbl_t::const_iterator it = tbl_.find(row);
   if (it == tbl_.end()) {
     return 0.f;
   }
   float sq_norm = 0.f;
   const row_t& row_v = it->second;
   for (row_t::const_iterator row_it = row_v.begin(); row_it != row_v.end();
       ++row_it) {
     sq_norm += row_it->second * row_it->second;
   }
   return std::sqrt(sq_norm);
 }
void jubatus::core::storage::sparse_matrix_storage::clear () virtual
Reimplemented from jubatus::core::framework::model.
Definition at line 158 of file sparse_matrix_storage.cpp.
References column2id_, jubatus::core::common::key_manager::swap(), and tbl_.
Referenced by jubatus::core::recommender::inverted_index::clear(), jubatus::core::recommender::nearest_neighbor_recommender::clear(), jubatus::core::recommender::lsh::clear(), jubatus::core::recommender::recommender_mock::clear(), jubatus::core::recommender::minhash::clear(), and jubatus::core::recommender::euclid_lsh::clear().
{
   tbl_t().swap(tbl_);
   common::key_manager().swap(column2id_);
   // norm_ptr_->clear();
 }
float jubatus::core::storage::sparse_matrix_storage::get (const std::string & row, const std::string & column) const
Definition at line 68 of file sparse_matrix_storage.cpp.
References column2id_, jubatus::core::common::key_manager::get_id_const(), jubatus::core::common::key_manager::NOTFOUND, and tbl_.
{
   tbl_t::const_iterator it = tbl_.find(row);
   if (it == tbl_.end()) {
     return 0.f;
   }
   uint64_t id = column2id_.get_id_const(column);
   if (id == common::key_manager::NOTFOUND) {
     return 0.f;
   }
   row_t::const_iterator cit = it->second.find(id);
   if (cit == it->second.end()) {
     return 0.f;
   }
   return cit->second;
 }
void jubatus::core::storage::sparse_matrix_storage::get_all_row_ids (std::vector< std::string > & ids) const
Definition at line 151 of file sparse_matrix_storage.cpp.
References tbl_.
Referenced by jubatus::core::recommender::recommender_mock::get_all_row_ids(), jubatus::core::storage::inverted_index_storage::mix(), and jubatus::core::storage::inverted_index_storage::put_diff().
{
   ids.clear();
   for (tbl_t::const_iterator it = tbl_.begin(); it != tbl_.end(); ++it) {
     ids.push_back(it->first);
   }
 }
void jubatus::core::storage::sparse_matrix_storage::get_row (const std::string & row, std::vector< std::pair< std::string, float > > & columns) const
Definition at line 88 of file sparse_matrix_storage.cpp.
References jubatus::core::common::assoc_vector< K, V >::begin(), column2id_, jubatus::core::common::assoc_vector< K, V >::end(), jubatus::core::common::key_manager::get_key(), and tbl_.
Referenced by jubatus::core::recommender::inverted_index::clear_row(), jubatus::core::recommender::recommender_base::complete_row(), jubatus::core::recommender::recommender_base::decode_row(), jubatus::core::storage::inverted_index_storage::mix(), jubatus::core::storage::inverted_index_storage::put_diff(), jubatus::core::recommender::recommender_base::similar_row(), jubatus::core::recommender::nearest_neighbor_recommender::update_row(), jubatus::core::recommender::lsh::update_row(), jubatus::core::recommender::minhash::update_row(), jubatus::core::recommender::recommender_mock::update_row(), and jubatus::core::recommender::euclid_lsh::update_row().
{
   columns.clear();
   tbl_t::const_iterator it = tbl_.find(row);
   if (it == tbl_.end()) {
     return;
   }
   const row_t& row_v = it->second;
   for (row_t::const_iterator row_it = row_v.begin(); row_it != row_v.end();
       ++row_it) {
     columns.push_back(
         make_pair(column2id_.get_key(row_it->first), row_it->second));
   }
 }
storage::version jubatus::core::storage::sparse_matrix_storage::get_version () const inline
Definition at line 57 of file sparse_matrix_storage.hpp.
{
     return storage::version();
   }
jubatus::core::storage::sparse_matrix_storage::MSGPACK_DEFINE (tbl_ , column2id_)
sparse_matrix_storage & jubatus::core::storage::sparse_matrix_storage::operator= (const sparse_matrix_storage & sms)
Definition at line 43 of file sparse_matrix_storage.cpp.
References column2id_, and tbl_.
{
   tbl_ = sms.tbl_;
   column2id_ = sms.column2id_;
   return *this;
 }
void jubatus::core::storage::sparse_matrix_storage::pack (framework::packer & packer) const virtual
Implements jubatus::core::framework::model.
Definition at line 164 of file sparse_matrix_storage.cpp.
Referenced by jubatus::core::recommender::inverted_index::pack(), jubatus::core::recommender::nearest_neighbor_recommender::pack(), jubatus::core::recommender::lsh::pack(), jubatus::core::recommender::recommender_mock::pack(), jubatus::core::recommender::minhash::pack(), and jubatus::core::recommender::euclid_lsh::pack().
           {
   packer.pack(*this);
 }
void jubatus::core::storage::sparse_matrix_storage::remove (const std::string & row, const std::string & column)
Definition at line 118 of file sparse_matrix_storage.cpp.
References column2id_, jubatus::core::common::key_manager::get_id_const(), jubatus::core::common::key_manager::NOTFOUND, and tbl_.
{
   tbl_t::iterator it = tbl_.find(row);
   if (it == tbl_.end()) {
     return;
   }
   uint64_t id = column2id_.get_id_const(column);
   if (id == common::key_manager::NOTFOUND) {
     return;
   }
   row_t::iterator cit = it->second.find(id);
   if (cit == it->second.end()) {
     return;
   }
   // norm_ptr_->notify(row, cit->second, 0.f);
   it->second.erase(cit);
 }
void jubatus::core::storage::sparse_matrix_storage::remove_row (const std::string & row)
Definition at line 137 of file sparse_matrix_storage.cpp.
References tbl_.
Referenced by jubatus::core::recommender::inverted_index::clear_row(), jubatus::core::recommender::nearest_neighbor_recommender::clear_row(), jubatus::core::recommender::lsh::clear_row(), jubatus::core::recommender::recommender_mock::clear_row(), jubatus::core::recommender::minhash::clear_row(), jubatus::core::recommender::euclid_lsh::clear_row(), and jubatus::core::recommender::nearest_neighbor_recommender::unlearn_row().
{
   tbl_t::iterator it = tbl_.find(row);
   if (it == tbl_.end()) {
     return;
   }
   // for (row_t::const_iterator cit = it->second.begin();
   //     cit != it->second.end(); ++cit){
   // norm_ptr_->notify(row, cit->second, 0.f);
   // }
   tbl_.erase(it);
 }
void jubatus::core::storage::sparse_matrix_storage::set (const std::string & row, const std::string & column, float val)
Definition at line 50 of file sparse_matrix_storage.cpp.
References column2id_, jubatus::core::common::key_manager::get_id(), and tbl_.
                {
   tbl_[row][column2id_.get_id(column)] = val;
 }
void jubatus::core::storage::sparse_matrix_storage::set_row (const std::string & row, const std::vector< std::pair< std::string, float > > & columns)
Definition at line 57 of file sparse_matrix_storage.cpp.
References column2id_, jubatus::core::common::key_manager::get_id(), tbl_, and jubatus::core::common::jsonconfig::v().
Referenced by jubatus::core::storage::inverted_index_storage::get_diff(), jubatus::core::storage::inverted_index_storage::mix(), jubatus::core::recommender::inverted_index::update_row(), jubatus::core::recommender::nearest_neighbor_recommender::update_row(), jubatus::core::recommender::lsh::update_row(), jubatus::core::recommender::recommender_mock::update_row(), jubatus::core::recommender::minhash::update_row(), and jubatus::core::recommender::euclid_lsh::update_row().
{
   row_t& row_v = tbl_[row];
   for (size_t i = 0; i < columns.size(); ++i) {
     float& v = row_v[column2id_.get_id(columns[i].first)];
     // norm_ptr_->notify(row, v, columns[i].second);
     v = columns[i].second;
   }
 }
void jubatus::core::storage::sparse_matrix_storage::unpack (msgpack::object o) virtual
Implements jubatus::core::framework::model.
Definition at line 169 of file sparse_matrix_storage.cpp.
Referenced by jubatus::core::recommender::inverted_index::unpack(), jubatus::core::recommender::nearest_neighbor_recommender::unpack(), jubatus::core::recommender::lsh::unpack(), jubatus::core::recommender::recommender_mock::unpack(), jubatus::core::recommender::minhash::unpack(), and jubatus::core::recommender::euclid_lsh::unpack().
{
   o.convert(this);
 }
Member Data Documentation
common::key_manager jubatus::core::storage::sparse_matrix_storage::column2id_ private
Definition at line 66 of file sparse_matrix_storage.hpp.
Referenced by clear(), get(), get_row(), operator=(), remove(), set(), and set_row().
tbl_t jubatus::core::storage::sparse_matrix_storage::tbl_ private
Definition at line 65 of file sparse_matrix_storage.hpp.
Referenced by calc_l2norm(), clear(), get(), get_all_row_ids(), get_row(), operator=(), remove(), remove_row(), set(), and set_row().
storage::version jubatus::core::storage::sparse_matrix_storage::version_ private
Definition at line 67 of file sparse_matrix_storage.hpp.
The documentation for this class was generated from the following files:
jubatus/core/storage/sparse_matrix_storage.hpp
jubatus/core/storage/sparse_matrix_storage.cpp