jubatus_core: jubatus::core::bandit::softmax Class Reference
jubatus::core::bandit::softmax Class Reference
#include <softmax.hpp>
Public Member Functions
void clear ()
bool delete_arm (const std::string &arm_id)
arm_info_map get_arm_info (const std::string &player_id) const
void get_diff (diff_t &diff) const
storage::version get_version () const
void mix (const diff_t &lhs, diff_t &rhs) const
std::string name () const
void pack (framework::packer &pk) const
bool put_diff (const diff_t &diff)
bool register_arm (const std::string &arm_id)
bool register_reward (const std::string &player_id, const std::string &arm_id, double reward)
bool reset (const std::string &player_id)
std::string select_arm (const std::string &player_id)
softmax (bool assume_unrewarded, double tau)
void unpack (msgpack::object o)
Public Member Functions inherited from jubatus::core::bandit::bandit_base
bandit_base ()
virtual ~bandit_base ()
Private Attributes
jubatus::util::math::random::mtrand rand_
summation_storage s_
double tau_
Additional Inherited Members
Public Types inherited from jubatus::core::bandit::bandit_base
typedef jubatus::util::data::unordered_map< std::string, arm_info_map > diff_t
Detailed Description
Definition at line 30 of file softmax.hpp.
Constructor & Destructor Documentation
jubatus::core::bandit::softmax::softmax (bool assume_unrewarded, double tau)
Definition at line 32 of file softmax.cpp.
References JUBATUS_EXCEPTION.
     : tau_(tau), s_(assume_unrewarded) {
   if (tau <= 0) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("0 < tau"));
   }
 }
Member Function Documentation
void jubatus::core::bandit::softmax::clear () virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 79 of file softmax.cpp.
References jubatus::core::bandit::summation_storage::clear(), and s_.
                     {
   s_.clear();
 }
bool jubatus::core::bandit::softmax::delete_arm (const std::string & arm_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 62 of file softmax.cpp.
References jubatus::core::bandit::summation_storage::delete_arm(), and s_.
{
   return s_.delete_arm(arm_id);
 }
arm_info_map jubatus::core::bandit::softmax::get_arm_info (const std::string & player_id) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 72 of file softmax.cpp.
References jubatus::core::bandit::summation_storage::get_arm_info_map(), and s_.
{
   return s_.get_arm_info_map(player_id);
 }
void jubatus::core::bandit::softmax::get_diff (diff_t & diff) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 90 of file softmax.cpp.
References jubatus::core::bandit::summation_storage::get_diff(), and s_.
{
   s_.get_diff(diff);
 }
storage::version jubatus::core::bandit::softmax::get_version () const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 100 of file softmax.cpp.
{
   return storage::version();
 }
void jubatus::core::bandit::softmax::mix (const diff_t & lhs, diff_t & rhs) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 96 of file softmax.cpp.
References jubatus::core::bandit::summation_storage::mix(), and s_.
{
   s_.mix(lhs, rhs);
 }
std::string jubatus::core::bandit::softmax::name () const inline virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 48 of file softmax.hpp.
{
     return "softmax";
   }
void jubatus::core::bandit::softmax::pack (framework::packer & pk) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 83 of file softmax.cpp.
References s_.
{
   pk.pack(s_);
 }
bool jubatus::core::bandit::softmax::put_diff (const diff_t & diff) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 93 of file softmax.cpp.
References jubatus::core::bandit::summation_storage::put_diff(), and s_.
{
   return s_.put_diff(diff);
 }
bool jubatus::core::bandit::softmax::register_arm (const std::string & arm_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 59 of file softmax.cpp.
References jubatus::core::bandit::summation_storage::register_arm(), and s_.
{
   return s_.register_arm(arm_id);
 }
bool jubatus::core::bandit::softmax::register_reward (const std::string & player_id, const std::string & arm_id, double reward) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 66 of file softmax.cpp.
References jubatus::core::bandit::summation_storage::register_reward(), and s_.
{
   return s_.register_reward(player_id, arm_id, reward);
 }
bool jubatus::core::bandit::softmax::reset (const std::string & player_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 76 of file softmax.cpp.
References jubatus::core::bandit::summation_storage::reset(), and s_.
{
   return s_.reset(player_id);
 }
std::string jubatus::core::bandit::softmax::select_arm (const std::string & player_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 40 of file softmax.cpp.
References jubatus::core::bandit::summation_storage::get_arm_ids(), jubatus::core::bandit::summation_storage::get_expectation(), JUBATUS_EXCEPTION, jubatus::core::bandit::summation_storage::notify_selected(), rand_, s_, jubatus::core::bandit::select_by_weights(), and tau_.
{
   const std::vector<std::string>& arms = s_.get_arm_ids();
   if (arms.empty()) {
     throw JUBATUS_EXCEPTION(
         common::exception::runtime_error("arm is not registered"));
   }
   std::vector<double> weights;
   weights.reserve(arms.size());
   for (size_t i = 0; i < arms.size(); ++i) {
     double expectation = s_.get_expectation(player_id, arms[i]);
     weights.push_back(std::exp(expectation / tau_));
   }
   std::string result = arms[select_by_weights(weights, rand_)];
   s_.notify_selected(player_id, result);
   return result;
 }
void jubatus::core::bandit::softmax::unpack (msgpack::object o) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 86 of file softmax.cpp.
References s_.
{
   o.convert(&s_);
 }
Member Data Documentation
jubatus::util::math::random::mtrand jubatus::core::bandit::softmax::rand_ private
Definition at line 62 of file softmax.hpp.
Referenced by select_arm().
summation_storage jubatus::core::bandit::softmax::s_ private
Definition at line 63 of file softmax.hpp.
Referenced by clear(), delete_arm(), get_arm_info(), get_diff(), mix(), pack(), put_diff(), register_arm(), register_reward(), reset(), select_arm(), and unpack().
double jubatus::core::bandit::softmax::tau_ private
Definition at line 61 of file softmax.hpp.
Referenced by select_arm().
The documentation for this class was generated from the following files:
jubatus/core/bandit/softmax.hpp
jubatus/core/bandit/softmax.cpp