jubatus_core: jubatus::core::clustering::gmm_clustering_method Class Reference
jubatus::core::clustering::gmm_clustering_method Class Reference
#include <gmm_clustering_method.hpp>
Public Member Functions
void batch_update (wplist points)
wplist get_cluster (size_t cluster_id, const wplist &points) const
std::vector< wplist > get_clusters (const wplist &points) const
std::vector< common::sfv_t > get_k_center () const
common::sfv_t get_nearest_center (const common::sfv_t &point) const
int64_t get_nearest_center_index (const common::sfv_t &point) const
gmm_clustering_method (size_t k)
void online_update (wplist points)
~gmm_clustering_method ()
Public Member Functions inherited from jubatus::core::clustering::clustering_method
virtual ~clustering_method ()
Private Attributes
gmm gmm_
size_t k_
std::vector< common::sfv_t > kcenters_
eigen_feature_mapper mapper_
Detailed Description
Definition at line 31 of file gmm_clustering_method.hpp.
Constructor & Destructor Documentation
jubatus::core::clustering::gmm_clustering_method::gmm_clustering_method (size_t k) explicit
Definition at line 30 of file gmm_clustering_method.cpp.
Referenced by batch_update().
     : k_(k), kcenters_(), mapper_(), gmm_() {
 }
jubatus::core::clustering::gmm_clustering_method::~gmm_clustering_method ()
Definition at line 34 of file gmm_clustering_method.cpp.
{
 }
Member Function Documentation
void jubatus::core::clustering::gmm_clustering_method::batch_update (wplist points) virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 37 of file gmm_clustering_method.cpp.
References jubatus::core::clustering::gmm::batch(), jubatus::core::clustering::eigen_feature_mapper::clear(), jubatus::core::clustering::eigen_feature_mapper::convert(), jubatus::core::clustering::gmm::get_centers(), jubatus::core::clustering::eigen_feature_mapper::get_dimension(), gmm_, gmm_clustering_method(), k_, kcenters_, mapper_, and jubatus::core::clustering::eigen_feature_mapper::revert().
{
   if (points.empty()) {
     *this = gmm_clustering_method(k_);
     return;
   }
   mapper_.clear();
   eigen_wsvec_list_t data = mapper_.convert(points, true);
   gmm_.batch(data, mapper_.get_dimension(), k_);
   kcenters_ = mapper_.revert(gmm_.get_centers());
 }
wplist jubatus::core::clustering::gmm_clustering_method::get_cluster (size_t cluster_id, const wplist & points) const virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 65 of file gmm_clustering_method.cpp.
References get_clusters().
{
   return get_clusters(points)[cluster_id];
 }
std::vector< wplist > jubatus::core::clustering::gmm_clustering_method::get_clusters (const wplist & points) const virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 71 of file gmm_clustering_method.cpp.
References get_nearest_center_index(), and k_.
Referenced by get_cluster().
{
   std::vector<wplist> ret(k_);
   for (wplist::const_iterator it = points.begin(); it != points.end(); ++it) {
     int64_t c = get_nearest_center_index(it->data);
     ret[c].push_back(*it);
   }
   return ret;
 }
std::vector< common::sfv_t > jubatus::core::clustering::gmm_clustering_method::get_k_center () const virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 51 of file gmm_clustering_method.cpp.
References kcenters_.
{
   return kcenters_;
 }
common::sfv_t jubatus::core::clustering::gmm_clustering_method::get_nearest_center (const common::sfv_t & point) const virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 60 of file gmm_clustering_method.cpp.
References jubatus::core::clustering::eigen_feature_mapper::convertc(), jubatus::core::clustering::gmm::get_nearest_center(), gmm_, mapper_, and jubatus::core::clustering::eigen_feature_mapper::revert().
{
   return mapper_.revert(gmm_.get_nearest_center(mapper_.convertc(point)));
 }
int64_t jubatus::core::clustering::gmm_clustering_method::get_nearest_center_index (const common::sfv_t & point) const virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 55 of file gmm_clustering_method.cpp.
References jubatus::core::clustering::eigen_feature_mapper::convertc(), jubatus::core::clustering::gmm::get_nearest_center_index(), gmm_, and mapper_.
Referenced by get_clusters().
{
   return gmm_.get_nearest_center_index(mapper_.convertc(point));
 }
void jubatus::core::clustering::gmm_clustering_method::online_update (wplist points) virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 48 of file gmm_clustering_method.cpp.
{
 }
Member Data Documentation
gmm jubatus::core::clustering::gmm_clustering_method::gmm_ private
Definition at line 48 of file gmm_clustering_method.hpp.
Referenced by batch_update(), get_nearest_center(), and get_nearest_center_index().
size_t jubatus::core::clustering::gmm_clustering_method::k_ private
Definition at line 45 of file gmm_clustering_method.hpp.
Referenced by batch_update(), and get_clusters().
std::vector<common::sfv_t> jubatus::core::clustering::gmm_clustering_method::kcenters_ private
Definition at line 46 of file gmm_clustering_method.hpp.
Referenced by batch_update(), and get_k_center().
eigen_feature_mapper jubatus::core::clustering::gmm_clustering_method::mapper_ private
Definition at line 47 of file gmm_clustering_method.hpp.
Referenced by batch_update(), get_nearest_center(), and get_nearest_center_index().
The documentation for this class was generated from the following files:
jubatus/core/clustering/gmm_clustering_method.hpp
jubatus/core/clustering/gmm_clustering_method.cpp