jubatus_core: jubatus::core::storage::storage_base Class Reference
jubatus::core::storage::storage_base Class Reference abstract
#include <storage_base.hpp>
Public Member Functions
virtual void bulk_update (const common::sfv_t &sfv, float step_width, const std::string &inc_class, const std::string &dec_class)
virtual void clear ()=0
virtual bool delete_label (const std::string &label)=0
virtual void get (const std::string &feature, feature_val1_t &ret) const =0
virtual void get2 (const std::string &feature, feature_val2_t &ret) const =0
virtual void get3 (const std::string &feature, feature_val3_t &ret) const =0
virtual void get_diff (diff_t &) const
virtual std::vector< std::string > get_labels () const =0
virtual void get_status (std::map< std::string, std::string > &) const =0
virtual version get_version () const =0
virtual void inp (const common::sfv_t &sfv, map_feature_val1_t &ret) const =0
virtual void pack (framework::packer &packer) const =0
virtual void register_label (const std::string &label)=0
virtual void set (const std::string &feature, const std::string &klass, const val1_t &w)=0
virtual void set2 (const std::string &feature, const std::string &klass, const val2_t &w)=0
virtual void set3 (const std::string &feature, const std::string &klass, const val3_t &w)=0
virtual bool set_average_and_clear_diff (const diff_t &)
virtual bool set_label (const std::string &label)=0
virtual std::string type () const =0
virtual void unpack (msgpack::object o)=0
virtual void update (const std::string &feature, const std::string &inc_class, const std::string &dec_class, const val1_t &w)
virtual ~storage_base ()
Public Member Functions inherited from jubatus::core::framework::model
virtual ~model ()
Detailed Description
Definition at line 37 of file storage_base.hpp.
Constructor & Destructor Documentation
virtual jubatus::core::storage::storage_base::~storage_base () inline virtual
Definition at line 39 of file storage_base.hpp.
{
   }
Member Function Documentation
void jubatus::core::storage::storage_base::bulk_update (const common::sfv_t & sfv, float step_width, const std::string & inc_class, const std::string & dec_class) virtual
Reimplemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
Definition at line 47 of file storage_base.cpp.
References set(), and update().
{
   for (common::sfv_t::const_iterator it = sfv.begin(); it != sfv.end(); ++it) {
     const string& feature = it->first;
     float val = it->second;
     if (dec_class != "") {
       update(feature, inc_class, dec_class, step_width * val);
     } else {
       feature_val1_t ret;
       get(feature, ret);
       float pos_val = 0.f;
       for (size_t i = 0; i < ret.size(); ++i) {
         if (ret[i].first == inc_class) {
           pos_val = ret[i].second;
           break;
         }
       }
       set(feature, inc_class, pos_val + step_width * val);
     }
   }
 }
virtual void jubatus::core::storage::storage_base::clear () pure virtual
Reimplemented from jubatus::core::framework::model.
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
virtual bool jubatus::core::storage::storage_base::delete_label (const std::string & label) pure virtual
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
virtual void jubatus::core::storage::storage_base::get (const std::string & feature, feature_val1_t & ret) const pure virtual
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
virtual void jubatus::core::storage::storage_base::get2 (const std::string & feature, feature_val2_t & ret) const pure virtual
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
virtual void jubatus::core::storage::storage_base::get3 (const std::string & feature, feature_val3_t & ret) const pure virtual
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
void jubatus::core::storage::storage_base::get_diff (diff_t & v) const virtual
Reimplemented in jubatus::core::storage::local_storage_mixture.
Definition at line 72 of file storage_base.cpp.
References jubatus::core::storage::diff_t::diff.
{
   v.diff.clear();
 }
virtual std::vector<std::string> jubatus::core::storage::storage_base::get_labels () const pure virtual
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
virtual void jubatus::core::storage::storage_base::get_status (std::map< std::string, std::string > &) const pure virtual
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
virtual version jubatus::core::storage::storage_base::get_version () const pure virtual
Implemented in jubatus::core::storage::local_storage_mixture, and jubatus::core::storage::local_storage.
virtual void jubatus::core::storage::storage_base::inp (const common::sfv_t & sfv, map_feature_val1_t & ret) const pure virtual
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
virtual void jubatus::core::storage::storage_base::pack (framework::packer & packer) const pure virtual
Implements jubatus::core::framework::model.
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
virtual void jubatus::core::storage::storage_base::register_label (const std::string & label) pure virtual
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
virtual void jubatus::core::storage::storage_base::set (const std::string & feature, const std::string & klass, const val1_t & w) pure virtual
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
Referenced by bulk_update(), and update().
virtual void jubatus::core::storage::storage_base::set2 (const std::string & feature, const std::string & klass, const val2_t & w) pure virtual
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
virtual void jubatus::core::storage::storage_base::set3 (const std::string & feature, const std::string & klass, const val3_t & w) pure virtual
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
bool jubatus::core::storage::storage_base::set_average_and_clear_diff (const diff_t &) virtual
Reimplemented in jubatus::core::storage::local_storage_mixture.
Definition at line 76 of file storage_base.cpp.
{
   return true;
 }
virtual bool jubatus::core::storage::storage_base::set_label (const std::string & label) pure virtual
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
virtual std::string jubatus::core::storage::storage_base::type () const pure virtual
Implemented in jubatus::core::storage::local_storage_mixture, and jubatus::core::storage::local_storage.
virtual void jubatus::core::storage::storage_base::unpack (msgpack::object o) pure virtual
Implements jubatus::core::framework::model.
Implemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
void jubatus::core::storage::storage_base::update (const std::string & feature, const std::string & inc_class, const std::string & dec_class, const val1_t & w) virtual
Reimplemented in jubatus::core::storage::local_storage, and jubatus::core::storage::local_storage_mixture.
Definition at line 27 of file storage_base.cpp.
References set().
Referenced by bulk_update().
{
   feature_val1_t row;
   get(feature, row);
   float inc_class_val = w;
   float dec_class_val = -w;
   for (size_t i = 0; i < row.size(); ++i) {
     const string& label = row[i].first;
     if (label == inc_class) {
       inc_class_val += row[i].second;
     } else if (label == dec_class) {
       dec_class_val += row[i].second;
     }
   }
   set(feature, inc_class, inc_class_val);
   set(feature, dec_class, dec_class_val);
 }
The documentation for this class was generated from the following files:
jubatus/core/storage/storage_base.hpp
jubatus/core/storage/storage_base.cpp