jubatus_core: jubatus::core::recommender::recommender_mock Class Reference
jubatus::core::recommender::recommender_mock Class Reference
#include <recommender_mock.hpp>
Public Member Functions
virtual void clear ()
virtual void clear_row (const std::string &id)
virtual void get_all_row_ids (std::vector< std::string > &ids) const
framework::mixable * get_mixable () const
virtual void neighbor_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
void pack (framework::packer &packer) const
recommender_mock ()
void set_neighbor_relation (const common::sfv_t &query, const std::vector< std::pair< std::string, float > > &ids)
void set_neighbor_relation (const std::string &id, const std::vector< std::pair< std::string, float > > &ids)
void set_similar_relation (const common::sfv_t &query, const std::vector< std::pair< std::string, float > > &ids)
void set_similar_relation (const std::string &id, const std::vector< std::pair< std::string, float > > &ids)
virtual void similar_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
virtual std::string type () const
void unpack (msgpack::object o)
virtual void update_row (const std::string &id, const sfv_diff_t &diff)
virtual ~recommender_mock ()
Public Member Functions inherited from jubatus::core::recommender::recommender_base
void complete_row (const std::string &id, common::sfv_t &ret) const
void complete_row (const common::sfv_t &query, common::sfv_t &ret) const
void decode_row (const std::string &id, common::sfv_t &ret) const
virtual const core::storage::recommender_storage_base * get_const_storage () const
virtual jubatus::util::lang::shared_ptr< const storage::column_table > get_const_table () const
virtual jubatus::util::lang::shared_ptr< storage::column_table > get_table ()
virtual jubatus::util::lang::shared_ptr< unlearner::unlearner_base > get_unlearner ()
virtual void neighbor_row (const std::string &id, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
recommender_base ()
virtual void similar_row (const std::string &id, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
virtual ~recommender_base ()
Public Member Functions inherited from jubatus::core::framework::model
virtual ~model ()
Private Attributes
jubatus::util::lang::shared_ptr< mixable_recommender_mock_storage > mixable_storage_
Additional Inherited Members
Static Public Member Functions inherited from jubatus::core::recommender::recommender_base
static float calc_l2norm (const common::sfv_t &query)
static float calc_similality (common::sfv_t &q1, common::sfv_t &q2)
Protected Attributes inherited from jubatus::core::recommender::recommender_base
core::storage::sparse_matrix_storage orig_
Static Protected Attributes inherited from jubatus::core::recommender::recommender_base
static const uint64_t complete_row_similar_num_ = 128
Detailed Description
Definition at line 31 of file recommender_mock.hpp.
Constructor & Destructor Documentation
jubatus::core::recommender::recommender_mock::recommender_mock ()
Definition at line 34 of file recommender_mock.cpp.
     : mixable_storage_(new mixable_recommender_mock_storage(
         model_ptr(new recommender_mock_storage))) {
 }
jubatus::core::recommender::recommender_mock::~recommender_mock () virtual
Definition at line 39 of file recommender_mock.cpp.
{
 }
Member Function Documentation
void jubatus::core::recommender::recommender_mock::clear () virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 84 of file recommender_mock.cpp.
References jubatus::core::storage::sparse_matrix_storage::clear(), mixable_storage_, and jubatus::core::recommender::recommender_base::orig_.
{
   mixable_storage_->get_model()->clear();
   orig_.clear();
 }
void jubatus::core::recommender::recommender_mock::clear_row (const std::string & id) virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 89 of file recommender_mock.cpp.
References jubatus::core::recommender::recommender_base::decode_row(), mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::remove_row().
{
   common::sfv_t sfv;
   decode_row(id, sfv);
   mixable_storage_->get_model()->remove(sfv);
   orig_.remove_row(id);
 }
void jubatus::core::recommender::recommender_mock::get_all_row_ids (std::vector< std::string > & ids) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 108 of file recommender_mock.cpp.
References jubatus::core::storage::sparse_matrix_storage::get_all_row_ids(), and jubatus::core::recommender::recommender_base::orig_.
{
   orig_.get_all_row_ids(ids);
 }
framework::mixable * jubatus::core::recommender::recommender_mock::get_mixable () const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 131 of file recommender_mock.cpp.
References mixable_storage_.
{
   return mixable_storage_.get();
 }
void jubatus::core::recommender::recommender_mock::neighbor_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 77 of file recommender_mock.cpp.
References mixable_storage_.
{
   mixable_storage_->get_model()->neighbor_items_distance(query, ids, ret_num);
 }
void jubatus::core::recommender::recommender_mock::pack (framework::packer & packer) const virtual
Implements jubatus::core::framework::model.
Definition at line 116 of file recommender_mock.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::pack().
{
   orig_.pack(packer);
   mixable_storage_->get_model()->pack(packer);
 }
void jubatus::core::recommender::recommender_mock::set_neighbor_relation (const common::sfv_t & query, const std::vector< std::pair< std::string, float > > & ids)
void jubatus::core::recommender::recommender_mock::set_neighbor_relation (const std::string & id, const std::vector< std::pair< std::string, float > > & ids)
void jubatus::core::recommender::recommender_mock::set_similar_relation (const common::sfv_t & query, const std::vector< std::pair< std::string, float > > & ids)
void jubatus::core::recommender::recommender_mock::set_similar_relation (const std::string & id, const std::vector< std::pair< std::string, float > > & ids)
void jubatus::core::recommender::recommender_mock::similar_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 70 of file recommender_mock.cpp.
References mixable_storage_.
{
   mixable_storage_->get_model()->similar_items_similarity(query, ids, ret_num);
 }
string jubatus::core::recommender::recommender_mock::type () const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 112 of file recommender_mock.cpp.
{
   return "recommender_mock";
 }
void jubatus::core::recommender::recommender_mock::unpack (msgpack::object o) virtual
Implements jubatus::core::framework::model.
Definition at line 121 of file recommender_mock.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::unpack().
{
   std::vector<msgpack::object> mems;
   o.convert(&mems);
   if (mems.size() != 2) {
     throw msgpack::type_error();
   }
   orig_.unpack(mems[0]);
   mixable_storage_->get_model()->unpack(mems[1]);
 }
void jubatus::core::recommender::recommender_mock::update_row (const std::string & id, const sfv_diff_t & diff) virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 97 of file recommender_mock.cpp.
References jubatus::core::storage::sparse_matrix_storage::get_row(), mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::set_row().
{
   common::sfv_t old_sfv;
   orig_.get_row(id, old_sfv);
   orig_.set_row(id, diff);
   common::sfv_t new_sfv;
   orig_.get_row(id, new_sfv);
   mixable_storage_->get_model()->update(old_sfv, new_sfv);
 }
Member Data Documentation
jubatus::util::lang::shared_ptr<mixable_recommender_mock_storage> jubatus::core::recommender::recommender_mock::mixable_storage_ private
Definition at line 73 of file recommender_mock.hpp.
Referenced by clear(), clear_row(), get_mixable(), neighbor_row(), pack(), similar_row(), unpack(), and update_row().
The documentation for this class was generated from the following files:
jubatus/core/recommender/recommender_mock.hpp
jubatus/core/recommender/recommender_mock.cpp