jubatus_core: jubatus::core::storage::bit_vector Class Reference
jubatus::core::storage::bit_vector Class Reference
#include <bit_vector.hpp>
Public Member Functions
uint64_t bit_num () const
bit_vector ()
uint64_t calc_hamming_similarity (const bit_vector &bv) const
void debug_print (std::ostream &os) const
MSGPACK_DEFINE (bits_, bit_num_)
bool operator== (const bit_vector &v) const
void resize_and_clear (uint64_t bit_num)
void set_bit (uint64_t pos)
void swap (bit_vector &v)
~bit_vector ()
Static Public Member Functions
static uint64_t pop_count (uint64_t r)
Private Attributes
uint64_t bit_num_
std::vector< uint64_t > bits_
Detailed Description
Definition at line 30 of file bit_vector.hpp.
Constructor & Destructor Documentation
jubatus::core::storage::bit_vector::bit_vector ()
Definition at line 29 of file bit_vector.cpp.
     : bit_num_(0) {
 }
jubatus::core::storage::bit_vector::~bit_vector ()
Definition at line 33 of file bit_vector.cpp.
{
 }
Member Function Documentation
uint64_t jubatus::core::storage::bit_vector::bit_num () const inline
Definition at line 51 of file bit_vector.hpp.
References bit_num_.
Referenced by calc_hamming_similarity(), operator==(), resize_and_clear(), and jubatus::core::storage::bit_index_storage::similar_row().
{
     return bit_num_;
   }
uint64_t jubatus::core::storage::bit_vector::calc_hamming_similarity (const bit_vector & bv) const
Definition at line 50 of file bit_vector.cpp.
References bit_num(), bit_num_, bits_, and pop_count().
Referenced by jubatus::core::storage::similar_row_one().
{
   size_t bit_num, max_index;
   if (bit_num_ < bv.bit_num_) {
     bit_num = bit_num_;
     max_index = bits_.size() - 1;
   } else {
     bit_num = bv.bit_num_;
     max_index = bv.bits_.size() - 1;
   }
   if (bit_num == 0) {
     return 0;
   }
   const uint64_t* a = &bits_[0];
   const uint64_t* a_back = a + max_index;
   const uint64_t* b = &bv.bits_[0];
   uint64_t heads_match = 0;
   while (a != a_back) {
     heads_match += pop_count(~(*a++ ^ *b++));
   }
   const uint64_t tail_match = (bit_num - 1) % BLOCKSIZE + 1
       - pop_count(*a ^ *b);
   return heads_match + tail_match + (bit_num_ + bv.bit_num_ - 2 * bit_num);
 }
void jubatus::core::storage::bit_vector::debug_print (std::ostream & os) const inline
Definition at line 55 of file bit_vector.hpp.
References bit_num_, and bits_.
{
     for (uint64_t i = 0; i < bit_num_; ++i) {
       if ((bits_[i / 64] >> (i % 64)) & 1LLU) {
         os << "1";
       } else {
         os << "0";
       }
     }
   }
jubatus::core::storage::bit_vector::MSGPACK_DEFINE (bits_ , bit_num_)
bool jubatus::core::storage::bit_vector::operator== (const bit_vector & v) const
Definition at line 36 of file bit_vector.cpp.
References bit_num(), and bits_.
{
   return v.bit_num() == bit_num()
       && equal(bits_.begin(), bits_.end(), v.bits_.begin());
 }
static uint64_t jubatus::core::storage::bit_vector::pop_count (uint64_t r) inline static
Definition at line 41 of file bit_vector.hpp.
Referenced by calc_hamming_similarity().
{
     r = (r & 0x5555555555555555ULL) + ((r >> 1) & 0x5555555555555555ULL);
     r = (r & 0x3333333333333333ULL) + ((r >> 2) & 0x3333333333333333ULL);
     r = (r + (r >> 4)) & 0x0f0f0f0f0f0f0f0fULL;
     r = r + (r >> 8);
     r = r + (r >> 16);
     r = r + (r >> 32);
     return (uint64_t)(r & 0x7f);
   }
void jubatus::core::storage::bit_vector::resize_and_clear (uint64_t bit_num)
Definition at line 41 of file bit_vector.cpp.
References bit_num(), bit_num_, and bits_.
Referenced by jubatus::core::recommender::minhash::calc_minhash_values(), and jubatus::core::recommender::set_bit_vector().
{
   bit_num_ = bit_num;
   bits_.resize((bit_num + BLOCKSIZE - 1) / BLOCKSIZE, 0);
 }
void jubatus::core::storage::bit_vector::set_bit (uint64_t pos)
Definition at line 46 of file bit_vector.cpp.
References bits_, and jubatus::core::storage::BLOCKSIZE.
Referenced by jubatus::core::recommender::minhash::calc_minhash_values(), and jubatus::core::recommender::set_bit_vector().
{
   bits_[pos / BLOCKSIZE] |= (1LLU << (pos % BLOCKSIZE));
 }
void jubatus::core::storage::bit_vector::swap (bit_vector & v) inline
Definition at line 65 of file bit_vector.hpp.
References bit_num_, bits_, and jubatus::core::clustering::swap().
Referenced by jubatus::core::recommender::set_bit_vector().
{
     bits_.swap(v.bits_);
     std::swap(bit_num_, v.bit_num_);
   }
Member Data Documentation
uint64_t jubatus::core::storage::bit_vector::bit_num_ private
Definition at line 74 of file bit_vector.hpp.
Referenced by bit_num(), calc_hamming_similarity(), debug_print(), resize_and_clear(), and swap().
std::vector<uint64_t> jubatus::core::storage::bit_vector::bits_ private
Definition at line 73 of file bit_vector.hpp.
Referenced by calc_hamming_similarity(), debug_print(), operator==(), resize_and_clear(), set_bit(), and swap().
The documentation for this class was generated from the following files:
jubatus/core/storage/bit_vector.hpp
jubatus/core/storage/bit_vector.cpp