jubatus_core: jubatus::core::nearest_neighbor::euclid_lsh Class Reference
jubatus::core::nearest_neighbor::euclid_lsh Class Reference
#include <euclid_lsh.hpp>
Classes
struct config
Public Member Functions
virtual float calc_similarity (float distance) const
euclid_lsh (const config &conf, jubatus::util::lang::shared_ptr< storage::column_table > table, const std::string &id)
euclid_lsh (const config &conf, jubatus::util::lang::shared_ptr< storage::column_table > table, std::vector< storage::column_type > &schema, const std::string &id)
virtual void neighbor_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const
virtual void neighbor_row (const std::string &query, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const
virtual void set_row (const std::string &id, const common::sfv_t &sfv)
virtual std::string type () const
Public Member Functions inherited from jubatus::core::nearest_neighbor::nearest_neighbor_base
virtual void clear ()
void get_all_row_ids (std::vector< std::string > &ids) const
jubatus::util::lang::shared_ptr< const storage::column_table > get_const_table () const
framework::mixable * get_mixable () const
jubatus::util::lang::shared_ptr< storage::column_table > get_table ()
nearest_neighbor_base (jubatus::util::lang::shared_ptr< storage::column_table > table, const std::string &id)
void pack (framework::packer &packer) const
virtual void similar_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const
virtual void similar_row (const std::string &query_id, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const
void unpack (msgpack::object o)
virtual ~nearest_neighbor_base ()
Private Member Functions
void fill_schema (std::vector< storage::column_type > &schema)
storage::const_bit_vector_column & lsh_column () const
void neighbor_row_from_hash (const storage::bit_vector &bv, float norm, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const
storage::const_float_column & norm_column () const
void set_config (const config &conf)
Private Attributes
uint64_t first_column_id_
uint32_t hash_num_
Additional Inherited Members
Protected Attributes inherited from jubatus::core::nearest_neighbor::nearest_neighbor_base
std::string my_id_
Detailed Description
Definition at line 35 of file euclid_lsh.hpp.
Constructor & Destructor Documentation
jubatus::core::nearest_neighbor::euclid_lsh::euclid_lsh (const config & conf, jubatus::util::lang::shared_ptr< storage::column_table > table, const std::string & id)
jubatus::core::nearest_neighbor::euclid_lsh::euclid_lsh (const config & conf, jubatus::util::lang::shared_ptr< storage::column_table > table, std::vector< storage::column_type > & schema, const std::string & id)
Member Function Documentation
virtual float jubatus::core::nearest_neighbor::euclid_lsh::calc_similarity (float distance) const inline virtual
Reimplemented from jubatus::core::nearest_neighbor::nearest_neighbor_base.
Definition at line 75 of file euclid_lsh.hpp.
{
     return -distance;
   }
void jubatus::core::nearest_neighbor::euclid_lsh::fill_schema (std::vector< storage::column_type > & schema) private
Definition at line 125 of file euclid_lsh.cpp.
{
   first_column_id_ = schema.size();
   schema.push_back(column_type(column_type::bit_vector_type, hash_num_));
   schema.push_back(column_type(column_type::float_type));
 }
const_bit_vector_column & jubatus::core::nearest_neighbor::euclid_lsh::lsh_column () const private
Definition at line 131 of file euclid_lsh.cpp.
{
   return get_const_table()->get_bit_vector_column(first_column_id_);
 }
virtual void jubatus::core::nearest_neighbor::euclid_lsh::neighbor_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, uint64_t ret_num) const virtual
Implements jubatus::core::nearest_neighbor::nearest_neighbor_base.
virtual void jubatus::core::nearest_neighbor::euclid_lsh::neighbor_row (const std::string & query, std::vector< std::pair< std::string, float > > & ids, uint64_t ret_num) const virtual
Implements jubatus::core::nearest_neighbor::nearest_neighbor_base.
void jubatus::core::nearest_neighbor::euclid_lsh::neighbor_row_from_hash (const storage::bit_vector & bv, float norm, std::vector< std::pair< std::string, float > > & ids, uint64_t ret_num) const private
Definition at line 139 of file euclid_lsh.cpp.
References jubatus::core::storage::fixed_size_heap< T, Comp >::get_sorted(), jubatus::core::storage::fixed_size_heap< T, Comp >::push(), and jubatus::core::regression::squared_norm().
{
   jubatus::util::lang::shared_ptr<const column_table> table = get_const_table();
   jubatus::core::storage::fixed_size_heap<pair<float, size_t> > heap(ret_num);
   {
     const_bit_vector_column& bv_col = lsh_column();
     const_float_column& norm_col = norm_column();
     const float denom = bv.bit_num();
     for (size_t i = 0; i < table->size(); ++i) {
       const size_t hamm_dist = bv.calc_hamming_distance(bv_col[i]);
       const float theta = hamm_dist * M_PI / denom;
       const float score =
           norm_col[i] * (norm_col[i] - 2 * norm * std::cos(theta));
       heap.push(make_pair(score, i));
     }
   }
   vector<pair<float, size_t> > sorted;
   heap.get_sorted(sorted);
   ids.clear();
   const float squared_norm = norm * norm;
   for (size_t i = 0; i < sorted.size(); ++i) {
     ids.push_back(make_pair(table->get_key(sorted[i].second),
                             std::sqrt(squared_norm + sorted[i].first)));
   }
 }
const_float_column & jubatus::core::nearest_neighbor::euclid_lsh::norm_column () const private
Definition at line 135 of file euclid_lsh.cpp.
{
   return get_const_table()->get_float_column(first_column_id_ + 1);
 }
void jubatus::core::nearest_neighbor::euclid_lsh::set_config (const config & conf) private
Definition at line 116 of file euclid_lsh.cpp.
References jubatus::core::nearest_neighbor::euclid_lsh::config::hash_num, and JUBATUS_EXCEPTION.
{
   if (!(1 <= conf.hash_num)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("1 <= hash_num"));
   }
   hash_num_ = conf.hash_num;
 }
void jubatus::core::nearest_neighbor::euclid_lsh::set_row (const std::string & id, const common::sfv_t & sfv) virtual
Implements jubatus::core::nearest_neighbor::nearest_neighbor_base.
Definition at line 83 of file euclid_lsh.cpp.
References jubatus::core::nearest_neighbor::cosine_lsh().
{
   // TODO(beam2d): support nested algorithm, e.g. when used by lof and then we
   // cannot suppose that the first two columns are assigned to euclid_lsh.
   get_table()->add(id, owner(my_id_), cosine_lsh(sfv, hash_num_), l2norm(sfv));
 }
virtual std::string jubatus::core::nearest_neighbor::euclid_lsh::type () const inline virtual
Implements jubatus::core::nearest_neighbor::nearest_neighbor_base.
Definition at line 61 of file euclid_lsh.hpp.
{
     return "euclid_lsh";
   }
Member Data Documentation
uint64_t jubatus::core::nearest_neighbor::euclid_lsh::first_column_id_ private
Definition at line 91 of file euclid_lsh.hpp.
uint32_t jubatus::core::nearest_neighbor::euclid_lsh::hash_num_ private
Definition at line 92 of file euclid_lsh.hpp.
The documentation for this class was generated from the following files:
jubatus/core/nearest_neighbor/euclid_lsh.hpp
jubatus/core/nearest_neighbor/euclid_lsh.cpp