jubatus_core: jubatus::core::clustering::simple_storage Class Reference
jubatus::core::clustering::simple_storage Class Reference
#include <simple_storage.hpp>
Public Member Functions
void add (const weighted_point &point)
wplist get_mine () const
simple_storage (const std::string &name, const clustering_config &config)
Public Member Functions inherited from jubatus::core::clustering::storage
void clear ()
virtual wplist get_all () const
virtual wplist get_common () const
void get_diff (diff_t &d) const
size_t get_revision ()
core::storage::version get_version () const
void mix (const diff_t &, diff_t &ret)
MSGPACK_DEFINE (revision_, name_, config_, common_)
void pack (framework::packer &packer) const
bool put_diff (const diff_t &d)
storage (const std::string &name, const clustering_config &config)
void unpack (msgpack::object o)
virtual ~storage ()
Public Member Functions inherited from jubatus::core::clustering::event_dispatcher< storage_event_type, wplist >
void add_event_listener (const storage_event_type &type, callback_t callback)
virtual ~event_dispatcher ()
Private Member Functions
void clear_impl_ ()
void pack_impl_ (framework::packer &packer) const
void unpack_impl_ (msgpack::object o)
Private Attributes
wplist mine_
Additional Inherited Members
Protected Member Functions inherited from jubatus::core::clustering::storage
void increment_revision ()
Protected Member Functions inherited from jubatus::core::clustering::event_dispatcher< storage_event_type, wplist >
void dispatch (const storage_event_type &type, const wplist &data) const
Protected Attributes inherited from jubatus::core::clustering::storage
std::vector< std::pair< std::string, wplist > > common_
clustering_config config_
std::string name_
size_t revision_
Protected Attributes inherited from jubatus::core::clustering::event_dispatcher< storage_event_type, wplist >
event_type_table events_
Detailed Description
Definition at line 27 of file simple_storage.hpp.
Constructor & Destructor Documentation
jubatus::core::clustering::simple_storage::simple_storage (const std::string & name, const clustering_config & config)
Definition at line 26 of file simple_storage.cpp.
     : storage(name, config) {
 }
Member Function Documentation
void jubatus::core::clustering::simple_storage::add (const weighted_point & point) virtual
Implements jubatus::core::clustering::storage.
Definition at line 32 of file simple_storage.cpp.
References jubatus::core::clustering::clustering_config::bucket_size, jubatus::core::clustering::storage::config_, jubatus::core::clustering::storage::increment_revision(), and mine_.
{
   static size_t cnt = 0;
   ++cnt;
   if (cnt % config_.bucket_size == 0) {
     increment_revision();
   }
   mine_.push_back(point);
 }
void jubatus::core::clustering::simple_storage::clear_impl_ () private virtual
Reimplemented from jubatus::core::clustering::storage.
Definition at line 61 of file simple_storage.cpp.
References jubatus::core::clustering::storage::clear_impl_(), and mine_.
{
   storage::clear_impl_();
   mine_.clear();
 }
wplist jubatus::core::clustering::simple_storage::get_mine () const virtual
Implements jubatus::core::clustering::storage.
Definition at line 41 of file simple_storage.cpp.
References mine_.
{
   return mine_;
 }
void jubatus::core::clustering::simple_storage::pack_impl_ (framework::packer & packer) const private virtual
Reimplemented from jubatus::core::clustering::storage.
Definition at line 45 of file simple_storage.cpp.
References mine_, and jubatus::core::clustering::storage::pack_impl_().
{
   packer.pack_array(2);
   storage::pack_impl_(packer);
   packer.pack(mine_);
 }
void jubatus::core::clustering::simple_storage::unpack_impl_ (msgpack::object o) private virtual
Reimplemented from jubatus::core::clustering::storage.
Definition at line 51 of file simple_storage.cpp.
References mine_, and jubatus::core::clustering::storage::unpack_impl_().
{
   std::vector<msgpack::object> mems;
   o.convert(&mems);
   if (mems.size() != 2) {
     throw msgpack::type_error();
   }
   storage::unpack_impl_(mems[0]);
   mems[1].convert(&mine_);
 }
Member Data Documentation
wplist jubatus::core::clustering::simple_storage::mine_ private
Definition at line 39 of file simple_storage.hpp.
Referenced by add(), clear_impl_(), get_mine(), pack_impl_(), and unpack_impl_().
The documentation for this class was generated from the following files:
jubatus/core/clustering/simple_storage.hpp
jubatus/core/clustering/simple_storage.cpp