jubatus_core: jubatus::core::framework::push_mixable Class Reference
jubatus::core::framework::push_mixable Class Reference abstract
#include <push_mixable.hpp>
Public Member Functions
virtual void get_argument (packer &) const =0
virtual void pull (const msgpack::object &arg, packer &) const =0
virtual void push (const msgpack::object &)=0
push_mixable ()
virtual ~push_mixable ()
Public Member Functions inherited from jubatus::core::framework::mixable
virtual storage::version get_version () const
mixable ()
mixable (const std::string &name)
virtual std::set< std::string > mixables () const
virtual ~mixable ()
Additional Inherited Members
Protected Attributes inherited from jubatus::core::framework::mixable
std::set< std::string > mixables_
Detailed Description
Definition at line 29 of file push_mixable.hpp.
Constructor & Destructor Documentation
jubatus::core::framework::push_mixable::push_mixable ()
Definition at line 23 of file push_mixable.cpp.
                            : mixable("push_mixable") {
 }
jubatus::core::framework::push_mixable::~push_mixable () virtual
Definition at line 26 of file push_mixable.cpp.
{
 }
Member Function Documentation
virtual void jubatus::core::framework::push_mixable::get_argument (packer &) const pure virtual
Implemented in jubatus::core::driver::driver_base::mixable_holder, and jubatus::core::framework::mixable_versioned_table.
Referenced by jubatus::core::driver::driver_base::mixable_holder::get_argument().
virtual void jubatus::core::framework::push_mixable::pull (const msgpack::object & arg, packer &) const pure virtual
Implemented in jubatus::core::driver::driver_base::mixable_holder, and jubatus::core::framework::mixable_versioned_table.
Referenced by jubatus::core::driver::driver_base::mixable_holder::pull().
virtual void jubatus::core::framework::push_mixable::push (const msgpack::object &) pure virtual
Implemented in jubatus::core::driver::driver_base::mixable_holder, and jubatus::core::framework::mixable_versioned_table.
Referenced by jubatus::core::driver::driver_base::mixable_holder::push().
The documentation for this class was generated from the following files:
jubatus/core/framework/push_mixable.hpp
jubatus/core/framework/push_mixable.cpp