jubatus_core: jubatus::core::common::jsonconfig::config Class Reference
jubatus::core::common::jsonconfig::config Class Reference
#include <config.hpp>
Classes
class iterator
Public Member Functions
template<typename T >
T As () const
iterator begin () const
config ()
config (const jubatus::util::text::json::json &j)
config (const jubatus::util::text::json::json &j, const std::string &path)
bool contain (const std::string &key) const
iterator end () const
const jubatus::util::text::json::json & get () const
template<class T >
bool is () const
config operator[] (size_t index) const
config operator[] (const std::string &key) const
const std::string & path () const
size_t size () const
jubatus::util::text::json::json::json_type_t type () const
Private Attributes
jubatus::util::text::json::json json_
std::string path_
Detailed Description
Definition at line 40 of file config.hpp.
Constructor & Destructor Documentation
jubatus::core::common::jsonconfig::config::config () inline
Definition at line 44 of file config.hpp.
Referenced by operator[](), and jubatus::core::common::jsonconfig::config::iterator::value().
       : json_() {
   }
jubatus::core::common::jsonconfig::config::config (const jubatus::util::text::json::json & j) inline explicit
Definition at line 48 of file config.hpp.
       : json_(j) {
   }
jubatus::core::common::jsonconfig::config::config (const jubatus::util::text::json::json & j, const std::string & path) inline
Definition at line 52 of file config.hpp.
       : json_(j),
         path_(path) {
   }
Member Function Documentation
template<typename T > T jubatus::core::common::jsonconfig::config::As () const inline
Definition at line 58 of file config.hpp.
References jubatus::core::common::jsonconfig::config_cast().
                {
     return config_cast<T>(*this);
   }
config::iterator jubatus::core::common::jsonconfig::config::begin () const
Definition at line 94 of file config.cpp.
References json_.
Referenced by jubatus::core::common::jsonconfig::serialize().
{
   return iterator(*this, json_.begin());
 }
bool jubatus::core::common::jsonconfig::config::contain (const std::string & key) const
Definition at line 77 of file config.cpp.
References json_, JUBATUS_EXCEPTION, path_, and type().
Referenced by jubatus::core::common::jsonconfig::serialize().
{
   if (type() != jubatus::util::text::json::json::Object) {
     throw JUBATUS_EXCEPTION(
         type_error(path_, jubatus::util::text::json::json::Object, type()));
   }
   return json_.count(key) > 0;
 }
config::iterator jubatus::core::common::jsonconfig::config::end () const
Definition at line 98 of file config.cpp.
References json_.
Referenced by jubatus::core::common::jsonconfig::serialize().
{
   return iterator(*this, json_.end());
 }
const jubatus::util::text::json::json& jubatus::core::common::jsonconfig::config::get () const inline
Definition at line 72 of file config.hpp.
References json_.
Referenced by jubatus::core::common::jsonconfig::json_config_iarchive_cast::get(), and jubatus::core::common::jsonconfig::serialize().
{
     return json_;
   }
template<class T > bool jubatus::core::common::jsonconfig::config::is () const inline
Definition at line 80 of file config.hpp.
References json_.
                   {
     return jubatus::util::text::json::is<T>(json_);
   }
config jubatus::core::common::jsonconfig::config::operator[] (size_t index) const
Definition at line 49 of file config.cpp.
References config(), json_, JUBATUS_EXCEPTION, path_, and type().
{
   try {
     if (index < json_.size()) {
       std::ostringstream os;
       os << path_ << "[" << index << "]";
       return config(json_[index], os.str());
     } else {
       throw JUBATUS_EXCEPTION(out_of_range(path_, json_.size(), index));
     }
   } catch (const std::bad_cast& e) {
     throw JUBATUS_EXCEPTION(
         type_error(path_, jubatus::util::text::json::json::Array, type()));
   }
 }
config jubatus::core::common::jsonconfig::config::operator[] (const std::string & key) const
Definition at line 64 of file config.cpp.
References config(), json_, JUBATUS_EXCEPTION, path_, and type().
{
   try {
     std::ostringstream os;
     os << path_ << "." << key;
     return config(json_[key], os.str());
   } catch (const std::out_of_range& e) {
     throw JUBATUS_EXCEPTION(not_found(path_, key));
   } catch (const std::bad_cast& e) {
     throw JUBATUS_EXCEPTION(
         type_error(path_, jubatus::util::text::json::json::Object, type()));
   }
 }
const std::string& jubatus::core::common::jsonconfig::config::path () const inline
Definition at line 75 of file config.hpp.
References path_.
Referenced by jubatus::core::common::jsonconfig::detail::check_json_float(), jubatus::core::common::jsonconfig::detail::check_json_type(), and jubatus::core::common::jsonconfig::serialize().
{
     return path_;
   }
size_t jubatus::core::common::jsonconfig::config::size () const
Definition at line 85 of file config.cpp.
References json_, JUBATUS_EXCEPTION, path_, and type().
{
   try {
     return json_.size();
   } catch (const std::bad_cast& e) {
     throw JUBATUS_EXCEPTION(
         type_error(path_, jubatus::util::text::json::json::Array, type()));
   }
 }
jubatus::util::text::json::json::json_type_t jubatus::core::common::jsonconfig::config::type () const inline
Definition at line 84 of file config.hpp.
References json_.
Referenced by contain(), jubatus::core::bandit::bandit_factory::create(), jubatus::core::classifier::classifier_factory::create_classifier(), operator[](), and size().
{
     return json_.type();
   }
Member Data Documentation
jubatus::util::text::json::json jubatus::core::common::jsonconfig::config::json_ private
Definition at line 134 of file config.hpp.
Referenced by begin(), contain(), end(), get(), is(), operator[](), size(), and type().
std::string jubatus::core::common::jsonconfig::config::path_ private
Definition at line 135 of file config.hpp.
Referenced by contain(), operator[](), path(), and size().
The documentation for this class was generated from the following files:
jubatus/core/common/jsonconfig/config.hpp
jubatus/core/common/jsonconfig/config.cpp