jubatus_core: jubatus::core::common::hash_util Class Reference
jubatus::core::common::hash_util Class Reference
#include <hash.hpp>
Static Public Member Functions
static uint64_t calc_string_hash (const std::string &s)
Detailed Description
Definition at line 27 of file hash.hpp.
Member Function Documentation
static uint64_t jubatus::core::common::hash_util::calc_string_hash (const std::string & s) inline static
Definition at line 29 of file hash.hpp.
Referenced by jubatus::core::recommender::minhash::calc_minhash_values(), jubatus::core::recommender::euclid_lsh::calculate_lsh(), jubatus::core::recommender::lsh::generate_column_base(), jubatus::core::common::portable_mixer< Storage, Diff >::get_hash(), jubatus::core::nearest_neighbor::minhash::hash(), jubatus::core::fv_converter::feature_hasher::hash_feature_keys(), and jubatus::core::nearest_neighbor::random_projection().
{
     // FNV-1 hash function
     uint64_t hash = 14695981039346656037LLU;
     for (size_t i = 0; i < s.size(); ++i) {
       hash *= 1099511628211LLU;
       hash ^= s[i];
     }
     return hash;
   }
The documentation for this class was generated from the following file:
jubatus/core/common/hash.hpp