jubatus_core: jubatus::core::fv_converter::weight_manager Class Reference
jubatus::core::fv_converter::weight_manager Class Reference
#include <weight_manager.hpp>
Public Member Functions
void add_weight (const std::string &key, float weight)
void clear ()
void get_diff (versioned_weight_diff &diff) const
storage::version get_version () const
void get_weight (common::sfv_t &fv) const
void mix (const versioned_weight_diff &lhs, versioned_weight_diff &acc) const
MSGPACK_DEFINE (version_, diff_weights_, master_weights_)
void pack (framework::packer &pk) const
bool put_diff (const versioned_weight_diff &diff)
std::string to_string () const
void unpack (msgpack::object o)
void update_weight (const common::sfv_t &fv)
weight_manager ()
Public Member Functions inherited from jubatus::core::framework::model
virtual ~model ()
Private Member Functions
uint64_t get_document_count () const
size_t get_document_frequency (const std::string &key) const
double get_global_weight (const std::string &key) const
double get_user_weight (const std::string &key) const
Private Attributes
keyword_weights diff_weights_
keyword_weights master_weights_
util::concurrent::mutex mutex_
storage::version version_
Detailed Description
Definition at line 50 of file weight_manager.hpp.
Constructor & Destructor Documentation
jubatus::core::fv_converter::weight_manager::weight_manager ()
Definition at line 65 of file weight_manager.cpp.
     : diff_weights_(),
       master_weights_() {
 }
Member Function Documentation
void jubatus::core::fv_converter::weight_manager::add_weight (const std::string & key, float weight)
Definition at line 108 of file weight_manager.cpp.
References jubatus::core::fv_converter::keyword_weights::add_weight(), diff_weights_, and mutex_.
{
   scoped_lock lk(mutex_);
   diff_weights_.add_weight(key, weight);
 }
void jubatus::core::fv_converter::weight_manager::clear () inline virtual
Reimplemented from jubatus::core::framework::model.
Definition at line 86 of file weight_manager.hpp.
References jubatus::core::fv_converter::keyword_weights::clear(), diff_weights_, master_weights_, and mutex_.
                {
     util::concurrent::scoped_lock lk(mutex_);
     diff_weights_.clear();
     master_weights_.clear();
   }
void jubatus::core::fv_converter::weight_manager::get_diff (versioned_weight_diff & diff) const inline
Definition at line 59 of file weight_manager.hpp.
References diff_weights_, mutex_, and version_.
{
     util::concurrent::scoped_lock lk(mutex_);
     diff = versioned_weight_diff(diff_weights_, version_);
   }
uint64_t jubatus::core::fv_converter::weight_manager::get_document_count () const inline private
Definition at line 118 of file weight_manager.hpp.
References diff_weights_, jubatus::core::fv_converter::keyword_weights::get_document_count(), and master_weights_.
Referenced by get_global_weight().
{
     return diff_weights_.get_document_count() +
         master_weights_.get_document_count();
   }
size_t jubatus::core::fv_converter::weight_manager::get_document_frequency (const std::string & key) const inline private
Definition at line 123 of file weight_manager.hpp.
References diff_weights_, jubatus::core::fv_converter::keyword_weights::get_document_frequency(), and master_weights_.
Referenced by get_global_weight().
{
     return diff_weights_.get_document_frequency(key) +
         master_weights_.get_document_frequency(key);
   }
double jubatus::core::fv_converter::weight_manager::get_global_weight (const std::string & key) const private
Definition at line 84 of file weight_manager.cpp.
References get_document_count(), get_document_frequency(), and get_user_weight().
Referenced by get_weight().
{
   size_t p = key.find_last_of('/');
   if (p == std::string::npos) {
     return 1.0;
   }
   std::string type = key.substr(p + 1);
   if (type == "bin") {
     return 1.0;
   } else if (type == "idf") {
     double doc_count = get_document_count();
     double doc_freq = get_document_frequency(key);
     return std::log((doc_count + 1) / (doc_freq + 1));
   } else if (type == "weight") {
     p = key.find_last_of('#');
     if (p == std::string::npos) {
       return 0;
     } else {
       return get_user_weight(key.substr(0, p));
     }
   } else {
     return 1;
   }
 }
double jubatus::core::fv_converter::weight_manager::get_user_weight (const std::string & key) const inline private
Definition at line 128 of file weight_manager.hpp.
References diff_weights_, jubatus::core::fv_converter::keyword_weights::get_user_weight(), and master_weights_.
Referenced by get_global_weight().
{
     return diff_weights_.get_user_weight(key) +
         master_weights_.get_user_weight(key);
   }
storage::version jubatus::core::fv_converter::weight_manager::get_version () const inline
Definition at line 92 of file weight_manager.hpp.
References version_.
{
     return version_;
   }
void jubatus::core::fv_converter::weight_manager::get_weight (common::sfv_t & fv) const
Definition at line 75 of file weight_manager.cpp.
References get_global_weight(), and mutex_.
{
   scoped_lock lk(mutex_);
   for (common::sfv_t::iterator it = fv.begin(); it != fv.end(); ++it) {
     double global_weight = get_global_weight(it->first);
     it->second = static_cast<float>(it->second * global_weight);
   }
   fv.erase(remove_if(fv.begin(), fv.end(), is_zero()), fv.end());
 }
void jubatus::core::fv_converter::weight_manager::mix (const versioned_weight_diff & lhs, versioned_weight_diff & acc) const inline
Definition at line 76 of file weight_manager.hpp.
References jubatus::core::fv_converter::keyword_weights::merge(), jubatus::core::fv_converter::versioned_weight_diff::version_, and jubatus::core::fv_converter::versioned_weight_diff::weights_.
{
     if (lhs.version_ == acc.version_) {
       acc.weights_.merge(lhs.weights_);
     } else if (lhs.version_ > acc.version_) {
       acc = lhs;
     }
   }
jubatus::core::fv_converter::weight_manager::MSGPACK_DEFINE (version_ , diff_weights_ , master_weights_)
void jubatus::core::fv_converter::weight_manager::pack (framework::packer & pk) const inline virtual
Implements jubatus::core::framework::model.
Definition at line 98 of file weight_manager.hpp.
References mutex_.
{
     util::concurrent::scoped_lock lk(mutex_);
     pk.pack(*this);
   }
bool jubatus::core::fv_converter::weight_manager::put_diff (const versioned_weight_diff & diff) inline
Definition at line 64 of file weight_manager.hpp.
References jubatus::core::fv_converter::keyword_weights::clear(), diff_weights_, jubatus::core::storage::version::increment(), master_weights_, jubatus::core::fv_converter::keyword_weights::merge(), mutex_, jubatus::core::fv_converter::versioned_weight_diff::version_, version_, and jubatus::core::fv_converter::versioned_weight_diff::weights_.
{
     util::concurrent::scoped_lock lk(mutex_);
     if (diff.version_ == version_) {
       master_weights_.merge(diff.weights_);
       diff_weights_.clear();
       version_.increment();
       return true;
     } else {
       return false;
     }
   }
std::string jubatus::core::fv_converter::weight_manager::to_string () const inline
Definition at line 108 of file weight_manager.hpp.
References diff_weights_, master_weights_, mutex_, jubatus::core::fv_converter::keyword_weights::to_string(), and version_.
{
     util::concurrent::scoped_lock lk(mutex_);
     std::stringstream ss;
     ss << "version:" << version_
        << " diff_weights:" << diff_weights_.to_string()
        << " master_weights:" << master_weights_.to_string();
     return ss.str();
   }
void jubatus::core::fv_converter::weight_manager::unpack (msgpack::object o) inline virtual
Implements jubatus::core::framework::model.
Definition at line 103 of file weight_manager.hpp.
References mutex_.
{
     util::concurrent::scoped_lock lk(mutex_);
     o.convert(this);
   }
void jubatus::core::fv_converter::weight_manager::update_weight (const common::sfv_t & fv)
Definition at line 70 of file weight_manager.cpp.
References diff_weights_, mutex_, and jubatus::core::fv_converter::keyword_weights::update_document_frequency().
{
   scoped_lock lk(mutex_);
   diff_weights_.update_document_frequency(fv);
 }
Member Data Documentation
keyword_weights jubatus::core::fv_converter::weight_manager::diff_weights_ private
Definition at line 137 of file weight_manager.hpp.
Referenced by add_weight(), clear(), get_diff(), get_document_count(), get_document_frequency(), get_user_weight(), put_diff(), to_string(), and update_weight().
keyword_weights jubatus::core::fv_converter::weight_manager::master_weights_ private
Definition at line 138 of file weight_manager.hpp.
Referenced by clear(), get_document_count(), get_document_frequency(), get_user_weight(), put_diff(), and to_string().
util::concurrent::mutex jubatus::core::fv_converter::weight_manager::mutex_ mutable private
Definition at line 135 of file weight_manager.hpp.
Referenced by add_weight(), clear(), get_diff(), get_weight(), pack(), put_diff(), to_string(), unpack(), and update_weight().
storage::version jubatus::core::fv_converter::weight_manager::version_ private
Definition at line 136 of file weight_manager.hpp.
Referenced by get_diff(), get_version(), put_diff(), and to_string().
The documentation for this class was generated from the following files:
jubatus/core/fv_converter/weight_manager.hpp
jubatus/core/fv_converter/weight_manager.cpp