jubatus_core: jubatus::core::framework::linear_mixable Class Reference
jubatus::core::framework::linear_mixable Class Reference abstract
#include <linear_mixable.hpp>
Public Member Functions
virtual diff_object convert_diff_object (const msgpack::object &) const =0
virtual void get_diff (packer &) const =0
linear_mixable ()
virtual void mix (const msgpack::object &obj, diff_object) const =0
virtual bool put_diff (const diff_object &obj)=0
virtual ~linear_mixable ()
Public Member Functions inherited from jubatus::core::framework::mixable
virtual storage::version get_version () const
mixable ()
mixable (const std::string &name)
virtual std::set< std::string > mixables () const
virtual ~mixable ()
Additional Inherited Members
Protected Attributes inherited from jubatus::core::framework::mixable
std::set< std::string > mixables_
Detailed Description
Definition at line 38 of file linear_mixable.hpp.
Constructor & Destructor Documentation
jubatus::core::framework::linear_mixable::linear_mixable ()
Definition at line 26 of file linear_mixable.cpp.
                                : mixable("linear_mixable") {
 }
jubatus::core::framework::linear_mixable::~linear_mixable () virtual
Definition at line 29 of file linear_mixable.cpp.
{
 }
Member Function Documentation
virtual diff_object jubatus::core::framework::linear_mixable::convert_diff_object (const msgpack::object &) const pure virtual
Implemented in jubatus::core::framework::linear_mixable_helper< Model, Diff >, jubatus::core::framework::linear_mixable_helper< burst, burst::diff_t >, jubatus::core::framework::linear_mixable_helper< graph_wo_index, graph_wo_index::diff_type >, jubatus::core::framework::linear_mixable_helper< weight_manager, versioned_weight_diff >, jubatus::core::framework::linear_mixable_helper< stat, std::pair< double, size_t > >, jubatus::core::framework::linear_mixable_helper< jubatus::core::bandit::bandit_base, jubatus::core::bandit::bandit_base::diff_t >, jubatus::core::framework::linear_function_mixer, jubatus::core::driver::driver_base::mixable_holder, and jubatus::core::framework::mixable_versioned_table.
Referenced by jubatus::core::driver::driver_base::mixable_holder::convert_diff_object().
virtual void jubatus::core::framework::linear_mixable::get_diff (packer &) const pure virtual
Implemented in jubatus::core::framework::linear_mixable_helper< Model, Diff >, jubatus::core::framework::linear_mixable_helper< burst, burst::diff_t >, jubatus::core::framework::linear_mixable_helper< graph_wo_index, graph_wo_index::diff_type >, jubatus::core::framework::linear_mixable_helper< weight_manager, versioned_weight_diff >, jubatus::core::framework::linear_mixable_helper< stat, std::pair< double, size_t > >, jubatus::core::framework::linear_mixable_helper< jubatus::core::bandit::bandit_base, jubatus::core::bandit::bandit_base::diff_t >, jubatus::core::framework::linear_function_mixer, jubatus::core::driver::driver_base::mixable_holder, and jubatus::core::framework::mixable_versioned_table.
Referenced by jubatus::core::driver::driver_base::mixable_holder::get_diff().
virtual void jubatus::core::framework::linear_mixable::mix (const msgpack::object & obj, diff_object) const pure virtual
Implemented in jubatus::core::framework::linear_mixable_helper< Model, Diff >, jubatus::core::framework::linear_mixable_helper< burst, burst::diff_t >, jubatus::core::framework::linear_mixable_helper< graph_wo_index, graph_wo_index::diff_type >, jubatus::core::framework::linear_mixable_helper< weight_manager, versioned_weight_diff >, jubatus::core::framework::linear_mixable_helper< stat, std::pair< double, size_t > >, jubatus::core::framework::linear_mixable_helper< jubatus::core::bandit::bandit_base, jubatus::core::bandit::bandit_base::diff_t >, jubatus::core::framework::linear_function_mixer, jubatus::core::driver::driver_base::mixable_holder, and jubatus::core::framework::mixable_versioned_table.
Referenced by jubatus::core::driver::driver_base::mixable_holder::mix().
virtual bool jubatus::core::framework::linear_mixable::put_diff (const diff_object & obj) pure virtual
Implemented in jubatus::core::framework::linear_mixable_helper< Model, Diff >, jubatus::core::framework::linear_mixable_helper< burst, burst::diff_t >, jubatus::core::framework::linear_mixable_helper< graph_wo_index, graph_wo_index::diff_type >, jubatus::core::framework::linear_mixable_helper< weight_manager, versioned_weight_diff >, jubatus::core::framework::linear_mixable_helper< stat, std::pair< double, size_t > >, jubatus::core::framework::linear_mixable_helper< jubatus::core::bandit::bandit_base, jubatus::core::bandit::bandit_base::diff_t >, jubatus::core::framework::linear_function_mixer, jubatus::core::driver::driver_base::mixable_holder, and jubatus::core::framework::mixable_versioned_table.
Referenced by jubatus::core::driver::driver_base::mixable_holder::put_diff().
The documentation for this class was generated from the following files:
jubatus/core/framework/linear_mixable.hpp
jubatus/core/framework/linear_mixable.cpp