jubatus_core: jubatus::core::storage::fixed_size_heap< T, Comp > Class Template Reference
jubatus::core::storage::fixed_size_heap< T, Comp > Class Template Reference
#include <fixed_size_heap.hpp>
Public Member Functions
fixed_size_heap (size_t max)
fixed_size_heap (size_t max, const Comp &comp)
size_t get_max_size () const
void get_sorted (std::vector< T > &v) const
void push (const T &v)
size_t size () const
Private Attributes
const Comp comp_
std::vector< T > data_
const size_t max_size_
Detailed Description
template<typename T, typename Comp = std::less<T>>
class jubatus::core::storage::fixed_size_heap< T, Comp >
Definition at line 29 of file fixed_size_heap.hpp.
Constructor & Destructor Documentation
template<typename T, typename Comp = std::less<T>> jubatus::core::storage::fixed_size_heap< T, Comp >::fixed_size_heap (size_t max) inline explicit
Definition at line 31 of file fixed_size_heap.hpp.
       : max_size_(max),
         comp_(Comp()) {
   }
template<typename T, typename Comp = std::less<T>> jubatus::core::storage::fixed_size_heap< T, Comp >::fixed_size_heap (size_t max, const Comp & comp) inline
Definition at line 36 of file fixed_size_heap.hpp.
       : max_size_(max),
         comp_(comp) {
   }
Member Function Documentation
template<typename T, typename Comp = std::less<T>> size_t jubatus::core::storage::fixed_size_heap< T, Comp >::get_max_size () const inline
Definition at line 66 of file fixed_size_heap.hpp.
References jubatus::core::storage::fixed_size_heap< T, Comp >::max_size_.
{
     return max_size_;
   }
template<typename T, typename Comp = std::less<T>> void jubatus::core::storage::fixed_size_heap< T, Comp >::get_sorted (std::vector< T > & v) const inline
Definition at line 56 of file fixed_size_heap.hpp.
References jubatus::core::storage::fixed_size_heap< T, Comp >::comp_, and jubatus::core::storage::fixed_size_heap< T, Comp >::data_.
Referenced by jubatus::core::storage::inverted_index_storage::calc_scores(), jubatus::core::nearest_neighbor::euclid_lsh::neighbor_row_from_hash(), jubatus::core::nearest_neighbor::ranking_hamming_bit_vectors(), and jubatus::core::storage::bit_index_storage::similar_row().
{
     std::vector<T> vec(data_);
     std::sort(vec.begin(), vec.end(), comp_);
     v.swap(vec);
   }
template<typename T, typename Comp = std::less<T>> void jubatus::core::storage::fixed_size_heap< T, Comp >::push (const T & v) inline
Definition at line 41 of file fixed_size_heap.hpp.
References jubatus::core::storage::fixed_size_heap< T, Comp >::comp_, jubatus::core::storage::fixed_size_heap< T, Comp >::data_, jubatus::core::storage::fixed_size_heap< T, Comp >::max_size_, and jubatus::core::common::jsonconfig::v().
Referenced by jubatus::core::storage::inverted_index_storage::calc_scores(), jubatus::core::nearest_neighbor::euclid_lsh::neighbor_row_from_hash(), jubatus::core::nearest_neighbor::ranking_hamming_bit_vectors(), and jubatus::core::storage::similar_row_one().
{
     if (data_.size() < max_size_) {
       data_.push_back(v);
       if (data_.size() == max_size_) {
         std::make_heap(data_.begin(), data_.end(), comp_);
       }
     } else {
       if (max_size_ > 0 && comp_(v, data_.front())) {
         std::pop_heap(data_.begin(), data_.end(), comp_);
         data_.back() = v;
         std::push_heap(data_.begin(), data_.end(), comp_);
       }
     }
   }
template<typename T, typename Comp = std::less<T>> size_t jubatus::core::storage::fixed_size_heap< T, Comp >::size () const inline
Definition at line 62 of file fixed_size_heap.hpp.
References jubatus::core::storage::fixed_size_heap< T, Comp >::data_.
                       {
     return data_.size();
   }
Member Data Documentation
template<typename T, typename Comp = std::less<T>> const Comp jubatus::core::storage::fixed_size_heap< T, Comp >::comp_ private
Definition at line 73 of file fixed_size_heap.hpp.
Referenced by jubatus::core::storage::fixed_size_heap< T, Comp >::get_sorted(), and jubatus::core::storage::fixed_size_heap< T, Comp >::push().
template<typename T, typename Comp = std::less<T>> std::vector<T> jubatus::core::storage::fixed_size_heap< T, Comp >::data_ private
Definition at line 71 of file fixed_size_heap.hpp.
Referenced by jubatus::core::storage::fixed_size_heap< T, Comp >::get_sorted(), jubatus::core::storage::fixed_size_heap< T, Comp >::push(), and jubatus::core::storage::fixed_size_heap< T, Comp >::size().
template<typename T, typename Comp = std::less<T>> const size_t jubatus::core::storage::fixed_size_heap< T, Comp >::max_size_ private
Definition at line 72 of file fixed_size_heap.hpp.
Referenced by jubatus::core::storage::fixed_size_heap< T, Comp >::get_max_size(), and jubatus::core::storage::fixed_size_heap< T, Comp >::push().
The documentation for this class was generated from the following file:
jubatus/core/storage/fixed_size_heap.hpp