jubatus_core: jubatus::core::classifier::ClassifierUtil Class Reference
jubatus::core::classifier::ClassifierUtil Class Reference
#include <classifier_util.hpp>
Static Public Member Functions
template<class T , class U >
static void get_two (const T &t, const std::string &label1, const std::string &label2, U &u1, U &u2)
Detailed Description
Definition at line 26 of file classifier_util.hpp.
Member Function Documentation
template<class T , class U > static void jubatus::core::classifier::ClassifierUtil::get_two (const T & t, const std::string & label1, const std::string & label2, U & u1, U & u2) inline static
Definition at line 29 of file classifier_util.hpp.
Referenced by jubatus::core::classifier::arow::update(), jubatus::core::classifier::normal_herd::update(), and jubatus::core::classifier::confidence_weighted::update().
              {
     for (size_t i = 0; i < t.size(); ++i) {
       if (t[i].first == label1) {
         u1 = t[i].second;
       } else if (t[i].first == label2) {
         u2 = t[i].second;
       }
     }
   }
The documentation for this class was generated from the following file:
jubatus/core/classifier/classifier_util.hpp