jubatus_core: jubatus::core::clustering::eigen_feature_mapper Class Reference
jubatus::core::clustering::eigen_feature_mapper Class Reference
#include <eigen_feature_mapper.hpp>
Public Member Functions
void clear ()
eigen_wsvec_list_t convert (const wplist &src, bool update_map=true)
eigen_svec_list_t convert (const std::vector< common::sfv_t > &src, bool update_map=true)
eigen_wsvec_t convert (const weighted_point &src, bool update_map=true)
eigen_svec_t convert (const common::sfv_t &src, bool update_map=true)
eigen_svec_t convertc (const common::sfv_t &src) const
eigen_feature_mapper ()
int get_dimension ()
wplist revert (const eigen_wsvec_list_t &src) const
std::vector< common::sfv_t > revert (const eigen_svec_list_t &src) const
common::sfv_t revert (const eigen_svec_t &src) const
weighted_point revert (const eigen_wsvec_t &src) const
Private Member Functions
void insert (const std::pair< std::string, float > &item, bool update_map, eigen_svec_t &dst)
void insertc (const std::pair< std::string, float > &, eigen_svec_t &dst) const
void rinsert (const std::pair< int, float > &, common::sfv_t &dst) const
Private Attributes
int d_
jubatus::util::data::unordered_map< std::string, size_t > map_
jubatus::util::data::unordered_map< size_t, std::string > rmap_
Detailed Description
Definition at line 31 of file eigen_feature_mapper.hpp.
Constructor & Destructor Documentation
jubatus::core::clustering::eigen_feature_mapper::eigen_feature_mapper () inline
Definition at line 33 of file eigen_feature_mapper.hpp.
 : d_(0) {}
Member Function Documentation
void jubatus::core::clustering::eigen_feature_mapper::clear ()
Definition at line 30 of file eigen_feature_mapper.cpp.
References d_, map_, and rmap_.
Referenced by jubatus::core::clustering::gmm_clustering_method::batch_update().
{
   map_.clear();
   rmap_.clear();
   d_ = 0;
 }
eigen_wsvec_list_t jubatus::core::clustering::eigen_feature_mapper::convert (const wplist & src, bool update_map = true)
Definition at line 84 of file eigen_feature_mapper.cpp.
References d_, and jubatus::core::common::jsonconfig::v().
Referenced by jubatus::core::clustering::gmm_clustering_method::batch_update(), and convert().
                      {
   eigen_wsvec_list_t ret(src.size());
   eigen_wsvec_list_t::iterator ob = ret.begin();
   wplist::const_iterator ib = src.begin();
   while (ib != src.end()) {
     *ob = convert(*ib, update_map);
     ++ob;
     ++ib;
   }
   for (ob = ret.begin(); ob != ret.end(); ++ob) {
     eigen_svec_t v(d_);
     for (eigen_svec_t::InnerIterator it(ob->data); it; ++it) {
       v.coeffRef(it.index()) = it.value();
     }
     ob->data = v;
   }
   return ret;
 }
eigen_svec_list_t jubatus::core::clustering::eigen_feature_mapper::convert (const std::vector< common::sfv_t > & src, bool update_map = true)
eigen_wsvec_t jubatus::core::clustering::eigen_feature_mapper::convert (const weighted_point & src, bool update_map = true)
Definition at line 58 of file eigen_feature_mapper.cpp.
References convert(), jubatus::core::clustering::eigen_wsvec_t::data, jubatus::core::clustering::weighted_point::data, jubatus::core::clustering::eigen_wsvec_t::weight, and jubatus::core::clustering::weighted_point::weight.
                      {
   eigen_wsvec_t ret;
   ret.data = convert(src.data, update_map);
   ret.weight = src.weight;
   return ret;
 }
eigen_svec_t jubatus::core::clustering::eigen_feature_mapper::convert (const common::sfv_t & src, bool update_map = true)
Definition at line 40 of file eigen_feature_mapper.cpp.
References d_, and insert().
                      {
   eigen_svec_t ret(d_);
   for (common::sfv_t::const_iterator it = src.begin(); it != src.end(); ++it) {
     insert(*it, update_map, ret);
   }
   return ret;
 }
eigen_svec_t jubatus::core::clustering::eigen_feature_mapper::convertc (const common::sfv_t & src) const
Definition at line 50 of file eigen_feature_mapper.cpp.
References d_, and insertc().
Referenced by jubatus::core::clustering::gmm_clustering_method::get_nearest_center(), and jubatus::core::clustering::gmm_clustering_method::get_nearest_center_index().
{
   eigen_svec_t ret(d_);
   for (common::sfv_t::const_iterator it = src.begin(); it != src.end(); ++it) {
     insertc(*it, ret);
   }
   return ret;
 }
int jubatus::core::clustering::eigen_feature_mapper::get_dimension ()
Definition at line 36 of file eigen_feature_mapper.cpp.
References d_.
Referenced by jubatus::core::clustering::gmm_clustering_method::batch_update().
{
   return d_;
 }
void jubatus::core::clustering::eigen_feature_mapper::insert (const std::pair< std::string, float > & item, bool update_map, eigen_svec_t & dst) private
Definition at line 147 of file eigen_feature_mapper.cpp.
References d_, map_, and rmap_.
Referenced by convert().
{
   if (dst.rows() < d_) {
     dst.resize(d_);
   }
   if (map_.find(item.first) != map_.end()) {
     dst.coeffRef(map_[item.first]) = item.second;
   } else if (update_map) {
     rmap_[d_] = item.first;
     map_[item.first] = d_++;
     insert(item, update_map, dst);
   }
 }
void jubatus::core::clustering::eigen_feature_mapper::insertc (const std::pair< std::string, float > & , eigen_svec_t & dst) const private
Definition at line 163 of file eigen_feature_mapper.cpp.
References d_, and map_.
Referenced by convertc().
{
   if (dst.rows() < d_) {
     dst.resize(d_);
   }
   if (map_.find(item.first) != map_.end()) {
     dst.coeffRef((map_.find(item.first))->second) = item.second;
   }
 }
wplist jubatus::core::clustering::eigen_feature_mapper::revert (const eigen_wsvec_list_t & src) const
Definition at line 134 of file eigen_feature_mapper.cpp.
Referenced by jubatus::core::clustering::gmm_clustering_method::batch_update(), jubatus::core::clustering::gmm_clustering_method::get_nearest_center(), and revert().
{
   wplist ret(src.size());
   eigen_wsvec_list_t::const_iterator ib = src.begin();
   wplist::iterator ob = ret.begin();
   while (ib != src.end()) {
     *ob = revert(*ib);
     ++ob;
     ++ib;
   }
   return ret;
 }
std::vector< common::sfv_t > jubatus::core::clustering::eigen_feature_mapper::revert (const eigen_svec_list_t & src) const
Definition at line 121 of file eigen_feature_mapper.cpp.
References revert().
{
   std::vector<common::sfv_t> ret(src.size());
   eigen_svec_list_t::const_iterator ib = src.begin();
   std::vector<common::sfv_t>::iterator ob = ret.begin();
   while (ib != src.end()) {
     *ob = revert(*ib);
     ++ob;
     ++ib;
   }
   return ret;
 }
common::sfv_t jubatus::core::clustering::eigen_feature_mapper::revert (const eigen_svec_t & src) const
Definition at line 105 of file eigen_feature_mapper.cpp.
References rinsert().
{
   common::sfv_t ret;
   for (eigen_svec_t::InnerIterator it(src); it; ++it) {
     rinsert(std::make_pair(it.row(), static_cast<float>(it.value())), ret);
   }
   return ret;
 }
weighted_point jubatus::core::clustering::eigen_feature_mapper::revert (const eigen_wsvec_t & src) const
Definition at line 113 of file eigen_feature_mapper.cpp.
References jubatus::core::clustering::eigen_wsvec_t::data, jubatus::core::clustering::weighted_point::data, revert(), jubatus::core::clustering::eigen_wsvec_t::weight, and jubatus::core::clustering::weighted_point::weight.
{
   weighted_point ret;
   ret.weight = src.weight;
   ret.data = revert(src.data);
   return ret;
 }
void jubatus::core::clustering::eigen_feature_mapper::rinsert (const std::pair< int, float > & , common::sfv_t & dst) const private
Definition at line 174 of file eigen_feature_mapper.cpp.
References rmap_.
Referenced by revert().
{
   if (rmap_.find(item.first) != rmap_.end()) {
     dst.push_back(
         make_pair((rmap_.find(item.first))->second, item.second));
   }
 }
Member Data Documentation
int jubatus::core::clustering::eigen_feature_mapper::d_ private
Definition at line 65 of file eigen_feature_mapper.hpp.
Referenced by clear(), convert(), convertc(), get_dimension(), insert(), and insertc().
jubatus::util::data::unordered_map<std::string, size_t> jubatus::core::clustering::eigen_feature_mapper::map_ private
Definition at line 49 of file eigen_feature_mapper.hpp.
Referenced by clear(), insert(), and insertc().
jubatus::util::data::unordered_map<size_t, std::string> jubatus::core::clustering::eigen_feature_mapper::rmap_ private
Definition at line 50 of file eigen_feature_mapper.hpp.
Referenced by clear(), insert(), and rinsert().
The documentation for this class was generated from the following files:
jubatus/core/clustering/eigen_feature_mapper.hpp
jubatus/core/clustering/eigen_feature_mapper.cpp