jubatus_core: jubatus::core::bandit::ucb1 Class Reference
jubatus::core::bandit::ucb1 Class Reference
#include <ucb1.hpp>
Public Member Functions
void clear ()
bool delete_arm (const std::string &arm_id)
arm_info_map get_arm_info (const std::string &player_id) const
void get_diff (diff_t &diff) const
void mix (const diff_t &lhs, diff_t &rhs) const
std::string name () const
void pack (framework::packer &pk) const
bool put_diff (const diff_t &diff)
bool register_arm (const std::string &arm_id)
bool register_reward (const std::string &player_id, const std::string &arm_id, double reward)
bool reset (const std::string &player_id)
std::string select_arm (const std::string &player_id)
ucb1 ()
void unpack (msgpack::object o)
Public Member Functions inherited from jubatus::core::bandit::bandit_base
bandit_base ()
core::storage::version get_version () const
virtual ~bandit_base ()
Private Attributes
summation_storage s_
Additional Inherited Members
Public Types inherited from jubatus::core::bandit::bandit_base
typedef jubatus::util::data::unordered_map< std::string, arm_info_map > diff_t
Detailed Description
Definition at line 29 of file ucb1.hpp.
Constructor & Destructor Documentation
jubatus::core::bandit::ucb1::ucb1 ()
Definition at line 28 of file ucb1.cpp.
            {
 }
Member Function Documentation
void jubatus::core::bandit::ucb1::clear () virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 82 of file ucb1.cpp.
References jubatus::core::bandit::summation_storage::clear(), and s_.
                  {
   s_.clear();
 }
bool jubatus::core::bandit::ucb1::delete_arm (const std::string & arm_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 65 of file ucb1.cpp.
References jubatus::core::bandit::summation_storage::delete_arm(), and s_.
{
   return s_.delete_arm(arm_id);
 }
arm_info_map jubatus::core::bandit::ucb1::get_arm_info (const std::string & player_id) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 75 of file ucb1.cpp.
References jubatus::core::bandit::summation_storage::get_arm_info_map(), and s_.
{
   return s_.get_arm_info_map(arm_id);
 }
void jubatus::core::bandit::ucb1::get_diff (diff_t & diff) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 93 of file ucb1.cpp.
References jubatus::core::bandit::summation_storage::get_diff(), and s_.
{
   s_.get_diff(diff);
 }
void jubatus::core::bandit::ucb1::mix (const diff_t & lhs, diff_t & rhs) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 99 of file ucb1.cpp.
References jubatus::core::bandit::summation_storage::mix(), and s_.
{
   s_.mix(lhs, rhs);
 }
std::string jubatus::core::bandit::ucb1::name () const inline virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 47 of file ucb1.hpp.
{
     return "ucb1";
   }
void jubatus::core::bandit::ucb1::pack (framework::packer & pk) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 86 of file ucb1.cpp.
References s_.
{
   pk.pack(s_);
 }
bool jubatus::core::bandit::ucb1::put_diff (const diff_t & diff) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 96 of file ucb1.cpp.
References jubatus::core::bandit::summation_storage::put_diff(), and s_.
{
   return s_.put_diff(diff);
 }
bool jubatus::core::bandit::ucb1::register_arm (const std::string & arm_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 62 of file ucb1.cpp.
References jubatus::core::bandit::summation_storage::register_arm(), and s_.
{
   return s_.register_arm(arm_id);
 }
bool jubatus::core::bandit::ucb1::register_reward (const std::string & player_id, const std::string & arm_id, double reward) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 69 of file ucb1.cpp.
References jubatus::core::bandit::summation_storage::register_reward(), and s_.
{
   return s_.register_reward(player_id, arm_id, reward);
 }
bool jubatus::core::bandit::ucb1::reset (const std::string & player_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 79 of file ucb1.cpp.
References jubatus::core::bandit::summation_storage::reset(), and s_.
{
   return s_.reset(player_id);
 }
std::string jubatus::core::bandit::ucb1::select_arm (const std::string & player_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 31 of file ucb1.cpp.
References jubatus::core::bandit::summation_storage::get_arm_ids(), jubatus::core::bandit::summation_storage::get_arm_info(), JUBATUS_EXCEPTION, s_, jubatus::core::bandit::arm_info::trial_count, and jubatus::core::bandit::arm_info::weight.
{
   const std::vector<std::string>& arms = s_.get_arm_ids();
   if (arms.empty()) {
     throw JUBATUS_EXCEPTION(
         common::exception::runtime_error("arm is not registered"));
   }
   int total_trial = 0;
   for (size_t i = 0; i < arms.size(); ++i) {
     const arm_info& a = s_.get_arm_info(player_id, arms[i]);
     if (a.trial_count == 0) {
       return arms[i];
     }
     total_trial += a.trial_count;
   }
   double log_total_trial = std::log(total_trial);
   double score_max = -DBL_MAX;
   std::string result;
   for (size_t i = 0; i < arms.size(); ++i) {
     const arm_info& a = s_.get_arm_info(player_id, arms[i]);
     double exp = a.weight / a.trial_count;
     double score = exp + std::sqrt(2 * log_total_trial / a.trial_count);
     if (score > score_max) {
       score_max = score;
       result = arms[i];
     }
   }
   return result;
 }
void jubatus::core::bandit::ucb1::unpack (msgpack::object o) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 89 of file ucb1.cpp.
References s_.
{
   o.convert(&s_);
 }
Member Data Documentation
summation_storage jubatus::core::bandit::ucb1::s_ private
Definition at line 59 of file ucb1.hpp.
Referenced by clear(), delete_arm(), get_arm_info(), get_diff(), mix(), pack(), put_diff(), register_arm(), register_reward(), reset(), select_arm(), and unpack().
The documentation for this class was generated from the following files:
jubatus/core/bandit/ucb1.hpp
jubatus/core/bandit/ucb1.cpp