jubatus_core: jubatus::core::common::exception::jubatus_exception Class Reference
jubatus::core::common::exception::jubatus_exception Class Reference abstract
#include <exception.hpp>
Public Member Functions
std::string diagnostic_information (bool display_what=false) const
error_info_list_t error_info () const
jubatus_exception () throw ()
std::string name () const throw ()
virtual exception_thrower_ptr thrower () const =0
virtual const char * what () const throw ()
virtual ~jubatus_exception () throw ()
Private Attributes
std::string exception_class_name_
error_info_list_t info_list_
Friends
template<class Exception >
const Exception & add_info (const Exception &e, jubatus::util::lang::shared_ptr< error_info_base > info)
Detailed Description
Definition at line 90 of file exception.hpp.
Constructor & Destructor Documentation
jubatus::core::common::exception::jubatus_exception::jubatus_exception () throw () inline
Definition at line 92 of file exception.hpp.
{
   }
virtual jubatus::core::common::exception::jubatus_exception::~jubatus_exception () throw () inline virtual
Definition at line 94 of file exception.hpp.
{
   }
Member Function Documentation
std::string jubatus::core::common::exception::jubatus_exception::diagnostic_information (bool display_what = false) const
Definition at line 31 of file exception.cpp.
References info_list_, and what().
{
   std::ostringstream tmp;
   tmp << "Dynamic exception type: ";
   tmp << jubatus::util::lang::demangle(typeid(*this).name());
   if (display_what && strcmp(what(), "")) {
     tmp << "::what: " << what();
   }
   tmp << '\n';
   size_t frame = 0;
   for (error_info_list_t::const_iterator it = info_list_.begin(), end =
       info_list_.end(); it != end; ++it) {
     if ((*it)->splitter()) {
       frame++;
       continue;
     }
     tmp << "    #" << frame << " [" << (*it)->tag_typeid_name() << "] = "
         << (*it)->as_string() << '\n';
   }
   return tmp.str();
 }
error_info_list_t jubatus::core::common::exception::jubatus_exception::error_info () const
Definition at line 27 of file exception.cpp.
References info_list_.
{
   return info_list_;
 }
std::string jubatus::core::common::exception::jubatus_exception::name () const throw () inline
Definition at line 104 of file exception.hpp.
References exception_class_name_.
Referenced by what().
{
     // does not assume multithreading
     if (exception_class_name_.empty()) {
       exception_class_name_ = jubatus::util::lang::demangle(
           typeid(*this).name());
     }
     return exception_class_name_;
   }
virtual exception_thrower_ptr jubatus::core::common::exception::jubatus_exception::thrower () const pure virtual
Implemented in jubatus::core::common::exception::jubaexception< Exception >, jubatus::core::common::exception::jubaexception< stat_error >, jubatus::core::common::exception::jubaexception< config_exception >, jubatus::core::common::exception::jubaexception< runtime_error >, jubatus::core::common::exception::jubaexception< unknown_exception >, jubatus::core::common::exception::jubaexception< cast_check_error >, jubatus::core::common::exception::jubaexception< invalid_row_set >, jubatus::core::common::exception::jubaexception< config_not_set >, jubatus::core::common::exception::jubaexception< bit_vector_unmatch_exception >, jubatus::core::common::exception::jubaexception< nearest_neighbor_exception >, jubatus::core::common::exception::jubaexception< config_error >, jubatus::core::common::exception::jubaexception< storage_exception >, and jubatus::core::common::exception::jubaexception< storage_not_set >.
Referenced by jubatus::core::common::exception::get_current_exception().
virtual const char* jubatus::core::common::exception::jubatus_exception::what () const throw () inline virtual
Reimplemented in jubatus::core::common::config_not_set, jubatus::core::common::exception::runtime_error, jubatus::core::common::exception::unknown_exception, jubatus::core::storage::bit_vector_unmatch_exception, jubatus::core::storage::invalid_row_set, jubatus::core::stat::stat_error, jubatus::core::common::jsonconfig::config_error, jubatus::core::nearest_neighbor::nearest_neighbor_exception, and jubatus::core::storage::storage_exception.
Definition at line 114 of file exception.hpp.
References exception_class_name_, and name().
Referenced by diagnostic_information().
{
     name();
     return exception_class_name_.c_str();
   }
Friends And Related Function Documentation
template<class Exception > const Exception& add_info (const Exception & e, jubatus::util::lang::shared_ptr< error_info_base > info) friend
Definition at line 128 of file exception.hpp.
{
   e.info_list_.push_back(info);
   return e;
 }
Member Data Documentation
std::string jubatus::core::common::exception::jubatus_exception::exception_class_name_ mutable private
Definition at line 123 of file exception.hpp.
Referenced by name(), and what().
error_info_list_t jubatus::core::common::exception::jubatus_exception::info_list_ mutable private
Definition at line 124 of file exception.hpp.
Referenced by diagnostic_information(), and error_info().
The documentation for this class was generated from the following files:
jubatus/core/common/exception.hpp
jubatus/core/common/exception.cpp