jubatus_core: jubatus::core::burst::result_storage Class Reference
jubatus::core::burst::result_storage Class Reference
#include <result_storage.hpp>
Classes
class impl_
Public Types
typedef std::vector< result_t > diff_t
typedef burst_result result_t
Public Member Functions
diff_t get_diff () const
result_t get_latest_result () const
result_t get_result_at (double pos) const
void pack (framework::packer &packer) const
void put_diff (const diff_t &diff)
result_storage (int stored_results_max)
void store (const result_t &result)
void unpack (msgpack::object o)
~result_storage ()
Private Attributes
jubatus::util::lang::scoped_ptr< impl_ > p_
Detailed Description
Definition at line 31 of file result_storage.hpp.
Member Typedef Documentation
typedef std::vector<result_t> jubatus::core::burst::result_storage::diff_t
Definition at line 43 of file result_storage.hpp.
typedef burst_result jubatus::core::burst::result_storage::result_t
Definition at line 33 of file result_storage.hpp.
Constructor & Destructor Documentation
jubatus::core::burst::result_storage::result_storage (int stored_results_max) explicit
Definition at line 122 of file result_storage.cpp.
     : p_(new impl_(stored_results_max)) {
 }
jubatus::core::burst::result_storage::~result_storage ()
Definition at line 126 of file result_storage.cpp.
{
 }
Member Function Documentation
result_storage::diff_t jubatus::core::burst::result_storage::get_diff () const
Definition at line 144 of file result_storage.cpp.
References JUBATUS_ASSERT, and p_.
{
   JUBATUS_ASSERT(p_);
   return p_->get_diff();
 }
burst_result jubatus::core::burst::result_storage::get_latest_result () const
Definition at line 134 of file result_storage.cpp.
References JUBATUS_ASSERT, and p_.
Referenced by jubatus::core::burst::burst::impl_::get_all_bursted_results(), and jubatus::core::burst::burst::impl_::get_result().
{
   JUBATUS_ASSERT(p_);
   return p_->get_latest_result();
 }
burst_result jubatus::core::burst::result_storage::get_result_at (double pos) const
Definition at line 139 of file result_storage.cpp.
References JUBATUS_ASSERT, and p_.
Referenced by jubatus::core::burst::aggregator::impl_::flush_results(), jubatus::core::burst::burst::impl_::get_all_bursted_results_at(), and jubatus::core::burst::burst::impl_::get_result_at().
{
   JUBATUS_ASSERT(p_);
   return p_->get_result_at(pos);
 }
void jubatus::core::burst::result_storage::pack (framework::packer & packer) const
Definition at line 154 of file result_storage.cpp.
References JUBATUS_ASSERT, and p_.
{
   JUBATUS_ASSERT(p_);
   packer.pack(*p_);
 }
void jubatus::core::burst::result_storage::put_diff (const diff_t & diff)
Definition at line 149 of file result_storage.cpp.
References JUBATUS_ASSERT, and p_.
{
   JUBATUS_ASSERT(p_);
   p_->put_diff(diff);
 }
void jubatus::core::burst::result_storage::store (const result_t & result)
Definition at line 129 of file result_storage.cpp.
References JUBATUS_ASSERT, and p_.
Referenced by jubatus::core::burst::aggregator::impl_::flush_results().
{
   JUBATUS_ASSERT(p_);
   p_->store(result);
 }
void jubatus::core::burst::result_storage::unpack (msgpack::object o)
Definition at line 159 of file result_storage.cpp.
References JUBATUS_ASSERT, and p_.
{
   JUBATUS_ASSERT(p_);
   o.convert(p_.get());
 }
Member Data Documentation
jubatus::util::lang::scoped_ptr<impl_> jubatus::core::burst::result_storage::p_ private
Definition at line 51 of file result_storage.hpp.
Referenced by get_diff(), get_latest_result(), get_result_at(), pack(), put_diff(), store(), and unpack().
The documentation for this class was generated from the following files:
jubatus/core/burst/result_storage.hpp
jubatus/core/burst/result_storage.cpp