jubatus_core: jubatus::core::recommender::nearest_neighbor_recommender Class Reference
jubatus::core::recommender::nearest_neighbor_recommender Class Reference
#include <nearest_neighbor_recommender.hpp>
Classes
class unlearning_callback
Public Member Functions
void clear ()
void clear_row (const std::string &id)
void get_all_row_ids (std::vector< std::string > &ids) const
framework::mixable * get_mixable () const
nearest_neighbor_recommender (jubatus::util::lang::shared_ptr< nearest_neighbor::nearest_neighbor_base > nearest_neighbor_engine)
nearest_neighbor_recommender (jubatus::util::lang::shared_ptr< nearest_neighbor::nearest_neighbor_base > nearest_neighbor_engine, jubatus::util::lang::shared_ptr< unlearner::unlearner_base > unlearner)
void neighbor_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
void pack (framework::packer &packer) const
void similar_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
std::string type () const
void unpack (msgpack::object o)
void update_row (const std::string &id, const sfv_diff_t &diff)
Public Member Functions inherited from jubatus::core::recommender::recommender_base
void complete_row (const std::string &id, common::sfv_t &ret) const
void complete_row (const common::sfv_t &query, common::sfv_t &ret) const
void decode_row (const std::string &id, common::sfv_t &ret) const
virtual const core::storage::recommender_storage_base * get_const_storage () const
virtual void neighbor_row (const std::string &id, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
recommender_base ()
virtual void similar_row (const std::string &id, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
virtual ~recommender_base ()
Public Member Functions inherited from jubatus::core::framework::model
virtual ~model ()
Private Member Functions
jubatus::util::lang::shared_ptr< const table::column_table > get_const_table () const
jubatus::util::lang::shared_ptr< table::column_table > get_table ()
jubatus::util::lang::shared_ptr< unlearner::unlearner_base > get_unlearner ()
void unlearn_row (const std::string &id)
Private Attributes
jubatus::util::lang::shared_ptr< nearest_neighbor::nearest_neighbor_base > nearest_neighbor_engine_
jubatus::util::lang::shared_ptr< unlearner::unlearner_base > unlearner_
Additional Inherited Members
Static Public Member Functions inherited from jubatus::core::recommender::recommender_base
static float calc_l2norm (const common::sfv_t &query)
static float calc_similality (common::sfv_t &q1, common::sfv_t &q2)
Protected Attributes inherited from jubatus::core::recommender::recommender_base
core::storage::sparse_matrix_storage orig_
Static Protected Attributes inherited from jubatus::core::recommender::recommender_base
static const uint64_t complete_row_similar_num_ = 128
Detailed Description
Definition at line 33 of file nearest_neighbor_recommender.hpp.
Constructor & Destructor Documentation
jubatus::core::recommender::nearest_neighbor_recommender::nearest_neighbor_recommender (jubatus::util::lang::shared_ptr< nearest_neighbor::nearest_neighbor_base > nearest_neighbor_engine) explicit
Definition at line 46 of file nearest_neighbor_recommender.cpp.
     : nearest_neighbor_engine_(nearest_neighbor_engine) {
 }
jubatus::core::recommender::nearest_neighbor_recommender::nearest_neighbor_recommender (jubatus::util::lang::shared_ptr< nearest_neighbor::nearest_neighbor_base > nearest_neighbor_engine, jubatus::util::lang::shared_ptr< unlearner::unlearner_base > unlearner)
Definition at line 52 of file nearest_neighbor_recommender.cpp.
References unlearner_.
     : nearest_neighbor_engine_(nearest_neighbor_engine),
       unlearner_(unlearner) {
   unlearner_->set_callback(unlearning_callback(this));
 }
Member Function Documentation
void jubatus::core::recommender::nearest_neighbor_recommender::clear () virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 75 of file nearest_neighbor_recommender.cpp.
References jubatus::core::storage::sparse_matrix_storage::clear(), nearest_neighbor_engine_, jubatus::core::recommender::recommender_base::orig_, and unlearner_.
{
   orig_.clear();
   nearest_neighbor_engine_->clear();
   if (unlearner_) {
     unlearner_->clear();
   }
 }
void jubatus::core::recommender::nearest_neighbor_recommender::clear_row (const std::string & id) virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 83 of file nearest_neighbor_recommender.cpp.
References get_table(), jubatus::core::recommender::recommender_base::orig_, jubatus::core::storage::sparse_matrix_storage::remove_row(), and unlearner_.
{
   orig_.remove_row(id);
   get_table()->delete_row(id);
   if (unlearner_) {
     unlearner_->remove(id);
   }
 }
void jubatus::core::recommender::nearest_neighbor_recommender::get_all_row_ids (std::vector< std::string > & ids) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 114 of file nearest_neighbor_recommender.cpp.
References nearest_neighbor_engine_.
{
   nearest_neighbor_engine_->get_all_row_ids(ids);
 }
jubatus::util::lang::shared_ptr< const table::column_table > jubatus::core::recommender::nearest_neighbor_recommender::get_const_table () const private virtual
Reimplemented from jubatus::core::recommender::recommender_base.
Definition at line 147 of file nearest_neighbor_recommender.cpp.
References nearest_neighbor_engine_.
{
   return nearest_neighbor_engine_->get_const_table();
 }
framework::mixable * jubatus::core::recommender::nearest_neighbor_recommender::get_mixable () const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 123 of file nearest_neighbor_recommender.cpp.
References nearest_neighbor_engine_.
{
   return nearest_neighbor_engine_->get_mixable();
 }
jubatus::util::lang::shared_ptr< table::column_table > jubatus::core::recommender::nearest_neighbor_recommender::get_table () private virtual
Reimplemented from jubatus::core::recommender::recommender_base.
Definition at line 142 of file nearest_neighbor_recommender.cpp.
References nearest_neighbor_engine_.
Referenced by clear_row(), and unlearn_row().
{
   return nearest_neighbor_engine_->get_table();
 }
jubatus::util::lang::shared_ptr< unlearner::unlearner_base > jubatus::core::recommender::nearest_neighbor_recommender::get_unlearner () private virtual
Reimplemented from jubatus::core::recommender::recommender_base.
Definition at line 152 of file nearest_neighbor_recommender.cpp.
References unlearner_.
{
   return unlearner_;
 }
void jubatus::core::recommender::nearest_neighbor_recommender::neighbor_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 68 of file nearest_neighbor_recommender.cpp.
References nearest_neighbor_engine_.
{
   nearest_neighbor_engine_->neighbor_row(query, ids, ret_num);
 }
void jubatus::core::recommender::nearest_neighbor_recommender::pack (framework::packer & packer) const virtual
Implements jubatus::core::framework::model.
Definition at line 127 of file nearest_neighbor_recommender.cpp.
References nearest_neighbor_engine_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::pack().
{
   packer.pack_array(2);
   orig_.pack(packer);
   nearest_neighbor_engine_->pack(packer);
 }
void jubatus::core::recommender::nearest_neighbor_recommender::similar_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 61 of file nearest_neighbor_recommender.cpp.
References nearest_neighbor_engine_.
{
   nearest_neighbor_engine_->similar_row(query, ids, ret_num);
 }
std::string jubatus::core::recommender::nearest_neighbor_recommender::type () const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 119 of file nearest_neighbor_recommender.cpp.
References nearest_neighbor_engine_.
{
   return "nearest_neighbor_recommender:" + nearest_neighbor_engine_->type();
 }
void jubatus::core::recommender::nearest_neighbor_recommender::unlearn_row (const std::string & id) private
Callback from unlearner
Definition at line 94 of file nearest_neighbor_recommender.cpp.
References get_table(), jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::remove_row().
Referenced by jubatus::core::recommender::nearest_neighbor_recommender::unlearning_callback::operator()().
{
   orig_.remove_row(id);
   get_table()->delete_row(id);
 }
void jubatus::core::recommender::nearest_neighbor_recommender::unpack (msgpack::object o) virtual
Implements jubatus::core::framework::model.
Definition at line 133 of file nearest_neighbor_recommender.cpp.
References nearest_neighbor_engine_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::unpack().
{
   if (o.type != msgpack::type::ARRAY || o.via.array.size != 2) {
     throw msgpack::type_error();
   }
   orig_.unpack(o.via.array.ptr[0]);
   nearest_neighbor_engine_->unpack(o.via.array.ptr[1]);
 }
void jubatus::core::recommender::nearest_neighbor_recommender::update_row (const std::string & id, const sfv_diff_t & diff) virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 99 of file nearest_neighbor_recommender.cpp.
References jubatus::core::storage::sparse_matrix_storage::get_row(), JUBATUS_EXCEPTION, nearest_neighbor_engine_, jubatus::core::recommender::recommender_base::orig_, jubatus::core::storage::sparse_matrix_storage::set_row(), and unlearner_.
{
   if (unlearner_) {
     if (!unlearner_->touch(id)) {
       throw JUBATUS_EXCEPTION(common::exception::runtime_error(
           "no more space available to add new ID: " + id));
     }
   }
   orig_.set_row(id, diff);
   common::sfv_t row;
   orig_.get_row(id, row);
   nearest_neighbor_engine_->set_row(id, row);
 }
Member Data Documentation
jubatus::util::lang::shared_ptr<nearest_neighbor::nearest_neighbor_base> jubatus::core::recommender::nearest_neighbor_recommender::nearest_neighbor_engine_ private
Definition at line 73 of file nearest_neighbor_recommender.hpp.
Referenced by clear(), get_all_row_ids(), get_const_table(), get_mixable(), get_table(), neighbor_row(), pack(), similar_row(), type(), unpack(), and update_row().
jubatus::util::lang::shared_ptr<unlearner::unlearner_base> jubatus::core::recommender::nearest_neighbor_recommender::unlearner_ private
Definition at line 77 of file nearest_neighbor_recommender.hpp.
Referenced by clear(), clear_row(), get_unlearner(), nearest_neighbor_recommender(), and update_row().
The documentation for this class was generated from the following files:
jubatus/core/recommender/nearest_neighbor_recommender.hpp
jubatus/core/recommender/nearest_neighbor_recommender.cpp