jubatus_core: jubatus::core::clustering::storage Class Reference
jubatus::core::clustering::storage Class Reference abstract
#include <storage.hpp>
Public Member Functions
virtual void add (const weighted_point &point)=0
void clear ()
virtual wplist get_all () const
virtual wplist get_common () const
void get_diff (diff_t &d) const
virtual wplist get_mine () const =0
size_t get_revision ()
core::storage::version get_version () const
void mix (const diff_t &, diff_t &ret)
MSGPACK_DEFINE (revision_, name_, config_, common_)
void pack (framework::packer &packer) const
bool put_diff (const diff_t &d)
storage (const std::string &name, const clustering_config &config)
void unpack (msgpack::object o)
virtual ~storage ()
Public Member Functions inherited from jubatus::core::clustering::event_dispatcher< storage_event_type, wplist >
void add_event_listener (const storage_event_type &type, callback_t callback)
virtual ~event_dispatcher ()
Protected Member Functions
virtual void clear_impl_ ()
void increment_revision ()
virtual void pack_impl_ (framework::packer &packer) const
virtual void unpack_impl_ (msgpack::object o)
Protected Member Functions inherited from jubatus::core::clustering::event_dispatcher< storage_event_type, wplist >
void dispatch (const storage_event_type &type, const wplist &data) const
Protected Attributes
std::vector< std::pair< std::string, wplist > > common_
clustering_config config_
std::string name_
size_t revision_
Protected Attributes inherited from jubatus::core::clustering::event_dispatcher< storage_event_type, wplist >
event_type_table events_
Detailed Description
Definition at line 41 of file storage.hpp.
Constructor & Destructor Documentation
jubatus::core::clustering::storage::storage (const std::string & name, const clustering_config & config)
Definition at line 28 of file storage.cpp.
     : revision_(0),
       name_(name),
       config_(config) {
 }
virtual jubatus::core::clustering::storage::~storage () inline virtual
Definition at line 44 of file storage.hpp.
 {}
Member Function Documentation
virtual void jubatus::core::clustering::storage::add (const weighted_point & point) pure virtual
Implemented in jubatus::core::clustering::compressive_storage, and jubatus::core::clustering::simple_storage.
void jubatus::core::clustering::storage::clear ()
Definition at line 97 of file storage.cpp.
References clear_impl_(), jubatus::core::clustering::event_dispatcher< storage_event_type, wplist >::dispatch(), get_all(), and jubatus::core::clustering::REVISION_CHANGE.
                     {
   // TODO(gintenlabo): consider revisions
   clear_impl_();
   dispatch(REVISION_CHANGE, get_all());
 }
void jubatus::core::clustering::storage::clear_impl_ () protected virtual
Reimplemented in jubatus::core::clustering::compressive_storage, and jubatus::core::clustering::simple_storage.
Definition at line 118 of file storage.cpp.
References common_.
Referenced by clear(), jubatus::core::clustering::simple_storage::clear_impl_(), and jubatus::core::clustering::compressive_storage::clear_impl_().
{
   common_.clear();
 }
wplist jubatus::core::clustering::storage::get_all () const virtual
Definition at line 34 of file storage.cpp.
References jubatus::core::clustering::concat(), get_common(), and get_mine().
Referenced by clear(), increment_revision(), and unpack().
{
   wplist ret = get_mine();
   wplist common = get_common();
   concat(common, ret);
   return ret;
 }
wplist jubatus::core::clustering::storage::get_common () const virtual
Definition at line 41 of file storage.cpp.
References common_, and jubatus::core::clustering::concat().
Referenced by get_all().
{
   wplist ret;
   for (diff_t::const_iterator it = common_.begin();
       it != common_.end(); ++it) {
     concat(it->second, ret);
   }
   return ret;
 }
void jubatus::core::clustering::storage::get_diff (diff_t & d) const
Definition at line 50 of file storage.cpp.
References get_mine(), and name_.
{
   d.clear();
   wplist coreset = get_mine();
   d.push_back(make_pair(name_, coreset));
 }
virtual wplist jubatus::core::clustering::storage::get_mine () const pure virtual
Implemented in jubatus::core::clustering::compressive_storage, and jubatus::core::clustering::simple_storage.
Referenced by get_all(), and get_diff().
size_t jubatus::core::clustering::storage::get_revision ()
Definition at line 103 of file storage.cpp.
References revision_.
{
   return revision_;
 }
core::storage::version jubatus::core::clustering::storage::get_version () const inline
Definition at line 58 of file storage.hpp.
{
     return core::storage::version();
   }
void jubatus::core::clustering::storage::increment_revision () protected
Definition at line 107 of file storage.cpp.
References jubatus::core::clustering::event_dispatcher< storage_event_type, wplist >::dispatch(), get_all(), revision_, and jubatus::core::clustering::REVISION_CHANGE.
Referenced by jubatus::core::clustering::simple_storage::add(), jubatus::core::clustering::compressive_storage::add(), and put_diff().
{
   ++revision_;
   dispatch(REVISION_CHANGE, get_all());
 }
void jubatus::core::clustering::storage::mix (const diff_t & lhs, diff_t & ret)
Definition at line 69 of file storage.cpp.
{
   diff_t::const_iterator lb = lhs.begin(), le =  lhs.end();
   diff_t::iterator b = ret.begin(), e = ret.end();
   while (lb != le && b != e) {
     if ((*lb).first < (*b).first) {
       b = ret.insert(b, (*lb));
       ++lb;
     } else if ((*lb).first > (*b).first) {
       ++b;
     } else {
       std::copy((*lb).second.begin(), (*lb).second.end(),
           std::back_inserter((*b).second));
       ++b;
       ++lb;
     }
   }
   std::copy(lb, le, std::back_inserter(ret));
 };
jubatus::core::clustering::storage::MSGPACK_DEFINE (revision_ , name_ , config_ , common_)
void jubatus::core::clustering::storage::pack (framework::packer & packer) const
Definition at line 88 of file storage.cpp.
References pack_impl_().
{
   pack_impl_(packer);
 }
void jubatus::core::clustering::storage::pack_impl_ (framework::packer & packer) const protected virtual
Reimplemented in jubatus::core::clustering::compressive_storage, and jubatus::core::clustering::simple_storage.
Definition at line 112 of file storage.cpp.
Referenced by pack(), jubatus::core::clustering::simple_storage::pack_impl_(), and jubatus::core::clustering::compressive_storage::pack_impl_().
{
   packer.pack(*this);
 }
bool jubatus::core::clustering::storage::put_diff (const diff_t & d)
Definition at line 56 of file storage.cpp.
References common_, increment_revision(), and name_.
{
   common_.clear();
   for (diff_t::const_iterator it = diff.begin(); it != diff.end(); ++it) {
     if (it->first != name_) {
       common_.push_back(*it);
     }
   }
   increment_revision();
   // TODO(kumagi): return false if we want to reject the diff
   return true;
 }
void jubatus::core::clustering::storage::unpack (msgpack::object o)
Definition at line 92 of file storage.cpp.
References jubatus::core::clustering::event_dispatcher< storage_event_type, wplist >::dispatch(), get_all(), jubatus::core::clustering::REVISION_CHANGE, and unpack_impl_().
{
   unpack_impl_(o);
   dispatch(REVISION_CHANGE, get_all());
 }
void jubatus::core::clustering::storage::unpack_impl_ (msgpack::object o) protected virtual
Reimplemented in jubatus::core::clustering::compressive_storage, and jubatus::core::clustering::simple_storage.
Definition at line 115 of file storage.cpp.
Referenced by unpack(), jubatus::core::clustering::simple_storage::unpack_impl_(), and jubatus::core::clustering::compressive_storage::unpack_impl_().
{
   o.convert(this);
 }
Member Data Documentation
std::vector<std::pair<std::string, wplist> > jubatus::core::clustering::storage::common_ protected
Definition at line 78 of file storage.hpp.
Referenced by clear_impl_(), get_common(), and put_diff().
clustering_config jubatus::core::clustering::storage::config_ protected
Definition at line 76 of file storage.hpp.
Referenced by jubatus::core::clustering::simple_storage::add(), jubatus::core::clustering::compressive_storage::add(), jubatus::core::clustering::compressive_storage::carry_up(), jubatus::core::clustering::compressive_storage::forget_weight(), jubatus::core::clustering::compressive_storage::is_next_bucket_full(), and jubatus::core::clustering::compressive_storage::reach_forgetting_threshold().
std::string jubatus::core::clustering::storage::name_ protected
Definition at line 75 of file storage.hpp.
Referenced by get_diff(), and put_diff().
size_t jubatus::core::clustering::storage::revision_ protected
Definition at line 74 of file storage.hpp.
Referenced by get_revision(), and increment_revision().
The documentation for this class was generated from the following files:
jubatus/core/clustering/storage.hpp
jubatus/core/clustering/storage.cpp