jubatus_core: jubatus::core::bandit::summation_storage Class Reference
jubatus::core::bandit::summation_storage Class Reference
#include <summation_storage.hpp>
Public Types
typedef bandit_base::diff_t table_t
Public Member Functions
void clear ()
bool delete_arm (const std::string &arm_id)
const std::vector< std::string > & get_arm_ids () const
arm_info get_arm_info (const std::string &player_id, const std::string &arm_id) const
arm_info_map get_arm_info_map (const std::string &player_id) const
void get_diff (table_t &diff) const
double get_expectation (const std::string &player_id, const std::string &arm_id) const
MSGPACK_DEFINE (arm_ids_, mixed_, unmixed_)
void notify_selected (const std::string &player_id, const std::string &arm_id)
bool put_diff (const table_t &diff)
bool register_arm (const std::string &arm_id)
bool register_reward (const std::string &player_id, const std::string &arm_id, double reward)
bool reset (const std::string &player_id)
summation_storage (bool assume_unrewarded)
Static Public Member Functions
static void mix (const table_t &lhs, table_t &rhs)
Private Attributes
std::vector< std::string > arm_ids_
const bool assume_unrewarded_
table_t mixed_
table_t unmixed_
Detailed Description
Definition at line 29 of file summation_storage.hpp.
Member Typedef Documentation
typedef bandit_base::diff_t jubatus::core::bandit::summation_storage::table_t
Definition at line 31 of file summation_storage.hpp.
Constructor & Destructor Documentation
jubatus::core::bandit::summation_storage::summation_storage (bool assume_unrewarded) explicit
Definition at line 27 of file summation_storage.cpp.
     : assume_unrewarded_(assume_unrewarded) {
 }
Member Function Documentation
void jubatus::core::bandit::summation_storage::clear ()
Definition at line 202 of file summation_storage.cpp.
References arm_ids_, mixed_, and unmixed_.
Referenced by jubatus::core::bandit::ucb1::clear(), jubatus::core::bandit::epsilon_greedy::clear(), jubatus::core::bandit::softmax::clear(), and jubatus::core::bandit::exp3::clear().
{
   arm_ids_.clear();
   mixed_.clear();
   unmixed_.clear();
 }
bool jubatus::core::bandit::summation_storage::delete_arm (const std::string & arm_id)
Definition at line 82 of file summation_storage.cpp.
References arm_ids_, mixed_, and unmixed_.
Referenced by jubatus::core::bandit::ucb1::delete_arm(), jubatus::core::bandit::epsilon_greedy::delete_arm(), jubatus::core::bandit::softmax::delete_arm(), and jubatus::core::bandit::exp3::delete_arm().
{
   delete_arm_(mixed_, arm_id);
   delete_arm_(unmixed_, arm_id);
   std::vector<std::string>::iterator iter =
       std::remove(arm_ids_.begin(), arm_ids_.end(), arm_id);
   if (iter == arm_ids_.end()) {
     return false;
   }
   arm_ids_.erase(iter, arm_ids_.end());
   return true;
 }
const std::vector<std::string>& jubatus::core::bandit::summation_storage::get_arm_ids () const inline
Definition at line 49 of file summation_storage.hpp.
References arm_ids_.
Referenced by jubatus::core::bandit::exp3::calc_weights_(), jubatus::core::bandit::exp3::register_reward(), jubatus::core::bandit::ucb1::select_arm(), jubatus::core::bandit::epsilon_greedy::select_arm(), jubatus::core::bandit::softmax::select_arm(), and jubatus::core::bandit::exp3::select_arm().
{
     return arm_ids_;
   }
arm_info jubatus::core::bandit::summation_storage::get_arm_info (const std::string & player_id, const std::string & arm_id) const
Definition at line 137 of file summation_storage.cpp.
References mixed_, jubatus::core::bandit::arm_info::trial_count, unmixed_, and jubatus::core::bandit::arm_info::weight.
Referenced by jubatus::core::bandit::exp3::calc_weights_(), get_arm_info_map(), get_expectation(), and jubatus::core::bandit::ucb1::select_arm().
{
   const arm_info a1 = get_arm_info_(mixed_, player_id, arm_id);
   const arm_info a2 = get_arm_info_(unmixed_, player_id, arm_id);
   arm_info result;
   result.trial_count = a1.trial_count + a2.trial_count;
   result.weight = a1.weight + a2.weight;
   return result;
 }
arm_info_map jubatus::core::bandit::summation_storage::get_arm_info_map (const std::string & player_id) const
Definition at line 159 of file summation_storage.cpp.
References arm_ids_, and get_arm_info().
Referenced by jubatus::core::bandit::ucb1::get_arm_info(), jubatus::core::bandit::epsilon_greedy::get_arm_info(), jubatus::core::bandit::softmax::get_arm_info(), and jubatus::core::bandit::exp3::get_arm_info().
{
   arm_info_map result;
   for (std::vector<std::string>::const_iterator iter = arm_ids_.begin();
        iter != arm_ids_.end(); ++iter) {
     result.insert(std::make_pair(*iter, get_arm_info(player_id, *iter)));
   }
   return result;
 }
void jubatus::core::bandit::summation_storage::get_diff (table_t & diff) const
Definition at line 171 of file summation_storage.cpp.
References unmixed_.
Referenced by jubatus::core::bandit::ucb1::get_diff(), jubatus::core::bandit::epsilon_greedy::get_diff(), jubatus::core::bandit::softmax::get_diff(), and jubatus::core::bandit::exp3::get_diff().
{
   diff = unmixed_;
 }
double jubatus::core::bandit::summation_storage::get_expectation (const std::string & player_id, const std::string & arm_id) const
Definition at line 149 of file summation_storage.cpp.
References get_arm_info(), jubatus::core::bandit::arm_info::trial_count, and jubatus::core::bandit::arm_info::weight.
Referenced by jubatus::core::bandit::epsilon_greedy::select_arm(), and jubatus::core::bandit::softmax::select_arm().
{
   const arm_info a = get_arm_info(player_id, arm_id);
   if (a.trial_count == 0) {
     return 0;
   }
   return a.weight / a.trial_count;
 }
void jubatus::core::bandit::summation_storage::mix (const table_t & lhs, table_t & rhs) static
Definition at line 181 of file summation_storage.cpp.
References jubatus::core::bandit::arm_info::trial_count, and jubatus::core::bandit::arm_info::weight.
Referenced by jubatus::core::bandit::ucb1::mix(), jubatus::core::bandit::epsilon_greedy::mix(), jubatus::core::bandit::softmax::mix(), jubatus::core::bandit::exp3::mix(), and put_diff().
{
   for (table_t::const_iterator iter = lhs.begin();
        iter != lhs.end(); ++iter) {
     arm_info_map& as0 = rhs[iter->first];
     const arm_info_map& as1 = iter->second;
     for (arm_info_map::const_iterator jter = as1.begin();
          jter != as1.end(); ++jter) {
       arm_info& a0 = as0[jter->first];
       const arm_info& a1 = jter->second;
       a0.trial_count += a1.trial_count;
       a0.weight += a1.weight;
     }
   }
 }
jubatus::core::bandit::summation_storage::MSGPACK_DEFINE (arm_ids_ , mixed_ , unmixed_)
void jubatus::core::bandit::summation_storage::notify_selected (const std::string & player_id, const std::string & arm_id)
Definition at line 95 of file summation_storage.cpp.
References arm_ids_, assume_unrewarded_, jubatus::core::bandit::arm_info::trial_count, and unmixed_.
Referenced by jubatus::core::bandit::ucb1::select_arm(), jubatus::core::bandit::epsilon_greedy::select_arm(), jubatus::core::bandit::softmax::select_arm(), and jubatus::core::bandit::exp3::select_arm().
{
   if (!assume_unrewarded_) {
     return;
   }
   arm_info& a = get_arm_info_(unmixed_, arm_ids_, player_id, arm_id);
   a.trial_count += 1;
 }
bool jubatus::core::bandit::summation_storage::put_diff (const table_t & diff)
Definition at line 175 of file summation_storage.cpp.
References mix(), mixed_, and unmixed_.
Referenced by jubatus::core::bandit::ucb1::put_diff(), jubatus::core::bandit::epsilon_greedy::put_diff(), jubatus::core::bandit::softmax::put_diff(), and jubatus::core::bandit::exp3::put_diff().
{
   mix(diff, mixed_);
   unmixed_.clear();
   return true;
 }
bool jubatus::core::bandit::summation_storage::register_arm (const std::string & arm_id)
Definition at line 31 of file summation_storage.cpp.
References arm_ids_, and unmixed_.
Referenced by jubatus::core::bandit::ucb1::register_arm(), jubatus::core::bandit::epsilon_greedy::register_arm(), jubatus::core::bandit::softmax::register_arm(), and jubatus::core::bandit::exp3::register_arm().
{
   if (std::find(arm_ids_.begin(), arm_ids_.end(), arm_id) != arm_ids_.end()) {
     // arm_id is already in arms_
     return false;
   }
   arm_ids_.push_back(arm_id);
   const arm_info a0 = {0, 0.0};
   for (table_t::iterator iter = unmixed_.begin();
       iter != unmixed_.end(); ++iter) {
     arm_info_map& as = iter->second;
     as.insert(std::make_pair(arm_id, a0));
   }
   return true;
 }
bool jubatus::core::bandit::summation_storage::register_reward (const std::string & player_id, const std::string & arm_id, double reward)
Definition at line 105 of file summation_storage.cpp.
References arm_ids_, assume_unrewarded_, jubatus::core::bandit::arm_info::trial_count, unmixed_, and jubatus::core::bandit::arm_info::weight.
Referenced by jubatus::core::bandit::ucb1::register_reward(), jubatus::core::bandit::epsilon_greedy::register_reward(), jubatus::core::bandit::softmax::register_reward(), and jubatus::core::bandit::exp3::register_reward().
                    {
   arm_info& a = get_arm_info_(unmixed_, arm_ids_, player_id, arm_id);
   if (!assume_unrewarded_) {
     a.trial_count += 1;
   }
   a.weight += reward;
   return true;
 }
bool jubatus::core::bandit::summation_storage::reset (const std::string & player_id)
Definition at line 196 of file summation_storage.cpp.
References mixed_, and unmixed_.
Referenced by jubatus::core::bandit::ucb1::reset(), jubatus::core::bandit::epsilon_greedy::reset(), jubatus::core::bandit::softmax::reset(), and jubatus::core::bandit::exp3::reset().
{
   bool result1 = mixed_.erase(player_id) > 0;
   bool result2 = unmixed_.erase(player_id) > 0;
   return result1 || result2;
 }
Member Data Documentation
std::vector<std::string> jubatus::core::bandit::summation_storage::arm_ids_ private
Definition at line 65 of file summation_storage.hpp.
Referenced by clear(), delete_arm(), get_arm_ids(), get_arm_info_map(), notify_selected(), register_arm(), and register_reward().
const bool jubatus::core::bandit::summation_storage::assume_unrewarded_ private
Definition at line 64 of file summation_storage.hpp.
Referenced by notify_selected(), and register_reward().
table_t jubatus::core::bandit::summation_storage::mixed_ private
Definition at line 66 of file summation_storage.hpp.
Referenced by clear(), delete_arm(), get_arm_info(), put_diff(), and reset().
table_t jubatus::core::bandit::summation_storage::unmixed_ private
Definition at line 66 of file summation_storage.hpp.
Referenced by clear(), delete_arm(), get_arm_info(), get_diff(), notify_selected(), put_diff(), register_arm(), register_reward(), and reset().
The documentation for this class was generated from the following files:
jubatus/core/bandit/summation_storage.hpp
jubatus/core/bandit/summation_storage.cpp