jubatus_core: jubatus/core/classifier/classifier_test_util.hpp File Reference
classifier_test_util.hpp File Reference
#include <algorithm>
#include <cstdlib>
#include <cmath>
#include <cfloat>
#include <string>
#include <utility>
#include <vector>
#include "jubatus/util/math/random.h"
Functions
std::pair< std::string, std::vector< double > > gen_random_data (jubatus::util::math::random::mtrand &rand)
std::pair< std::string, std::vector< double > > gen_random_data3 (jubatus::util::math::random::mtrand &rand)
void make_random (jubatus::util::math::random::mtrand &rand, float mu, float sigma, size_t dim, std::vector< double > &v)
void make_random (jubatus::util::math::random::mtrand &rand, const std::vector< float > &mus, float sigma, size_t dim, std::vector< double > &v)
Function Documentation
std::pair<std::string, std::vector<double> > gen_random_data (jubatus::util::math::random::mtrand & rand)
Definition at line 54 of file classifier_test_util.hpp.
References make_random().
{
   const float mu_pos = 1.0;
   const float mu_neg = -1.0;
   const float sigma = 1.5;
   const size_t dim = 10;
   float mu;
   std::pair<std::string, std::vector<double> > p;
   if (rand() % 2 == 0) {
     p.first = "OK";
     mu = mu_pos;
   } else {
     p.first = "NG";
     mu = mu_neg;
   }
   make_random(rand, mu, sigma, dim, p.second);
   return p;
 }
std::pair<std::string, std::vector<double> > gen_random_data3 (jubatus::util::math::random::mtrand & rand)
Definition at line 74 of file classifier_test_util.hpp.
References make_random().
{
   const char* labels[] = { "1", "2", "3" };
   std::vector<float> mus;
   mus.push_back(3);
   mus.push_back(0);
   mus.push_back(-3);
   const float sigma = 1.0;
   const size_t dim = 10;
   std::pair<std::string, std::vector<double> > p;
   size_t l = rand() % 3;
   p.first = labels[l];
   std::rotate(mus.begin(), mus.begin() + l, mus.end());
   make_random(rand, mus, sigma, dim, p.second);
   return p;
 }
void make_random (jubatus::util::math::random::mtrand & rand, float mu, float sigma, size_t dim, std::vector< double > & v)
Definition at line 30 of file classifier_test_util.hpp.
Referenced by gen_random_data(), and gen_random_data3().
{
   for (size_t i = 0; i < dim; i++) {
     float value = rand.next_gaussian(mu, sigma);
     v.push_back(value);
   }
 }
void make_random (jubatus::util::math::random::mtrand & rand, const std::vector< float > & mus, float sigma, size_t dim, std::vector< double > & v)
Definition at line 42 of file classifier_test_util.hpp.
{
   for (size_t i = 0; i < dim; i++) {
     float value = rand.next_gaussian(mus[i % mus.size()], sigma);
     v.push_back(value);
   }
 }