jubatus_core: jubatus::core::classifier::linear_classifier Class Reference
jubatus::core::classifier::linear_classifier Class Reference abstract
#include <linear_classifier.hpp>
Public Member Functions
std::string classify (const common::sfv_t &fv) const
void classify_with_scores (const common::sfv_t &fv, classify_result &scores) const
void clear ()
bool delete_label (const std::string &label)
std::vector< std::string > get_labels () const
framework::mixable * get_mixable ()
virtual void get_status (std::map< std::string, std::string > &status) const
jubatus::util::lang::shared_ptr< unlearner::unlearner_base > label_unlearner () const
linear_classifier (storage_ptr storage)
virtual std::string name () const =0
void pack (framework::packer &pk) const
bool set_label (const std::string &label)
void set_label_unlearner (jubatus::util::lang::shared_ptr< unlearner::unlearner_base > label_unlearner)
virtual void train (const common::sfv_t &fv, const std::string &label)=0
bool unlearn_label (const std::string &label)
void unpack (msgpack::object o)
virtual ~linear_classifier ()
Public Member Functions inherited from jubatus::core::classifier::classifier_base
classifier_base ()
virtual ~classifier_base ()
Protected Member Functions
float calc_margin (const common::sfv_t &sfv, const std::string &label, std::string &incorrect_label) const
float calc_margin_and_variance (const common::sfv_t &sfv, const std::string &label, std::string &incorrect_label, float &variance) const
void check_touchable (const std::string &label)
std::string get_largest_incorrect_label (const common::sfv_t &sfv, const std::string &label, classify_result &scores) const
void touch (const std::string &label)
void update_weight (const common::sfv_t &sfv, float step_weigth, const std::string &pos_label, const std::string &neg_class)
Static Protected Member Functions
static float squared_norm (const common::sfv_t &sfv)
Protected Attributes
framework::linear_function_mixer mixable_storage_
storage_ptr storage_
jubatus::util::lang::shared_ptr< unlearner::unlearner_base > unlearner_
Detailed Description
Definition at line 38 of file linear_classifier.hpp.
Constructor & Destructor Documentation
jubatus::core::classifier::linear_classifier::linear_classifier (storage_ptr storage) explicit
Definition at line 42 of file linear_classifier.cpp.
   : storage_(storage), mixable_storage_(storage_) {
 }
jubatus::core::classifier::linear_classifier::~linear_classifier () virtual
Definition at line 46 of file linear_classifier.cpp.
{
 }
Member Function Documentation
float jubatus::core::classifier::linear_classifier::calc_margin (const common::sfv_t & sfv, const std::string & label, std::string & incorrect_label) const protected
Definition at line 151 of file linear_classifier.cpp.
References get_largest_incorrect_label().
Referenced by calc_margin_and_variance(), jubatus::core::classifier::passive_aggressive_1::train(), and jubatus::core::classifier::passive_aggressive_2::train().
{
   classify_result scores;
   incorrect_label = get_largest_incorrect_label(fv, label, scores);
   float correct_score = 0.f;
   float incorrect_score = 0.f;
   for (vector<classify_result_elem>::const_iterator it = scores.begin();
       it != scores.end(); ++it) {
     if (it->label == label) {
       correct_score = it->score;
     } else if (it->label == incorrect_label) {
       incorrect_score = it->score;
     }
   }
   return incorrect_score - correct_score;
 }
float jubatus::core::classifier::linear_classifier::calc_margin_and_variance (const common::sfv_t & sfv, const std::string & label, std::string & incorrect_label, float & variance) const protected
Definition at line 170 of file linear_classifier.cpp.
References calc_margin(), and storage_.
Referenced by jubatus::core::classifier::arow::train(), jubatus::core::classifier::normal_herd::train(), and jubatus::core::classifier::confidence_weighted::train().
                       {
   float margin = calc_margin(sfv, label, incorrect_label);
   var = 0.f;
   util::concurrent::scoped_lock lk(storage_->get_lock());
   for (size_t i = 0; i < sfv.size(); ++i) {
     const string& feature = sfv[i].first;
     const float val = sfv[i].second;
     feature_val2_t weight_covars;
     storage_->get2_nolock(feature, weight_covars);
     float label_covar = 1.f;
     float incorrect_label_covar = 1.f;
     for (size_t j = 0; j < weight_covars.size(); ++j) {
       if (weight_covars[j].first == label) {
         label_covar = weight_covars[j].second.v2;
       } else if (weight_covars[j].first == incorrect_label) {
         incorrect_label_covar = weight_covars[j].second.v2;
       }
     }
     var += (label_covar + incorrect_label_covar) * val * val;
   }
   return margin;
 }
void jubatus::core::classifier::linear_classifier::check_touchable (const std::string & label) protected
Definition at line 225 of file linear_classifier.cpp.
References JUBATUS_EXCEPTION, and unlearner_.
Referenced by set_label(), touch(), jubatus::core::classifier::perceptron::train(), jubatus::core::classifier::arow::train(), jubatus::core::classifier::normal_herd::train(), jubatus::core::classifier::confidence_weighted::train(), jubatus::core::classifier::passive_aggressive_1::train(), and jubatus::core::classifier::passive_aggressive_2::train().
{
   if (unlearner_ && !unlearner_->can_touch(label)) {
     throw JUBATUS_EXCEPTION(common::exception::runtime_error(
         "no more space available to add new label: " + label));
   }
 }
string jubatus::core::classifier::linear_classifier::classify (const common::sfv_t & fv) const
Definition at line 81 of file linear_classifier.cpp.
References classify_with_scores().
Referenced by jubatus::core::classifier::perceptron::train().
{
   classify_result result;
   classify_with_scores(fv, result);
   float max_score = -FLT_MAX;
   string max_class;
   for (vector<classify_result_elem>::const_iterator it = result.begin();
       it != result.end(); ++it) {
     if (it == result.begin() || it->score > max_score) {
       max_score = it->score;
       max_class = it->label;
     }
   }
   return max_class;
 }
void jubatus::core::classifier::linear_classifier::classify_with_scores (const common::sfv_t & fv, classify_result & scores) const virtual
Implements jubatus::core::classifier::classifier_base.
Definition at line 68 of file linear_classifier.cpp.
References storage_.
Referenced by classify(), and get_largest_incorrect_label().
{
   scores.clear();
   map_feature_val1_t ret;
   storage_->inp(sfv, ret);
   for (map_feature_val1_t::const_iterator it = ret.begin(); it != ret.end();
       ++it) {
     scores.push_back(classify_result_elem(it->first, it->second));
   }
 }
void jubatus::core::classifier::linear_classifier::clear () virtual
Implements jubatus::core::classifier::classifier_base.
Definition at line 96 of file linear_classifier.cpp.
References storage_, and unlearner_.
{
   storage_->clear();
   if (unlearner_) {
     unlearner_->clear();
   }
 }
bool jubatus::core::classifier::linear_classifier::delete_label (const std::string & label) virtual
Implements jubatus::core::classifier::classifier_base.
Definition at line 232 of file linear_classifier.cpp.
References storage_, and unlearner_.
{
   // Remove the label from the model.
   bool result = storage_->delete_label(label);
   if (unlearner_ && result) {
     // Notify unlearner that the label was removed.
     result = unlearner_->remove(label);
   }
   return result;
 }
vector< string > jubatus::core::classifier::linear_classifier::get_labels () const virtual
Implements jubatus::core::classifier::classifier_base.
Definition at line 103 of file linear_classifier.cpp.
References storage_.
{
   return storage_->get_labels();
 }
string jubatus::core::classifier::linear_classifier::get_largest_incorrect_label (const common::sfv_t & sfv, const std::string & label, classify_result & scores) const protected
Definition at line 131 of file linear_classifier.cpp.
References classify_with_scores().
Referenced by calc_margin().
{
   classify_with_scores(fv, scores);
   float max_score = -FLT_MAX;
   string max_class;
   for (vector<classify_result_elem>::const_iterator it = scores.begin();
       it != scores.end(); ++it) {
     if (it->label == label) {
       continue;
     }
     if (it->score > max_score || it == scores.begin()) {
       max_score = it->score;
       max_class = it->label;
     }
   }
   return max_class;
 }
framework::mixable * jubatus::core::classifier::linear_classifier::get_mixable () virtual
Implements jubatus::core::classifier::classifier_base.
Definition at line 213 of file linear_classifier.cpp.
References mixable_storage_.
{
   return &mixable_storage_;
 }
void jubatus::core::classifier::linear_classifier::get_status (std::map< std::string, std::string > & status) const virtual
Implements jubatus::core::classifier::classifier_base.
Definition at line 118 of file linear_classifier.cpp.
References storage_.
{
   storage_->get_status(status);
   status["storage"] = storage_->type();
 }
jubatus::util::lang::shared_ptr<unlearner::unlearner_base> jubatus::core::classifier::linear_classifier::label_unlearner () const inline
Definition at line 49 of file linear_classifier.hpp.
References unlearner_.
Referenced by set_label_unlearner().
{
     return unlearner_;
   }
virtual std::string jubatus::core::classifier::linear_classifier::name () const pure virtual
Implements jubatus::core::classifier::classifier_base.
Implemented in jubatus::core::classifier::passive_aggressive_2, jubatus::core::classifier::confidence_weighted, jubatus::core::classifier::normal_herd, jubatus::core::classifier::passive_aggressive_1, jubatus::core::classifier::arow, jubatus::core::classifier::passive_aggressive, and jubatus::core::classifier::perceptron.
void jubatus::core::classifier::linear_classifier::pack (framework::packer & pk) const virtual
Implements jubatus::core::classifier::classifier_base.
Definition at line 206 of file linear_classifier.cpp.
References storage_.
{
   storage_->pack(pk);
 }
bool jubatus::core::classifier::linear_classifier::set_label (const std::string & label) virtual
Implements jubatus::core::classifier::classifier_base.
Definition at line 107 of file linear_classifier.cpp.
References check_touchable(), storage_, and unlearner_.
{
   check_touchable(label);
   bool result = storage_->set_label(label);
   if (unlearner_ && result) {
     result = unlearner_->touch(label);
   }
   return result;
 }
void jubatus::core::classifier::linear_classifier::set_label_unlearner (jubatus::util::lang::shared_ptr< unlearner::unlearner_base > label_unlearner) virtual
Implements jubatus::core::classifier::classifier_base.
Definition at line 58 of file linear_classifier.cpp.
References label_unlearner(), mixable_storage_, jubatus::core::framework::linear_function_mixer::set_label_unlearner(), and unlearner_.
{
   label_unlearner->set_callback(
       jubatus::util::lang::bind(
           delete_label_wrapper, this, jubatus::util::lang::_1));
   mixable_storage_.set_label_unlearner(label_unlearner);
   unlearner_ = label_unlearner;
 }
float jubatus::core::classifier::linear_classifier::squared_norm (const common::sfv_t & sfv) static protected
Definition at line 198 of file linear_classifier.cpp.
Referenced by jubatus::core::classifier::passive_aggressive_1::train(), and jubatus::core::classifier::passive_aggressive_2::train().
{
   float ret = 0.f;
   for (size_t i = 0; i < fv.size(); ++i) {
     ret += fv[i].second * fv[i].second;
   }
   return ret;
 }
void jubatus::core::classifier::linear_classifier::touch (const std::string & label) protected
Definition at line 217 of file linear_classifier.cpp.
References check_touchable(), and unlearner_.
Referenced by jubatus::core::classifier::perceptron::train(), jubatus::core::classifier::passive_aggressive_1::train(), jubatus::core::classifier::passive_aggressive_2::train(), jubatus::core::classifier::arow::update(), jubatus::core::classifier::normal_herd::update(), and jubatus::core::classifier::confidence_weighted::update().
{
   check_touchable(label);
   if (unlearner_) {
     unlearner_->touch(label);
   }
 }
virtual void jubatus::core::classifier::linear_classifier::train (const common::sfv_t & fv, const std::string & label) pure virtual
Implements jubatus::core::classifier::classifier_base.
Implemented in jubatus::core::classifier::passive_aggressive_2, jubatus::core::classifier::confidence_weighted, jubatus::core::classifier::normal_herd, jubatus::core::classifier::passive_aggressive_1, jubatus::core::classifier::arow, jubatus::core::classifier::passive_aggressive, and jubatus::core::classifier::perceptron.
bool jubatus::core::classifier::linear_classifier::unlearn_label (const std::string & label)
Callback function to delete the label via unlearner.
Definition at line 247 of file linear_classifier.cpp.
References storage_.
{
   // this method must be called via touch() function.
   // touch() must be done with holding lock
   // so this function must not get lock
   return storage_->delete_label_nolock(label);
 }
void jubatus::core::classifier::linear_classifier::unpack (msgpack::object o) virtual
Implements jubatus::core::classifier::classifier_base.
Definition at line 209 of file linear_classifier.cpp.
References storage_.
{
   storage_->unpack(o);
 }
void jubatus::core::classifier::linear_classifier::update_weight (const common::sfv_t & sfv, float step_weigth, const std::string & pos_label, const std::string & neg_class) protected
Definition at line 123 of file linear_classifier.cpp.
References storage_.
Referenced by jubatus::core::classifier::perceptron::train(), jubatus::core::classifier::passive_aggressive_1::train(), and jubatus::core::classifier::passive_aggressive_2::train().
{
   storage_->bulk_update(sfv, step_width, pos_label, neg_label);
 }
Member Data Documentation
framework::linear_function_mixer jubatus::core::classifier::linear_classifier::mixable_storage_ protected
Definition at line 101 of file linear_classifier.hpp.
Referenced by get_mixable(), and set_label_unlearner().
storage_ptr jubatus::core::classifier::linear_classifier::storage_ protected
Definition at line 99 of file linear_classifier.hpp.
Referenced by calc_margin_and_variance(), classify_with_scores(), clear(), delete_label(), get_labels(), get_status(), pack(), set_label(), jubatus::core::classifier::arow::train(), jubatus::core::classifier::normal_herd::train(), jubatus::core::classifier::confidence_weighted::train(), jubatus::core::classifier::passive_aggressive_1::train(), jubatus::core::classifier::passive_aggressive_2::train(), unlearn_label(), unpack(), jubatus::core::classifier::arow::update(), jubatus::core::classifier::normal_herd::update(), jubatus::core::classifier::confidence_weighted::update(), and update_weight().
jubatus::util::lang::shared_ptr<unlearner::unlearner_base> jubatus::core::classifier::linear_classifier::unlearner_ protected
Definition at line 100 of file linear_classifier.hpp.
Referenced by check_touchable(), clear(), delete_label(), label_unlearner(), set_label(), set_label_unlearner(), and touch().
The documentation for this class was generated from the following files:
jubatus/core/classifier/linear_classifier.hpp
jubatus/core/classifier/linear_classifier.cpp