jubatus_core: jubatus::core::driver::clustering Class Reference
jubatus::core::driver::clustering Class Reference
#include <clustering.hpp>
Public Member Functions
void clear ()
clustering (jubatus::util::lang::shared_ptr< core::clustering::clustering > clustering_method, jubatus::util::lang::shared_ptr< fv_converter::datum_to_fv_converter > converter)
void do_clustering ()
core::clustering::cluster_set get_core_members () const
std::vector< fv_converter::datum > get_k_center () const
fv_converter::datum get_nearest_center (const fv_converter::datum &point) const
core::clustering::cluster_unit get_nearest_members (const fv_converter::datum &point) const
size_t get_revision () const
void pack (framework::packer &pk) const
void push (const std::vector< fv_converter::datum > &points)
void unpack (msgpack::object o)
virtual ~clustering ()
Public Member Functions inherited from jubatus::core::driver::driver_base
driver_base ()
virtual framework::mixable * get_mixable ()
std::vector< storage::version > get_versions () const
virtual ~driver_base ()
Private Member Functions
fv_converter::datum to_datum (const common::sfv_t &src) const
std::vector< fv_converter::datum > to_datum_vector (const std::vector< common::sfv_t > &src) const
common::sfv_t to_sfv (const fv_converter::datum &dat)
common::sfv_t to_sfv_const (const fv_converter::datum &dat) const
std::pair< double, fv_converter::datum > to_weighted_datum (const core::clustering::weighted_point &src) const
core::clustering::cluster_unit to_weighted_datum_vector (const std::vector< core::clustering::weighted_point > &src) const
core::clustering::weighted_point to_weighted_point (const fv_converter::datum &src)
std::vector< core::clustering::weighted_point > to_weighted_point_vector (const std::vector< fv_converter::datum > &src)
Private Attributes
jubatus::util::lang::shared_ptr< core::clustering::clustering > clustering_
jubatus::util::lang::shared_ptr< fv_converter::datum_to_fv_converter > converter_
fv_converter::mixable_weight_manager wm_
Additional Inherited Members
Protected Member Functions inherited from jubatus::core::driver::driver_base
void register_mixable (framework::mixable *mixable)
Protected Attributes inherited from jubatus::core::driver::driver_base
mixable_holder holder_
Detailed Description
Definition at line 40 of file clustering.hpp.
Constructor & Destructor Documentation
jubatus::core::driver::clustering::clustering (jubatus::util::lang::shared_ptr< core::clustering::clustering > clustering_method, jubatus::util::lang::shared_ptr< fv_converter::datum_to_fv_converter > converter)
jubatus::core::driver::clustering::~clustering () virtual
Definition at line 53 of file clustering.cpp.
{
 }
Member Function Documentation
void jubatus::core::driver::clustering::clear () virtual
Implements jubatus::core::driver::driver_base.
Definition at line 202 of file clustering.cpp.
{
   clustering_->clear();
   converter_->clear_weights();
 }
void jubatus::core::driver::clustering::do_clustering ()
Definition at line 98 of file clustering.cpp.
{
   clustering_->do_clustering();
 }
core::clustering::cluster_set jubatus::core::driver::clustering::get_core_members () const
Definition at line 77 of file clustering.cpp.
{
   vector<vector<core::clustering::weighted_point> > src =
       clustering_->get_core_members();
   core::clustering::cluster_set ret;
   ret.reserve(src.size());
   std::transform(
       src.begin(),
       src.end(),
       std::back_inserter(ret),
       jubatus::util::lang::bind(
           &clustering::to_weighted_datum_vector,
           this, jubatus::util::lang::_1));
   return ret;
 }
vector< datum > jubatus::core::driver::clustering::get_k_center () const
Definition at line 72 of file clustering.cpp.
{
   return to_datum_vector(clustering_->get_k_center());
 }
fv_converter::datum jubatus::core::driver::clustering::get_nearest_center (const fv_converter::datum & point) const
core::clustering::cluster_unit jubatus::core::driver::clustering::get_nearest_members (const fv_converter::datum & point) const
size_t jubatus::core::driver::clustering::get_revision () const
Definition at line 94 of file clustering.cpp.
{
   return clustering_->get_revision();
 }
void jubatus::core::driver::clustering::pack (framework::packer & pk) const virtual
Implements jubatus::core::driver::driver_base.
Definition at line 182 of file clustering.cpp.
{
   pk.pack_array(2);
   clustering_->pack(pk);
   wm_.get_model()->pack(pk);
 }
void jubatus::core::driver::clustering::push (const std::vector< fv_converter::datum > & points)
datum jubatus::core::driver::clustering::to_datum (const common::sfv_t & src) const private
Definition at line 118 of file clustering.cpp.
References jubatus::core::fv_converter::revert_feature().
{
   datum ret;
   fv_converter::revert_feature(src, ret);
   return ret;
 }
vector< datum > jubatus::core::driver::clustering::to_datum_vector (const std::vector< common::sfv_t > & src) const private
Definition at line 138 of file clustering.cpp.
{
   vector<datum> ret;
   ret.reserve(src.size());
   std::transform(
       src.begin(),
       src.end(),
       std::back_inserter(ret),
       jubatus::util::lang::bind(
           &clustering::to_datum,
           this, jubatus::util::lang::_1));
   return ret;
 }
common::sfv_t jubatus::core::driver::clustering::to_sfv (const fv_converter::datum & dat) private
Definition at line 104 of file clustering.cpp.
References jubatus::core::common::sort_and_merge().
{
   common::sfv_t ret;
   converter_->convert_and_update_weight(dat, ret);
   common::sort_and_merge(ret);
   return ret;
 }
common::sfv_t jubatus::core::driver::clustering::to_sfv_const (const fv_converter::datum & dat) const private
Definition at line 111 of file clustering.cpp.
References jubatus::core::common::sort_and_merge().
{
   common::sfv_t ret;
   converter_->convert(dat, ret);
   common::sort_and_merge(ret);
   return ret;
 }
pair< double, datum > jubatus::core::driver::clustering::to_weighted_datum (const core::clustering::weighted_point & src) const private
Definition at line 133 of file clustering.cpp.
References jubatus::core::clustering::weighted_point::original, and jubatus::core::clustering::weighted_point::weight.
{
   return std::make_pair(src.weight, src.original);
 }
core::clustering::cluster_unit jubatus::core::driver::clustering::to_weighted_datum_vector (const std::vector< core::clustering::weighted_point > & src) const private
Definition at line 168 of file clustering.cpp.
{
   core::clustering::cluster_unit ret;
   ret.reserve(src.size());
   std::transform(
       src.begin(),
       src.end(),
       std::back_inserter(ret),
       jubatus::util::lang::bind(
           &clustering::to_weighted_datum,
           this, jubatus::util::lang::_1));
   return ret;
 }
core::clustering::weighted_point jubatus::core::driver::clustering::to_weighted_point (const fv_converter::datum & src) private
Definition at line 124 of file clustering.cpp.
References jubatus::core::clustering::weighted_point::data, jubatus::core::clustering::weighted_point::original, and jubatus::core::clustering::weighted_point::weight.
                       {
   core::clustering::weighted_point ret;
   ret.data = to_sfv(src);
   ret.weight = 1;
   ret.original = src;
   return ret;
 }
vector< core::clustering::weighted_point > jubatus::core::driver::clustering::to_weighted_point_vector (const std::vector< fv_converter::datum > & src) private
Definition at line 153 of file clustering.cpp.
{
   vector<core::clustering::weighted_point> ret;
   ret.reserve(src.size());
   std::transform(
       src.begin(),
       src.end(),
       std::back_inserter(ret),
       jubatus::util::lang::bind(
           &clustering::to_weighted_point,
           this, jubatus::util::lang::_1));
   return ret;
 }
void jubatus::core::driver::clustering::unpack (msgpack::object o) virtual
Implements jubatus::core::driver::driver_base.
Definition at line 188 of file clustering.cpp.
{
   if (o.type != msgpack::type::ARRAY || o.via.array.size != 2) {
     throw msgpack::type_error();
   }
   // clear
   clustering_->clear();
   converter_->clear_weights();
   // load
   clustering_->unpack(o.via.array.ptr[0]);
   wm_.get_model()->unpack(o.via.array.ptr[1]);
 }
Member Data Documentation
jubatus::util::lang::shared_ptr<core::clustering::clustering> jubatus::core::driver::clustering::clustering_ private
Definition at line 85 of file clustering.hpp.
jubatus::util::lang::shared_ptr<fv_converter::datum_to_fv_converter> jubatus::core::driver::clustering::converter_ private
Definition at line 84 of file clustering.hpp.
fv_converter::mixable_weight_manager jubatus::core::driver::clustering::wm_ private
Definition at line 86 of file clustering.hpp.
The documentation for this class was generated from the following files:
jubatus/core/driver/clustering.hpp
jubatus/core/driver/clustering.cpp