jubatus_core: jubatus::core::table::detail::abstract_column_base Class Reference
jubatus::core::table::detail::abstract_column_base Class Reference abstract
#include <abstract_column.hpp>
Public Member Functions
abstract_column_base (const column_type &type)
virtual void clear ()=0
virtual void dump () const =0
virtual void dump (std::ostream &os, uint64_t target) const =0
JUBATUS_GEN_FUNCTIONS_ (uint8_t)
JUBATUS_GEN_FUNCTIONS_ (uint16_t)
JUBATUS_GEN_FUNCTIONS_ (uint32_t)
JUBATUS_GEN_FUNCTIONS_ (uint64_t)
JUBATUS_GEN_FUNCTIONS_ (int8_t)
JUBATUS_GEN_FUNCTIONS_ (int16_t)
JUBATUS_GEN_FUNCTIONS_ (int32_t)
JUBATUS_GEN_FUNCTIONS_ (int64_t)
JUBATUS_GEN_FUNCTIONS_ (float)
JUBATUS_GEN_FUNCTIONS_ (double)
JUBATUS_GEN_FUNCTIONS_ (std::string)
JUBATUS_GEN_FUNCTIONS_ (bit_vector)
JUBATUS_GEN_FUNCTIONS_ (msgpack::object)
virtual void pack_with_index (const uint64_t index, framework::packer &pk) const
virtual bool remove (uint64_t target)=0
column_type type () const
virtual ~abstract_column_base ()
Private Attributes
column_type my_type_
Detailed Description
Definition at line 41 of file abstract_column.hpp.
Constructor & Destructor Documentation
jubatus::core::table::detail::abstract_column_base::abstract_column_base (const column_type & type) inline explicit
Definition at line 43 of file abstract_column.hpp.
       : my_type_(type) {
   }
virtual jubatus::core::table::detail::abstract_column_base::~abstract_column_base () inline virtual
Definition at line 46 of file abstract_column.hpp.
{
   }
Member Function Documentation
virtual void jubatus::core::table::detail::abstract_column_base::clear () pure virtual
Implemented in jubatus::core::table::typed_column< bit_vector >, and jubatus::core::table::typed_column< T >.
virtual void jubatus::core::table::detail::abstract_column_base::dump () const pure virtual
Implemented in jubatus::core::table::typed_column< bit_vector >, and jubatus::core::table::typed_column< T >.
virtual void jubatus::core::table::detail::abstract_column_base::dump (std::ostream & os, uint64_t target) const pure virtual
Implemented in jubatus::core::table::typed_column< bit_vector >, and jubatus::core::table::typed_column< T >.
jubatus::core::table::detail::abstract_column_base::JUBATUS_GEN_FUNCTIONS_ (uint8_t)
jubatus::core::table::detail::abstract_column_base::JUBATUS_GEN_FUNCTIONS_ (uint16_t)
jubatus::core::table::detail::abstract_column_base::JUBATUS_GEN_FUNCTIONS_ (uint32_t)
jubatus::core::table::detail::abstract_column_base::JUBATUS_GEN_FUNCTIONS_ (uint64_t)
jubatus::core::table::detail::abstract_column_base::JUBATUS_GEN_FUNCTIONS_ (int8_t)
jubatus::core::table::detail::abstract_column_base::JUBATUS_GEN_FUNCTIONS_ (int16_t)
jubatus::core::table::detail::abstract_column_base::JUBATUS_GEN_FUNCTIONS_ (int32_t)
jubatus::core::table::detail::abstract_column_base::JUBATUS_GEN_FUNCTIONS_ (int64_t)
jubatus::core::table::detail::abstract_column_base::JUBATUS_GEN_FUNCTIONS_ (float)
jubatus::core::table::detail::abstract_column_base::JUBATUS_GEN_FUNCTIONS_ (double)
jubatus::core::table::detail::abstract_column_base::JUBATUS_GEN_FUNCTIONS_ (std::string)
jubatus::core::table::detail::abstract_column_base::JUBATUS_GEN_FUNCTIONS_ (bit_vector)
jubatus::core::table::detail::abstract_column_base::JUBATUS_GEN_FUNCTIONS_ (msgpack::object)
virtual void jubatus::core::table::detail::abstract_column_base::pack_with_index (const uint64_t index, framework::packer & pk) const inline virtual
Reimplemented in jubatus::core::table::typed_column< bit_vector >, and jubatus::core::table::typed_column< T >.
Definition at line 90 of file abstract_column.hpp.
{
   }
virtual bool jubatus::core::table::detail::abstract_column_base::remove (uint64_t target) pure virtual
Implemented in jubatus::core::table::typed_column< bit_vector >, and jubatus::core::table::typed_column< T >.
column_type jubatus::core::table::detail::abstract_column_base::type () const inline
Definition at line 49 of file abstract_column.hpp.
References my_type_.
Referenced by jubatus::core::table::typed_column< bit_vector >::bytes_per_value_(), jubatus::core::table::typed_column< bit_vector >::check_bit_vector_(), jubatus::core::table::typed_column< T >::dump(), jubatus::core::table::typed_column< bit_vector >::insert(), jubatus::core::table::typed_column< bit_vector >::operator[](), jubatus::core::table::typed_column< bit_vector >::push_back(), and jubatus::core::table::typed_column< bit_vector >::update().
{
     return my_type_;
   }
Member Data Documentation
column_type jubatus::core::table::detail::abstract_column_base::my_type_ private
Definition at line 97 of file abstract_column.hpp.
Referenced by type().
The documentation for this class was generated from the following file:
jubatus/core/table/column/abstract_column.hpp