jubatus_core: jubatus::core::classifier::passive_aggressive_1 Class Reference
jubatus::core::classifier::passive_aggressive_1 Class Reference
#include <passive_aggressive_1.hpp>
Public Member Functions
std::string name () const
passive_aggressive_1 (storage_ptr storage)
passive_aggressive_1 (const classifier_config &config, storage_ptr storage)
void train (const common::sfv_t &fv, const std::string &label)
Public Member Functions inherited from jubatus::core::classifier::linear_classifier
std::string classify (const common::sfv_t &fv) const
void classify_with_scores (const common::sfv_t &fv, classify_result &scores) const
void clear ()
bool delete_label (const std::string &label)
std::vector< std::string > get_labels () const
framework::mixable * get_mixable ()
virtual void get_status (std::map< std::string, std::string > &status) const
jubatus::util::lang::shared_ptr< unlearner::unlearner_base > label_unlearner () const
linear_classifier (storage_ptr storage)
void pack (framework::packer &pk) const
bool set_label (const std::string &label)
void set_label_unlearner (jubatus::util::lang::shared_ptr< unlearner::unlearner_base > label_unlearner)
bool unlearn_label (const std::string &label)
void unpack (msgpack::object o)
virtual ~linear_classifier ()
Public Member Functions inherited from jubatus::core::classifier::classifier_base
classifier_base ()
virtual ~classifier_base ()
Private Attributes
classifier_config config_
Additional Inherited Members
Protected Member Functions inherited from jubatus::core::classifier::linear_classifier
float calc_margin (const common::sfv_t &sfv, const std::string &label, std::string &incorrect_label) const
float calc_margin_and_variance (const common::sfv_t &sfv, const std::string &label, std::string &incorrect_label, float &variance) const
void check_touchable (const std::string &label)
std::string get_largest_incorrect_label (const common::sfv_t &sfv, const std::string &label, classify_result &scores) const
void touch (const std::string &label)
void update_weight (const common::sfv_t &sfv, float step_weigth, const std::string &pos_label, const std::string &neg_class)
Static Protected Member Functions inherited from jubatus::core::classifier::linear_classifier
static float squared_norm (const common::sfv_t &sfv)
Protected Attributes inherited from jubatus::core::classifier::linear_classifier
framework::linear_function_mixer mixable_storage_
storage_ptr storage_
jubatus::util::lang::shared_ptr< unlearner::unlearner_base > unlearner_
Detailed Description
Definition at line 28 of file passive_aggressive_1.hpp.
Constructor & Destructor Documentation
jubatus::core::classifier::passive_aggressive_1::passive_aggressive_1 (storage_ptr storage) explicit
Definition at line 31 of file passive_aggressive_1.cpp.
     : linear_classifier(storage) {
 }
jubatus::core::classifier::passive_aggressive_1::passive_aggressive_1 (const classifier_config & config, storage_ptr storage)
Definition at line 35 of file passive_aggressive_1.cpp.
References JUBATUS_EXCEPTION, and jubatus::core::classifier::classifier_config::regularization_weight.
     : linear_classifier(storage),
       config_(config) {
   if (!(0.f < config.regularization_weight)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("0.0 < regularization_weight"));
   }
 }
Member Function Documentation
string jubatus::core::classifier::passive_aggressive_1::name () const virtual
Implements jubatus::core::classifier::linear_classifier.
Definition at line 72 of file passive_aggressive_1.cpp.
{
   return string("passive_aggressive_1");
 }
void jubatus::core::classifier::passive_aggressive_1::train (const common::sfv_t & fv, const std::string & label) virtual
Implements jubatus::core::classifier::linear_classifier.
Definition at line 47 of file passive_aggressive_1.cpp.
References jubatus::core::classifier::linear_classifier::calc_margin(), jubatus::core::classifier::linear_classifier::check_touchable(), config_, jubatus::core::classifier::classifier_config::regularization_weight, jubatus::core::classifier::linear_classifier::squared_norm(), jubatus::core::classifier::linear_classifier::storage_, jubatus::core::classifier::linear_classifier::touch(), and jubatus::core::classifier::linear_classifier::update_weight().
{
   check_touchable(label);
   string incorrect_label;
   float margin = calc_margin(sfv, label, incorrect_label);
   float loss = 1.f + margin;
   if (loss < 0.f) {
     storage_->register_label(label);
     return;
   }
   float sfv_norm = squared_norm(sfv);
   if (sfv_norm == 0.f) {
     storage_->register_label(label);
     return;
   }
   update_weight(
       sfv,
       min(config_.regularization_weight, loss / (2 * sfv_norm)),
       label,
       incorrect_label);
   touch(label);
 }
Member Data Documentation
classifier_config jubatus::core::classifier::passive_aggressive_1::config_ private
Definition at line 37 of file passive_aggressive_1.hpp.
Referenced by train().
The documentation for this class was generated from the following files:
jubatus/core/classifier/passive_aggressive_1.hpp
jubatus/core/classifier/passive_aggressive_1.cpp