jubatus_core: jubatus::core::fv_converter::factory_extender Class Reference
jubatus::core::fv_converter::factory_extender Class Reference abstract
#include <factory.hpp>
Public Member Functions
virtual binary_feature * create_binary_feature (const std::string &name, const param_t &) const =0
virtual combination_feature * create_combination_feature (const std::string &name, const param_t &) const =0
virtual num_feature * create_num_feature (const std::string &name, const param_t &) const =0
virtual num_filter * create_num_filter (const std::string &name, const param_t &) const =0
virtual string_feature * create_string_feature (const std::string &name, const param_t &) const =0
virtual string_filter * create_string_filter (const std::string &name, const param_t &) const =0
virtual ~factory_extender ()
Detailed Description
Definition at line 34 of file factory.hpp.
Constructor & Destructor Documentation
virtual jubatus::core::fv_converter::factory_extender::~factory_extender () inline virtual
Definition at line 36 of file factory.hpp.
 {}
Member Function Documentation
virtual binary_feature* jubatus::core::fv_converter::factory_extender::create_binary_feature (const std::string & name, const param_t &) const pure virtual
Referenced by jubatus::core::fv_converter::initialize_converter().
virtual combination_feature* jubatus::core::fv_converter::factory_extender::create_combination_feature (const std::string & name, const param_t &) const pure virtual
Referenced by jubatus::core::fv_converter::initialize_converter().
virtual num_feature* jubatus::core::fv_converter::factory_extender::create_num_feature (const std::string & name, const param_t &) const pure virtual
Referenced by jubatus::core::fv_converter::initialize_converter().
virtual num_filter* jubatus::core::fv_converter::factory_extender::create_num_filter (const std::string & name, const param_t &) const pure virtual
Referenced by jubatus::core::fv_converter::initialize_converter().
virtual string_feature* jubatus::core::fv_converter::factory_extender::create_string_feature (const std::string & name, const param_t &) const pure virtual
Referenced by jubatus::core::fv_converter::initialize_converter().
virtual string_filter* jubatus::core::fv_converter::factory_extender::create_string_filter (const std::string & name, const param_t &) const pure virtual
Referenced by jubatus::core::fv_converter::initialize_converter().
The documentation for this class was generated from the following file:
jubatus/core/fv_converter/factory.hpp