jubatus_core: jubatus::core::common::jsonconfig::json_config_iarchive_cast Class Reference
jubatus::core::common::jsonconfig::json_config_iarchive_cast Class Reference
#include <cast.hpp>
Public Member Functions
config_error_list * errors () const
const jubatus::util::text::json::json & get () const
const config & get_config () const
json_config_iarchive_cast (const config &js)
json_config_iarchive_cast (const config &js, config_error_list *errors)
template<class T >
void push_error (const T &e)
bool trace_error () const
Private Attributes
config_error_list * errors_
const config & js_
Detailed Description
Definition at line 60 of file cast.hpp.
Constructor & Destructor Documentation
jubatus::core::common::jsonconfig::json_config_iarchive_cast::json_config_iarchive_cast (const config & js) inline explicit
Definition at line 62 of file cast.hpp.
       : js_(js),
         errors_(NULL) {
   }
jubatus::core::common::jsonconfig::json_config_iarchive_cast::json_config_iarchive_cast (const config & js, config_error_list * errors) inline
Definition at line 66 of file cast.hpp.
       : js_(js),
         errors_(errors) {
   }
Member Function Documentation
config_error_list* jubatus::core::common::jsonconfig::json_config_iarchive_cast::errors () const inline
Definition at line 90 of file cast.hpp.
References errors_.
Referenced by jubatus::core::common::jsonconfig::serialize().
{
     return errors_;
   }
const jubatus::util::text::json::json& jubatus::core::common::jsonconfig::json_config_iarchive_cast::get () const inline
Definition at line 74 of file cast.hpp.
References jubatus::core::common::jsonconfig::config::get(), and js_.
Referenced by jubatus::core::common::jsonconfig::detail::check_json_float(), jubatus::core::common::jsonconfig::detail::check_json_type(), and jubatus::core::common::jsonconfig::serialize().
{
     return js_.get();
   }
const config& jubatus::core::common::jsonconfig::json_config_iarchive_cast::get_config () const inline
Definition at line 71 of file cast.hpp.
References js_.
Referenced by jubatus::core::common::jsonconfig::detail::check_json_float(), jubatus::core::common::jsonconfig::detail::check_json_type(), and jubatus::core::common::jsonconfig::serialize().
{
     return js_;
   }
template<class T > void jubatus::core::common::jsonconfig::json_config_iarchive_cast::push_error (const T & e) inline
Definition at line 83 of file cast.hpp.
References errors_.
Referenced by jubatus::core::common::jsonconfig::detail::check_json_float(), jubatus::core::common::jsonconfig::detail::check_json_type(), and jubatus::core::common::jsonconfig::serialize().
{
     if (errors_) {
       errors_->push_back(
           jubatus::util::lang::shared_ptr<config_error>(new T(e)));
     }
   }
bool jubatus::core::common::jsonconfig::json_config_iarchive_cast::trace_error () const inline
Definition at line 78 of file cast.hpp.
References errors_.
Referenced by jubatus::core::common::jsonconfig::detail::check_json_float(), jubatus::core::common::jsonconfig::detail::check_json_type(), and jubatus::core::common::jsonconfig::serialize().
{
     return errors_;
   }
Member Data Documentation
config_error_list* jubatus::core::common::jsonconfig::json_config_iarchive_cast::errors_ private
Definition at line 96 of file cast.hpp.
Referenced by errors(), push_error(), and trace_error().
const config& jubatus::core::common::jsonconfig::json_config_iarchive_cast::js_ private
Definition at line 95 of file cast.hpp.
Referenced by get(), and get_config().
The documentation for this class was generated from the following file:
jubatus/core/common/jsonconfig/cast.hpp