jubatus_core: jubatus::core::recommender::recommender_factory Class Reference
jubatus::core::recommender::recommender_factory Class Reference
#include <recommender_factory.hpp>
Static Public Member Functions
static jubatus::util::lang::shared_ptr< recommender_base > create_recommender (const std::string &name, const common::jsonconfig::config &param, const std::string &id)
Detailed Description
Definition at line 35 of file recommender_factory.hpp.
Member Function Documentation
shared_ptr< recommender_base > jubatus::core::recommender::recommender_factory::create_recommender (const std::string & name, const common::jsonconfig::config & param, const std::string & id) static
Definition at line 56 of file recommender_factory.cpp.
References jubatus::core::nearest_neighbor::create_nearest_neighbor(), jubatus::core::unlearner::create_unlearner(), and JUBATUS_EXCEPTION.
Referenced by jubatus::core::anomaly::anomaly_factory::create_anomaly().
                       {
   if (name == "inverted_index") {
     // inverted_index doesn't have parameter
     return shared_ptr<recommender_base>(new inverted_index);
   } else if (name == "minhash") {
     return shared_ptr<recommender_base>(
         new minhash(config_cast_check<minhash::config>(param)));
   } else if (name == "lsh") {
     return shared_ptr<recommender_base>(
         new lsh(config_cast_check<lsh::config>(param)));
   } else if (name == "euclid_lsh") {
     return shared_ptr<recommender_base>(
         new euclid_lsh(config_cast_check<euclid_lsh::config>(param)));
   } else if (name == "nearest_neighbor_recommender") {
     nearest_neighbor_recommender_config conf =
         config_cast_check<nearest_neighbor_recommender_config>(param);
     shared_ptr<storage::column_table> table(new storage::column_table);
     shared_ptr<nearest_neighbor::nearest_neighbor_base>
         nearest_neighbor_engine(nearest_neighbor::create_nearest_neighbor(
             conf.method, conf.parameter, table, id));
     if (conf.unlearner) {
       if (!conf.unlearner_parameter) {
         throw JUBATUS_EXCEPTION(
             common::config_exception() << common::exception::error_message(
                 "unlearner is set but unlearner_parameter is not found"));
       }
       shared_ptr<unlearner::unlearner_base> unl(unlearner::create_unlearner(
           *conf.unlearner, common::jsonconfig::config(
               *conf.unlearner_parameter)));
       return shared_ptr<recommender_base>(
           new nearest_neighbor_recommender(nearest_neighbor_engine, unl));
     }
     return shared_ptr<recommender_base>(
         new nearest_neighbor_recommender(nearest_neighbor_engine));
   } else {
     throw JUBATUS_EXCEPTION(common::unsupported_method(name));
   }
 }
The documentation for this class was generated from the following files:
jubatus/core/recommender/recommender_factory.hpp
jubatus/core/recommender/recommender_factory.cpp