jubatus_core: jubatus::core::common::assoc_vector< K, V > Class Template Reference
jubatus::core::common::assoc_vector< K, V > Class Template Reference
#include <assoc_vector.hpp>
Classes
struct less_pair_and_key
Public Types
typedef data_type::const_iterator const_iterator
typedef std::vector< std::pair< K, V > > data_type
typedef data_type::iterator iterator
Public Member Functions
const_iterator begin () const
iterator begin ()
size_t count (const K &key) const
bool empty () const
const_iterator end () const
iterator end ()
iterator erase (const K &key)
iterator erase (iterator it)
const_iterator find (const K &key) const
iterator find (const K &key)
template<typename Packer >
void msgpack_pack (Packer &pk) const
void msgpack_unpack (msgpack::object o)
V & operator[] (const K &key)
size_t size () const
Private Attributes
std::vector< std::pair< K, V > > data_
Detailed Description
template<typename K, typename V>
class jubatus::core::common::assoc_vector< K, V >
Definition at line 30 of file assoc_vector.hpp.
Member Typedef Documentation
template<typename K , typename V > typedef data_type::const_iterator jubatus::core::common::assoc_vector< K, V >::const_iterator
Definition at line 33 of file assoc_vector.hpp.
template<typename K , typename V > typedef std::vector<std::pair<K, V> > jubatus::core::common::assoc_vector< K, V >::data_type
Definition at line 32 of file assoc_vector.hpp.
template<typename K , typename V > typedef data_type::iterator jubatus::core::common::assoc_vector< K, V >::iterator
Definition at line 34 of file assoc_vector.hpp.
Member Function Documentation
template<typename K , typename V > const_iterator jubatus::core::common::assoc_vector< K, V >::begin () const inline
Definition at line 36 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::data_.
Referenced by jubatus::core::storage::inverted_index_storage::add_inp_scores(), jubatus::core::storage::sparse_matrix_storage::calc_l2norm(), jubatus::core::common::assoc_vector< K, V >::find(), jubatus::core::storage::sparse_matrix_storage::get_row(), and jubatus::core::common::assoc_vector< K, V >::operator[]().
{
     return data_.begin();
   }
template<typename K , typename V > iterator jubatus::core::common::assoc_vector< K, V >::begin () inline
Definition at line 40 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::data_.
                    {
     return data_.begin();
   }
template<typename K , typename V > size_t jubatus::core::common::assoc_vector< K, V >::count (const K & key) const inline
Definition at line 77 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::end(), and jubatus::core::common::assoc_vector< K, V >::find().
{
     if (find(key) == end()) {
       return 0;
     } else {
       return 1;
     }
   }
template<typename K , typename V > bool jubatus::core::common::assoc_vector< K, V >::empty () const inline
Definition at line 56 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::data_.
                      {
     return data_.empty();
   }
template<typename K , typename V > const_iterator jubatus::core::common::assoc_vector< K, V >::end () const inline
Definition at line 44 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::data_.
Referenced by jubatus::core::storage::inverted_index_storage::add_inp_scores(), jubatus::core::storage::sparse_matrix_storage::calc_l2norm(), jubatus::core::common::assoc_vector< K, V >::count(), jubatus::core::common::assoc_vector< K, V >::erase(), jubatus::core::common::assoc_vector< K, V >::find(), jubatus::core::storage::sparse_matrix_storage::get_row(), and jubatus::core::common::assoc_vector< K, V >::operator[]().
{
     return data_.end();
   }
template<typename K , typename V > iterator jubatus::core::common::assoc_vector< K, V >::end () inline
Definition at line 48 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::data_.
                  {
     return data_.end();
   }
template<typename K , typename V > iterator jubatus::core::common::assoc_vector< K, V >::erase (const K & key) inline
Definition at line 85 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::data_, jubatus::core::common::assoc_vector< K, V >::end(), and jubatus::core::common::assoc_vector< K, V >::find().
Referenced by jubatus::core::storage::inverted_index_storage::put_diff().
{
     iterator it = find(key);
     if (it != data_.end()) {
       return erase(it);
     } else {
       return end();
     }
   }
template<typename K , typename V > iterator jubatus::core::common::assoc_vector< K, V >::erase (iterator it) inline
Definition at line 94 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::data_.
{
     return data_.erase(it);
   }
template<typename K , typename V > const_iterator jubatus::core::common::assoc_vector< K, V >::find (const K & key) const inline
Definition at line 60 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::begin(), and jubatus::core::common::assoc_vector< K, V >::end().
Referenced by jubatus::core::storage::inverted_index_storage::add_inp_scores(), jubatus::core::common::assoc_vector< K, V >::count(), jubatus::core::common::assoc_vector< K, V >::erase(), and jubatus::core::common::assoc_vector< K, V >::find().
{
     const_iterator it = std::lower_bound(begin(),
                                          end(),
                                          key,
                                          less_pair_and_key());
     if (it != end() && it->first == key) {
       return it;
     } else {
       return end();
     }
   }
template<typename K , typename V > iterator jubatus::core::common::assoc_vector< K, V >::find (const K & key) inline
Definition at line 72 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::begin(), and jubatus::core::common::assoc_vector< K, V >::find().
{
     const_iterator it = const_cast<const assoc_vector&>(*this).find(key);
     return begin() + (it - begin());
   }
template<typename K , typename V > template<typename Packer > void jubatus::core::common::assoc_vector< K, V >::msgpack_pack (Packer & pk) const inline
Definition at line 109 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::data_.
{
     pk.pack_map(data_.size());
     for (std::size_t i = 0; i < data_.size(); ++i) {
       pk.pack(data_[i].first);
       pk.pack(data_[i].second);
     }
   }
template<typename K , typename V > void jubatus::core::common::assoc_vector< K, V >::msgpack_unpack (msgpack::object o) inline
Definition at line 117 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::data_.
{
     if (o.type != msgpack::type::MAP) {
       throw msgpack::type_error();
     }
     std::vector<std::pair<K, V> > data(o.via.map.size);
     for (std::size_t i = 0; i < data.size(); ++i) {
       o.via.map.ptr[i].key.convert(&data[i].first);
       o.via.map.ptr[i].val.convert(&data[i].second);
     }
     data.swap(data_);
   }
template<typename K , typename V > V& jubatus::core::common::assoc_vector< K, V >::operator[] (const K & key) inline
Definition at line 98 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::begin(), jubatus::core::common::assoc_vector< K, V >::data_, and jubatus::core::common::assoc_vector< K, V >::end().
{
     iterator it = std::lower_bound(begin(), end(), key, less_pair_and_key());
     if (it != data_.end() && it->first == key) {
       return it->second;
     } else {
       it = data_.insert(it, std::make_pair(key, V()));
       return it->second;
     }
   }
template<typename K , typename V > size_t jubatus::core::common::assoc_vector< K, V >::size () const inline
Definition at line 52 of file assoc_vector.hpp.
References jubatus::core::common::assoc_vector< K, V >::data_.
                       {
     return data_.size();
   }
Member Data Documentation
template<typename K , typename V > std::vector<std::pair<K, V> > jubatus::core::common::assoc_vector< K, V >::data_ private
Definition at line 137 of file assoc_vector.hpp.
Referenced by jubatus::core::common::assoc_vector< K, V >::begin(), jubatus::core::common::assoc_vector< K, V >::empty(), jubatus::core::common::assoc_vector< K, V >::end(), jubatus::core::common::assoc_vector< K, V >::erase(), jubatus::core::common::assoc_vector< K, V >::msgpack_pack(), jubatus::core::common::assoc_vector< K, V >::msgpack_unpack(), jubatus::core::common::assoc_vector< K, V >::operator[](), and jubatus::core::common::assoc_vector< K, V >::size().
The documentation for this class was generated from the following file:
jubatus/core/common/assoc_vector.hpp