jubatus_core: jubatus::core::bandit::exp3 Class Reference
jubatus::core::bandit::exp3 Class Reference
#include <exp3.hpp>
Public Member Functions
void clear ()
bool delete_arm (const std::string &arm_id)
exp3 (double gamma)
arm_info_map get_arm_info (const std::string &player_id) const
void get_diff (diff_t &diff) const
void mix (const diff_t &lhs, diff_t &rhs) const
std::string name () const
void pack (framework::packer &pk) const
bool put_diff (const diff_t &diff)
bool register_arm (const std::string &arm_id)
bool register_reward (const std::string &player_id, const std::string &arm_id, double reward)
bool reset (const std::string &player_id)
std::string select_arm (const std::string &player_id)
void unpack (msgpack::object o)
Public Member Functions inherited from jubatus::core::bandit::bandit_base
bandit_base ()
core::storage::version get_version () const
virtual ~bandit_base ()
Private Member Functions
void calc_weights_ (const std::string &player_id, std::vector< double > &weights) const
Private Attributes
double gamma_
jubatus::util::math::random::mtrand rand_
summation_storage s_
Additional Inherited Members
Public Types inherited from jubatus::core::bandit::bandit_base
typedef jubatus::util::data::unordered_map< std::string, arm_info_map > diff_t
Detailed Description
Definition at line 31 of file exp3.hpp.
Constructor & Destructor Documentation
jubatus::core::bandit::exp3::exp3 (double gamma) explicit
Definition at line 28 of file exp3.cpp.
References JUBATUS_EXCEPTION.
     : gamma_(gamma) {
   if (gamma < 0 || 1 < gamma) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("0 <= gamma <= 1"));
   }
 }
Member Function Documentation
void jubatus::core::bandit::exp3::calc_weights_ (const std::string & player_id, std::vector< double > & weights) const private
Definition at line 36 of file exp3.cpp.
References gamma_, jubatus::core::bandit::summation_storage::get_arm_ids(), jubatus::core::bandit::summation_storage::get_arm_info(), JUBATUS_EXCEPTION, s_, and jubatus::core::bandit::arm_info::weight.
Referenced by register_reward(), and select_arm().
{
   const std::vector<std::string>& arms = s_.get_arm_ids();
   if (arms.empty()) {
     throw JUBATUS_EXCEPTION(
         common::exception::runtime_error("arm is not registered"));
   }
   const size_t n = arms.size();
   weights.clear();
   weights.reserve(n);
   double total_weight = 0;
   for (size_t i = 0; i < n; ++i) {
     const double weight = std::exp(s_.get_arm_info(player_id, arms[i]).weight);
     weights.push_back(weight);
     total_weight += weight;
   }
   for (size_t i = 0; i < n; ++i) {
     weights[i] = (1.0 - gamma_) * weights[i] / total_weight + gamma_ * n;
   }
 }
void jubatus::core::bandit::exp3::clear () virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 98 of file exp3.cpp.
References jubatus::core::bandit::summation_storage::clear(), and s_.
                  {
   s_.clear();
 }
bool jubatus::core::bandit::exp3::delete_arm (const std::string & arm_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 73 of file exp3.cpp.
References jubatus::core::bandit::summation_storage::delete_arm(), and s_.
{
   return s_.delete_arm(arm_id);
 }
arm_info_map jubatus::core::bandit::exp3::get_arm_info (const std::string & player_id) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 91 of file exp3.cpp.
References jubatus::core::bandit::summation_storage::get_arm_info_map(), and s_.
{
   return s_.get_arm_info_map(arm_id);
 }
void jubatus::core::bandit::exp3::get_diff (diff_t & diff) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 109 of file exp3.cpp.
References jubatus::core::bandit::summation_storage::get_diff(), and s_.
{
   s_.get_diff(diff);
 }
void jubatus::core::bandit::exp3::mix (const diff_t & lhs, diff_t & rhs) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 115 of file exp3.cpp.
References jubatus::core::bandit::summation_storage::mix(), and s_.
{
   s_.mix(lhs, rhs);
 }
std::string jubatus::core::bandit::exp3::name () const inline virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 49 of file exp3.hpp.
{
     return "exp3";
   }
void jubatus::core::bandit::exp3::pack (framework::packer & pk) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 102 of file exp3.cpp.
References s_.
{
   pk.pack(s_);
 }
bool jubatus::core::bandit::exp3::put_diff (const diff_t & diff) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 112 of file exp3.cpp.
References jubatus::core::bandit::summation_storage::put_diff(), and s_.
{
   return s_.put_diff(diff);
 }
bool jubatus::core::bandit::exp3::register_arm (const std::string & arm_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 70 of file exp3.cpp.
References jubatus::core::bandit::summation_storage::register_arm(), and s_.
{
   return s_.register_arm(arm_id);
 }
bool jubatus::core::bandit::exp3::register_reward (const std::string & player_id, const std::string & arm_id, double reward) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 77 of file exp3.cpp.
References calc_weights_(), gamma_, jubatus::core::bandit::summation_storage::get_arm_ids(), jubatus::core::bandit::summation_storage::register_reward(), and s_.
{
   const std::vector<std::string>& arms = s_.get_arm_ids();
   size_t i = std::find(arms.begin(), arms.end(), arm_id) - arms.begin();
   if (i >= arms.size()) {
     return false;
   }
   std::vector<double> weights;
   calc_weights_(player_id, weights);
   return s_.register_reward(player_id, arm_id,
                             reward * weights[i] * gamma_ / arms.size());
 }
bool jubatus::core::bandit::exp3::reset (const std::string & player_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 95 of file exp3.cpp.
References jubatus::core::bandit::summation_storage::reset(), and s_.
{
   return s_.reset(player_id);
 }
std::string jubatus::core::bandit::exp3::select_arm (const std::string & player_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 58 of file exp3.cpp.
References calc_weights_(), jubatus::core::bandit::summation_storage::get_arm_ids(), JUBATUS_EXCEPTION, rand_, s_, and jubatus::core::bandit::select_by_weights().
{
   const std::vector<std::string>& arms = s_.get_arm_ids();
   if (arms.empty()) {
     throw JUBATUS_EXCEPTION(
         common::exception::runtime_error("arm is not registered"));
   }
   std::vector<double> weights;
   calc_weights_(player_id, weights);
   return arms[select_by_weights(weights, rand_)];
 }
void jubatus::core::bandit::exp3::unpack (msgpack::object o) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 105 of file exp3.cpp.
References s_.
{
   o.convert(&s_);
 }
Member Data Documentation
double jubatus::core::bandit::exp3::gamma_ private
Definition at line 61 of file exp3.hpp.
Referenced by calc_weights_(), and register_reward().
jubatus::util::math::random::mtrand jubatus::core::bandit::exp3::rand_ private
Definition at line 62 of file exp3.hpp.
Referenced by select_arm().
summation_storage jubatus::core::bandit::exp3::s_ private
Definition at line 63 of file exp3.hpp.
Referenced by calc_weights_(), clear(), delete_arm(), get_arm_info(), get_diff(), mix(), pack(), put_diff(), register_arm(), register_reward(), reset(), select_arm(), and unpack().
The documentation for this class was generated from the following files:
jubatus/core/bandit/exp3.hpp
jubatus/core/bandit/exp3.cpp