jubatus_core: jubatus::core::bandit::epsilon_greedy Class Reference
jubatus::core::bandit::epsilon_greedy Class Reference
#include <epsilon_greedy.hpp>
Public Member Functions
void clear ()
bool delete_arm (const std::string &arm_id)
epsilon_greedy (bool assume_unrewarded, double eps)
arm_info_map get_arm_info (const std::string &player_id) const
void get_diff (diff_t &diff) const
storage::version get_version () const
void mix (const diff_t &lhs, diff_t &rhs) const
std::string name () const
void pack (framework::packer &pk) const
bool put_diff (const diff_t &diff)
bool register_arm (const std::string &arm_id)
bool register_reward (const std::string &player_id, const std::string &arm_id, double reward)
bool reset (const std::string &player_id)
std::string select_arm (const std::string &player_id)
void unpack (msgpack::object o)
Public Member Functions inherited from jubatus::core::bandit::bandit_base
bandit_base ()
virtual ~bandit_base ()
Private Attributes
double eps_
jubatus::util::math::random::mtrand rand_
summation_storage s_
Additional Inherited Members
Public Types inherited from jubatus::core::bandit::bandit_base
typedef jubatus::util::data::unordered_map< std::string, arm_info_map > diff_t
Detailed Description
Definition at line 30 of file epsilon_greedy.hpp.
Constructor & Destructor Documentation
jubatus::core::bandit::epsilon_greedy::epsilon_greedy (bool assume_unrewarded, double eps)
Definition at line 29 of file epsilon_greedy.cpp.
References JUBATUS_EXCEPTION.
     : eps_(eps), s_(assume_unrewarded) {
   if (eps < 0 || 1 < eps) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("0 <= epsilon <= 1"));
   }
 }
Member Function Documentation
void jubatus::core::bandit::epsilon_greedy::clear () virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 84 of file epsilon_greedy.cpp.
References jubatus::core::bandit::summation_storage::clear(), and s_.
{
   s_.clear();
 }
bool jubatus::core::bandit::epsilon_greedy::delete_arm (const std::string & arm_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 67 of file epsilon_greedy.cpp.
References jubatus::core::bandit::summation_storage::delete_arm(), and s_.
{
   return s_.delete_arm(arm_id);
 }
arm_info_map jubatus::core::bandit::epsilon_greedy::get_arm_info (const std::string & player_id) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 77 of file epsilon_greedy.cpp.
References jubatus::core::bandit::summation_storage::get_arm_info_map(), and s_.
{
   return s_.get_arm_info_map(player_id);
 }
void jubatus::core::bandit::epsilon_greedy::get_diff (diff_t & diff) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 95 of file epsilon_greedy.cpp.
References jubatus::core::bandit::summation_storage::get_diff(), and s_.
{
   s_.get_diff(diff);
 }
storage::version jubatus::core::bandit::epsilon_greedy::get_version () const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 105 of file epsilon_greedy.cpp.
{
   return storage::version();
 }
void jubatus::core::bandit::epsilon_greedy::mix (const diff_t & lhs, diff_t & rhs) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 101 of file epsilon_greedy.cpp.
References jubatus::core::bandit::summation_storage::mix(), and s_.
{
   s_.mix(lhs, rhs);
 }
std::string jubatus::core::bandit::epsilon_greedy::name () const inline virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 48 of file epsilon_greedy.hpp.
{
     return "epsilon_greedy";
   }
void jubatus::core::bandit::epsilon_greedy::pack (framework::packer & pk) const virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 88 of file epsilon_greedy.cpp.
References s_.
{
   pk.pack(s_);
 }
bool jubatus::core::bandit::epsilon_greedy::put_diff (const diff_t & diff) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 98 of file epsilon_greedy.cpp.
References jubatus::core::bandit::summation_storage::put_diff(), and s_.
{
   return s_.put_diff(diff);
 }
bool jubatus::core::bandit::epsilon_greedy::register_arm (const std::string & arm_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 64 of file epsilon_greedy.cpp.
References jubatus::core::bandit::summation_storage::register_arm(), and s_.
{
   return s_.register_arm(arm_id);
 }
bool jubatus::core::bandit::epsilon_greedy::register_reward (const std::string & player_id, const std::string & arm_id, double reward) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 71 of file epsilon_greedy.cpp.
References jubatus::core::bandit::summation_storage::register_reward(), and s_.
{
   return s_.register_reward(player_id, arm_id, reward);
 }
bool jubatus::core::bandit::epsilon_greedy::reset (const std::string & player_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 81 of file epsilon_greedy.cpp.
References jubatus::core::bandit::summation_storage::reset(), and s_.
{
   return s_.reset(player_id);
 }
std::string jubatus::core::bandit::epsilon_greedy::select_arm (const std::string & player_id) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 37 of file epsilon_greedy.cpp.
References eps_, jubatus::core::bandit::summation_storage::get_arm_ids(), jubatus::core::bandit::summation_storage::get_expectation(), JUBATUS_EXCEPTION, jubatus::core::bandit::summation_storage::notify_selected(), rand_, and s_.
{
   const std::vector<std::string>& arms = s_.get_arm_ids();
   if (arms.empty()) {
     throw JUBATUS_EXCEPTION(
         common::exception::runtime_error("arm is not registered"));
   }
   std::string result;
   if (rand_.next_double() < eps_) {
     // exploration
     result = arms[rand_.next_int(arms.size())];
   } else {
     // exploitation
     result = arms[0];
     double exp_max = s_.get_expectation(player_id, arms[0]);
     for (size_t i = 1; i < arms.size(); ++i) {
       double exp = s_.get_expectation(player_id, arms[i]);
       if (exp > exp_max) {
         result = arms[i];
         exp_max = exp;
       }
     }
   }
   s_.notify_selected(player_id, result);
   return result;
 }
void jubatus::core::bandit::epsilon_greedy::unpack (msgpack::object o) virtual
Implements jubatus::core::bandit::bandit_base.
Definition at line 91 of file epsilon_greedy.cpp.
References s_.
{
   o.convert(&s_);
 }
Member Data Documentation
double jubatus::core::bandit::epsilon_greedy::eps_ private
Definition at line 61 of file epsilon_greedy.hpp.
Referenced by select_arm().
jubatus::util::math::random::mtrand jubatus::core::bandit::epsilon_greedy::rand_ private
Definition at line 62 of file epsilon_greedy.hpp.
Referenced by select_arm().
summation_storage jubatus::core::bandit::epsilon_greedy::s_ private
Definition at line 63 of file epsilon_greedy.hpp.
Referenced by clear(), delete_arm(), get_arm_info(), get_diff(), mix(), pack(), put_diff(), register_arm(), register_reward(), reset(), select_arm(), and unpack().
The documentation for this class was generated from the following files:
jubatus/core/bandit/epsilon_greedy.hpp
jubatus/core/bandit/epsilon_greedy.cpp