jubatus_core: jubatus::core::nearest_neighbor::nearest_neighbor_base Class Reference
jubatus::core::nearest_neighbor::nearest_neighbor_base Class Reference abstract
#include <nearest_neighbor_base.hpp>
Public Member Functions
virtual float calc_similarity (float distance) const
virtual void clear ()
void get_all_row_ids (std::vector< std::string > &ids) const
jubatus::util::lang::shared_ptr< const storage::column_table > get_const_table () const
framework::mixable * get_mixable () const
jubatus::util::lang::shared_ptr< storage::column_table > get_table ()
nearest_neighbor_base (jubatus::util::lang::shared_ptr< storage::column_table > table, const std::string &id)
virtual void neighbor_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const =0
virtual void neighbor_row (const std::string &query_id, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const =0
void pack (framework::packer &packer) const
virtual void set_row (const std::string &id, const common::sfv_t &sfv)=0
virtual void similar_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const
virtual void similar_row (const std::string &query_id, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const
virtual std::string type () const =0
void unpack (msgpack::object o)
virtual ~nearest_neighbor_base ()
Protected Attributes
std::string my_id_
Private Attributes
jubatus::util::lang::shared_ptr< framework::mixable_versioned_table > mixable_table_
Detailed Description
Definition at line 37 of file nearest_neighbor_base.hpp.
Constructor & Destructor Documentation
jubatus::core::nearest_neighbor::nearest_neighbor_base::nearest_neighbor_base (jubatus::util::lang::shared_ptr< storage::column_table > table, const std::string & id) explicit
Definition at line 34 of file nearest_neighbor_base.cpp.
References mixable_table_.
     : my_id_(id),
       mixable_table_(new framework::mixable_versioned_table) {
   mixable_table_->set_model(table);
 }
virtual jubatus::core::nearest_neighbor::nearest_neighbor_base::~nearest_neighbor_base () inline virtual
Definition at line 42 of file nearest_neighbor_base.hpp.
 {}
Member Function Documentation
virtual float jubatus::core::nearest_neighbor::nearest_neighbor_base::calc_similarity (float distance) const inline virtual
Reimplemented in jubatus::core::nearest_neighbor::euclid_lsh.
Definition at line 67 of file nearest_neighbor_base.hpp.
{
     return 1 - distance;
   }
void jubatus::core::nearest_neighbor::nearest_neighbor_base::clear () virtual
Definition at line 52 of file nearest_neighbor_base.cpp.
References mixable_table_.
{
   mixable_table_->get_model()->clear();
 }
void jubatus::core::nearest_neighbor::nearest_neighbor_base::get_all_row_ids (std::vector< std::string > & ids) const
Definition at line 42 of file nearest_neighbor_base.cpp.
References get_const_table().
{
   vector<string> ret;
   shared_ptr<const storage::column_table> table = get_const_table();
   ret.reserve(table->size());
   for (size_t i = 0; i < table->size(); ++i) {
     ret.push_back(table->get_key(i));
   }
   ret.swap(ids);
 }
jubatus::util::lang::shared_ptr<const storage::column_table> jubatus::core::nearest_neighbor::nearest_neighbor_base::get_const_table () const inline
Definition at line 47 of file nearest_neighbor_base.hpp.
References mixable_table_.
Referenced by get_all_row_ids(), and pack().
{
     return mixable_table_->get_model();
   }
framework::mixable * jubatus::core::nearest_neighbor::nearest_neighbor_base::get_mixable () const
Definition at line 84 of file nearest_neighbor_base.cpp.
References mixable_table_.
{
   return mixable_table_.get();
 }
jubatus::util::lang::shared_ptr<storage::column_table> jubatus::core::nearest_neighbor::nearest_neighbor_base::get_table () inline
Definition at line 50 of file nearest_neighbor_base.hpp.
References mixable_table_.
Referenced by unpack().
{
     return mixable_table_->get_model();
   }
virtual void jubatus::core::nearest_neighbor::nearest_neighbor_base::neighbor_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, uint64_t ret_num) const pure virtual
Implemented in jubatus::core::nearest_neighbor::euclid_lsh, and jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base.
virtual void jubatus::core::nearest_neighbor::nearest_neighbor_base::neighbor_row (const std::string & query_id, std::vector< std::pair< std::string, float > > & ids, uint64_t ret_num) const pure virtual
Implemented in jubatus::core::nearest_neighbor::euclid_lsh, and jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base.
void jubatus::core::nearest_neighbor::nearest_neighbor_base::pack (framework::packer & packer) const
Definition at line 76 of file nearest_neighbor_base.cpp.
References get_const_table().
{
   get_const_table()->pack(packer);
 }
virtual void jubatus::core::nearest_neighbor::nearest_neighbor_base::set_row (const std::string & id, const common::sfv_t & sfv) pure virtual
Implemented in jubatus::core::nearest_neighbor::euclid_lsh, and jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base.
virtual void jubatus::core::nearest_neighbor::nearest_neighbor_base::similar_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, uint64_t ret_num) const virtual
virtual void jubatus::core::nearest_neighbor::nearest_neighbor_base::similar_row (const std::string & query_id, std::vector< std::pair< std::string, float > > & ids, uint64_t ret_num) const virtual
virtual std::string jubatus::core::nearest_neighbor::nearest_neighbor_base::type () const pure virtual
Implemented in jubatus::core::nearest_neighbor::minhash, jubatus::core::nearest_neighbor::euclid_lsh, and jubatus::core::nearest_neighbor::lsh.
void jubatus::core::nearest_neighbor::nearest_neighbor_base::unpack (msgpack::object o)
Definition at line 80 of file nearest_neighbor_base.cpp.
References get_table().
{
   get_table()->unpack(o);
 }
Member Data Documentation
jubatus::util::lang::shared_ptr<framework::mixable_versioned_table> jubatus::core::nearest_neighbor::nearest_neighbor_base::mixable_table_ private
Definition at line 90 of file nearest_neighbor_base.hpp.
Referenced by clear(), get_const_table(), get_mixable(), get_table(), and nearest_neighbor_base().
std::string jubatus::core::nearest_neighbor::nearest_neighbor_base::my_id_ protected
Definition at line 86 of file nearest_neighbor_base.hpp.
The documentation for this class was generated from the following files:
jubatus/core/nearest_neighbor/nearest_neighbor_base.hpp
jubatus/core/nearest_neighbor/nearest_neighbor_base.cpp