jubatus_core: jubatus::core::storage::local_storage Class Reference
jubatus::core::storage::local_storage Class Reference
#include <local_storage.hpp>
Public Member Functions
void bulk_update (const common::sfv_t &sfv, float step_width, const std::string &inc_class, const std::string &dec_class)
void clear ()
bool delete_label (const std::string &label)
bool delete_label_nolock (const std::string &label)
void get (const std::string &feature, feature_val1_t &ret) const
void get2 (const std::string &feature, feature_val2_t &ret) const
void get2_nolock (const std::string &feature, feature_val2_t &ret) const
void get3 (const std::string &feature, feature_val3_t &ret) const
void get3_nolock (const std::string &feature, feature_val3_t &ret) const
std::vector< std::string > get_labels () const
util::concurrent::mutex & get_lock () const
void get_nolock (const std::string &feature, feature_val1_t &ret) const
void get_status (std::map< std::string, std::string > &status) const
storage::version get_version () const
void inp (const common::sfv_t &sfv, map_feature_val1_t &ret) const
local_storage ()
MSGPACK_DEFINE (tbl_, class2id_)
void pack (framework::packer &packer) const
void register_label (const std::string &label)
void set (const std::string &feature, const std::string &klass, const val1_t &w)
void set2 (const std::string &feature, const std::string &klass, const val2_t &w)
void set2_nolock (const std::string &feature, const std::string &klass, const val2_t &w)
void set3 (const std::string &feature, const std::string &klass, const val3_t &w)
void set3_nolock (const std::string &feature, const std::string &klass, const val3_t &w)
bool set_label (const std::string &label)
void set_nolock (const std::string &feature, const std::string &klass, const val1_t &w)
std::string type () const
void unpack (msgpack::object o)
void update (const std::string &feature, const std::string &inc_class, const std::string &dec_class, const val1_t &v)
~local_storage ()
Public Member Functions inherited from jubatus::core::storage::storage_base
virtual void get_diff (diff_t &) const
virtual bool set_average_and_clear_diff (const diff_t &)
virtual ~storage_base ()
Public Member Functions inherited from jubatus::core::framework::model
virtual ~model ()
Private Attributes
common::key_manager class2id_
util::concurrent::mutex mutex_
id_features3_t tbl_
Friends
std::ostream & operator<< (std::ostream &os, const local_storage &ls)
Detailed Description
Definition at line 38 of file local_storage.hpp.
Constructor & Destructor Documentation
jubatus::core::storage::local_storage::local_storage ()
Definition at line 34 of file local_storage.cpp.
{
 }
jubatus::core::storage::local_storage::~local_storage ()
Definition at line 37 of file local_storage.cpp.
{
 }
Member Function Documentation
void jubatus::core::storage::local_storage::bulk_update (const common::sfv_t & sfv, float step_width, const std::string & inc_class, const std::string & dec_class) virtual
Reimplemented from jubatus::core::storage::storage_base.
Definition at line 191 of file local_storage.cpp.
References class2id_, jubatus::core::common::key_manager::get_id(), mutex_, and tbl_.
{
   scoped_lock lk(mutex_);
   uint64_t inc_id = class2id_.get_id(inc_class);
   typedef common::sfv_t::const_iterator iter_t;
   if (dec_class != "") {
     uint64_t dec_id = class2id_.get_id(dec_class);
     for (iter_t it = sfv.begin(); it != sfv.end(); ++it) {
       float val = it->second * step_width;
       id_feature_val3_t& feature_row = tbl_[it->first];
       feature_row[inc_id].v1 += val;
       feature_row[dec_id].v1 -= val;
     }
   } else {
     for (iter_t it = sfv.begin(); it != sfv.end(); ++it) {
       float val = it->second * step_width;
       id_feature_val3_t& feature_row = tbl_[it->first];
       feature_row[inc_id].v1 += val;
     }
   }
 }
void jubatus::core::storage::local_storage::clear () virtual
Implements jubatus::core::storage::storage_base.
Definition at line 271 of file local_storage.cpp.
References class2id_, mutex_, jubatus::core::common::key_manager::swap(), and tbl_.
{
   scoped_lock lk(mutex_);
   // Clear and minimize
   id_features3_t().swap(tbl_);
   common::key_manager().swap(class2id_);
 }
bool jubatus::core::storage::local_storage::delete_label (const std::string & label) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 247 of file local_storage.cpp.
References delete_label_nolock(), and mutex_.
{
   scoped_lock lk(mutex_);
   return delete_label_nolock(label);
 }
bool jubatus::core::storage::local_storage::delete_label_nolock (const std::string & label) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 252 of file local_storage.cpp.
References class2id_, jubatus::core::common::key_manager::delete_key(), jubatus::core::common::key_manager::get_id_const(), jubatus::core::common::key_manager::NOTFOUND, and tbl_.
Referenced by delete_label().
{
   uint64_t delete_id = class2id_.get_id_const(label);
   if (delete_id == common::key_manager::NOTFOUND) {
     return false;
   }
   for (id_features3_t::iterator it = tbl_.begin();
        it != tbl_.end();
        ) {
     const bool deleted = it->second.erase(delete_id);
     if (deleted && it->second.empty()) {
       it = tbl_.erase(it);
     } else {
       ++it;
     }
   }
   class2id_.delete_key(label);
   return true;
 }
void jubatus::core::storage::local_storage::get (const std::string & feature, feature_val1_t & ret) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 40 of file local_storage.cpp.
References get_nolock(), and mutex_.
{
   scoped_lock lk(mutex_);
   get_nolock(feature, ret);
 }
void jubatus::core::storage::local_storage::get2 (const std::string & feature, feature_val2_t & ret) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 58 of file local_storage.cpp.
References get2_nolock(), and mutex_.
{
   scoped_lock lk(mutex_);
   get2_nolock(feature, ret);
 }
void jubatus::core::storage::local_storage::get2_nolock (const std::string & feature, feature_val2_t & ret) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 63 of file local_storage.cpp.
References class2id_, jubatus::core::common::key_manager::get_key(), and tbl_.
Referenced by get2().
{
   ret.clear();
   id_features3_t::const_iterator cit = tbl_.find(feature);
   if (cit == tbl_.end()) {
     return;
   }
   const id_feature_val3_t& m = cit->second;
   for (id_feature_val3_t::const_iterator it = m.begin(); it != m.end(); ++it) {
     ret.push_back(make_pair(class2id_.get_key(it->first),
                             val2_t(it->second.v1, it->second.v2)));
   }
 }
void jubatus::core::storage::local_storage::get3 (const std::string & feature, feature_val3_t & ret) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 77 of file local_storage.cpp.
References get3_nolock(), and mutex_.
{
   scoped_lock lk(mutex_);
   get3_nolock(feature, ret);
 }
void jubatus::core::storage::local_storage::get3_nolock (const std::string & feature, feature_val3_t & ret) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 82 of file local_storage.cpp.
References class2id_, jubatus::core::common::key_manager::get_key(), and tbl_.
Referenced by get3().
{
   ret.clear();
   id_features3_t::const_iterator cit = tbl_.find(feature);
   if (cit == tbl_.end()) {
     return;
   }
   const id_feature_val3_t& m = cit->second;
   for (id_feature_val3_t::const_iterator it = m.begin(); it != m.end(); ++it) {
     ret.push_back(make_pair(class2id_.get_key(it->first), it->second));
   }
 }
vector< string > jubatus::core::storage::local_storage::get_labels () const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 237 of file local_storage.cpp.
References class2id_, jubatus::core::common::key_manager::get_all_id2key(), and mutex_.
{
   scoped_lock lk(mutex_);
   return class2id_.get_all_id2key();
 }
util::concurrent::mutex & jubatus::core::storage::local_storage::get_lock () const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 227 of file local_storage.cpp.
References mutex_.
{
   return mutex_;
 }
void jubatus::core::storage::local_storage::get_nolock (const std::string & feature, feature_val1_t & ret) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 45 of file local_storage.cpp.
References class2id_, jubatus::core::common::key_manager::get_key(), and tbl_.
Referenced by get().
{
   ret.clear();
   id_features3_t::const_iterator cit = tbl_.find(feature);
   if (cit == tbl_.end()) {
     return;
   }
   const id_feature_val3_t& m = cit->second;
   for (id_feature_val3_t::const_iterator it = m.begin(); it != m.end(); ++it) {
     ret.push_back(make_pair(class2id_.get_key(it->first), it->second.v1));
   }
 }
void jubatus::core::storage::local_storage::get_status (std::map< std::string, std::string > & status) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 175 of file local_storage.cpp.
References class2id_, mutex_, jubatus::core::common::key_manager::size(), and tbl_.
{
   scoped_lock lk(mutex_);
   status["num_features"] =
     jubatus::util::lang::lexical_cast<std::string>(tbl_.size());
   status["num_classes"] =
     jubatus::util::lang::lexical_cast<std::string>(class2id_.size());
 }
storage::version jubatus::core::storage::local_storage::get_version () const inline virtual
Implements jubatus::core::storage::storage_base.
Definition at line 103 of file local_storage.hpp.
{
     return storage::version();
   }
void jubatus::core::storage::local_storage::inp (const common::sfv_t & sfv, map_feature_val1_t & ret) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 95 of file local_storage.cpp.
References class2id_, jubatus::core::common::key_manager::get_all_id2key(), jubatus::core::common::key_manager::get_id_const(), mutex_, jubatus::core::common::key_manager::NOTFOUND, and tbl_.
           {
   ret.clear();
   scoped_lock lk(mutex_);
   // Use uin64_t map instead of string map as hash function for string is slow
   jubatus::util::data::unordered_map<uint64_t, float> ret_id;
   for (common::sfv_t::const_iterator it = sfv.begin(); it != sfv.end(); ++it) {
     const string& feature = it->first;
     const float val = it->second;
     id_features3_t::const_iterator it2 = tbl_.find(feature);
     if (it2 == tbl_.end()) {
       continue;
     }
     const id_feature_val3_t& m = it2->second;
     for (id_feature_val3_t::const_iterator it3 = m.begin(); it3 != m.end();
         ++it3) {
       ret_id[it3->first] += it3->second.v1 * val;
     }
   }
   std::vector<std::string> labels = class2id_.get_all_id2key();
   for (size_t i = 0; i < labels.size(); ++i) {
     const std::string& label = labels[i];
     uint64_t id = class2id_.get_id_const(label);
     if (id == common::key_manager::NOTFOUND || ret_id.count(id) == 0) {
       ret[label] = 0.0;
     } else {
       ret[label] = ret_id[id];
     }
   }
 }
jubatus::core::storage::local_storage::MSGPACK_DEFINE (tbl_ , class2id_)
void jubatus::core::storage::local_storage::pack (framework::packer & packer) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 278 of file local_storage.cpp.
References mutex_.
{
   scoped_lock lk(mutex_);
   packer.pack(*this);
 }
void jubatus::core::storage::local_storage::register_label (const std::string & label) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 231 of file local_storage.cpp.
References class2id_, jubatus::core::common::key_manager::get_id(), and mutex_.
{
   scoped_lock lk(mutex_);
   // get_id method creates an entry when the label doesn't exist
   class2id_.get_id(label);
 }
void jubatus::core::storage::local_storage::set (const std::string & feature, const std::string & klass, const val1_t & w) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 128 of file local_storage.cpp.
References class2id_, jubatus::core::common::key_manager::get_id(), mutex_, set_nolock(), and tbl_.
                      {
   scoped_lock lk(mutex_);
   set_nolock(feature, klass, w);
   tbl_[feature][class2id_.get_id(klass)].v1 = w;
 }
void jubatus::core::storage::local_storage::set2 (const std::string & feature, const std::string & klass, const val2_t & w) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 143 of file local_storage.cpp.
References mutex_, and set2_nolock().
                      {
   scoped_lock lk(mutex_);
   set2_nolock(feature, klass, w);
 }
void jubatus::core::storage::local_storage::set2_nolock (const std::string & feature, const std::string & klass, const val2_t & w) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 151 of file local_storage.cpp.
References class2id_, jubatus::core::common::key_manager::get_id(), tbl_, jubatus::core::storage::val2_t::v1, jubatus::core::storage::val3_t::v1, jubatus::core::storage::val2_t::v2, and jubatus::core::storage::val3_t::v2.
Referenced by set2().
                      {
   val3_t& val3 = tbl_[feature][class2id_.get_id(klass)];
   val3.v1 = w.v1;
   val3.v2 = w.v2;
 }
void jubatus::core::storage::local_storage::set3 (const std::string & feature, const std::string & klass, const val3_t & w) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 160 of file local_storage.cpp.
References mutex_, and set3_nolock().
                      {
   scoped_lock lk(mutex_);
   set3_nolock(feature, klass, w);
 }
void jubatus::core::storage::local_storage::set3_nolock (const std::string & feature, const std::string & klass, const val3_t & w) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 168 of file local_storage.cpp.
References class2id_, jubatus::core::common::key_manager::get_id(), and tbl_.
Referenced by set3().
                      {
   tbl_[feature][class2id_.get_id(klass)] = w;
 }
bool jubatus::core::storage::local_storage::set_label (const std::string & label) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 242 of file local_storage.cpp.
References class2id_, mutex_, and jubatus::core::common::key_manager::set_key().
{
   scoped_lock lk(mutex_);
   return class2id_.set_key(label);
 }
void jubatus::core::storage::local_storage::set_nolock (const std::string & feature, const std::string & klass, const val1_t & w) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 136 of file local_storage.cpp.
References class2id_, jubatus::core::common::key_manager::get_id(), and tbl_.
Referenced by set().
                      {
   tbl_[feature][class2id_.get_id(klass)].v1 = w;
 }
std::string jubatus::core::storage::local_storage::type () const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 288 of file local_storage.cpp.
{
   return "local_storage";
 }
void jubatus::core::storage::local_storage::unpack (msgpack::object o) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 283 of file local_storage.cpp.
References mutex_.
{
   scoped_lock lk(mutex_);
   o.convert(this);
 }
void jubatus::core::storage::local_storage::update (const std::string & feature, const std::string & inc_class, const std::string & dec_class, const val1_t & v) virtual
Reimplemented from jubatus::core::storage::storage_base.
Definition at line 216 of file local_storage.cpp.
References class2id_, jubatus::core::common::key_manager::get_id(), mutex_, tbl_, and jubatus::core::common::jsonconfig::v().
                      {
   scoped_lock lk(mutex_);
   id_feature_val3_t& feature_row = tbl_[feature];
   feature_row[class2id_.get_id(inc_class)].v1 += v;
   feature_row[class2id_.get_id(dec_class)].v1 -= v;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const local_storage & ls) friend
Definition at line 117 of file local_storage.hpp.
{
     util::concurrent::scoped_lock lk(ls.mutex_);
     os << "{" << std::endl;
     for (id_features3_t::const_iterator it = ls.tbl_.begin();
          it != ls.tbl_.end();
          ++it) {
       os << "  {" << it->first << ": " << "{" << std::endl;
       const id_feature_val3_t val = it->second;
       for (id_feature_val3_t::const_iterator jt = val.begin();
            jt != val.end();
            ++jt) {
         os << "    " << ls.class2id_.get_key(jt->first) << ": " << jt->second;
         {
           id_feature_val3_t::const_iterator jt_next = jt;
           ++jt_next;
           if (jt_next != val.end()) {
             os << ", ";
           }
         }
         os << std::endl;
       }
       os << "  }";
       {
         id_features3_t::const_iterator it_next = it;
         ++it_next;
         if (it_next != ls.tbl_.end()) {
           os << ",";
         }
       }
       os << std::endl;
     }
     os << "}";
     return os;
   }
Member Data Documentation
common::key_manager jubatus::core::storage::local_storage::class2id_ private
Definition at line 114 of file local_storage.hpp.
Referenced by bulk_update(), clear(), delete_label_nolock(), get2_nolock(), get3_nolock(), get_labels(), get_nolock(), get_status(), inp(), register_label(), set(), set2_nolock(), set3_nolock(), set_label(), set_nolock(), and update().
util::concurrent::mutex jubatus::core::storage::local_storage::mutex_ mutable private
Definition at line 112 of file local_storage.hpp.
Referenced by bulk_update(), clear(), delete_label(), get(), get2(), get3(), get_labels(), get_lock(), get_status(), inp(), pack(), register_label(), set(), set2(), set3(), set_label(), unpack(), and update().
id_features3_t jubatus::core::storage::local_storage::tbl_ private
Definition at line 113 of file local_storage.hpp.
Referenced by bulk_update(), clear(), delete_label_nolock(), get2_nolock(), get3_nolock(), get_nolock(), get_status(), inp(), set(), set2_nolock(), set3_nolock(), set_nolock(), and update().
The documentation for this class was generated from the following files:
jubatus/core/storage/local_storage.hpp
jubatus/core/storage/local_storage.cpp