jubatus_core: jubatus::core::storage::typed_column< T > Class Template Reference
jubatus::core::storage::typed_column< T > Class Template Reference
#include <bit_vector_ranking.hpp>
Public Member Functions
void clear ()
void dump (std::ostream &os, uint64_t target) const
bool insert (uint64_t target, const T &value)
bool insert (uint64_t target, const msgpack::object &obj)
const T & operator[] (uint64_t index) const
T & operator[] (uint64_t index)
template<class Buffer >
void pack_array (msgpack::packer< Buffer > &packer) const
void pack_with_index (const uint64_t index, framework::packer &pk) const
void push_back (const T &value)
void push_back (const msgpack::object &obj)
bool remove (uint64_t target)
uint64_t size () const
typed_column (const column_type &type)
void unpack_array (msgpack::object o)
bool update (uint64_t index, const T &value)
bool update (uint64_t target, const msgpack::object &obj)
Public Member Functions inherited from jubatus::core::storage::detail::abstract_column_base
abstract_column_base (const column_type &type)
JUBATUS_GEN_FUNCTIONS_ (uint8_t)
JUBATUS_GEN_FUNCTIONS_ (uint16_t)
JUBATUS_GEN_FUNCTIONS_ (uint32_t)
JUBATUS_GEN_FUNCTIONS_ (uint64_t)
JUBATUS_GEN_FUNCTIONS_ (int8_t)
JUBATUS_GEN_FUNCTIONS_ (int16_t)
JUBATUS_GEN_FUNCTIONS_ (int32_t)
JUBATUS_GEN_FUNCTIONS_ (int64_t)
JUBATUS_GEN_FUNCTIONS_ (float)
JUBATUS_GEN_FUNCTIONS_ (double)
JUBATUS_GEN_FUNCTIONS_ (std::string)
JUBATUS_GEN_FUNCTIONS_ (bit_vector)
JUBATUS_GEN_FUNCTIONS_ (msgpack::object)
column_type type () const
virtual ~abstract_column_base ()
Private Attributes
std::vector< T > array_
Friends
std::ostream & operator<< (std::ostream &os, const typed_column< T > &it)
Detailed Description
template<typename T>
class jubatus::core::storage::typed_column< T >
Definition at line 31 of file bit_vector_ranking.hpp.
Constructor & Destructor Documentation
template<typename T> jubatus::core::storage::typed_column< T >::typed_column (const column_type & type) inline explicit
Definition at line 105 of file abstract_column.hpp.
       : detail::abstract_column_base(type) {
   }
Member Function Documentation
template<typename T> void jubatus::core::storage::typed_column< T >::clear () inline virtual
Implements jubatus::core::storage::detail::abstract_column_base.
Definition at line 151 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_.
                {
     array_.clear();
   }
template<typename T> void jubatus::core::storage::typed_column< T >::dump (std::ostream & os, uint64_t target) const inline virtual
Implements jubatus::core::storage::detail::abstract_column_base.
Definition at line 197 of file abstract_column.hpp.
{
     os << "[" << target << "] " << (*this)[target] << std::endl;
   }
template<typename T> bool jubatus::core::storage::typed_column< T >::insert (uint64_t target, const T & value) inline
Definition at line 120 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_, and jubatus::core::storage::typed_column< T >::size().
Referenced by jubatus::core::storage::typed_column< T >::insert(), and jubatus::core::storage::typed_column< bit_vector >::insert().
{
     if (size() < target) {
       return false;
     }
     array_.insert(array_.begin() + target, value);
     return true;
   }
template<typename T> bool jubatus::core::storage::typed_column< T >::insert (uint64_t target, const msgpack::object & obj) inline
Definition at line 127 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::insert().
{
     return typed_column::insert(target, obj.as<T>());
   }
template<typename T> const T& jubatus::core::storage::typed_column< T >::operator[] (uint64_t index) const inline
Definition at line 159 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_, and jubatus::core::storage::typed_column< T >::size().
{
     if (size() <= index) {
       throw length_unmatch_exception(
         "invalid index [" +
         jubatus::util::lang::lexical_cast<std::string>(index) +
         "] for [" +
         jubatus::util::lang::lexical_cast<std::string>(array_.size()));
     }
     return array_[index];
   }
template<typename T> T& jubatus::core::storage::typed_column< T >::operator[] (uint64_t index) inline
Definition at line 170 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_, and jubatus::core::storage::typed_column< T >::size().
{
     if (size() <= index) {
       throw length_unmatch_exception(
         "invalid index [" +
         jubatus::util::lang::lexical_cast<std::string>(index) +
         "] for [" +
         jubatus::util::lang::lexical_cast<std::string>(array_.size()));
     }
     return array_[index];
   }
template<typename T> template<class Buffer > void jubatus::core::storage::typed_column< T >::pack_array (msgpack::packer< Buffer > & packer) const inline
Definition at line 202 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_.
{
     packer.pack(array_);
   }
template<typename T> void jubatus::core::storage::typed_column< T >::pack_with_index (const uint64_t index, framework::packer & pk) const inline virtual
Reimplemented from jubatus::core::storage::detail::abstract_column_base.
Definition at line 181 of file abstract_column.hpp.
{
     pk.pack((*this)[index]);
   }
template<typename T> void jubatus::core::storage::typed_column< T >::push_back (const T & value) inline
Definition at line 113 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_.
Referenced by jubatus::core::storage::typed_column< T >::push_back(), jubatus::core::storage::typed_column< bit_vector >::push_back(), and jubatus::core::anomaly::light_lof::update_entries().
{
     array_.push_back(value);
   }
template<typename T> void jubatus::core::storage::typed_column< T >::push_back (const msgpack::object & obj) inline
Definition at line 116 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::push_back().
{
     typed_column::push_back(obj.as<T>());
   }
template<typename T> bool jubatus::core::storage::typed_column< T >::remove (uint64_t target) inline virtual
Implements jubatus::core::storage::detail::abstract_column_base.
Definition at line 142 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_, jubatus::core::storage::typed_column< T >::size(), jubatus::core::clustering::swap(), and jubatus::core::storage::swap().
{
     if (size() <= target) {
       return false;
     }
     using std::swap;
     swap(array_[target], array_.back());
     array_.pop_back();
     return true;
   }
template<typename T> uint64_t jubatus::core::storage::typed_column< T >::size () const inline
Definition at line 155 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_.
Referenced by jubatus::core::storage::typed_column< bit_vector >::get_data_at_(), jubatus::core::storage::typed_column< T >::insert(), jubatus::core::storage::typed_column< bit_vector >::insert(), jubatus::core::storage::typed_column< T >::operator[](), jubatus::core::storage::typed_column< bit_vector >::push_back(), jubatus::core::storage::typed_column< T >::remove(), jubatus::core::storage::typed_column< bit_vector >::remove(), jubatus::core::storage::typed_column< T >::update(), and jubatus::core::storage::typed_column< bit_vector >::update().
{
     return array_.size();
   }
template<typename T> void jubatus::core::storage::typed_column< T >::unpack_array (msgpack::object o) inline
Definition at line 205 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_.
{
     o.convert(&array_);
   }
template<typename T> bool jubatus::core::storage::typed_column< T >::update (uint64_t index, const T & value) inline
Definition at line 131 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_, and jubatus::core::storage::typed_column< T >::size().
Referenced by jubatus::core::storage::typed_column< T >::update(), and jubatus::core::storage::typed_column< bit_vector >::update().
{
     if (size() <= index) {
       return false;
     }
     array_[index] = value;
     return true;
   }
template<typename T> bool jubatus::core::storage::typed_column< T >::update (uint64_t target, const msgpack::object & obj) inline
Definition at line 138 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::update().
{
     return typed_column::update(target, obj.as<T>());
   }
Friends And Related Function Documentation
template<typename T> std::ostream& operator<< (std::ostream & os, const typed_column< T > & it) friend
Definition at line 186 of file abstract_column.hpp.
{
     os << "[column (" << it.type().type_as_string() << ")"
         << " size:" << it.size() << " {" << std::endl;
     for (size_t i = 0; i < it.size(); ++i) {
       it.dump(os, i);
     }
     os << "} ]" << std::endl;
     return os;
   }
Member Data Documentation
template<typename T> std::vector<T> jubatus::core::storage::typed_column< T >::array_ private
Definition at line 210 of file abstract_column.hpp.
Referenced by jubatus::core::storage::typed_column< T >::clear(), jubatus::core::storage::typed_column< bit_vector >::clear(), jubatus::core::storage::typed_column< T >::insert(), jubatus::core::storage::typed_column< bit_vector >::insert(), jubatus::core::storage::typed_column< T >::operator[](), jubatus::core::storage::typed_column< T >::pack_array(), jubatus::core::storage::typed_column< bit_vector >::pack_array(), jubatus::core::storage::typed_column< T >::push_back(), jubatus::core::storage::typed_column< bit_vector >::push_back(), jubatus::core::storage::typed_column< T >::remove(), jubatus::core::storage::typed_column< bit_vector >::remove(), jubatus::core::storage::typed_column< T >::size(), jubatus::core::storage::typed_column< bit_vector >::size(), jubatus::core::storage::typed_column< T >::unpack_array(), jubatus::core::storage::typed_column< bit_vector >::unpack_array(), and jubatus::core::storage::typed_column< T >::update().
The documentation for this class was generated from the following files:
jubatus/core/nearest_neighbor/bit_vector_ranking.hpp
jubatus/core/storage/abstract_column.hpp