jubatus_core: jubatus::core::burst::result_storage::impl_ Class Reference
jubatus::core::burst::result_storage::impl_ Class Reference
Public Member Functions
diff_t get_diff () const
result_t get_latest_result () const
result_t get_result_at (double pos) const
impl_ (int stored_results_max)
MSGPACK_DEFINE (results_, results_max_, oldest_start_pos_not_mixed_)
void put_diff (const diff_t &diff)
void store (const result_t &result, bool merge=false)
Private Types
typedef std::deque< result_t > results_t
Private Attributes
double oldest_start_pos_not_mixed_
results_t results_
size_t results_max_
Detailed Description
Definition at line 29 of file result_storage.cpp.
Member Typedef Documentation
typedef std::deque<result_t> jubatus::core::burst::result_storage::impl_::results_t private
Definition at line 30 of file result_storage.cpp.
Constructor & Destructor Documentation
jubatus::core::burst::result_storage::impl_::impl_ (int stored_results_max) inline explicit
Definition at line 36 of file result_storage.cpp.
       : results_max_(stored_results_max), oldest_start_pos_not_mixed_(DBL_MAX) {
   }
Member Function Documentation
diff_t jubatus::core::burst::result_storage::impl_::get_diff () const inline
Definition at line 93 of file result_storage.cpp.
{
     diff_t diff;
     typedef results_t::const_iterator iterator_t;
     for (iterator_t iter = results_.begin(), end = results_.end();
         iter != end; ++iter) {
       if (iter->has_start_pos_older_than(oldest_start_pos_not_mixed_)) {
         break;
       }
       diff.push_back(*iter);
     }
     return diff;
   }
result_t jubatus::core::burst::result_storage::impl_::get_latest_result () const inline
Definition at line 76 of file result_storage.cpp.
{
     if (results_.empty()) {
       return result_t();
     }
     return results_.front();
   }
result_t jubatus::core::burst::result_storage::impl_::get_result_at (double pos) const inline
Definition at line 82 of file result_storage.cpp.
{
     typedef results_t::const_iterator iterator_t;
     for (iterator_t iter = results_.begin(), end = results_.end();
         iter != end; ++iter) {
       if (iter->contains(pos)) {
         return *iter;
       }
     }
     return result_t();
   }
jubatus::core::burst::result_storage::impl_::MSGPACK_DEFINE (results_ , results_max_ , oldest_start_pos_not_mixed_)
void jubatus::core::burst::result_storage::impl_::put_diff (const diff_t & diff) inline
Definition at line 108 of file result_storage.cpp.
References store().
{
     // merge diff
     for (diff_t::const_iterator iter = diff.begin();
          iter != diff.end(); ++iter) {
       store(*iter, true);
     }
     // clear diff
     oldest_start_pos_not_mixed_ = DBL_MAX;
   }
void jubatus::core::burst::result_storage::impl_::store (const result_t & result, bool merge = false) inline
Definition at line 40 of file result_storage.cpp.
References jubatus::core::burst::burst_result::get_batch_size(), jubatus::core::burst::burst_result::get_start_pos(), JUBATUS_ASSERT, JUBATUS_ASSERT_EQ, and results_max_.
Referenced by put_diff().
{
     double result_start_pos = result.get_start_pos();
     if (results_.empty()) {
       results_.push_front(result);
     } else {
       typedef results_t::iterator iterator_t;
       for (iterator_t iter = results_.begin(), end = results_.end();
           iter != end; ++iter) {
         if (iter->has_start_pos_older_than(result_start_pos)) {
           results_.insert(iter, result);
           break;
         } else if (iter->has_same_start_pos_to(result_start_pos)) {
           JUBATUS_ASSERT_EQ(
               iter->get_batch_size(), result.get_batch_size(), "");
           JUBATUS_ASSERT(iter->has_same_batch_interval(result));
           if (merge) {
             bool mixed = iter->mix(result);
             JUBATUS_ASSERT(mixed);
           } else {
             *iter = result;  // update with new result
           }
           break;
         }
       }
     }
     if (result_start_pos < oldest_start_pos_not_mixed_) {
       oldest_start_pos_not_mixed_ = result_start_pos;
     }
     while (results_.size() > results_max_) {
       results_.pop_back();
     }
   }
Member Data Documentation
double jubatus::core::burst::result_storage::impl_::oldest_start_pos_not_mixed_ private
Definition at line 33 of file result_storage.cpp.
results_t jubatus::core::burst::result_storage::impl_::results_ private
Definition at line 31 of file result_storage.cpp.
size_t jubatus::core::burst::result_storage::impl_::results_max_ private
Definition at line 32 of file result_storage.cpp.
Referenced by store().
The documentation for this class was generated from the following file:
jubatus/core/burst/result_storage.cpp