jubatus_core: jubatus::core::common::byte_buffer Class Reference
jubatus::core::common::byte_buffer Class Reference
#include <byte_buffer.hpp>
Public Member Functions
void assign (const void *ptr, size_t size)
byte_buffer ()
byte_buffer (size_t size)
byte_buffer (const void *ptr, size_t size)
const char * ptr () const
char * ptr ()
size_t size () const
void swap (byte_buffer &other)
Private Attributes
jubatus::util::lang::shared_ptr< std::vector< char > > buf_
Detailed Description
Definition at line 30 of file byte_buffer.hpp.
Constructor & Destructor Documentation
jubatus::core::common::byte_buffer::byte_buffer () inline
Definition at line 32 of file byte_buffer.hpp.
Referenced by assign().
                 {
   }
jubatus::core::common::byte_buffer::byte_buffer (size_t size) inline explicit
Definition at line 35 of file byte_buffer.hpp.
       : buf_(new std::vector<char>(size)) {
   }
jubatus::core::common::byte_buffer::byte_buffer (const void * ptr, size_t size) inline
Definition at line 39 of file byte_buffer.hpp.
References buf_, and ptr().
{
     const char* const first = static_cast<const char*>(ptr);
     buf_.reset(new std::vector<char>(first, first+size));
   }
Member Function Documentation
void jubatus::core::common::byte_buffer::assign (const void * ptr, size_t size) inline
Definition at line 60 of file byte_buffer.hpp.
References buf_, byte_buffer(), and ptr().
Referenced by msgpack::operator>>().
{
     if (buf_.unique()) {
       const char* const first = static_cast<const char*>(ptr);
       buf_->assign(first, first + size);
     } else {
       byte_buffer(ptr, size).swap(*this);
     }
   }
const char* jubatus::core::common::byte_buffer::ptr () const inline
Definition at line 69 of file byte_buffer.hpp.
References buf_.
Referenced by assign(), byte_buffer(), msgpack::operator<<(), and ptr().
{
     if (buf_ && !buf_->empty()) {
       return &(*buf_)[0];
       // `buf_->data()' is much better (C++11 feature)
     } else {
       return NULL;
     }
   }
char* jubatus::core::common::byte_buffer::ptr () inline
Definition at line 78 of file byte_buffer.hpp.
References ptr().
               {
     return const_cast<char*>(
       const_cast<const byte_buffer*>(this)->ptr());
   }
size_t jubatus::core::common::byte_buffer::size () const inline
Definition at line 83 of file byte_buffer.hpp.
References buf_.
Referenced by msgpack::operator<<().
                       {
     if (buf_) {
       return buf_->size();
     } else {
       return 0;
     }
   }
void jubatus::core::common::byte_buffer::swap (byte_buffer & other) inline
Definition at line 49 of file byte_buffer.hpp.
References buf_.
Referenced by jubatus::core::common::swap().
{
     this->buf_.swap(other.buf_);
     // jubatus::util::lang::shared_ptr provides no non-member swap;
     // `swap(this->buf_, other.buf_);' may be inefficient.
     // when jubatus::util::lang::shared_ptr provide non-member swap,
     // this function should be rewritten with it
     // because if new data members are added to
     // jubatus::util::lang::shared_ptr, member function swap
     // (currently derived from base) may cause object slicing.
   }
Member Data Documentation
jubatus::util::lang::shared_ptr<std::vector<char> > jubatus::core::common::byte_buffer::buf_ private
Definition at line 92 of file byte_buffer.hpp.
Referenced by assign(), byte_buffer(), ptr(), size(), and swap().
The documentation for this class was generated from the following file:
jubatus/core/common/byte_buffer.hpp