jubatus_core: jubatus::core::burst::intersection_helper Class Reference
jubatus::core::burst::intersection_helper Class Reference
#include <window_intersection.hpp>
Public Member Functions
int adjust_index (int index) const
int get_index_ (double pos) const
int get_index_for_boundary (double boundary_pos) const
template<class Window >
std::pair< int, int > get_intersection (const Window &w) const
bool has_batch_interval_equals_to (double interval1) const
intersection_helper (double start_pos=0, double batch_interval=1, int batch_size=0)
template<class Window >
intersection_helper (const Window &w)
bool position_near (double pos0, double pos1) const
Static Public Member Functions
static int no_index ()
Private Attributes
double batch_interval_
int batch_size_
double start_pos_
Detailed Description
Definition at line 40 of file window_intersection.hpp.
Constructor & Destructor Documentation
jubatus::core::burst::intersection_helper::intersection_helper (double start_pos = 0, double batch_interval = 1, int batch_size = 0) inline explicit
Definition at line 42 of file window_intersection.hpp.
       : start_pos_(start_pos),
         batch_interval_(batch_interval),
         batch_size_(batch_size) {
   }
template<class Window > jubatus::core::burst::intersection_helper::intersection_helper (const Window & w) inline explicit
Definition at line 51 of file window_intersection.hpp.
       : start_pos_(w.get_start_pos()),
         batch_interval_(w.get_batch_interval()),
         batch_size_(w.get_batch_size()) {
   }
Member Function Documentation
int jubatus::core::burst::intersection_helper::adjust_index (int index) const inline
Definition at line 97 of file window_intersection.hpp.
References batch_size_.
Referenced by get_intersection().
{
     if (index < 0) {
       return 0;
     } else if (index > batch_size_) {
       return batch_size_;
     } else {
       return index;
     }
   }
int jubatus::core::burst::intersection_helper::get_index_ (double pos) const inline
Definition at line 107 of file window_intersection.hpp.
References batch_interval_, and start_pos_.
Referenced by get_index_for_boundary().
{
     return static_cast<int>(std::floor((pos - start_pos_) / batch_interval_));
   }
int jubatus::core::burst::intersection_helper::get_index_for_boundary (double boundary_pos) const inline
Definition at line 73 of file window_intersection.hpp.
References batch_interval_, get_index_(), no_index(), position_near(), and start_pos_.
Referenced by get_intersection().
{
     int candidate = get_index_(boundary_pos + batch_interval_/2);
     double candidate_pos = start_pos_ + candidate * batch_interval_;
     if (!position_near(boundary_pos, candidate_pos)) {
       return no_index();
     }
     return candidate;
   }
template<class Window > std::pair<int, int> jubatus::core::burst::intersection_helper::get_intersection (const Window & w) const inline
Definition at line 58 of file window_intersection.hpp.
References adjust_index(), get_index_for_boundary(), has_batch_interval_equals_to(), and no_index().
Referenced by jubatus::core::burst::get_intersection().
{
     int begin = get_index_for_boundary(w.get_start_pos());
     int end = get_index_for_boundary(w.get_end_pos());
     if (begin == no_index() ||
         end == no_index() ||
         !has_batch_interval_equals_to(w.get_batch_interval())) {
       // nonsense data is given (should throw an exception?)
       return std::make_pair(no_index(), no_index());
     }
     return std::make_pair(adjust_index(begin),
                           adjust_index(end));
   }
bool jubatus::core::burst::intersection_helper::has_batch_interval_equals_to (double interval1) const inline
Definition at line 91 of file window_intersection.hpp.
References batch_interval_, batch_size_, and position_near().
Referenced by get_intersection(), and jubatus::core::burst::burst_result::has_same_batch_interval().
{
     // comparing end_pos
     size_t n = (std::max)(batch_size_, 1);
     return position_near(n * interval1, n * batch_interval_);
   }
static int jubatus::core::burst::intersection_helper::no_index () inline static
Definition at line 83 of file window_intersection.hpp.
Referenced by get_index_for_boundary(), and get_intersection().
                         {  // constexpr is needed
     return std::numeric_limits<int>::min();
   }
bool jubatus::core::burst::intersection_helper::position_near (double pos0, double pos1) const inline
Definition at line 87 of file window_intersection.hpp.
References batch_interval_, and jubatus::core::burst::window_position_near().
Referenced by get_index_for_boundary(), and has_batch_interval_equals_to().
{
     return window_position_near(pos0, pos1, batch_interval_);
   }
Member Data Documentation
double jubatus::core::burst::intersection_helper::batch_interval_ private
Definition at line 113 of file window_intersection.hpp.
Referenced by get_index_(), get_index_for_boundary(), has_batch_interval_equals_to(), and position_near().
int jubatus::core::burst::intersection_helper::batch_size_ private
Definition at line 114 of file window_intersection.hpp.
Referenced by adjust_index(), and has_batch_interval_equals_to().
double jubatus::core::burst::intersection_helper::start_pos_ private
Definition at line 112 of file window_intersection.hpp.
Referenced by get_index_(), and get_index_for_boundary().
The documentation for this class was generated from the following file:
jubatus/core/burst/window_intersection.hpp