jubatus_core: jubatus::core::clustering::clustering Class Reference
jubatus::core::clustering::clustering Class Reference
#include <clustering.hpp>
Public Member Functions
void clear ()
clustering (const std::string &name, const std::string &method, const clustering_config &cfg)
void do_clustering ()
std::vector< wplist > get_core_members () const
wplist get_coreset () const
std::vector< common::sfv_t > get_k_center () const
framework::mixable * get_mixable () const
common::sfv_t get_nearest_center (const common::sfv_t &point) const
wplist get_nearest_members (const common::sfv_t &point) const
size_t get_revision () const
jubatus::util::lang::shared_ptr< storage > get_storage ()
void pack (framework::packer &pk) const
bool push (const std::vector< weighted_point > &points)
void set_clustering_method (jubatus::util::lang::shared_ptr< clustering_method > clustering_method)
void set_storage (jubatus::util::lang::shared_ptr< storage > storage)
std::string type () const
void unpack (msgpack::object o)
virtual ~clustering ()
Private Member Functions
wplist get_coreset_mine () const
void init ()
void update_clusters (const wplist &points, bool batch)
Private Attributes
jubatus::util::lang::shared_ptr< clustering_method > clustering_method_
clustering_config config_
std::string method_
std::string name_
jubatus::util::lang::shared_ptr< mixable_storage > storage_
Detailed Description
Definition at line 47 of file clustering.hpp.
Constructor & Destructor Documentation
jubatus::core::clustering::clustering::clustering (const std::string & name, const std::string & method, const clustering_config & cfg)
Definition at line 37 of file clustering.cpp.
References jubatus::core::clustering::clustering_config::bicriteria_base_size, jubatus::core::clustering::clustering_config::bucket_length, jubatus::core::clustering::clustering_config::bucket_size, jubatus::core::clustering::clustering_config::compressed_bucket_size, jubatus::core::clustering::clustering_config::compressor_method, jubatus::core::clustering::clustering_config::forgetting_factor, jubatus::core::clustering::clustering_config::forgetting_threshold, init(), JUBATUS_EXCEPTION, and jubatus::core::clustering::clustering_config::k.
     : config_(cfg),
       name_(name),
       method_(method),
       storage_() {
   // TODO(@rimms): move to factory
   if (method =="gmm" &&
       cfg.compressor_method == "compressive_kmeans") {
     throw JUBATUS_EXCEPTION(common::invalid_parameter(
         "method = gmm, compressor_method != compressive_kmeans"));
   }
   // TODO(@rimms): move to factory
   if (method =="kmeans" &&
       cfg.compressor_method == "compressive_gmm") {
     throw JUBATUS_EXCEPTION(common::invalid_parameter(
         "method = kmeans, compressor_method != compressive_gmm"));
   }
   if (!(1 <= cfg.k)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("1 <= k"));
   }
   if (!(2 <= cfg.bucket_size)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("2 <= bucket_size"));
   }
   if (!(2 <= cfg.bucket_length)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("2 <= bucket_length"));
   }
   if (!(1 <= cfg.bicriteria_base_size &&
       cfg.bicriteria_base_size < cfg.compressed_bucket_size)) {
     throw JUBATUS_EXCEPTION(common::invalid_parameter(
         "1 <= bicriteria_base_size < compressed_bucket_size"));
   }
   if (!(cfg.compressed_bucket_size < cfg.bucket_size)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("compressed_bucket_size < bucket_size"));
   }
   if (!(0.0 <= cfg.forgetting_factor)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("0.0 <= forgetting_factor"));
   }
   if (!(0.0 <= cfg.forgetting_threshold &&
       cfg.forgetting_threshold <= 1.0)) {
     throw JUBATUS_EXCEPTION(common::invalid_parameter(
         "0.0 <= forgetting_threshold <= 1.0"));
   }
   init();
 }
jubatus::core::clustering::clustering::~clustering () virtual
Definition at line 100 of file clustering.cpp.
{
 }
Member Function Documentation
void jubatus::core::clustering::clustering::clear ()
Definition at line 189 of file clustering.cpp.
References storage_.
{
   storage_->get_model()->clear();
 }
void jubatus::core::clustering::clustering::do_clustering ()
Definition at line 193 of file clustering.cpp.
References clustering_method_, and storage_.
{
   clustering_method_->batch_update(storage_->get_model()->get_all());
 }
std::vector< wplist > jubatus::core::clustering::clustering::get_core_members () const
Definition at line 165 of file clustering.cpp.
References clustering_method_, and get_coreset().
{
   return clustering_method_->get_clusters(get_coreset());
 }
wplist jubatus::core::clustering::clustering::get_coreset () const
Definition at line 145 of file clustering.cpp.
References storage_.
Referenced by get_core_members(), and get_nearest_members().
{
   return storage_->get_model()->get_all();
 }
wplist jubatus::core::clustering::clustering::get_coreset_mine () const private
std::vector< common::sfv_t > jubatus::core::clustering::clustering::get_k_center () const
Definition at line 149 of file clustering.cpp.
References clustering_method_.
{
   return clustering_method_->get_k_center();
 }
framework::mixable * jubatus::core::clustering::clustering::get_mixable () const
Definition at line 173 of file clustering.cpp.
References storage_.
{
   return storage_.get();
 }
common::sfv_t jubatus::core::clustering::clustering::get_nearest_center (const common::sfv_t & point) const
Definition at line 153 of file clustering.cpp.
References clustering_method_.
{
   return clustering_method_->get_nearest_center(point);
 }
wplist jubatus::core::clustering::clustering::get_nearest_members (const common::sfv_t & point) const
Definition at line 157 of file clustering.cpp.
References clustering_method_, and get_coreset().
{
   int64_t clustering_id = clustering_method_->get_nearest_center_index(point);
   if (clustering_id == -1) {
     return wplist();
   }
   return clustering_method_->get_cluster(clustering_id, get_coreset());
 }
size_t jubatus::core::clustering::clustering::get_revision () const
Definition at line 169 of file clustering.cpp.
References storage_.
{
   return storage_->get_model()->get_revision();
 }
jubatus::util::lang::shared_ptr< storage > jubatus::core::clustering::clustering::get_storage ()
Definition at line 119 of file clustering.cpp.
References storage_.
{
   return storage_->get_model();
 }
void jubatus::core::clustering::clustering::init () private
Definition at line 103 of file clustering.cpp.
References config_, jubatus::core::clustering::storage_factory::create(), jubatus::core::clustering::clustering_method_factory::create(), method_, name_, set_clustering_method(), and set_storage().
Referenced by clustering().
                       {
   set_storage(storage_factory::create(name_, config_));
   set_clustering_method(
       clustering_method_factory::create(method_, config_));
 }
void jubatus::core::clustering::clustering::pack (framework::packer & pk) const
Definition at line 181 of file clustering.cpp.
References storage_.
{
   storage_->get_model()->pack(pk);
 }
bool jubatus::core::clustering::clustering::push (const std::vector< weighted_point > & points)
Definition at line 136 of file clustering.cpp.
References storage_.
{
   jubatus::util::lang::shared_ptr<storage> sto = storage_->get_model();
   for (std::vector<weighted_point>::const_iterator it = points.begin();
        it != points.end(); ++it) {
     sto->add(*it);
   }
   return true;
 }
void jubatus::core::clustering::clustering::set_clustering_method (jubatus::util::lang::shared_ptr< clustering_method > clustering_method)
Definition at line 131 of file clustering.cpp.
References clustering_method_.
Referenced by init().
{
   clustering_method_ = clustering_method;
 }
void jubatus::core::clustering::clustering::set_storage (jubatus::util::lang::shared_ptr< storage > storage)
Definition at line 109 of file clustering.cpp.
References jubatus::core::clustering::REVISION_CHANGE, storage_, jubatus::core::clustering::UPDATE, and update_clusters().
Referenced by init().
{
   storage->add_event_listener(REVISION_CHANGE,
       jubatus::util::lang::bind(&clustering::update_clusters,
           this, jubatus::util::lang::_1, true));
   storage->add_event_listener(UPDATE,
       jubatus::util::lang::bind(&clustering::update_clusters,
           this, jubatus::util::lang::_1, false));
   storage_.reset(new mixable_storage(storage));
 }
std::string jubatus::core::clustering::clustering::type () const
Definition at line 177 of file clustering.cpp.
{
   return "clustering";
 }
void jubatus::core::clustering::clustering::unpack (msgpack::object o)
Definition at line 185 of file clustering.cpp.
References storage_.
{
   storage_->get_model()->unpack(o);
 }
void jubatus::core::clustering::clustering::update_clusters (const wplist & points, bool batch) private
Definition at line 123 of file clustering.cpp.
References clustering_method_.
Referenced by set_storage().
{
   if (batch) {
     clustering_method_->batch_update(points);
   } else {
     clustering_method_->online_update(points);
   }
 }
Member Data Documentation
jubatus::util::lang::shared_ptr<clustering_method> jubatus::core::clustering::clustering::clustering_method_ private
Definition at line 89 of file clustering.hpp.
Referenced by do_clustering(), get_core_members(), get_k_center(), get_nearest_center(), get_nearest_members(), set_clustering_method(), and update_clusters().
clustering_config jubatus::core::clustering::clustering::config_ private
Definition at line 85 of file clustering.hpp.
Referenced by init().
std::string jubatus::core::clustering::clustering::method_ private
Definition at line 87 of file clustering.hpp.
Referenced by init().
std::string jubatus::core::clustering::clustering::name_ private
Definition at line 86 of file clustering.hpp.
Referenced by init().
jubatus::util::lang::shared_ptr<mixable_storage> jubatus::core::clustering::clustering::storage_ private
Definition at line 90 of file clustering.hpp.
Referenced by clear(), do_clustering(), get_coreset(), get_mixable(), get_revision(), get_storage(), pack(), push(), set_storage(), and unpack().
The documentation for this class was generated from the following files:
jubatus/core/clustering/clustering.hpp
jubatus/core/clustering/clustering.cpp