jubatus_core: jubatus::core::recommender::euclid_lsh Class Reference
jubatus::core::recommender::euclid_lsh Class Reference
#include <euclid_lsh.hpp>
Classes
struct config
Public Member Functions
virtual void clear ()
virtual void clear_row (const std::string &id)
euclid_lsh ()
euclid_lsh (const config &config)
virtual void get_all_row_ids (std::vector< std::string > &ids) const
framework::mixable * get_mixable () const
virtual void neighbor_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
virtual void neighbor_row (const std::string &id, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
void pack (framework::packer &packer) const
virtual void similar_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
virtual void similar_row (const std::string &id, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
virtual std::string type () const
void unpack (msgpack::object o)
virtual void update_row (const std::string &id, const sfv_diff_t &diff)
~euclid_lsh ()
Public Member Functions inherited from jubatus::core::recommender::recommender_base
void complete_row (const std::string &id, common::sfv_t &ret) const
void complete_row (const common::sfv_t &query, common::sfv_t &ret) const
void decode_row (const std::string &id, common::sfv_t &ret) const
virtual const core::storage::recommender_storage_base * get_const_storage () const
virtual jubatus::util::lang::shared_ptr< const storage::column_table > get_const_table () const
virtual jubatus::util::lang::shared_ptr< storage::column_table > get_table ()
virtual jubatus::util::lang::shared_ptr< unlearner::unlearner_base > get_unlearner ()
recommender_base ()
virtual ~recommender_base ()
Public Member Functions inherited from jubatus::core::framework::model
virtual ~model ()
Static Public Attributes
static const float DEFAULT_BIN_WIDTH = 100
static const uint64_t DEFAULT_HASH_NUM = 64
static const uint32_t DEFAULT_NUM_PROBE = 64
static const bool DEFAULT_RETAIN_PROJECTION = false
static const uint32_t DEFAULT_SEED = 1091
static const uint64_t DEFAULT_TABLE_NUM = 4
Private Member Functions
std::vector< float > calculate_lsh (const common::sfv_t &query) const
std::vector< float > get_projection (uint32_t seed) const
void initialize_model ()
Private Attributes
float bin_width_
jubatus::util::concurrent::mutex cache_lock_
jubatus::util::lang::shared_ptr< storage::mixable_lsh_index_storage > mixable_storage_
uint32_t num_probe_
jubatus::util::data::unordered_map< uint32_t, std::vector< float > > projection_cache_
bool retain_projection_
Additional Inherited Members
Static Public Member Functions inherited from jubatus::core::recommender::recommender_base
static float calc_l2norm (const common::sfv_t &query)
static float calc_similality (common::sfv_t &q1, common::sfv_t &q2)
Protected Attributes inherited from jubatus::core::recommender::recommender_base
core::storage::sparse_matrix_storage orig_
Static Protected Attributes inherited from jubatus::core::recommender::recommender_base
static const uint64_t complete_row_similar_num_ = 128
Detailed Description
Definition at line 47 of file euclid_lsh.hpp.
Constructor & Destructor Documentation
jubatus::core::recommender::euclid_lsh::euclid_lsh ()
Definition at line 93 of file euclid_lsh.cpp.
     : mixable_storage_(new storage::mixable_lsh_index_storage(
         model_ptr(new lsh_index_storage(DEFAULT_HASH_NUM,
                                         DEFAULT_TABLE_NUM,
                                         DEFAULT_SEED)))),
       bin_width_(DEFAULT_BIN_WIDTH),
       num_probe_(DEFAULT_NUM_PROBE),
       retain_projection_(DEFAULT_RETAIN_PROJECTION) {
 }
jubatus::core::recommender::euclid_lsh::euclid_lsh (const config & config) explicit
Definition at line 103 of file euclid_lsh.cpp.
References jubatus::core::recommender::euclid_lsh::config::bin_width, jubatus::core::recommender::euclid_lsh::config::hash_num, JUBATUS_EXCEPTION, mixable_storage_, jubatus::core::recommender::euclid_lsh::config::probe_num, jubatus::core::recommender::euclid_lsh::config::seed, and jubatus::core::recommender::euclid_lsh::config::table_num.
     : mixable_storage_(),
       bin_width_(config.bin_width),
       num_probe_(config.probe_num),
       retain_projection_(config.retain_projection) {
   if (!(1 <= config.hash_num)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("1 <= hash_num"));
   }
   if (!(1 <= config.table_num)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("1 <= table_num"));
   }
   if (!(0.f < config.bin_width)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("0.0 < bin_width"));
   }
   if (!(0 <= config.probe_num)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("0 <= probe_num"));
   }
   if (!(0 <= config.seed)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("0 <= seed"));
   }
   typedef storage::mixable_lsh_index_storage mli_storage;
   typedef mli_storage::model_ptr model_ptr;
   typedef storage::lsh_index_storage li_storage;
   model_ptr p(new li_storage(config.hash_num, config.table_num, config.seed));
   mixable_storage_.reset(new mli_storage(p));
 }
jubatus::core::recommender::euclid_lsh::~euclid_lsh ()
Definition at line 142 of file euclid_lsh.cpp.
{
 }
Member Function Documentation
vector< float > jubatus::core::recommender::euclid_lsh::calculate_lsh (const common::sfv_t & query) const private
Definition at line 222 of file euclid_lsh.cpp.
References bin_width_, jubatus::core::common::hash_util::calc_string_hash(), get_projection(), and mixable_storage_.
Referenced by update_row().
{
   vector<float> hash(mixable_storage_->get_model()->all_lsh_num());
   for (size_t i = 0; i < query.size(); ++i) {
     const uint32_t seed = common::hash_util::calc_string_hash(query[i].first);
     const vector<float> proj = get_projection(seed);
     for (size_t j = 0; j < hash.size(); ++j) {
       hash[j] += query[i].second * proj[j];
     }
   }
   for (size_t j = 0; j < hash.size(); ++j) {
     hash[j] /= bin_width_;
   }
   return hash;
 }
void jubatus::core::recommender::euclid_lsh::clear () virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 185 of file euclid_lsh.cpp.
References jubatus::core::storage::sparse_matrix_storage::clear(), mixable_storage_, jubatus::core::recommender::recommender_base::orig_, projection_cache_, and jubatus::core::clustering::swap().
{
   orig_.clear();
   mixable_storage_->get_model()->clear();
   // Clear projection cache
   jubatus::util::data::unordered_map<uint32_t, std::vector<float> >()
     .swap(projection_cache_);
 }
void jubatus::core::recommender::euclid_lsh::clear_row (const std::string & id) virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 194 of file euclid_lsh.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::remove_row().
{
   orig_.remove_row(id);
   mixable_storage_->get_model()->remove_row(id);
 }
void jubatus::core::recommender::euclid_lsh::get_all_row_ids (std::vector< std::string > & ids) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 210 of file euclid_lsh.cpp.
References mixable_storage_.
{
   mixable_storage_->get_model()->get_all_row_ids(ids);
 }
framework::mixable * jubatus::core::recommender::euclid_lsh::get_mixable () const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 218 of file euclid_lsh.cpp.
References mixable_storage_.
{
   return mixable_storage_.get();
 }
vector< float > jubatus::core::recommender::euclid_lsh::get_projection (uint32_t seed) const private
Definition at line 237 of file euclid_lsh.cpp.
References cache_lock_, mixable_storage_, projection_cache_, and retain_projection_.
Referenced by calculate_lsh().
{
   if (retain_projection_) {
     scoped_lock lk(cache_lock_);  // lock is needed only retain_projection
     vector<float>& proj = projection_cache_[seed];
     if (!proj.empty()) {
       return proj;
     }
     calc_projection(seed, mixable_storage_->get_model()->all_lsh_num(), proj);
     return proj;
   } else {
     vector<float> proj;
     calc_projection(seed, mixable_storage_->get_model()->all_lsh_num(), proj);
     return proj;
   }
 }
void jubatus::core::recommender::euclid_lsh::initialize_model () private
Definition at line 253 of file euclid_lsh.cpp.
References mixable_storage_.
{
   typedef storage::mixable_lsh_index_storage::model_ptr model_ptr;
   model_ptr p(new storage::lsh_index_storage);
   mixable_storage_.reset(new storage::mixable_lsh_index_storage(p));
 }
virtual void jubatus::core::recommender::euclid_lsh::neighbor_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Implements jubatus::core::recommender::recommender_base.
virtual void jubatus::core::recommender::euclid_lsh::neighbor_row (const std::string & id, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Reimplemented from jubatus::core::recommender::recommender_base.
void jubatus::core::recommender::euclid_lsh::pack (framework::packer & packer) const virtual
Implements jubatus::core::framework::model.
Definition at line 259 of file euclid_lsh.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::pack().
{
   packer.pack_array(2);
   orig_.pack(packer);
   mixable_storage_->get_model()->pack(packer);
 }
virtual void jubatus::core::recommender::euclid_lsh::similar_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Implements jubatus::core::recommender::recommender_base.
virtual void jubatus::core::recommender::euclid_lsh::similar_row (const std::string & id, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Reimplemented from jubatus::core::recommender::recommender_base.
string jubatus::core::recommender::euclid_lsh::type () const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 214 of file euclid_lsh.cpp.
{
   return "euclid_lsh";
 }
void jubatus::core::recommender::euclid_lsh::unpack (msgpack::object o) virtual
Implements jubatus::core::framework::model.
Definition at line 265 of file euclid_lsh.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::unpack().
{
   if (o.type != msgpack::type::ARRAY || o.via.array.size != 2) {
     throw msgpack::type_error();
   }
   orig_.unpack(o.via.array.ptr[0]);
   mixable_storage_->get_model()->unpack(o.via.array.ptr[1]);
 }
void jubatus::core::recommender::euclid_lsh::update_row (const std::string & id, const sfv_diff_t & diff) virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 199 of file euclid_lsh.cpp.
References calculate_lsh(), jubatus::core::storage::sparse_matrix_storage::get_row(), mixable_storage_, jubatus::core::recommender::recommender_base::orig_, jubatus::core::storage::sparse_matrix_storage::set_row(), and jubatus::core::storage::lsh_index_storage::set_row().
{
   storage::lsh_index_storage& lsh_index = *mixable_storage_->get_model();
   orig_.set_row(id, diff);
   common::sfv_t row;
   orig_.get_row(id, row);
   const vector<float> hash = calculate_lsh(row);
   const float norm = calc_norm(row);
   lsh_index.set_row(id, hash, norm);
 }
Member Data Documentation
float jubatus::core::recommender::euclid_lsh::bin_width_ private
Definition at line 123 of file euclid_lsh.hpp.
Referenced by calculate_lsh().
jubatus::util::concurrent::mutex jubatus::core::recommender::euclid_lsh::cache_lock_ mutable private
Definition at line 128 of file euclid_lsh.hpp.
Referenced by get_projection().
const float jubatus::core::recommender::euclid_lsh::DEFAULT_BIN_WIDTH = 100 static
Definition at line 54 of file euclid_lsh.hpp.
const uint64_t jubatus::core::recommender::euclid_lsh::DEFAULT_HASH_NUM = 64 static
Definition at line 52 of file euclid_lsh.hpp.
const uint32_t jubatus::core::recommender::euclid_lsh::DEFAULT_NUM_PROBE = 64 static
Definition at line 55 of file euclid_lsh.hpp.
const bool jubatus::core::recommender::euclid_lsh::DEFAULT_RETAIN_PROJECTION = false static
Definition at line 57 of file euclid_lsh.hpp.
const uint32_t jubatus::core::recommender::euclid_lsh::DEFAULT_SEED = 1091 static
Definition at line 56 of file euclid_lsh.hpp.
const uint64_t jubatus::core::recommender::euclid_lsh::DEFAULT_TABLE_NUM = 4 static
Definition at line 53 of file euclid_lsh.hpp.
jubatus::util::lang::shared_ptr<storage::mixable_lsh_index_storage> jubatus::core::recommender::euclid_lsh::mixable_storage_ private
Definition at line 122 of file euclid_lsh.hpp.
Referenced by calculate_lsh(), clear(), clear_row(), euclid_lsh(), get_all_row_ids(), get_mixable(), get_projection(), initialize_model(), pack(), unpack(), and update_row().
uint32_t jubatus::core::recommender::euclid_lsh::num_probe_ private
Definition at line 124 of file euclid_lsh.hpp.
jubatus::util::data::unordered_map<uint32_t, std::vector<float> > jubatus::core::recommender::euclid_lsh::projection_cache_ mutable private
Definition at line 127 of file euclid_lsh.hpp.
Referenced by clear(), and get_projection().
bool jubatus::core::recommender::euclid_lsh::retain_projection_ private
Definition at line 129 of file euclid_lsh.hpp.
Referenced by get_projection().
The documentation for this class was generated from the following files:
jubatus/core/recommender/euclid_lsh.hpp
jubatus/core/recommender/euclid_lsh.cpp