jubatus_core: jubatus::core::storage::typed_column< bit_vector > Class Template Reference
jubatus::core::storage::typed_column< bit_vector > Class Template Reference
#include <abstract_column.hpp>
Public Member Functions
void clear ()
void dump (std::ostream &os, uint64_t target) const
bool insert (uint64_t target, const bit_vector &value)
bool insert (uint64_t target, const msgpack::object &obj)
bit_vector operator[] (uint64_t index)
bit_vector operator[] (uint64_t index) const
template<class Buffer >
void pack_array (msgpack::packer< Buffer > &packer) const
void pack_with_index (const uint64_t index, framework::packer &pk) const
void push_back (const bit_vector &value)
void push_back (const msgpack::object &obj)
bool remove (uint64_t target)
uint64_t size () const
typed_column (const column_type &type)
void unpack_array (msgpack::object o)
bool update (uint64_t index, const bit_vector &value)
bool update (uint64_t index, const msgpack::object &obj)
Public Member Functions inherited from jubatus::core::storage::detail::abstract_column_base
abstract_column_base (const column_type &type)
JUBATUS_GEN_FUNCTIONS_ (uint8_t)
JUBATUS_GEN_FUNCTIONS_ (uint16_t)
JUBATUS_GEN_FUNCTIONS_ (uint32_t)
JUBATUS_GEN_FUNCTIONS_ (uint64_t)
JUBATUS_GEN_FUNCTIONS_ (int8_t)
JUBATUS_GEN_FUNCTIONS_ (int16_t)
JUBATUS_GEN_FUNCTIONS_ (int32_t)
JUBATUS_GEN_FUNCTIONS_ (int64_t)
JUBATUS_GEN_FUNCTIONS_ (float)
JUBATUS_GEN_FUNCTIONS_ (double)
JUBATUS_GEN_FUNCTIONS_ (std::string)
JUBATUS_GEN_FUNCTIONS_ (bit_vector)
JUBATUS_GEN_FUNCTIONS_ (msgpack::object)
column_type type () const
virtual ~abstract_column_base ()
Private Member Functions
size_t blocks_per_value_ () const
size_t bytes_per_value_ () const
void check_bit_vector_ (const bit_vector &tested) const
uint64_t * get_data_at_ (size_t index)
const uint64_t * get_data_at_ (size_t index) const
void update_at_ (size_t index, const void *raw_data)
Private Attributes
std::vector< uint64_t > array_
Friends
std::ostream & operator<< (std::ostream &os, const typed_column< bit_vector > &c)
Detailed Description
template<>
class jubatus::core::storage::typed_column< bit_vector >
Definition at line 214 of file abstract_column.hpp.
Constructor & Destructor Documentation
jubatus::core::storage::typed_column< bit_vector >::typed_column (const column_type & type) inline explicit
Definition at line 216 of file abstract_column.hpp.
       : detail::abstract_column_base(type) {
   }
Member Function Documentation
size_t jubatus::core::storage::typed_column< bit_vector >::blocks_per_value_ () const inline private
Definition at line 327 of file abstract_column.hpp.
{
     return (bytes_per_value_() + sizeof(uint64_t) - 1) / sizeof(uint64_t);
   }
size_t jubatus::core::storage::typed_column< bit_vector >::bytes_per_value_ () const inline private
Definition at line 324 of file abstract_column.hpp.
References jubatus::core::storage::bit_vector_base< uint64_t >::memory_size(), and jubatus::core::storage::detail::abstract_column_base::type().
{
     return bit_vector::memory_size(type().bit_vector_length());
   }
void jubatus::core::storage::typed_column< bit_vector >::check_bit_vector_ (const bit_vector & tested) const inline private
Definition at line 348 of file abstract_column.hpp.
References jubatus::core::storage::bit_vector_base< bit_base >::bit_num(), jubatus::core::storage::column_type::bit_vector_length(), and jubatus::core::storage::detail::abstract_column_base::type().
{
     const size_t bit_num_expected = type().bit_vector_length();
     if (tested.bit_num() > bit_num_expected) {
       throw length_unmatch_exception(
         "invalid length of bit_vector (" +
         jubatus::util::lang::lexical_cast<std::string>(tested.bit_num()) + ", "
         "expected " +
         jubatus::util::lang::lexical_cast<std::string>(bit_num_expected) + ")");
     }
   }
void jubatus::core::storage::typed_column< bit_vector >::clear () inline virtual
Implements jubatus::core::storage::detail::abstract_column_base.
Definition at line 290 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_.
                {
     array_.clear();
   }
void jubatus::core::storage::typed_column< bit_vector >::dump (std::ostream & os, uint64_t target) const inline virtual
Implements jubatus::core::storage::detail::abstract_column_base.
Definition at line 309 of file abstract_column.hpp.
{
     os << "[" << target << "] " << (*this)[target] << std::endl;
   }
uint64_t* jubatus::core::storage::typed_column< bit_vector >::get_data_at_ (size_t index) inline private
Definition at line 331 of file abstract_column.hpp.
References JUBATUS_ASSERT_LT, and jubatus::core::storage::typed_column< T >::size().
{
     JUBATUS_ASSERT_LT(index, size(), "");
     return &array_[blocks_per_value_() * index];
   }
const uint64_t* jubatus::core::storage::typed_column< bit_vector >::get_data_at_ (size_t index) const inline private
Definition at line 335 of file abstract_column.hpp.
References JUBATUS_ASSERT_LT, and jubatus::core::storage::typed_column< T >::size().
{
     JUBATUS_ASSERT_LT(index, size(), "");
     return &array_[blocks_per_value_() * index];
   }
bool jubatus::core::storage::typed_column< bit_vector >::insert (uint64_t target, const bit_vector & value) inline
Definition at line 235 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_, jubatus::core::storage::bit_vector_base< bit_base >::raw_data_unsafe(), and jubatus::core::storage::typed_column< T >::size().
{
     check_bit_vector_(value);
     if (size() < target) {
       return false;
     }
     array_.insert(
         array_.begin() + target * blocks_per_value_(),
         blocks_per_value_(), 0);
     update_at_(target, value.raw_data_unsafe());
     return true;
   }
bool jubatus::core::storage::typed_column< bit_vector >::insert (uint64_t target, const msgpack::object & obj) inline
Definition at line 247 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::insert(), and jubatus::core::storage::detail::abstract_column_base::type().
{
     bit_vector value(type().bit_vector_length());
     obj.convert(&value);
     return typed_column::insert(target, value);
   }
bit_vector jubatus::core::storage::typed_column< bit_vector >::operator[] (uint64_t index) inline
Definition at line 272 of file abstract_column.hpp.
References jubatus::core::storage::detail::abstract_column_base::type().
{
     return bit_vector(get_data_at_(index), type().bit_vector_length());
   }
bit_vector jubatus::core::storage::typed_column< bit_vector >::operator[] (uint64_t index) const inline
Definition at line 275 of file abstract_column.hpp.
References jubatus::core::storage::detail::abstract_column_base::type().
{
     return bit_vector(get_data_at_(index), type().bit_vector_length());
   }
template<class Buffer > void jubatus::core::storage::typed_column< bit_vector >::pack_array (msgpack::packer< Buffer > & packer) const inline
Definition at line 314 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_.
{
     packer.pack(array_);
   }
void jubatus::core::storage::typed_column< bit_vector >::pack_with_index (const uint64_t index, framework::packer & pk) const inline virtual
Reimplemented from jubatus::core::storage::detail::abstract_column_base.
Definition at line 293 of file abstract_column.hpp.
{
     pk.pack((*this)[index]);
   }
void jubatus::core::storage::typed_column< bit_vector >::push_back (const bit_vector & value) inline
Definition at line 224 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_, jubatus::core::storage::bit_vector_base< bit_base >::raw_data_unsafe(), and jubatus::core::storage::typed_column< T >::size().
{
     check_bit_vector_(value);
     array_.resize(array_.size() + blocks_per_value_());
     update_at_(size() - 1, value.raw_data_unsafe());
   }
void jubatus::core::storage::typed_column< bit_vector >::push_back (const msgpack::object & obj) inline
Definition at line 229 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::push_back(), and jubatus::core::storage::detail::abstract_column_base::type().
{
     bit_vector value(type().bit_vector_length());
     obj.convert(&value);
     typed_column::push_back(value);
   }
bool jubatus::core::storage::typed_column< bit_vector >::remove (uint64_t target) inline virtual
Implements jubatus::core::storage::detail::abstract_column_base.
Definition at line 278 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_, JUBATUS_ASSERT_GE, and jubatus::core::storage::typed_column< T >::size().
{
     if (target >= size()) {
       return false;
     }
     if (target < size() - 1) {
       const void* back = get_data_at_(size() - 1);
       memcpy(get_data_at_(target), back, bytes_per_value_());
     }
     JUBATUS_ASSERT_GE(array_.size(), blocks_per_value_(), "");
     array_.resize(array_.size() - blocks_per_value_());
     return true;
   }
uint64_t jubatus::core::storage::typed_column< bit_vector >::size () const inline
Definition at line 268 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_, and JUBATUS_ASSERT_EQ.
{
     JUBATUS_ASSERT_EQ(array_.size() % blocks_per_value_(), 0u, "");
     return array_.size() / blocks_per_value_();
   }
void jubatus::core::storage::typed_column< bit_vector >::unpack_array (msgpack::object o) inline
Definition at line 317 of file abstract_column.hpp.
References jubatus::core::storage::typed_column< T >::array_.
{
     o.convert(&array_);
   }
bool jubatus::core::storage::typed_column< bit_vector >::update (uint64_t index, const bit_vector & value) inline
Definition at line 253 of file abstract_column.hpp.
References jubatus::core::storage::bit_vector_base< bit_base >::raw_data_unsafe(), and jubatus::core::storage::typed_column< T >::size().
{
     check_bit_vector_(value);
     if (size() < index) {
       return false;
     }
     update_at_(index, value.raw_data_unsafe());
     return true;
   }
bool jubatus::core::storage::typed_column< bit_vector >::update (uint64_t index, const msgpack::object & obj) inline
Definition at line 262 of file abstract_column.hpp.
References jubatus::core::storage::detail::abstract_column_base::type(), and jubatus::core::storage::typed_column< T >::update().
{
     bit_vector value(type().bit_vector_length());
     obj.convert(&value);
     return typed_column::update(index, value);
   }
void jubatus::core::storage::typed_column< bit_vector >::update_at_ (size_t index, const void * raw_data) inline private
Definition at line 340 of file abstract_column.hpp.
{
     if (raw_data) {
       memcpy(get_data_at_(index), raw_data, bytes_per_value_());
     } else {
       memset(get_data_at_(index), 0, bytes_per_value_());
     }
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const typed_column< bit_vector > & c) friend
Definition at line 298 of file abstract_column.hpp.
{
     os << "[column (bit_vector)"
         << " size:" << c.size() << " {" << std::endl;
     for (size_t i = 0; i < c.size(); ++i) {
       c.dump(os, i);
     }
     os << "} ]" << std::endl;
     return os;
   }
Member Data Documentation
std::vector<uint64_t> jubatus::core::storage::typed_column< bit_vector >::array_ private
Definition at line 322 of file abstract_column.hpp.
The documentation for this class was generated from the following file:
jubatus/core/storage/abstract_column.hpp