jubatus_core: jubatus::core::recommender::minhash Class Reference
jubatus::core::recommender::minhash Class Reference
#include <minhash.hpp>
Classes
struct config
Public Member Functions
void clear ()
void clear_row (const std::string &id)
void get_all_row_ids (std::vector< std::string > &ids) const
framework::mixable * get_mixable () const
minhash ()
minhash (const config &config)
void neighbor_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
void pack (framework::packer &packer) const
void similar_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
std::string type () const
void unpack (msgpack::object o)
void update_row (const std::string &id, const sfv_diff_t &diff)
~minhash ()
Public Member Functions inherited from jubatus::core::recommender::recommender_base
void complete_row (const std::string &id, common::sfv_t &ret) const
void complete_row (const common::sfv_t &query, common::sfv_t &ret) const
void decode_row (const std::string &id, common::sfv_t &ret) const
virtual const core::storage::recommender_storage_base * get_const_storage () const
virtual jubatus::util::lang::shared_ptr< const table::column_table > get_const_table () const
virtual jubatus::util::lang::shared_ptr< table::column_table > get_table ()
virtual jubatus::util::lang::shared_ptr< unlearner::unlearner_base > get_unlearner ()
virtual void neighbor_row (const std::string &id, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
recommender_base ()
virtual void similar_row (const std::string &id, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
virtual ~recommender_base ()
Public Member Functions inherited from jubatus::core::framework::model
virtual ~model ()
Private Member Functions
void calc_minhash_values (const common::sfv_t &sfv, core::storage::bit_vector &bv) const
void initialize_model ()
Static Private Member Functions
static float calc_hash (uint64_t a, uint64_t b, float val)
static void hash_mix64 (uint64_t &a, uint64_t &b, uint64_t &c)
Private Attributes
uint64_t hash_num_
jubatus::util::lang::shared_ptr< storage::mixable_bit_index_storage > mixable_storage_
Static Private Attributes
static const uint64_t hash_prime = 0xc3a5c85c97cb3127ULL
Additional Inherited Members
Static Public Member Functions inherited from jubatus::core::recommender::recommender_base
static float calc_l2norm (const common::sfv_t &query)
static float calc_similality (common::sfv_t &q1, common::sfv_t &q2)
Protected Attributes inherited from jubatus::core::recommender::recommender_base
core::storage::sparse_matrix_storage orig_
Static Protected Attributes inherited from jubatus::core::recommender::recommender_base
static const uint64_t complete_row_similar_num_ = 128
Detailed Description
Definition at line 33 of file minhash.hpp.
Constructor & Destructor Documentation
jubatus::core::recommender::minhash::minhash ()
Definition at line 40 of file minhash.cpp.
References initialize_model().
     : hash_num_(64) {
   initialize_model();
 }
jubatus::core::recommender::minhash::minhash (const config & config) explicit
Definition at line 45 of file minhash.cpp.
References jubatus::core::recommender::minhash::config::hash_num, initialize_model(), and JUBATUS_EXCEPTION.
     : hash_num_(config.hash_num) {
   if (!(1 <= config.hash_num)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("1 <= hash_num"));
   }
   initialize_model();
 }
jubatus::core::recommender::minhash::~minhash ()
Definition at line 56 of file minhash.cpp.
                   {
 }
Member Function Documentation
float jubatus::core::recommender::minhash::calc_hash (uint64_t a, uint64_t b, float val) static private
Definition at line 171 of file minhash.cpp.
References hash_mix64(), and hash_prime.
Referenced by calc_minhash_values().
{
   uint64_t c = hash_prime;
   hash_mix64(a, b, c);
   hash_mix64(a, b, c);
   float r = static_cast<float>(a) / static_cast<float>(0xFFFFFFFFFFFFFFFFLLU);
   return -std::log(r) / val;
 }
void jubatus::core::recommender::minhash::calc_minhash_values (const common::sfv_t & sfv, core::storage::bit_vector & bv) const private
Definition at line 93 of file minhash.cpp.
References calc_hash(), jubatus::core::common::hash_util::calc_string_hash(), hash_num_, jubatus::core::storage::bit_vector::resize_and_clear(), and jubatus::core::storage::bit_vector::set_bit().
Referenced by similar_row(), and update_row().
{
   vector<float> min_values_buffer(hash_num_, FLT_MAX);
   vector<uint64_t> hash_buffer(hash_num_);
   for (size_t i = 0; i < sfv.size(); ++i) {
     uint64_t key_hash = common::hash_util::calc_string_hash(sfv[i].first);
     float val = sfv[i].second;
     for (uint64_t j = 0; j < hash_num_; ++j) {
       float hashval = calc_hash(key_hash, j, val);
       if (hashval < min_values_buffer[j]) {
         min_values_buffer[j] = hashval;
         hash_buffer[j] = key_hash;
       }
     }
   }
   bv.resize_and_clear(hash_num_);
   for (size_t i = 0; i < hash_buffer.size(); ++i) {
     if ((hash_buffer[i] & 1LLU) == 1) {
       bv.set_bit(i);
     }
   }
 }
void jubatus::core::recommender::minhash::clear () virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 83 of file minhash.cpp.
References jubatus::core::storage::sparse_matrix_storage::clear(), mixable_storage_, and jubatus::core::recommender::recommender_base::orig_.
                     {
   orig_.clear();
   mixable_storage_->get_model()->clear();
 }
void jubatus::core::recommender::minhash::clear_row (const std::string & id) virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 88 of file minhash.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::remove_row().
{
   orig_.remove_row(id);
   mixable_storage_->get_model()->remove_row(id);
 }
void jubatus::core::recommender::minhash::get_all_row_ids (std::vector< std::string > & ids) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 127 of file minhash.cpp.
References mixable_storage_.
{
   mixable_storage_->get_model()->get_all_row_ids(ids);
 }
framework::mixable * jubatus::core::recommender::minhash::get_mixable () const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 183 of file minhash.cpp.
References mixable_storage_.
{
   return mixable_storage_.get();
 }
void jubatus::core::recommender::minhash::hash_mix64 (uint64_t & a, uint64_t & b, uint64_t & c) static private
Definition at line 132 of file minhash.cpp.
Referenced by calc_hash().
{
   a -= b;
   a -= c;
   a ^= (c >> 43);
   b -= c;
   b -= a;
   b ^= (a << 9);
   c -= a;
   c -= b;
   c ^= (b >> 8);
   a -= b;
   a -= c;
   a ^= (c >> 38);
   b -= c;
   b -= a;
   b ^= (a << 23);
   c -= a;
   c -= b;
   c ^= (b >> 5);
   a -= b;
   a -= c;
   a ^= (c >> 35);
   b -= c;
   b -= a;
   b ^= (a << 49);
   c -= a;
   c -= b;
   c ^= (b >> 11);
   a -= b;
   a -= c;
   a ^= (c >> 12);
   b -= c;
   b -= a;
   b ^= (a << 18);
   c -= a;
   c -= b;
   c ^= (b >> 22);
 }
void jubatus::core::recommender::minhash::initialize_model () private
Definition at line 187 of file minhash.cpp.
References mixable_storage_.
Referenced by minhash().
{
   shared_ptr<storage::bit_index_storage> p(new storage::bit_index_storage);
   mixable_storage_.reset(new storage::mixable_bit_index_storage(p));
 }
void jubatus::core::recommender::minhash::neighbor_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 73 of file minhash.cpp.
References similar_row().
{
   similar_row(query, ids, ret_num);
   for (size_t i = 0; i < ids.size(); ++i) {
     ids[i].second = 1 - ids[i].second;
   }
 }
void jubatus::core::recommender::minhash::pack (framework::packer & packer) const virtual
Implements jubatus::core::framework::model.
Definition at line 192 of file minhash.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::pack().
{
   packer.pack_array(2);
   orig_.pack(packer);
   mixable_storage_->get_model()->pack(packer);
 }
void jubatus::core::recommender::minhash::similar_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 59 of file minhash.cpp.
References calc_minhash_values(), and mixable_storage_.
Referenced by neighbor_row().
{
   ids.clear();
   if (ret_num == 0) {
     return;
   }
   bit_vector query_bv;
   calc_minhash_values(query, query_bv);
   mixable_storage_->get_model()->similar_row(query_bv, ids, ret_num);
 }
string jubatus::core::recommender::minhash::type () const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 179 of file minhash.cpp.
{
   return string("minhash");
 }
void jubatus::core::recommender::minhash::unpack (msgpack::object o) virtual
Implements jubatus::core::framework::model.
Definition at line 198 of file minhash.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::unpack().
{
   if (o.type != msgpack::type::ARRAY || o.via.array.size != 2) {
     throw msgpack::type_error();
   }
   orig_.unpack(o.via.array.ptr[0]);
   mixable_storage_->get_model()->unpack(o.via.array.ptr[1]);
 }
void jubatus::core::recommender::minhash::update_row (const std::string & id, const sfv_diff_t & diff) virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 117 of file minhash.cpp.
References calc_minhash_values(), jubatus::core::storage::sparse_matrix_storage::get_row(), mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::set_row().
{
   orig_.set_row(id, diff);
   common::sfv_t row;
   orig_.get_row(id, row);
   bit_vector bv;
   calc_minhash_values(row, bv);
   mixable_storage_->get_model()->set_row(id, bv);
 }
Member Data Documentation
uint64_t jubatus::core::recommender::minhash::hash_num_ private
Definition at line 82 of file minhash.hpp.
Referenced by calc_minhash_values().
const uint64_t jubatus::core::recommender::minhash::hash_prime = 0xc3a5c85c97cb3127ULL static private
Definition at line 81 of file minhash.hpp.
Referenced by calc_hash().
jubatus::util::lang::shared_ptr<storage::mixable_bit_index_storage> jubatus::core::recommender::minhash::mixable_storage_ private
Definition at line 84 of file minhash.hpp.
Referenced by clear(), clear_row(), get_all_row_ids(), get_mixable(), initialize_model(), pack(), similar_row(), unpack(), and update_row().
The documentation for this class was generated from the following files:
jubatus/core/recommender/minhash.hpp
jubatus/core/recommender/minhash.cpp