jubatus_core: jubatus::core::regression::passive_aggressive Class Reference
jubatus::core::regression::passive_aggressive Class Reference
#include <passive_aggressive.hpp>
Classes
struct config
Public Member Functions
void clear ()
passive_aggressive (const config &config, storage_ptr storage)
passive_aggressive (storage_ptr storage)
void train (const common::sfv_t &fv, float value)
Public Member Functions inherited from jubatus::core::regression::regression_base
float estimate (const common::sfv_t &fv) const
virtual void get_status (std::map< std::string, std::string > &status) const
storage_ptr get_storage ()
regression_base (storage_ptr storage)
virtual ~regression_base ()
Private Attributes
config config_
float count_
float sq_sum_
float sum_
Additional Inherited Members
Protected Member Functions inherited from jubatus::core::regression::regression_base
void update (const common::sfv_t &fv, float coeff)
Protected Attributes inherited from jubatus::core::regression::regression_base
storage_ptr storage_
Detailed Description
Definition at line 28 of file passive_aggressive.hpp.
Constructor & Destructor Documentation
jubatus::core::regression::passive_aggressive::passive_aggressive (const config & config, storage_ptr storage)
Definition at line 27 of file passive_aggressive.cpp.
References JUBATUS_EXCEPTION, jubatus::core::regression::passive_aggressive::config::regularization_weight, and jubatus::core::regression::passive_aggressive::config::sensitivity.
     : regression_base(storage),
       config_(config),
       sum_(0.f),
       sq_sum_(0.f),
       count_(0.f) {
   if (!(0.f < config.regularization_weight)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("0.0 < regularization_weight"));
   }
   if (!(0.f <= config.sensitivity)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("0.0 <= sensitivity"));
   }
 }
jubatus::core::regression::passive_aggressive::passive_aggressive (storage_ptr storage) explicit
Definition at line 47 of file passive_aggressive.cpp.
     : regression_base(storage),
       sum_(0.f),
       sq_sum_(0.f),
       count_(0.f) {
 }
Member Function Documentation
void jubatus::core::regression::passive_aggressive::clear () virtual
Reimplemented from jubatus::core::regression::regression_base.
Definition at line 83 of file passive_aggressive.cpp.
References jubatus::core::regression::regression_base::clear(), count_, sq_sum_, and sum_.
{
   regression_base::clear();
   sum_ = 0.f;
   sq_sum_ = 0.f;
   count_ = 0.f;
 }
void jubatus::core::regression::passive_aggressive::train (const common::sfv_t & fv, float value) virtual
Implements jubatus::core::regression::regression_base.
Definition at line 62 of file passive_aggressive.cpp.
References config_, count_, jubatus::core::regression::regression_base::estimate(), jubatus::core::regression::passive_aggressive::config::regularization_weight, jubatus::core::regression::passive_aggressive::config::sensitivity, sq_sum_, jubatus::core::regression::squared_norm(), sum_, and jubatus::core::regression::regression_base::update().
{
   sum_ += value;
   sq_sum_ += value * value;
   count_ += 1;
   float avg = sum_ / count_;
   float std_dev = std::sqrt(sq_sum_ / count_ -  avg * avg);
   float predict = estimate(fv);
   float error = value - predict;
   float sign_error = error > 0.f ? 1.0f : -1.0f;
   float loss = sign_error * error - config_.sensitivity * std_dev;
   if (loss > 0.f) {
     float C = config_.regularization_weight;
     float coeff = sign_error * std::min(C, loss) / squared_norm(fv);
     if (!std::isinf(coeff)) {
       update(fv, coeff);
     }
   }
 }
Member Data Documentation
config jubatus::core::regression::passive_aggressive::config_ private
Definition at line 55 of file passive_aggressive.hpp.
Referenced by train().
float jubatus::core::regression::passive_aggressive::count_ private
Definition at line 58 of file passive_aggressive.hpp.
Referenced by clear(), and train().
float jubatus::core::regression::passive_aggressive::sq_sum_ private
Definition at line 57 of file passive_aggressive.hpp.
Referenced by clear(), and train().
float jubatus::core::regression::passive_aggressive::sum_ private
Definition at line 56 of file passive_aggressive.hpp.
Referenced by clear(), and train().
The documentation for this class was generated from the following files:
jubatus/core/regression/passive_aggressive.hpp
jubatus/core/regression/passive_aggressive.cpp