jubatus_core: jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base Class Reference
jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base Class Reference abstract
#include <bit_vector_nearest_neighbor_base.hpp>
Public Member Functions
bit_vector_nearest_neighbor_base (uint32_t bitnum, jubatus::util::lang::shared_ptr< table::column_table > table, const std::string &id)
bit_vector_nearest_neighbor_base (uint32_t bitnum, jubatus::util::lang::shared_ptr< table::column_table > table, std::vector< table::column_type > &schema, const std::string &id)
uint32_t bitnum () const
virtual void neighbor_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const
virtual void neighbor_row (const std::string &query_id, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const
virtual void set_row (const std::string &id, const common::sfv_t &sfv)
Public Member Functions inherited from jubatus::core::nearest_neighbor::nearest_neighbor_base
virtual float calc_similarity (float distance) const
virtual void clear ()
void get_all_row_ids (std::vector< std::string > &ids) const
jubatus::util::lang::shared_ptr< const table::column_table > get_const_table () const
framework::mixable * get_mixable () const
jubatus::util::lang::shared_ptr< table::column_table > get_table ()
nearest_neighbor_base (jubatus::util::lang::shared_ptr< table::column_table > table, const std::string &id)
void pack (framework::packer &packer) const
virtual void similar_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const
virtual void similar_row (const std::string &query_id, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const
virtual std::string type () const =0
void unpack (msgpack::object o)
virtual ~nearest_neighbor_base ()
Private Member Functions
table::const_bit_vector_column & bit_vector_column () const
void fill_schema (std::vector< table::column_type > &schema)
virtual table::bit_vector hash (const common::sfv_t &sfv) const =0
void neighbor_row_from_hash (const table::bit_vector &query, std::vector< std::pair< std::string, float > > &ids, uint64_t ret_num) const
Private Attributes
uint64_t bit_vector_column_id_
uint32_t bitnum_
Additional Inherited Members
Protected Attributes inherited from jubatus::core::nearest_neighbor::nearest_neighbor_base
std::string my_id_
Detailed Description
Definition at line 31 of file bit_vector_nearest_neighbor_base.hpp.
Constructor & Destructor Documentation
jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base::bit_vector_nearest_neighbor_base (uint32_t bitnum, jubatus::util::lang::shared_ptr< table::column_table > table, const std::string & id)
jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base::bit_vector_nearest_neighbor_base (uint32_t bitnum, jubatus::util::lang::shared_ptr< table::column_table > table, std::vector< table::column_type > & schema, const std::string & id)
Member Function Documentation
const_bit_vector_column & jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base::bit_vector_column () const private
Definition at line 96 of file bit_vector_nearest_neighbor_base.cpp.
References bit_vector_column_id_, and jubatus::core::nearest_neighbor::nearest_neighbor_base::get_const_table().
Referenced by neighbor_row_from_hash().
           {
   return get_const_table()->get_bit_vector_column(bit_vector_column_id_);
 }
uint32_t jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base::bitnum () const inline
Definition at line 43 of file bit_vector_nearest_neighbor_base.hpp.
References bitnum_.
Referenced by jubatus::core::nearest_neighbor::lsh::hash().
 { return bitnum_; }
void jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base::fill_schema (std::vector< table::column_type > & schema) private
Definition at line 90 of file bit_vector_nearest_neighbor_base.cpp.
References bit_vector_column_id_, and bitnum_.
{
   bit_vector_column_id_ = schema.size();
   schema.push_back(column_type(column_type::bit_vector_type, bitnum_));
 }
virtual table::bit_vector jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base::hash (const common::sfv_t & sfv) const private pure virtual
Implemented in jubatus::core::nearest_neighbor::minhash, and jubatus::core::nearest_neighbor::lsh.
Referenced by set_row().
virtual void jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base::neighbor_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, uint64_t ret_num) const virtual
Implements jubatus::core::nearest_neighbor::nearest_neighbor_base.
virtual void jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base::neighbor_row (const std::string & query_id, std::vector< std::pair< std::string, float > > & ids, uint64_t ret_num) const virtual
Implements jubatus::core::nearest_neighbor::nearest_neighbor_base.
void jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base::neighbor_row_from_hash (const table::bit_vector & query, std::vector< std::pair< std::string, float > > & ids, uint64_t ret_num) const private
Definition at line 101 of file bit_vector_nearest_neighbor_base.cpp.
References bit_vector_column(), jubatus::core::nearest_neighbor::nearest_neighbor_base::get_const_table(), and jubatus::core::nearest_neighbor::ranking_hamming_bit_vectors().
{
   vector<pair<uint64_t, float> > scores;
   ranking_hamming_bit_vectors(query, bit_vector_column(), scores, ret_num);
   jubatus::util::lang::shared_ptr<const column_table> table = get_const_table();
   ids.clear();
   for (size_t i = 0; i < scores.size(); ++i) {
     ids.push_back(make_pair(table->get_key(scores[i].first), scores[i].second));
   }
 }
void jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base::set_row (const std::string & id, const common::sfv_t & sfv) virtual
Implements jubatus::core::nearest_neighbor::nearest_neighbor_base.
Definition at line 59 of file bit_vector_nearest_neighbor_base.cpp.
References jubatus::core::nearest_neighbor::nearest_neighbor_base::get_table(), hash(), and jubatus::core::nearest_neighbor::nearest_neighbor_base::my_id_.
{
   // TODO(beam2d): support nested algorithm, e.g. when used by lof and then
   // we cannot suppose that the first column is assigned
   // to bit_vector_nearest_neighbor_base.
   get_table()->add(id, owner(my_id_), hash(sfv));
 }
Member Data Documentation
uint64_t jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base::bit_vector_column_id_ private
Definition at line 66 of file bit_vector_nearest_neighbor_base.hpp.
Referenced by bit_vector_column(), and fill_schema().
uint32_t jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base::bitnum_ private
Definition at line 67 of file bit_vector_nearest_neighbor_base.hpp.
Referenced by bitnum(), and fill_schema().
The documentation for this class was generated from the following files:
jubatus/core/nearest_neighbor/bit_vector_nearest_neighbor_base.hpp
jubatus/core/nearest_neighbor/bit_vector_nearest_neighbor_base.cpp