jubatus_core: jubatus::core::recommender::recommender_mock_storage Class Reference
jubatus::core::recommender::recommender_mock_storage Class Reference
#include <recommender_mock_storage.hpp>
Public Member Functions
void clear ()
void get_diff (recommender_mock_storage &diff) const
storage::version get_version () const
void mix (const recommender_mock_storage &lhs, recommender_mock_storage &rhs) const
MSGPACK_DEFINE (similar_relation_, neighbor_relation_)
std::string name () const
void neighbor_items_distance (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
void pack (framework::packer &packer) const
bool put_diff (const recommender_mock_storage &mixed_diff)
void remove (const common::sfv_t &query)
void set_neighbor_items (const common::sfv_t &query, const std::vector< std::pair< std::string, float > > &ids)
void set_similar_items (const common::sfv_t &query, const std::vector< std::pair< std::string, float > > &ids)
void similar_items_similarity (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
void unpack (msgpack::object o)
void update (const common::sfv_t &from, const common::sfv_t &to)
virtual ~recommender_mock_storage ()
Private Types
typedef std::map< common::sfv_t, std::vector< std::pair< std::string, float > > > relation_type
Static Private Member Functions
static void get_relation (const common::sfv_t &query, const relation_type &relmap, size_t ret_num, std::vector< std::pair< std::string, float > > &ids)
static void mix_relation (const relation_type &from, relation_type &to)
static void update_relation_key (const common::sfv_t &from, const common::sfv_t &to, relation_type &relmap)
Private Attributes
relation_type neighbor_relation_
relation_type similar_relation_
Detailed Description
Definition at line 33 of file recommender_mock_storage.hpp.
Member Typedef Documentation
typedef std::map<common::sfv_t, std::vector<std::pair<std::string, float> > > jubatus::core::recommender::recommender_mock_storage::relation_type private
Definition at line 73 of file recommender_mock_storage.hpp.
Constructor & Destructor Documentation
jubatus::core::recommender::recommender_mock_storage::~recommender_mock_storage () virtual
Definition at line 33 of file recommender_mock_storage.cpp.
{
 }
Member Function Documentation
void jubatus::core::recommender::recommender_mock_storage::clear ()
Definition at line 73 of file recommender_mock_storage.cpp.
References neighbor_relation_, and similar_relation_.
{
   similar_relation_.clear();
   neighbor_relation_.clear();
 }
void jubatus::core::recommender::recommender_mock_storage::get_diff (recommender_mock_storage & diff) const
Definition at line 90 of file recommender_mock_storage.cpp.
{
   diff = *this;
 }
void jubatus::core::recommender::recommender_mock_storage::get_relation (const common::sfv_t & query, const relation_type & relmap, size_t ret_num, std::vector< std::pair< std::string, float > > & ids) static private
Definition at line 110 of file recommender_mock_storage.cpp.
Referenced by neighbor_items_distance(), and similar_items_similarity().
{
   ids.clear();
   relation_type::const_iterator it = relmap.find(query);
   if (it != relmap.end()) {
     ids = it->second;
   }
   if (ids.size() > ret_num) {
     ids.resize(ret_num);
   }
 }
storage::version jubatus::core::recommender::recommender_mock_storage::get_version () const inline
Definition at line 59 of file recommender_mock_storage.hpp.
{
     return storage::version();
   }
void jubatus::core::recommender::recommender_mock_storage::mix (const recommender_mock_storage & lhs, recommender_mock_storage & rhs) const
Definition at line 100 of file recommender_mock_storage.cpp.
References mix_relation(), neighbor_relation_, and similar_relation_.
{
   mix_relation(lhs.similar_relation_, rhs.similar_relation_);
   mix_relation(lhs.neighbor_relation_, rhs.neighbor_relation_);
 }
void jubatus::core::recommender::recommender_mock_storage::mix_relation (const relation_type & from, relation_type & to) static private
Definition at line 144 of file recommender_mock_storage.cpp.
Referenced by mix().
{
   for (relation_type::const_iterator it = from.begin(); it != from.end();
       ++it) {
     to[it->first] = it->second;
   }
 }
jubatus::core::recommender::recommender_mock_storage::MSGPACK_DEFINE (similar_relation_ , neighbor_relation_)
string jubatus::core::recommender::recommender_mock_storage::name () const
Definition at line 78 of file recommender_mock_storage.cpp.
{
   return "recommender_mock_storage";
 }
void jubatus::core::recommender::recommender_mock_storage::neighbor_items_distance (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const
Definition at line 55 of file recommender_mock_storage.cpp.
References get_relation(), and neighbor_relation_.
{
   get_relation(query, neighbor_relation_, ret_num, ids);
 }
void jubatus::core::recommender::recommender_mock_storage::pack (framework::packer & packer) const
Definition at line 82 of file recommender_mock_storage.cpp.
{
   packer.pack(*this);
 }
bool jubatus::core::recommender::recommender_mock_storage::put_diff (const recommender_mock_storage & mixed_diff)
Definition at line 94 of file recommender_mock_storage.cpp.
{
   *this = mixed_diff;
   return true;
 }
void jubatus::core::recommender::recommender_mock_storage::remove (const common::sfv_t & query)
Definition at line 68 of file recommender_mock_storage.cpp.
References neighbor_relation_, and similar_relation_.
{
   similar_relation_.erase(query);
   neighbor_relation_.erase(query);
 }
void jubatus::core::recommender::recommender_mock_storage::set_neighbor_items (const common::sfv_t & query, const std::vector< std::pair< std::string, float > > & ids)
Definition at line 42 of file recommender_mock_storage.cpp.
References neighbor_relation_.
{
   neighbor_relation_[query] = ids;
 }
void jubatus::core::recommender::recommender_mock_storage::set_similar_items (const common::sfv_t & query, const std::vector< std::pair< std::string, float > > & ids)
Definition at line 36 of file recommender_mock_storage.cpp.
References similar_relation_.
{
   similar_relation_[query] = ids;
 }
void jubatus::core::recommender::recommender_mock_storage::similar_items_similarity (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const
Definition at line 48 of file recommender_mock_storage.cpp.
References get_relation(), and similar_relation_.
{
   get_relation(query, similar_relation_, ret_num, ids);
 }
void jubatus::core::recommender::recommender_mock_storage::unpack (msgpack::object o)
Definition at line 86 of file recommender_mock_storage.cpp.
{
   o.convert(this);
 }
void jubatus::core::recommender::recommender_mock_storage::update (const common::sfv_t & from, const common::sfv_t & to)
Definition at line 62 of file recommender_mock_storage.cpp.
References neighbor_relation_, similar_relation_, and update_relation_key().
{
   update_relation_key(from, to, similar_relation_);
   update_relation_key(from, to, neighbor_relation_);
 }
void jubatus::core::recommender::recommender_mock_storage::update_relation_key (const common::sfv_t & from, const common::sfv_t & to, relation_type & relmap) static private
Definition at line 128 of file recommender_mock_storage.cpp.
Referenced by update().
{
   relation_type::iterator it = relmap.find(from);
   if (it != relmap.end()) {
     relation_type::mapped_type val;
     val.swap(it->second);
     relmap.erase(it);
     relmap[to].swap(val);
   } else {
     relmap[to];  // add default value
   }
 }
Member Data Documentation
relation_type jubatus::core::recommender::recommender_mock_storage::neighbor_relation_ private
Definition at line 89 of file recommender_mock_storage.hpp.
Referenced by clear(), mix(), neighbor_items_distance(), remove(), set_neighbor_items(), and update().
relation_type jubatus::core::recommender::recommender_mock_storage::similar_relation_ private
Definition at line 88 of file recommender_mock_storage.hpp.
Referenced by clear(), mix(), remove(), set_similar_items(), similar_items_similarity(), and update().
The documentation for this class was generated from the following files:
jubatus/core/recommender/recommender_mock_storage.hpp
jubatus/core/recommender/recommender_mock_storage.cpp