jubatus_core: jubatus::core::recommender::lsh Class Reference
jubatus::core::recommender::lsh Class Reference
#include <lsh.hpp>
Classes
struct config
Public Member Functions
void clear ()
void clear_row (const std::string &id)
void get_all_row_ids (std::vector< std::string > &ids) const
framework::mixable * get_mixable () const
lsh (uint64_t hash_num)
lsh (const config &config)
lsh ()
void neighbor_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
void pack (framework::packer &packer) const
void similar_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
std::string type () const
void unpack (msgpack::object o)
void update_row (const std::string &id, const sfv_diff_t &diff)
~lsh ()
Public Member Functions inherited from jubatus::core::recommender::recommender_base
void complete_row (const std::string &id, common::sfv_t &ret) const
void complete_row (const common::sfv_t &query, common::sfv_t &ret) const
void decode_row (const std::string &id, common::sfv_t &ret) const
virtual const core::storage::recommender_storage_base * get_const_storage () const
virtual jubatus::util::lang::shared_ptr< const storage::column_table > get_const_table () const
virtual jubatus::util::lang::shared_ptr< storage::column_table > get_table ()
virtual jubatus::util::lang::shared_ptr< unlearner::unlearner_base > get_unlearner ()
virtual void neighbor_row (const std::string &id, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
recommender_base ()
virtual void similar_row (const std::string &id, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
virtual ~recommender_base ()
Public Member Functions inherited from jubatus::core::framework::model
virtual ~model ()
Private Member Functions
void calc_lsh_values (const common::sfv_t &sfv, storage::bit_vector &bv) const
void generate_column_base (const std::string &column)
void generate_column_bases (const common::sfv_t &v)
void initialize_model ()
Private Attributes
jubatus::util::data::unordered_map< std::string, std::vector< float > > column2baseval_
const uint64_t hash_num_
jubatus::util::lang::shared_ptr< storage::mixable_bit_index_storage > mixable_storage_
Additional Inherited Members
Static Public Member Functions inherited from jubatus::core::recommender::recommender_base
static float calc_l2norm (const common::sfv_t &query)
static float calc_similality (common::sfv_t &q1, common::sfv_t &q2)
Protected Attributes inherited from jubatus::core::recommender::recommender_base
core::storage::sparse_matrix_storage orig_
Static Protected Attributes inherited from jubatus::core::recommender::recommender_base
static const uint64_t complete_row_similar_num_ = 128
Detailed Description
Definition at line 40 of file lsh.hpp.
Constructor & Destructor Documentation
jubatus::core::recommender::lsh::lsh (uint64_t hash_num) explicit
Definition at line 44 of file lsh.cpp.
References initialize_model(), and JUBATUS_EXCEPTION.
     : hash_num_(hash_num) {
   if (!(1 <= hash_num)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("1 <= hash_num"));
   }
   initialize_model();
 }
jubatus::core::recommender::lsh::lsh (const config & config) explicit
Definition at line 53 of file lsh.cpp.
References jubatus::core::recommender::lsh::config::hash_num, initialize_model(), and JUBATUS_EXCEPTION.
     : hash_num_(config.hash_num) {
   if (!(1 <= config.hash_num)) {
     throw JUBATUS_EXCEPTION(
         common::invalid_parameter("1 <= hash_num"));
   }
   initialize_model();
 }
jubatus::core::recommender::lsh::lsh ()
Definition at line 64 of file lsh.cpp.
References initialize_model().
     : hash_num_(DEFAULT_HASH_NUM) {
   initialize_model();
 }
jubatus::core::recommender::lsh::~lsh ()
Definition at line 69 of file lsh.cpp.
           {
 }
Member Function Documentation
void jubatus::core::recommender::lsh::calc_lsh_values (const common::sfv_t & sfv, storage::bit_vector & bv) const private
Definition at line 108 of file lsh.cpp.
References column2baseval_, generate_column_bases(), hash_num_, jubatus::core::recommender::prod_invert_and_vector(), and jubatus::core::recommender::set_bit_vector().
Referenced by similar_row(), and update_row().
{
   const_cast<lsh*>(this)->generate_column_bases(sfv);
   vector<float> lsh_vals;
   prod_invert_and_vector(column2baseval_, sfv, hash_num_, lsh_vals);
   set_bit_vector(lsh_vals, bv);
 }
void jubatus::core::recommender::lsh::clear () virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 96 of file lsh.cpp.
References jubatus::core::storage::sparse_matrix_storage::clear(), column2baseval_, mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::clustering::swap().
                 {
   orig_.clear();
   jubatus::util::data::unordered_map<std::string, std::vector<float> >()
     .swap(column2baseval_);
   mixable_storage_->get_model()->clear();
 }
void jubatus::core::recommender::lsh::clear_row (const std::string & id) virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 103 of file lsh.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::remove_row().
{
   orig_.remove_row(id);
   mixable_storage_->get_model()->remove_row(id);
 }
void jubatus::core::recommender::lsh::generate_column_base (const std::string & column) private
Definition at line 122 of file lsh.cpp.
References jubatus::core::common::hash_util::calc_string_hash(), column2baseval_, jubatus::core::recommender::generate_random_vector(), and hash_num_.
Referenced by generate_column_bases().
{
   if (column2baseval_.count(column) != 0) {
     return;
   }
   const uint32_t seed = common::hash_util::calc_string_hash(column);
   generate_random_vector(hash_num_, seed, column2baseval_[column]);
 }
void jubatus::core::recommender::lsh::generate_column_bases (const common::sfv_t & v) private
Definition at line 116 of file lsh.cpp.
References generate_column_base().
Referenced by calc_lsh_values(), and update_row().
{
   for (size_t i = 0; i < sfv.size(); ++i) {
     generate_column_base(sfv[i].first);
   }
 }
void jubatus::core::recommender::lsh::get_all_row_ids (std::vector< std::string > & ids) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 140 of file lsh.cpp.
References mixable_storage_.
{
   mixable_storage_->get_model()->get_all_row_ids(ids);
 }
framework::mixable * jubatus::core::recommender::lsh::get_mixable () const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 148 of file lsh.cpp.
References mixable_storage_.
{
   return mixable_storage_.get();
 }
void jubatus::core::recommender::lsh::initialize_model () private
Definition at line 152 of file lsh.cpp.
References mixable_storage_.
Referenced by lsh().
{
   typedef storage::mixable_bit_index_storage::model_ptr model_ptr;
   typedef storage::mixable_bit_index_storage storage_t;
   model_ptr p(new storage::bit_index_storage);
   mixable_storage_.reset(new storage_t(p));
 }
void jubatus::core::recommender::lsh::neighbor_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 86 of file lsh.cpp.
References similar_row().
{
   similar_row(query, ids, ret_num);
   for (size_t i = 0; i < ids.size(); ++i) {
     ids[i].second = 1 - ids[i].second;
   }
 }
void jubatus::core::recommender::lsh::pack (framework::packer & packer) const virtual
Implements jubatus::core::framework::model.
Definition at line 159 of file lsh.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::pack().
{
   packer.pack_array(2);
   orig_.pack(packer);
   mixable_storage_->get_model()->pack(packer);
 }
void jubatus::core::recommender::lsh::similar_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 72 of file lsh.cpp.
References calc_lsh_values(), and mixable_storage_.
Referenced by neighbor_row().
{
   ids.clear();
   if (ret_num == 0) {
     return;
   }
   bit_vector query_bv;
   calc_lsh_values(query, query_bv);
   mixable_storage_->get_model()->similar_row(query_bv, ids, ret_num);
 }
string jubatus::core::recommender::lsh::type () const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 144 of file lsh.cpp.
{
   return string("lsh");
 }
void jubatus::core::recommender::lsh::unpack (msgpack::object o) virtual
Implements jubatus::core::framework::model.
Definition at line 165 of file lsh.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::unpack().
{
   if (o.type != msgpack::type::ARRAY || o.via.array.size != 2) {
     throw msgpack::type_error();
   }
   orig_.unpack(o.via.array.ptr[0]);
   mixable_storage_->get_model()->unpack(o.via.array.ptr[1]);
 }
void jubatus::core::recommender::lsh::update_row (const std::string & id, const sfv_diff_t & diff) virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 130 of file lsh.cpp.
References calc_lsh_values(), generate_column_bases(), jubatus::core::storage::sparse_matrix_storage::get_row(), mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::set_row().
{
   generate_column_bases(diff);
   orig_.set_row(id, diff);
   common::sfv_t row;
   orig_.get_row(id, row);
   bit_vector bv;
   calc_lsh_values(row, bv);
   mixable_storage_->get_model()->set_row(id, bv);
 }
Member Data Documentation
jubatus::util::data::unordered_map<std::string, std::vector<float> > jubatus::core::recommender::lsh::column2baseval_ private
Definition at line 86 of file lsh.hpp.
Referenced by calc_lsh_values(), clear(), and generate_column_base().
const uint64_t jubatus::core::recommender::lsh::hash_num_ private
Definition at line 91 of file lsh.hpp.
Referenced by calc_lsh_values(), and generate_column_base().
jubatus::util::lang::shared_ptr<storage::mixable_bit_index_storage> jubatus::core::recommender::lsh::mixable_storage_ private
Definition at line 89 of file lsh.hpp.
Referenced by clear(), clear_row(), get_all_row_ids(), get_mixable(), initialize_model(), pack(), similar_row(), unpack(), and update_row().
The documentation for this class was generated from the following files:
jubatus/core/recommender/lsh.hpp
jubatus/core/recommender/lsh.cpp