jubatus_core: jubatus::core::burst::basic_window< Batch > Class Template Reference
jubatus::core::burst::basic_window< Batch > Class Template Reference
#include <input_window.hpp>
Public Types
typedef Batch batch_type
Public Member Functions
basic_window (double batch_interval=1)
basic_window (double start_pos, double batch_interval, int32_t batch_size)
bool contains (double pos) const
double get_all_interval () const
batch_type & get_batch_by_index (size_t i)
const batch_type & get_batch_by_index (size_t i) const
double get_batch_interval () const
int32_t get_batch_size () const
const std::vector< batch_type > & get_batches () const
double get_end_pos () const
int get_index (double pos) const
double get_start_pos () const
void swap (basic_window &x)
Protected Member Functions
int get_index_ (double pos) const
Protected Attributes
double batch_interval_
std::vector< batch_type > batches_
double start_pos_
Friends
void swap (basic_window &x, basic_window &y)
Detailed Description
template<class Batch>
class jubatus::core::burst::basic_window< Batch >
Definition at line 35 of file input_window.hpp.
Member Typedef Documentation
template<class Batch> typedef Batch jubatus::core::burst::basic_window< Batch >::batch_type
Definition at line 37 of file input_window.hpp.
Constructor & Destructor Documentation
template<class Batch> jubatus::core::burst::basic_window< Batch >::basic_window (double batch_interval = 1) inline explicit
Definition at line 39 of file input_window.hpp.
       : batches_(), start_pos_(0), batch_interval_(batch_interval) {
     if (!(batch_interval > 0)) {
       throw JUBATUS_EXCEPTION(common::invalid_parameter(
           "window: batch_interval should be > 0"));
     }
   }
template<class Batch> jubatus::core::burst::basic_window< Batch >::basic_window (double start_pos, double batch_interval, int32_t batch_size) inline
Definition at line 47 of file input_window.hpp.
       : batches_(), start_pos_(start_pos), batch_interval_(batch_interval) {
     if (!(batch_interval > 0)) {
       throw JUBATUS_EXCEPTION(common::invalid_parameter(
           "window: batch_interval should be > 0"));
     }
     if (!(batch_size >= 0)) {
       throw JUBATUS_EXCEPTION(common::invalid_parameter(
           "window: batch_size should be >= 0"));
     }
     batches_.resize(batch_size);
   }
Member Function Documentation
template<class Batch> bool jubatus::core::burst::basic_window< Batch >::contains (double pos) const inline
Definition at line 80 of file input_window.hpp.
Referenced by jubatus::core::burst::basic_window< batch_result >::get_index().
{
     return get_start_pos() <= pos && pos < get_end_pos();
   }
template<class Batch> double jubatus::core::burst::basic_window< Batch >::get_all_interval () const inline
Definition at line 83 of file input_window.hpp.
Referenced by jubatus::core::burst::basic_window< batch_result >::get_end_pos().
{
     return batch_interval_ * get_batch_size();
   }
template<class Batch> batch_type& jubatus::core::burst::basic_window< Batch >::get_batch_by_index (size_t i) inline
Definition at line 98 of file input_window.hpp.
Referenced by jubatus::core::burst::aggregator::impl_::make_new_window_().
{
     return batches_[i];
   }
template<class Batch> const batch_type& jubatus::core::burst::basic_window< Batch >::get_batch_by_index (size_t i) const inline
Definition at line 101 of file input_window.hpp.
{
     return batches_[i];
   }
template<class Batch> double jubatus::core::burst::basic_window< Batch >::get_batch_interval () const inline
Definition at line 90 of file input_window.hpp.
Referenced by jubatus::core::burst::basic_window< batch_result >::get_index_().
{
     return batch_interval_;
   }
template<class Batch> int32_t jubatus::core::burst::basic_window< Batch >::get_batch_size () const inline
Definition at line 87 of file input_window.hpp.
Referenced by jubatus::core::burst::burst_result::burst_result(), jubatus::core::burst::basic_window< batch_result >::get_all_interval(), jubatus::core::burst::basic_window< batch_result >::get_index(), and jubatus::core::burst::result_window::result_window().
{
     return batches_.size();
   }
template<class Batch> const std::vector<batch_type>& jubatus::core::burst::basic_window< Batch >::get_batches () const inline
Definition at line 94 of file input_window.hpp.
Referenced by jubatus::core::burst::burst_result::burst_result(), and jubatus::core::burst::result_window::result_window().
{
     return batches_;
   }
template<class Batch> double jubatus::core::burst::basic_window< Batch >::get_end_pos () const inline
Definition at line 77 of file input_window.hpp.
Referenced by jubatus::core::burst::basic_window< batch_result >::contains().
{
     return start_pos_ + get_all_interval();
   }
template<class Batch> int jubatus::core::burst::basic_window< Batch >::get_index (double pos) const inline
Definition at line 61 of file input_window.hpp.
{
     int n = get_batch_size();
     int i = get_index_(pos);
     if (i < 0 || n <= i) {
       JUBATUS_ASSERT(!contains(pos));
       return -1;
     }
     JUBATUS_ASSERT(contains(pos));
     return i;
   }
template<class Batch> int jubatus::core::burst::basic_window< Batch >::get_index_ (double pos) const inline protected
Definition at line 121 of file input_window.hpp.
Referenced by jubatus::core::burst::basic_window< batch_result >::get_index().
{
     return static_cast<int>(
         std::floor((pos - start_pos_) / get_batch_interval()));
   }
template<class Batch> double jubatus::core::burst::basic_window< Batch >::get_start_pos () const inline
Definition at line 74 of file input_window.hpp.
Referenced by jubatus::core::burst::burst_result::burst_result(), jubatus::core::burst::basic_window< batch_result >::contains(), and jubatus::core::burst::aggregator::impl_::make_new_window_().
{
     return start_pos_;
   }
template<class Batch> void jubatus::core::burst::basic_window< Batch >::swap (basic_window< Batch > & x) inline
Definition at line 105 of file input_window.hpp.
Referenced by jubatus::core::burst::basic_window< batch_result >::swap().
{
     using std::swap;
     swap(batches_, x.batches_);
     swap(start_pos_, x.start_pos_);
     swap(batch_interval_, x.batch_interval_);
   }
Friends And Related Function Documentation
template<class Batch> void swap (basic_window< Batch > & x, basic_window< Batch > & y) friend
Definition at line 111 of file input_window.hpp.
{
     x.swap(y);
   }
Member Data Documentation
template<class Batch> double jubatus::core::burst::basic_window< Batch >::batch_interval_ protected
Definition at line 118 of file input_window.hpp.
Referenced by jubatus::core::burst::basic_window< batch_result >::get_all_interval(), jubatus::core::burst::basic_window< batch_result >::get_batch_interval(), and jubatus::core::burst::basic_window< batch_result >::swap().
template<class Batch> std::vector<batch_type> jubatus::core::burst::basic_window< Batch >::batches_ protected
Definition at line 116 of file input_window.hpp.
Referenced by jubatus::core::burst::basic_window< batch_result >::basic_window(), jubatus::core::burst::basic_window< batch_result >::get_batch_by_index(), jubatus::core::burst::basic_window< batch_result >::get_batch_size(), jubatus::core::burst::basic_window< batch_result >::get_batches(), and jubatus::core::burst::basic_window< batch_result >::swap().
template<class Batch> double jubatus::core::burst::basic_window< Batch >::start_pos_ protected
Definition at line 117 of file input_window.hpp.
Referenced by jubatus::core::burst::basic_window< batch_result >::get_end_pos(), jubatus::core::burst::basic_window< batch_result >::get_start_pos(), and jubatus::core::burst::basic_window< batch_result >::swap().
The documentation for this class was generated from the following file:
jubatus/core/burst/input_window.hpp