jubatus_core: jubatus::core::regression::regression_base Class Reference
jubatus::core::regression::regression_base Class Reference abstract
#include <regression_base.hpp>
Public Member Functions
virtual void clear ()
float estimate (const common::sfv_t &fv) const
virtual void get_status (std::map< std::string, std::string > &status) const
storage_ptr get_storage ()
regression_base (storage_ptr storage)
virtual void train (const common::sfv_t &fv, const float value)=0
virtual ~regression_base ()
Protected Member Functions
void update (const common::sfv_t &fv, float coeff)
Protected Attributes
storage_ptr storage_
Detailed Description
Definition at line 35 of file regression_base.hpp.
Constructor & Destructor Documentation
jubatus::core::regression::regression_base::regression_base (storage_ptr storage) explicit
Definition at line 27 of file regression_base.cpp.
     : storage_(storage) {
 }
virtual jubatus::core::regression::regression_base::~regression_base () inline virtual
Definition at line 39 of file regression_base.hpp.
{
   }
Member Function Documentation
void jubatus::core::regression::regression_base::clear () virtual
Reimplemented in jubatus::core::regression::passive_aggressive.
Definition at line 41 of file regression_base.cpp.
References storage_.
Referenced by jubatus::core::regression::passive_aggressive::clear().
{
   storage_->clear();
 }
float jubatus::core::regression::regression_base::estimate (const common::sfv_t & fv) const
Definition at line 31 of file regression_base.cpp.
References storage_.
Referenced by jubatus::core::regression::passive_aggressive::train().
{
   storage::map_feature_val1_t ret;
   storage_->inp(fv, ret);
   return ret["+"];
 }
void jubatus::core::regression::regression_base::get_status (std::map< std::string, std::string > & status) const virtual
Definition at line 45 of file regression_base.cpp.
References storage_.
           {
   storage_->get_status(status);
   status["storage"] = storage_->type();
 }
storage_ptr jubatus::core::regression::regression_base::get_storage ()
Definition at line 51 of file regression_base.cpp.
References storage_.
{
   return storage_;
 }
virtual void jubatus::core::regression::regression_base::train (const common::sfv_t & fv, const float value) pure virtual
Implemented in jubatus::core::regression::passive_aggressive.
void jubatus::core::regression::regression_base::update (const common::sfv_t & fv, float coeff) protected
Definition at line 37 of file regression_base.cpp.
References storage_.
Referenced by jubatus::core::regression::passive_aggressive::train().
{
   storage_->bulk_update(fv, coeff, "+", "");
 }
Member Data Documentation
storage_ptr jubatus::core::regression::regression_base::storage_ protected
Definition at line 57 of file regression_base.hpp.
Referenced by clear(), estimate(), get_status(), get_storage(), and update().
The documentation for this class was generated from the following files:
jubatus/core/regression/regression_base.hpp
jubatus/core/regression/regression_base.cpp