jubatus_core: jubatus::core::clustering::kmeans_clustering_method Class Reference
jubatus::core::clustering::kmeans_clustering_method Class Reference
#include <kmeans_clustering_method.hpp>
Public Member Functions
void batch_update (wplist points)
wplist get_cluster (size_t cluster_id, const wplist &points) const
std::vector< wplist > get_clusters (const wplist &points) const
std::vector< common::sfv_t > get_k_center () const
common::sfv_t get_nearest_center (const common::sfv_t &point) const
int64_t get_nearest_center_index (const common::sfv_t &point) const
kmeans_clustering_method (size_t k)
void online_update (wplist points)
~kmeans_clustering_method ()
Public Member Functions inherited from jubatus::core::clustering::clustering_method
virtual ~clustering_method ()
Private Member Functions
void do_batch_update (wplist &points)
void initialize_centers (wplist &points)
Private Attributes
size_t k_
std::vector< common::sfv_t > kcenters_
Detailed Description
Definition at line 27 of file kmeans_clustering_method.hpp.
Constructor & Destructor Documentation
jubatus::core::clustering::kmeans_clustering_method::kmeans_clustering_method (size_t k) explicit
Definition at line 32 of file kmeans_clustering_method.cpp.
     : k_(k) {
 }
jubatus::core::clustering::kmeans_clustering_method::~kmeans_clustering_method ()
Definition at line 36 of file kmeans_clustering_method.cpp.
{
 }
Member Function Documentation
void jubatus::core::clustering::kmeans_clustering_method::batch_update (wplist points) virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 39 of file kmeans_clustering_method.cpp.
References do_batch_update(), initialize_centers(), and kcenters_.
{
   if (points.empty()) {
     kcenters_.clear();
     return;
   }
   initialize_centers(points);
   do_batch_update(points);
 }
void jubatus::core::clustering::kmeans_clustering_method::do_batch_update (wplist & points) private
Definition at line 66 of file kmeans_clustering_method.cpp.
References jubatus::core::clustering::dist(), k_, kcenters_, jubatus::core::clustering::min_dist(), jubatus::core::clustering::scalar_dot(), and jubatus::core::clustering::scalar_mul_and_add().
Referenced by batch_update().
{
   static jubatus::util::math::random::mtrand r;
   bool terminated = false;
   if (points.size() < k_) {
     return;
   }
   while (!terminated) {
     vector<common::sfv_t> kcenters_new(k_);
     vector<double> center_count(k_, 0);
     for (wplist::iterator it = points.begin(); it != points.end(); ++it) {
       pair<int64_t, double> m = min_dist((*it).data, kcenters_);
       scalar_mul_and_add(it->data, it->weight, kcenters_new[m.first]);
       center_count[m.first] += it->weight;
     }
     terminated = true;
     for (size_t i = 0; i < k_; ++i) {
       if (center_count[i] == 0) {
         kcenters_new[i] = kcenters_[i];
         continue;
       }
       kcenters_new[i] = scalar_dot(kcenters_new[i], 1.0 / center_count[i]);
       double d = dist(kcenters_new[i], kcenters_[i]);
       if (d > 1e-9) {
         terminated = false;
       }
     }
     kcenters_ = kcenters_new;
   }
 }
wplist jubatus::core::clustering::kmeans_clustering_method::get_cluster (size_t cluster_id, const wplist & points) const virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 113 of file kmeans_clustering_method.cpp.
References get_clusters(), and k_.
{
   if (cluster_id >= k_) {
     return wplist();
   }
   return get_clusters(points)[cluster_id];
 }
vector< wplist > jubatus::core::clustering::kmeans_clustering_method::get_clusters (const wplist & points) const virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 122 of file kmeans_clustering_method.cpp.
References k_, kcenters_, and jubatus::core::clustering::min_dist().
Referenced by get_cluster().
{
   vector<wplist> ret(k_);
   for (wplist::const_iterator it = points.begin(); it != points.end(); ++it) {
     pair<int64_t, double> m = min_dist(it->data, kcenters_);
     ret[m.first].push_back(*it);
   }
   return ret;
 }
vector< common::sfv_t > jubatus::core::clustering::kmeans_clustering_method::get_k_center () const virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 99 of file kmeans_clustering_method.cpp.
References kcenters_.
{
   return kcenters_;
 }
common::sfv_t jubatus::core::clustering::kmeans_clustering_method::get_nearest_center (const common::sfv_t & point) const virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 108 of file kmeans_clustering_method.cpp.
References get_nearest_center_index(), and kcenters_.
{
   return kcenters_[get_nearest_center_index(point)];
 }
int64_t jubatus::core::clustering::kmeans_clustering_method::get_nearest_center_index (const common::sfv_t & point) const virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 103 of file kmeans_clustering_method.cpp.
References kcenters_, and jubatus::core::clustering::min_dist().
Referenced by get_nearest_center().
{
   return min_dist(point, kcenters_).first;
 }
void jubatus::core::clustering::kmeans_clustering_method::initialize_centers (wplist & points) private
Definition at line 48 of file kmeans_clustering_method.cpp.
References k_, kcenters_, and jubatus::core::clustering::min_dist().
Referenced by batch_update().
{
   if (points.size() < k_) {
     return;
   }
   kcenters_.clear();
   kcenters_.push_back(points[0].data);
   vector<double> weights;
   while (kcenters_.size() < k_) {
     weights.clear();
     for (wplist::iterator it = points.begin(); it != points.end(); ++it) {
       pair<int64_t, double> m = min_dist((*it).data, kcenters_);
       weights.push_back(m.second * it->weight);
     }
     discrete_distribution d(weights.begin(), weights.end());
     kcenters_.push_back(points[d()].data);
   }
 }
void jubatus::core::clustering::kmeans_clustering_method::online_update (wplist points) virtual
Implements jubatus::core::clustering::clustering_method.
Definition at line 96 of file kmeans_clustering_method.cpp.
{
 }
Member Data Documentation
size_t jubatus::core::clustering::kmeans_clustering_method::k_ private
Definition at line 45 of file kmeans_clustering_method.hpp.
Referenced by do_batch_update(), get_cluster(), get_clusters(), and initialize_centers().
std::vector<common::sfv_t> jubatus::core::clustering::kmeans_clustering_method::kcenters_ private
Definition at line 44 of file kmeans_clustering_method.hpp.
Referenced by batch_update(), do_batch_update(), get_clusters(), get_k_center(), get_nearest_center(), get_nearest_center_index(), and initialize_centers().
The documentation for this class was generated from the following files:
jubatus/core/clustering/kmeans_clustering_method.hpp
jubatus/core/clustering/kmeans_clustering_method.cpp