jubatus_core: jubatus::core::recommender::inverted_index Class Reference
jubatus::core::recommender::inverted_index Class Reference
#include <inverted_index.hpp>
Public Member Functions
void clear ()
void clear_row (const std::string &id)
void get_all_row_ids (std::vector< std::string > &ids) const
framework::mixable * get_mixable () const
inverted_index ()
void neighbor_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
void pack (framework::packer &packer) const
void similar_row (const common::sfv_t &query, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
std::string type () const
void unpack (msgpack::object o)
void update_row (const std::string &id, const sfv_diff_t &diff)
~inverted_index ()
Public Member Functions inherited from jubatus::core::recommender::recommender_base
void complete_row (const std::string &id, common::sfv_t &ret) const
void complete_row (const common::sfv_t &query, common::sfv_t &ret) const
void decode_row (const std::string &id, common::sfv_t &ret) const
virtual const core::storage::recommender_storage_base * get_const_storage () const
virtual jubatus::util::lang::shared_ptr< const storage::column_table > get_const_table () const
virtual jubatus::util::lang::shared_ptr< storage::column_table > get_table ()
virtual jubatus::util::lang::shared_ptr< unlearner::unlearner_base > get_unlearner ()
virtual void neighbor_row (const std::string &id, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
recommender_base ()
virtual void similar_row (const std::string &id, std::vector< std::pair< std::string, float > > &ids, size_t ret_num) const
virtual ~recommender_base ()
Public Member Functions inherited from jubatus::core::framework::model
virtual ~model ()
Private Attributes
jubatus::util::lang::shared_ptr< storage::mixable_inverted_index_storage > mixable_storage_
Additional Inherited Members
Static Public Member Functions inherited from jubatus::core::recommender::recommender_base
static float calc_l2norm (const common::sfv_t &query)
static float calc_similality (common::sfv_t &q1, common::sfv_t &q2)
Protected Attributes inherited from jubatus::core::recommender::recommender_base
core::storage::sparse_matrix_storage orig_
Static Protected Attributes inherited from jubatus::core::recommender::recommender_base
static const uint64_t complete_row_similar_num_ = 128
Detailed Description
Definition at line 35 of file inverted_index.hpp.
Constructor & Destructor Documentation
jubatus::core::recommender::inverted_index::inverted_index ()
Definition at line 36 of file inverted_index.cpp.
References mixable_storage_.
     : mixable_storage_() {
   typedef storage::inverted_index_storage ii_storage;
   typedef storage::mixable_inverted_index_storage mii_storage;
   jubatus::util::lang::shared_ptr<ii_storage> p(new ii_storage);
   mixable_storage_.reset(new mii_storage(p));
 }
jubatus::core::recommender::inverted_index::~inverted_index ()
Definition at line 44 of file inverted_index.cpp.
{
 }
Member Function Documentation
void jubatus::core::recommender::inverted_index::clear () virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 68 of file inverted_index.cpp.
References jubatus::core::storage::sparse_matrix_storage::clear(), mixable_storage_, and jubatus::core::recommender::recommender_base::orig_.
{
   orig_.clear();
   mixable_storage_->get_model()->clear();
 }
void jubatus::core::recommender::inverted_index::clear_row (const std::string & id) virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 73 of file inverted_index.cpp.
References jubatus::core::storage::sparse_matrix_storage::get_row(), mixable_storage_, jubatus::core::recommender::recommender_base::orig_, jubatus::core::storage::inverted_index_storage::remove(), and jubatus::core::storage::sparse_matrix_storage::remove_row().
{
   vector<pair<string, float> > columns;
   orig_.get_row(id, columns);
   storage::inverted_index_storage& inv = *mixable_storage_->get_model();
   for (size_t i = 0; i < columns.size(); ++i) {
     inv.remove(columns[i].first, id);
   }
   orig_.remove_row(id);
 }
void jubatus::core::recommender::inverted_index::get_all_row_ids (std::vector< std::string > & ids) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 91 of file inverted_index.cpp.
References mixable_storage_.
{
   mixable_storage_->get_model()->get_all_column_ids(ids);  // inv.column = row
 }
framework::mixable * jubatus::core::recommender::inverted_index::get_mixable () const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 113 of file inverted_index.cpp.
References mixable_storage_.
{
   return mixable_storage_.get();
 }
void jubatus::core::recommender::inverted_index::neighbor_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 58 of file inverted_index.cpp.
References similar_row().
{
   similar_row(query, ids, ret_num);
   for (size_t i = 0; i < ids.size(); ++i) {
     ids[i].second = 1 - ids[i].second;
   }
 }
void jubatus::core::recommender::inverted_index::pack (framework::packer & packer) const virtual
Implements jubatus::core::framework::model.
Definition at line 99 of file inverted_index.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::pack().
{
   packer.pack_array(2);
   orig_.pack(packer);
   mixable_storage_->get_model()->pack(packer);
 }
void jubatus::core::recommender::inverted_index::similar_row (const common::sfv_t & query, std::vector< std::pair< std::string, float > > & ids, size_t ret_num) const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 47 of file inverted_index.cpp.
References mixable_storage_.
Referenced by neighbor_row().
{
   ids.clear();
   if (ret_num == 0) {
     return;
   }
   mixable_storage_->get_model()->calc_scores(query, ids, ret_num);
 }
string jubatus::core::recommender::inverted_index::type () const virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 95 of file inverted_index.cpp.
{
   return string("inverted_index");
 }
void jubatus::core::recommender::inverted_index::unpack (msgpack::object o) virtual
Implements jubatus::core::framework::model.
Definition at line 105 of file inverted_index.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, and jubatus::core::storage::sparse_matrix_storage::unpack().
{
   if (o.type != msgpack::type::ARRAY || o.via.array.size != 2) {
     throw msgpack::type_error();
   }
   orig_.unpack(o.via.array.ptr[0]);
   mixable_storage_->get_model()->unpack(o.via.array.ptr[1]);
 }
void jubatus::core::recommender::inverted_index::update_row (const std::string & id, const sfv_diff_t & diff) virtual
Implements jubatus::core::recommender::recommender_base.
Definition at line 83 of file inverted_index.cpp.
References mixable_storage_, jubatus::core::recommender::recommender_base::orig_, jubatus::core::storage::inverted_index_storage::set(), and jubatus::core::storage::sparse_matrix_storage::set_row().
{
   orig_.set_row(id, diff);
   storage::inverted_index_storage& inv = *mixable_storage_->get_model();
   for (size_t i = 0; i < diff.size(); ++i) {
     inv.set(diff[i].first, id, diff[i].second);
   }
 }
Member Data Documentation
jubatus::util::lang::shared_ptr<storage::mixable_inverted_index_storage> jubatus::core::recommender::inverted_index::mixable_storage_ private
Definition at line 61 of file inverted_index.hpp.
Referenced by clear(), clear_row(), get_all_row_ids(), get_mixable(), inverted_index(), pack(), similar_row(), unpack(), and update_row().
The documentation for this class was generated from the following files:
jubatus/core/recommender/inverted_index.hpp
jubatus/core/recommender/inverted_index.cpp