jubatus_core: jubatus::core::driver::anomaly Class Reference
jubatus::core::driver::anomaly Class Reference
#include <anomaly.hpp>
Public Member Functions
std::pair< std::string, float > add (const std::string &id, const fv_converter::datum &d)
anomaly (jubatus::util::lang::shared_ptr< core::anomaly::anomaly_base > anomaly_method, jubatus::util::lang::shared_ptr< fv_converter::datum_to_fv_converter > converter)
float calc_score (const fv_converter::datum &d) const
void clear ()
void clear_row (const std::string &id)
uint64_t find_max_int_id () const
std::vector< std::string > get_all_rows () const
jubatus::core::anomaly::anomaly_base * get_model () const
bool is_updatable () const
float overwrite (const std::string &id, const fv_converter::datum &d)
void pack (framework::packer &pk) const
void unpack (msgpack::object o)
float update (const std::string &id, const fv_converter::datum &d)
virtual ~anomaly ()
Public Member Functions inherited from jubatus::core::driver::driver_base
driver_base ()
virtual framework::mixable * get_mixable ()
std::vector< storage::version > get_versions () const
virtual ~driver_base ()
Private Attributes
jubatus::util::lang::shared_ptr< core::anomaly::anomaly_base > anomaly_
jubatus::util::lang::shared_ptr< fv_converter::datum_to_fv_converter > converter_
fv_converter::mixable_weight_manager wm_
Additional Inherited Members
Protected Member Functions inherited from jubatus::core::driver::driver_base
void register_mixable (framework::mixable *mixable)
Protected Attributes inherited from jubatus::core::driver::driver_base
mixable_holder holder_
Detailed Description
Definition at line 35 of file anomaly.hpp.
Constructor & Destructor Documentation
jubatus::core::driver::anomaly::anomaly (jubatus::util::lang::shared_ptr< core::anomaly::anomaly_base > anomaly_method, jubatus::util::lang::shared_ptr< fv_converter::datum_to_fv_converter > converter)
Definition at line 42 of file anomaly.cpp.
References anomaly_, converter_, jubatus::core::framework::linear_mixable_helper< Model, Diff >::get_model(), jubatus::core::driver::driver_base::register_mixable(), and wm_.
     : converter_(converter),
       anomaly_(anomaly_method),
       wm_(mixable_weight_manager::model_ptr(new weight_manager)) {
   vector<framework::mixable*> mixables = anomaly_->get_mixables();
   for (size_t i = 0; i < mixables.size(); i++) {
     register_mixable(mixables[i]);
   }
   register_mixable(&wm_);
   converter_->set_weight_manager(wm_.get_model());
 }
jubatus::core::driver::anomaly::~anomaly () virtual
Definition at line 57 of file anomaly.cpp.
                   {
 }
Member Function Documentation
pair< string, float > jubatus::core::driver::anomaly::add (const std::string & id, const fv_converter::datum & d)
Definition at line 68 of file anomaly.cpp.
References anomaly_, overwrite(), and update().
{
   if (anomaly_->is_updatable()) {
     return make_pair(id, this->update(id, d));
   } else {
     return make_pair(id, this->overwrite(id, d));
   }
 }
float jubatus::core::driver::anomaly::calc_score (const fv_converter::datum & d) const
Definition at line 99 of file anomaly.cpp.
References anomaly_, converter_, and jubatus::core::common::jsonconfig::v().
{
   common::sfv_t v;
   converter_->convert(d, v);
   return anomaly_->calc_anomaly_score(v);
 }
void jubatus::core::driver::anomaly::clear () virtual
Implements jubatus::core::driver::driver_base.
Definition at line 94 of file anomaly.cpp.
References anomaly_, and converter_.
                     {
   anomaly_->clear();
   converter_->clear_weights();
 }
void jubatus::core::driver::anomaly::clear_row (const std::string & id)
Definition at line 64 of file anomaly.cpp.
References anomaly_.
{
   anomaly_->clear_row(id);
 }
uint64_t jubatus::core::driver::anomaly::find_max_int_id () const
Definition at line 111 of file anomaly.cpp.
References anomaly_.
{
   return anomaly_->find_max_int_id();
 }
vector< string > jubatus::core::driver::anomaly::get_all_rows () const
Definition at line 105 of file anomaly.cpp.
References anomaly_.
{
   vector<string> ids;
   anomaly_->get_all_row_ids(ids);
   return ids;
 }
jubatus::core::anomaly::anomaly_base* jubatus::core::driver::anomaly::get_model () const inline
Definition at line 44 of file anomaly.hpp.
References anomaly_.
{
     return anomaly_.get();
   }
bool jubatus::core::driver::anomaly::is_updatable () const
Definition at line 60 of file anomaly.cpp.
References anomaly_.
{
   return anomaly_->is_updatable();
 }
float jubatus::core::driver::anomaly::overwrite (const std::string & id, const fv_converter::datum & d)
Definition at line 86 of file anomaly.cpp.
References anomaly_, converter_, and jubatus::core::common::jsonconfig::v().
Referenced by add().
{
   common::sfv_t v;
   converter_->convert_and_update_weight(d, v);
   anomaly_->set_row(id, v);
   return anomaly_->calc_anomaly_score(id);
 }
void jubatus::core::driver::anomaly::pack (framework::packer & pk) const virtual
Implements jubatus::core::driver::driver_base.
Definition at line 115 of file anomaly.cpp.
References anomaly_, jubatus::core::framework::linear_mixable_helper< Model, Diff >::get_model(), and wm_.
{
   pk.pack_array(2);
   anomaly_->pack(pk);
   wm_.get_model()->pack(pk);
 }
void jubatus::core::driver::anomaly::unpack (msgpack::object o) virtual
Implements jubatus::core::driver::driver_base.
Definition at line 121 of file anomaly.cpp.
References anomaly_, converter_, jubatus::core::framework::linear_mixable_helper< Model, Diff >::get_model(), and wm_.
{
   if (o.type != msgpack::type::ARRAY || o.via.array.size != 2) {
     throw msgpack::type_error();
   }
   // clear before load
   anomaly_->clear();
   converter_->clear_weights();
   anomaly_->unpack(o.via.array.ptr[0]);
   wm_.get_model()->unpack(o.via.array.ptr[1]);
 }
float jubatus::core::driver::anomaly::update (const std::string & id, const fv_converter::datum & d)
Definition at line 78 of file anomaly.cpp.
References anomaly_, converter_, and jubatus::core::common::jsonconfig::v().
Referenced by add().
{
   common::sfv_t v;
   converter_->convert_and_update_weight(d, v);
   anomaly_->update_row(id, v);
   return anomaly_->calc_anomaly_score(id);
 }
Member Data Documentation
jubatus::util::lang::shared_ptr<core::anomaly::anomaly_base> jubatus::core::driver::anomaly::anomaly_ private
Definition at line 66 of file anomaly.hpp.
Referenced by add(), anomaly(), calc_score(), clear(), clear_row(), find_max_int_id(), get_all_rows(), get_model(), is_updatable(), overwrite(), pack(), unpack(), and update().
jubatus::util::lang::shared_ptr<fv_converter::datum_to_fv_converter> jubatus::core::driver::anomaly::converter_ private
Definition at line 65 of file anomaly.hpp.
Referenced by anomaly(), calc_score(), clear(), overwrite(), unpack(), and update().
fv_converter::mixable_weight_manager jubatus::core::driver::anomaly::wm_ private
Definition at line 67 of file anomaly.hpp.
Referenced by anomaly(), pack(), and unpack().
The documentation for this class was generated from the following files:
jubatus/core/driver/anomaly.hpp
jubatus/core/driver/anomaly.cpp