jubatus_core: jubatus::core::burst::burst_result Class Reference
jubatus::core::burst::burst_result Class Reference
#include <burst_result.hpp>
Public Member Functions
burst_result ()
burst_result (const input_window &input, double scaling_param, double gamma, double costcut_threshold, const burst_result &prev_result, int max_reuse_batches)
burst_result (const result_window &src)
bool contains (double pos) const
double get_all_interval () const
const batch_result & get_batch_at (double pos) const
double get_batch_interval () const
int get_batch_size () const
const std::vector< batch_result > & get_batches () const
double get_end_pos () const
double get_start_pos () const
bool has_same_batch_interval (const burst_result &x) const
bool has_same_start_pos_to (double start_pos) const
bool has_start_pos_newer_than (double start_pos) const
bool has_start_pos_older_than (double start_pos) const
bool is_bursted_at (double pos) const
bool is_bursted_at_latest_batch () const
bool is_valid () const
bool mix (const burst_result &w)
void msgpack_pack (framework::packer &packer) const
void msgpack_unpack (msgpack::object o)
void swap (burst_result &x)
Static Public Attributes
static const double invalid_pos = -1
Private Attributes
jubatus::util::lang::shared_ptr< const result_window > p_
Friends
void swap (burst_result &x, burst_result &y)
Detailed Description
Definition at line 33 of file burst_result.hpp.
Constructor & Destructor Documentation
jubatus::core::burst::burst_result::burst_result ()
Definition at line 46 of file burst_result.cpp.
{
 }
jubatus::core::burst::burst_result::burst_result (const input_window & input, double scaling_param, double gamma, double costcut_threshold, const burst_result & prev_result, int max_reuse_batches)
Definition at line 49 of file burst_result.cpp.
References jubatus::core::burst::burst_detect(), jubatus::core::burst::basic_window< Batch >::get_batch_size(), jubatus::core::burst::basic_window< Batch >::get_batches(), jubatus::core::burst::get_intersection(), jubatus::core::burst::basic_window< Batch >::get_start_pos(), and p_.
{
   const std::vector<batch_input>& input_batches = input.get_batches();
   const size_t n = input.get_batch_size();
   const int max_reuse = (std::min)(max_reuse_batches, static_cast<int>(n));
   // make vectors for engine
   std::vector<uint32_t> d_vec, r_vec;
   std::vector<double> burst_weights;
   d_vec.reserve(n);
   r_vec.reserve(n);
   burst_weights.reserve(n);
   for (size_t i = 0; i < n; ++i) {
     d_vec.push_back(input_batches[i].d);
     r_vec.push_back(input_batches[i].r);
     burst_weights.push_back(-1);  // uncalculated
   }
   // reuse batch weights
   if (prev_result.p_) {
     const result_window& prev = *prev_result.p_;
     if (prev.get_start_pos() <= input.get_start_pos()) {
       const std::pair<int, int> intersection = get_intersection(prev, input);
       const std::vector<batch_result>& prev_results = prev.get_batches();
       for (int i = 0, j = intersection.first;
            i < max_reuse && j < intersection.second;
            ++i, ++j) {
         burst_weights[i] = prev_results[j].burst_weight;
       }
     }
   }
   // doit
   burst::burst_detect(d_vec, r_vec, burst_weights,
                       scaling_param, gamma, costcut_threshold);
   // store result
   p_.reset(new result_window(input, burst_weights));
 }
jubatus::core::burst::burst_result::burst_result (const result_window & src) explicit
Definition at line 94 of file burst_result.cpp.
     : p_(new result_window(src)) {
 }
Member Function Documentation
bool jubatus::core::burst::burst_result::contains (double pos) const
Definition at line 110 of file burst_result.cpp.
References p_.
{
   return p_ && p_->contains(pos);
 }
double jubatus::core::burst::burst_result::get_all_interval () const
Definition at line 120 of file burst_result.cpp.
References p_.
{
   return p_ ? p_->get_all_interval() : 0;
 }
const batch_result & jubatus::core::burst::burst_result::get_batch_at (double pos) const
Definition at line 168 of file burst_result.cpp.
References p_.
{
   int i = p_ ? p_->get_index(pos) : -1;
   if (i < 0) {
     throw std::out_of_range("burst_result: pos is out of range");
   }
   return p_->get_batches()[i];
 }
double jubatus::core::burst::burst_result::get_batch_interval () const
Definition at line 117 of file burst_result.cpp.
References p_.
{
   return p_ ? p_->get_batch_interval() : 1;
 }
int jubatus::core::burst::burst_result::get_batch_size () const
Definition at line 114 of file burst_result.cpp.
References p_.
Referenced by mix(), and jubatus::core::burst::result_storage::impl_::store().
{
   return p_ ? p_->get_batch_size() : 0;
 }
const std::vector< batch_result > & jubatus::core::burst::burst_result::get_batches () const
Definition at line 164 of file burst_result.cpp.
References jubatus::core::burst::empty_batch_results, and p_.
{
   return p_ ? p_->get_batches() : empty_batch_results;
 }
double jubatus::core::burst::burst_result::get_end_pos () const
Definition at line 107 of file burst_result.cpp.
References invalid_pos, and p_.
{
   return p_ ? p_->get_end_pos() : invalid_pos;
 }
double jubatus::core::burst::burst_result::get_start_pos () const
Definition at line 104 of file burst_result.cpp.
References invalid_pos, and p_.
Referenced by mix(), and jubatus::core::burst::result_storage::impl_::store().
{
   return p_ ? p_->get_start_pos() : invalid_pos;
 }
bool jubatus::core::burst::burst_result::has_same_batch_interval (const burst_result & x) const
Definition at line 154 of file burst_result.cpp.
References jubatus::core::burst::intersection_helper::has_batch_interval_equals_to(), and p_.
Referenced by mix().
{
   if (!p_ || !x.p_) {
     return false;
   }
   double interval_x = x.p_->get_batch_interval();
   return intersection_helper(*p_).has_batch_interval_equals_to(interval_x);
 }
bool jubatus::core::burst::burst_result::has_same_start_pos_to (double start_pos) const
Definition at line 146 of file burst_result.cpp.
References p_, and jubatus::core::burst::window_position_near().
Referenced by mix().
{
   if (!p_) {
     return false;
   }
   double pos0 = p_->get_start_pos();
   return window_position_near(pos0, pos, p_->get_batch_interval());
 }
bool jubatus::core::burst::burst_result::has_start_pos_newer_than (double start_pos) const
Definition at line 135 of file burst_result.cpp.
References p_, and jubatus::core::burst::window_position_near().
{
   if (!p_) {
     return false;
   }
   double pos0 = p_->get_start_pos();
   if (pos0 > pos) {
     return !window_position_near(pos0, pos, p_->get_batch_interval());
   } else {
     return false;
   }
 }
bool jubatus::core::burst::burst_result::has_start_pos_older_than (double start_pos) const
Definition at line 124 of file burst_result.cpp.
References p_, and jubatus::core::burst::window_position_near().
{
   if (!p_) {
     return false;
   }
   double pos0 = p_->get_start_pos();
   if (pos0 < pos) {
     return !window_position_near(pos0, pos, p_->get_batch_interval());
   } else {
     return false;
   }
 }
bool jubatus::core::burst::burst_result::is_bursted_at (double pos) const
Definition at line 176 of file burst_result.cpp.
References p_.
Referenced by jubatus::core::burst::burst::impl_::get_all_bursted_results_at().
{
   int i = p_ ? p_->get_index(pos) : -1;
   if (i < 0) {
     return false;
   }
   return p_->get_batches()[i].is_bursted();
 }
bool jubatus::core::burst::burst_result::is_bursted_at_latest_batch () const
Definition at line 184 of file burst_result.cpp.
References p_.
Referenced by jubatus::core::burst::burst::impl_::get_all_bursted_results().
{
   if (!p_) {
     return false;
   }
   const std::vector<batch_result>& batches = p_->get_batches();
   return !batches.empty() && batches.back().is_bursted();
 }
bool jubatus::core::burst::burst_result::is_valid () const
Definition at line 98 of file burst_result.cpp.
References p_.
{
   return p_.get() != NULL;
 }
bool jubatus::core::burst::burst_result::mix (const burst_result & w)
Definition at line 192 of file burst_result.cpp.
References get_batch_size(), get_start_pos(), has_same_batch_interval(), has_same_start_pos_to(), and p_.
{
   if (!has_same_start_pos_to(w.get_start_pos()) ||
       !has_same_batch_interval(w) ||
       get_batch_size() != w.get_batch_size()) {
     return false;
   }
   if (p_ != w.p_) {
     if (accumulate_d_vec(*this) < accumulate_d_vec(w)) {
       p_ = w.p_;
     }
   }
   return true;
 }
void jubatus::core::burst::burst_result::msgpack_pack (framework::packer & packer) const
Definition at line 208 of file burst_result.cpp.
References invalid_pos, and p_.
{
   if (!p_) {
     result_window r(invalid_pos);
     packer.pack(r);
   } else {
     packer.pack(*p_);
   }
 }
void jubatus::core::burst::burst_result::msgpack_unpack (msgpack::object o)
Definition at line 217 of file burst_result.cpp.
References p_.
{
   shared_ptr<result_window> unpacked(new result_window());
   unpacked->msgpack_unpack(o);
   p_ = unpacked;
 }
void jubatus::core::burst::burst_result::swap (burst_result & x) inline
Definition at line 48 of file burst_result.hpp.
References p_.
Referenced by jubatus::core::burst::aggregator::impl_::flush_results().
{
     p_.swap(x.p_);
   }
Friends And Related Function Documentation
void swap (burst_result & x, burst_result & y) friend
Definition at line 51 of file burst_result.hpp.
{
     x.swap(y);
   }
Member Data Documentation
const double jubatus::core::burst::burst_result::invalid_pos = -1 static
Definition at line 57 of file burst_result.hpp.
Referenced by get_end_pos(), get_start_pos(), and msgpack_pack().
jubatus::util::lang::shared_ptr<const result_window> jubatus::core::burst::burst_result::p_ private
Definition at line 87 of file burst_result.hpp.
Referenced by burst_result(), contains(), get_all_interval(), get_batch_at(), get_batch_interval(), get_batch_size(), get_batches(), get_end_pos(), get_start_pos(), has_same_batch_interval(), has_same_start_pos_to(), has_start_pos_newer_than(), has_start_pos_older_than(), is_bursted_at(), is_bursted_at_latest_batch(), is_valid(), mix(), msgpack_pack(), msgpack_unpack(), and swap().
The documentation for this class was generated from the following files:
jubatus/core/burst/burst_result.hpp
jubatus/core/burst/burst_result.cpp