jubatus_core: jubatus::core::storage::local_storage_mixture Class Reference
jubatus::core::storage::local_storage_mixture Class Reference
#include <local_storage_mixture.hpp>
Public Member Functions
void bulk_update (const common::sfv_t &sfv, float step_width, const std::string &inc_class, const std::string &dec_class)
void clear ()
bool delete_label (const std::string &label)
bool delete_label_nolock (const std::string &label)
void get (const std::string &feature, feature_val1_t &ret) const
void get2 (const std::string &feature, feature_val2_t &ret) const
void get2_nolock (const std::string &feature, feature_val2_t &ret) const
void get3 (const std::string &feature, feature_val3_t &ret) const
void get3_nolock (const std::string &feature, feature_val3_t &ret) const
void get_diff (diff_t &ret) const
std::vector< std::string > get_labels () const
util::concurrent::mutex & get_lock () const
void get_nolock (const std::string &feature, feature_val1_t &ret) const
void get_status (std::map< std::string, std::string > &status) const
version get_version () const
void inp (const common::sfv_t &sfv, map_feature_val1_t &ret) const
inner product
local_storage_mixture ()
MSGPACK_DEFINE (tbl_, class2id_, tbl_diff_, model_version_)
void pack (framework::packer &packer) const
void register_label (const std::string &label)
void set (const std::string &feature, const std::string &klass, const val1_t &w)
void set2 (const std::string &feature, const std::string &klass, const val2_t &w)
void set2_nolock (const std::string &feature, const std::string &klass, const val2_t &w)
void set3 (const std::string &feature, const std::string &klass, const val3_t &w)
void set3_nolock (const std::string &feature, const std::string &klass, const val3_t &w)
bool set_average_and_clear_diff (const diff_t &average)
bool set_label (const std::string &label)
void set_nolock (const std::string &feature, const std::string &klass, const val1_t &w)
std::string type () const
void unpack (msgpack::object o)
void update (const std::string &feature, const std::string &inc_class, const std::string &dec_class, const val1_t &v)
~local_storage_mixture ()
Public Member Functions inherited from jubatus::core::storage::storage_base
virtual ~storage_base ()
Public Member Functions inherited from jubatus::core::framework::model
virtual ~model ()
Private Member Functions
bool get_internal (const std::string &feature, id_feature_val3_t &ret) const
Private Attributes
common::key_manager class2id_
version model_version_
util::concurrent::mutex mutex_
id_features3_t tbl_
id_features3_t tbl_diff_
Detailed Description
Definition at line 33 of file local_storage_mixture.hpp.
Constructor & Destructor Documentation
jubatus::core::storage::local_storage_mixture::local_storage_mixture ()
Definition at line 51 of file local_storage_mixture.cpp.
{
 }
jubatus::core::storage::local_storage_mixture::~local_storage_mixture ()
Definition at line 54 of file local_storage_mixture.cpp.
{
 }
Member Function Documentation
void jubatus::core::storage::local_storage_mixture::bulk_update (const common::sfv_t & sfv, float step_width, const std::string & inc_class, const std::string & dec_class) virtual
Reimplemented from jubatus::core::storage::storage_base.
Definition at line 238 of file local_storage_mixture.cpp.
References class2id_, jubatus::core::common::key_manager::get_id(), and tbl_diff_.
{
   uint64_t inc_id = class2id_.get_id(inc_class);
   typedef common::sfv_t::const_iterator iter_t;
   if (dec_class != "") {
     uint64_t dec_id = class2id_.get_id(dec_class);
     for (iter_t it = sfv.begin(); it != sfv.end(); ++it) {
       float val = it->second * step_width;
       id_feature_val3_t& feature_row = tbl_diff_[it->first];
       feature_row[inc_id].v1 += val;
       feature_row[dec_id].v1 -= val;
     }
   } else {
     for (iter_t it = sfv.begin(); it != sfv.end(); ++it) {
       float val = it->second * step_width;
       id_feature_val3_t& feature_row = tbl_diff_[it->first];
       feature_row[inc_id].v1 += val;
     }
   }
 }
void jubatus::core::storage::local_storage_mixture::clear () virtual
Implements jubatus::core::storage::storage_base.
Definition at line 319 of file local_storage_mixture.cpp.
References class2id_, jubatus::core::common::key_manager::swap(), tbl_, and tbl_diff_.
{
   // Clear and minimize
   id_features3_t().swap(tbl_);
   common::key_manager().swap(class2id_);
   id_features3_t().swap(tbl_diff_);
 }
bool jubatus::core::storage::local_storage_mixture::delete_label (const std::string & label) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 303 of file local_storage_mixture.cpp.
References delete_label_nolock(), and mutex_.
{
   util::concurrent::scoped_lock lk(mutex_);
   return delete_label_nolock(label);
 }
bool jubatus::core::storage::local_storage_mixture::delete_label_nolock (const std::string & label) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 308 of file local_storage_mixture.cpp.
References class2id_, jubatus::core::common::key_manager::delete_key(), jubatus::core::common::key_manager::get_id_const(), jubatus::core::common::key_manager::NOTFOUND, tbl_, and tbl_diff_.
Referenced by delete_label().
{
   uint64_t delete_id = class2id_.get_id_const(label);
   if (delete_id == common::key_manager::NOTFOUND) {
     return false;
   }
   delete_label_from_weight(delete_id, tbl_);
   delete_label_from_weight(delete_id, tbl_diff_);
   class2id_.delete_key(label);
   return true;
 }
void jubatus::core::storage::local_storage_mixture::get (const std::string & feature, feature_val1_t & ret) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 81 of file local_storage_mixture.cpp.
References get_nolock(), and mutex_.
{
   util::concurrent::scoped_lock lk(mutex_);
   get_nolock(feature, ret);
 }
void jubatus::core::storage::local_storage_mixture::get2 (const std::string & feature, feature_val2_t & ret) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 99 of file local_storage_mixture.cpp.
References get2_nolock(), and mutex_.
{
   util::concurrent::scoped_lock lk(mutex_);
   get2_nolock(feature, ret);
 }
void jubatus::core::storage::local_storage_mixture::get2_nolock (const std::string & feature, feature_val2_t & ret) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 105 of file local_storage_mixture.cpp.
References class2id_, get_internal(), and jubatus::core::common::key_manager::get_key().
Referenced by get2().
{
   ret.clear();
   id_feature_val3_t m3;
   get_internal(feature, m3);
   for (id_feature_val3_t::const_iterator it = m3.begin(); it != m3.end();
       ++it) {
     ret.push_back(
         make_pair(class2id_.get_key(it->first),
                   val2_t(it->second.v1, it->second.v2)));
   }
 }
void jubatus::core::storage::local_storage_mixture::get3 (const std::string & feature, feature_val3_t & ret) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 119 of file local_storage_mixture.cpp.
References get3_nolock(), and mutex_.
{
   util::concurrent::scoped_lock lk(mutex_);
   get3_nolock(feature, ret);
 }
void jubatus::core::storage::local_storage_mixture::get3_nolock (const std::string & feature, feature_val3_t & ret) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 125 of file local_storage_mixture.cpp.
References class2id_, get_internal(), and jubatus::core::common::key_manager::get_key().
Referenced by get3().
{
   ret.clear();
   id_feature_val3_t m3;
   get_internal(feature, m3);
   for (id_feature_val3_t::const_iterator it = m3.begin(); it != m3.end();
       ++it) {
     ret.push_back(make_pair(class2id_.get_key(it->first), it->second));
   }
 }
void jubatus::core::storage::local_storage_mixture::get_diff (diff_t & ret) const virtual
Reimplemented from jubatus::core::storage::storage_base.
Definition at line 262 of file local_storage_mixture.cpp.
References class2id_, jubatus::core::storage::diff_t::diff, jubatus::core::storage::diff_t::expect_version, jubatus::core::common::key_manager::get_key(), model_version_, and tbl_diff_.
{
   ret.diff.clear();
   for (jubatus::util::data::unordered_map<string, id_feature_val3_t>::
       const_iterator it = tbl_diff_.begin(); it != tbl_diff_.end(); ++it) {
     id_feature_val3_t::const_iterator it2 = it->second.begin();
     feature_val3_t fv3;
     for (; it2 != it->second.end(); ++it2) {
       fv3.push_back(make_pair(class2id_.get_key(it2->first), it2->second));
     }
     ret.diff.push_back(make_pair(it->first, fv3));
   }
   ret.expect_version = model_version_;
 }
bool jubatus::core::storage::local_storage_mixture::get_internal (const std::string & feature, id_feature_val3_t & ret) const private
Definition at line 57 of file local_storage_mixture.cpp.
References tbl_, and tbl_diff_.
Referenced by get2_nolock(), get3_nolock(), get_nolock(), and inp().
{
   ret.clear();
   id_features3_t::const_iterator it = tbl_.find(feature);
   bool found = false;
   if (it != tbl_.end()) {
     ret = it->second;
     found = true;
   }
   id_features3_t::const_iterator it_diff = tbl_diff_.find(feature);
   if (it_diff != tbl_diff_.end()) {
     found = true;
     for (id_feature_val3_t::const_iterator it2 = it_diff->second.begin();
         it2 != it_diff->second.end(); ++it2) {
       val3_t& val3 = ret[it2->first];  // may create
       increase(val3, it2->second);
     }
   }
   return found;
 }
std::vector< std::string > jubatus::core::storage::local_storage_mixture::get_labels () const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 326 of file local_storage_mixture.cpp.
References class2id_, and jubatus::core::common::key_manager::get_all_id2key().
{
   return class2id_.get_all_id2key();
 }
util::concurrent::mutex& jubatus::core::storage::local_storage_mixture::get_lock () const inline virtual
Implements jubatus::core::storage::storage_base.
Definition at line 90 of file local_storage_mixture.hpp.
References mutex_.
{
     return mutex_;
   }
void jubatus::core::storage::local_storage_mixture::get_nolock (const std::string & feature, feature_val1_t & ret) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 87 of file local_storage_mixture.cpp.
References class2id_, get_internal(), and jubatus::core::common::key_manager::get_key().
Referenced by get().
{
   ret.clear();
   id_feature_val3_t m3;
   get_internal(feature, m3);
   for (id_feature_val3_t::const_iterator it = m3.begin(); it != m3.end();
       ++it) {
     ret.push_back(make_pair(class2id_.get_key(it->first), it->second.v1));
   }
 }
void jubatus::core::storage::local_storage_mixture::get_status (std::map< std::string, std::string > & status) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 218 of file local_storage_mixture.cpp.
References class2id_, jubatus::core::common::key_manager::size(), tbl_, and tbl_diff_.
{
   status["num_features"] =
     jubatus::util::lang::lexical_cast<std::string>(tbl_.size());
   status["num_classes"] = jubatus::util::lang::lexical_cast<std::string>(
       class2id_.size());
   status["diff_size"] =
     jubatus::util::lang::lexical_cast<std::string>(tbl_diff_.size());
 }
version jubatus::core::storage::local_storage_mixture::get_version () const inline virtual
Implements jubatus::core::storage::storage_base.
Definition at line 105 of file local_storage_mixture.hpp.
References model_version_.
{
     return model_version_;
   }
void jubatus::core::storage::local_storage_mixture::inp (const common::sfv_t & sfv, map_feature_val1_t & ret) const virtual
inner product
Implements jubatus::core::storage::storage_base.
Definition at line 137 of file local_storage_mixture.cpp.
References class2id_, jubatus::core::common::key_manager::get_all_id2key(), jubatus::core::common::key_manager::get_id_const(), get_internal(), and jubatus::core::common::key_manager::NOTFOUND.
{
   ret.clear();
   // Use uin64_t map instead of string map as hash function for string is slow
   jubatus::util::data::unordered_map<uint64_t, float> ret_id;
   for (common::sfv_t::const_iterator it = sfv.begin(); it != sfv.end(); ++it) {
     const string& feature = it->first;
     const float val = it->second;
     id_feature_val3_t m;
     get_internal(feature, m);
     for (id_feature_val3_t::const_iterator it3 = m.begin(); it3 != m.end();
         ++it3) {
       ret_id[it3->first] += it3->second.v1 * val;
     }
   }
   std::vector<std::string> labels = class2id_.get_all_id2key();
   for (size_t i = 0; i < labels.size(); ++i) {
     const std::string& label = labels[i];
     uint64_t id = class2id_.get_id_const(label);
     if (id == common::key_manager::NOTFOUND || ret_id.count(id) == 0) {
       ret[label] = 0.0;
     } else {
       ret[label] = ret_id[id];
     }
   }
 }
jubatus::core::storage::local_storage_mixture::MSGPACK_DEFINE (tbl_ , class2id_ , tbl_diff_ , model_version_)
void jubatus::core::storage::local_storage_mixture::pack (framework::packer & packer) const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 334 of file local_storage_mixture.cpp.
{
   packer.pack(*this);
 }
void jubatus::core::storage::local_storage_mixture::register_label (const std::string & label) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 298 of file local_storage_mixture.cpp.
References class2id_, and jubatus::core::common::key_manager::get_id().
{
   // get_id method creates an entry when the label doesn't exist
   class2id_.get_id(label);
 }
void jubatus::core::storage::local_storage_mixture::set (const std::string & feature, const std::string & klass, const val1_t & w) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 166 of file local_storage_mixture.cpp.
References mutex_, and set_nolock().
                      {
   util::concurrent::scoped_lock lk(mutex_);
   set_nolock(feature, klass, w);
 }
void jubatus::core::storage::local_storage_mixture::set2 (const std::string & feature, const std::string & klass, const val2_t & w) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 182 of file local_storage_mixture.cpp.
References mutex_, and set2_nolock().
                      {
   util::concurrent::scoped_lock lk(mutex_);
   set2_nolock(feature, klass, w);
 }
void jubatus::core::storage::local_storage_mixture::set2_nolock (const std::string & feature, const std::string & klass, const val2_t & w) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 189 of file local_storage_mixture.cpp.
References class2id_, jubatus::core::common::key_manager::get_id(), tbl_, tbl_diff_, jubatus::core::storage::val2_t::v1, jubatus::core::storage::val3_t::v1, jubatus::core::storage::val2_t::v2, and jubatus::core::storage::val3_t::v2.
Referenced by set2().
                      {
   uint64_t class_id = class2id_.get_id(klass);
   float w1_in_table = tbl_[feature][class_id].v1;
   float w2_in_table = tbl_[feature][class_id].v2;
   val3_t& triple = tbl_diff_[feature][class_id];
   triple.v1 = w.v1 - w1_in_table;
   triple.v2 = w.v2 - w2_in_table;
 }
void jubatus::core::storage::local_storage_mixture::set3 (const std::string & feature, const std::string & klass, const val3_t & w) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 202 of file local_storage_mixture.cpp.
References mutex_, and set3_nolock().
                      {
   util::concurrent::scoped_lock lk(mutex_);
   set3_nolock(feature, klass, w);
 }
void jubatus::core::storage::local_storage_mixture::set3_nolock (const std::string & feature, const std::string & klass, const val3_t & w) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 209 of file local_storage_mixture.cpp.
References class2id_, jubatus::core::common::key_manager::get_id(), tbl_, tbl_diff_, and jubatus::core::common::jsonconfig::v().
Referenced by set3().
                      {
   uint64_t class_id = class2id_.get_id(klass);
   val3_t v = tbl_[feature][class_id];
   tbl_diff_[feature][class_id] = w - v;
 }
bool jubatus::core::storage::local_storage_mixture::set_average_and_clear_diff (const diff_t & average) virtual
Reimplemented from jubatus::core::storage::storage_base.
Definition at line 276 of file local_storage_mixture.cpp.
References class2id_, jubatus::core::storage::diff_t::diff, jubatus::core::storage::diff_t::expect_version, jubatus::core::common::key_manager::get_id(), jubatus::core::storage::version::increment(), model_version_, tbl_, and tbl_diff_.
{
   if (average.expect_version == model_version_) {
     for (features3_t::const_iterator it = average.diff.begin();
          it != average.diff.end();
          ++it) {
       const feature_val3_t& avg = it->second;
       id_feature_val3_t& orig = tbl_[it->first];
       for (feature_val3_t::const_iterator it2 = avg.begin(); it2 != avg.end();
            ++it2) {
         val3_t& triple = orig[class2id_.get_id(it2->first)];  // may create
         increase(triple, it2->second);
       }
     }
     model_version_.increment();
     tbl_diff_.clear();
     return true;
   } else {
     return false;
   }
 }
bool jubatus::core::storage::local_storage_mixture::set_label (const std::string & label) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 330 of file local_storage_mixture.cpp.
References class2id_, and jubatus::core::common::key_manager::set_key().
{
   return class2id_.set_key(label);
 }
void jubatus::core::storage::local_storage_mixture::set_nolock (const std::string & feature, const std::string & klass, const val1_t & w) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 173 of file local_storage_mixture.cpp.
References class2id_, jubatus::core::common::key_manager::get_id(), tbl_, and tbl_diff_.
Referenced by set().
                      {
   uint64_t class_id = class2id_.get_id(klass);
   float w_in_table = tbl_[feature][class_id].v1;
   tbl_diff_[feature][class_id].v1 = w - w_in_table;
 }
std::string jubatus::core::storage::local_storage_mixture::type () const virtual
Implements jubatus::core::storage::storage_base.
Definition at line 342 of file local_storage_mixture.cpp.
{
   return "local_storage_mixture";
 }
void jubatus::core::storage::local_storage_mixture::unpack (msgpack::object o) virtual
Implements jubatus::core::storage::storage_base.
Definition at line 338 of file local_storage_mixture.cpp.
{
   o.convert(this);
 }
void jubatus::core::storage::local_storage_mixture::update (const std::string & feature, const std::string & inc_class, const std::string & dec_class, const val1_t & v) virtual
Reimplemented from jubatus::core::storage::storage_base.
Definition at line 228 of file local_storage_mixture.cpp.
References class2id_, jubatus::core::common::key_manager::get_id(), tbl_diff_, and jubatus::core::common::jsonconfig::v().
                      {
   id_feature_val3_t& feature_row = tbl_diff_[feature];
   feature_row[class2id_.get_id(inc_class)].v1 += v;
   feature_row[class2id_.get_id(dec_class)].v1 -= v;
 }
Member Data Documentation
common::key_manager jubatus::core::storage::local_storage_mixture::class2id_ private
Definition at line 118 of file local_storage_mixture.hpp.
Referenced by bulk_update(), clear(), delete_label_nolock(), get2_nolock(), get3_nolock(), get_diff(), get_labels(), get_nolock(), get_status(), inp(), register_label(), set2_nolock(), set3_nolock(), set_average_and_clear_diff(), set_label(), set_nolock(), and update().
version jubatus::core::storage::local_storage_mixture::model_version_ private
Definition at line 120 of file local_storage_mixture.hpp.
Referenced by get_diff(), get_version(), and set_average_and_clear_diff().
util::concurrent::mutex jubatus::core::storage::local_storage_mixture::mutex_ mutable private
Definition at line 116 of file local_storage_mixture.hpp.
Referenced by delete_label(), get(), get2(), get3(), get_lock(), set(), set2(), and set3().
id_features3_t jubatus::core::storage::local_storage_mixture::tbl_ private
Definition at line 117 of file local_storage_mixture.hpp.
Referenced by clear(), delete_label_nolock(), get_internal(), get_status(), set2_nolock(), set3_nolock(), set_average_and_clear_diff(), and set_nolock().
id_features3_t jubatus::core::storage::local_storage_mixture::tbl_diff_ private
Definition at line 119 of file local_storage_mixture.hpp.
Referenced by bulk_update(), clear(), delete_label_nolock(), get_diff(), get_internal(), get_status(), set2_nolock(), set3_nolock(), set_average_and_clear_diff(), set_nolock(), and update().
The documentation for this class was generated from the following files:
jubatus/core/storage/local_storage_mixture.hpp
jubatus/core/storage/local_storage_mixture.cpp