jubatus_core: jubatus::core::anomaly::anomaly_factory Class Reference
jubatus::core::anomaly::anomaly_factory Class Reference
#include <anomaly_factory.hpp>
Static Public Member Functions
static jubatus::util::lang::shared_ptr< anomaly_base > create_anomaly (const std::string &name, const common::jsonconfig::config &param, const std::string &id)
Detailed Description
Definition at line 38 of file anomaly_factory.hpp.
Member Function Documentation
shared_ptr< anomaly_base > jubatus::core::anomaly::anomaly_factory::create_anomaly (const std::string & name, const common::jsonconfig::config & param, const std::string & id) static
Definition at line 73 of file anomaly_factory.cpp.
References jubatus::core::nearest_neighbor::create_nearest_neighbor(), jubatus::core::recommender::recommender_factory::create_recommender(), jubatus::core::unlearner::create_unlearner(), JUBATUS_EXCEPTION, and unlearner.
                       {
   if (name == "lof") {
     lof_config conf = config_cast_check<lof_config>(param);
     return shared_ptr<anomaly_base>(new lof(
         conf,
         recommender::recommender_factory::create_recommender(
             conf.method,
             conf.parameter, id)));
   } else if (name == "light_lof") {
     light_lof_config conf = config_cast_check<light_lof_config>(param);
     jubatus::util::lang::shared_ptr<table::column_table> nearest_neighbor_table(
         new table::column_table);
     jubatus::util::lang::shared_ptr<nearest_neighbor::nearest_neighbor_base>
         nearest_neighbor_engine(nearest_neighbor::create_nearest_neighbor(
             conf.method, conf.parameter, nearest_neighbor_table, id));
     if (conf.unlearner) {
       if (!conf.unlearner_parameter) {
         throw JUBATUS_EXCEPTION(
             common::config_exception()
             << common::exception::error_message(
               "unlearner is set but unlearner_parameter is not found"));
       }
       jubatus::util::lang::shared_ptr<unlearner::unlearner_base> unlearner(
           unlearner::create_unlearner(
               *conf.unlearner,
               *conf.unlearner_parameter));
       return shared_ptr<anomaly_base>(
           new light_lof(conf, id, nearest_neighbor_engine, unlearner));
     }
     return jubatus::util::lang::shared_ptr<anomaly_base>(
         new light_lof(conf, id, nearest_neighbor_engine));
   } else {
     throw JUBATUS_EXCEPTION(common::unsupported_method(name));
   }
 };
The documentation for this class was generated from the following files:
jubatus/core/anomaly/anomaly_factory.hpp
jubatus/core/anomaly/anomaly_factory.cpp