jubatus_core: jubatus::core::driver::driver_base Class Reference
jubatus::core::driver::driver_base Class Reference abstract
#include <driver.hpp>
Classes
class mixable_holder
Public Member Functions
virtual void clear ()=0
driver_base ()
virtual framework::mixable * get_mixable ()
std::vector< storage::version > get_versions () const
virtual void pack (framework::packer &packer) const =0
virtual void unpack (msgpack::object o)=0
virtual ~driver_base ()
Protected Member Functions
void register_mixable (framework::mixable *mixable)
Protected Attributes
mixable_holder holder_
Private Member Functions
driver_base (const driver_base &)
void operator= (const driver_base &)
Detailed Description
Definition at line 31 of file driver.hpp.
Constructor & Destructor Documentation
jubatus::core::driver::driver_base::driver_base () inline
Definition at line 33 of file driver.hpp.
 {}
virtual jubatus::core::driver::driver_base::~driver_base () inline virtual
Definition at line 34 of file driver.hpp.
 {}
jubatus::core::driver::driver_base::driver_base (const driver_base &) private
Member Function Documentation
virtual void jubatus::core::driver::driver_base::clear () pure virtual
Implemented in jubatus::core::driver::nearest_neighbor, jubatus::core::driver::graph, jubatus::core::driver::burst, jubatus::core::driver::clustering, jubatus::core::driver::anomaly, jubatus::core::driver::bandit, jubatus::core::driver::classifier, jubatus::core::driver::regression, jubatus::core::driver::stat, and jubatus::core::driver::recommender.
virtual framework::mixable* jubatus::core::driver::driver_base::get_mixable () inline virtual
Definition at line 35 of file driver.hpp.
References holder_.
{
     return &holder_;
   }
std::vector< storage::version > jubatus::core::driver::driver_base::get_versions () const
Definition at line 238 of file driver.cpp.
References jubatus::core::driver::driver_base::mixable_holder::get_versions(), and holder_.
{
   return holder_.get_versions();
 }
void jubatus::core::driver::driver_base::operator= (const driver_base &) private
virtual void jubatus::core::driver::driver_base::pack (framework::packer & packer) const pure virtual
Implemented in jubatus::core::driver::nearest_neighbor, jubatus::core::driver::graph, jubatus::core::driver::burst, jubatus::core::driver::anomaly, jubatus::core::driver::bandit, jubatus::core::driver::classifier, jubatus::core::driver::clustering, jubatus::core::driver::regression, jubatus::core::driver::stat, and jubatus::core::driver::recommender.
void jubatus::core::driver::driver_base::register_mixable (framework::mixable * mixable) protected
Definition at line 242 of file driver.cpp.
References holder_, and jubatus::core::driver::driver_base::mixable_holder::register_mixable().
Referenced by jubatus::core::driver::anomaly::anomaly(), jubatus::core::driver::bandit::bandit(), jubatus::core::driver::classifier::classifier(), jubatus::core::driver::graph::graph(), jubatus::core::driver::burst::init_(), jubatus::core::driver::recommender::recommender(), jubatus::core::driver::regression::regression(), and jubatus::core::driver::stat::stat().
{
   holder_.register_mixable(mixable);
 }
virtual void jubatus::core::driver::driver_base::unpack (msgpack::object o) pure virtual
Implemented in jubatus::core::driver::nearest_neighbor, jubatus::core::driver::graph, jubatus::core::driver::burst, jubatus::core::driver::anomaly, jubatus::core::driver::bandit, jubatus::core::driver::classifier, jubatus::core::driver::clustering, jubatus::core::driver::regression, jubatus::core::driver::stat, and jubatus::core::driver::recommender.
Member Data Documentation
mixable_holder jubatus::core::driver::driver_base::holder_ protected
Definition at line 69 of file driver.hpp.
Referenced by get_mixable(), get_versions(), jubatus::core::driver::burst::init_(), and register_mixable().
The documentation for this class was generated from the following files:
jubatus/core/driver/driver.hpp
jubatus/core/driver/driver.cpp