jubatus_core: jubatus::core::framework::linear_function_mixer Class Reference
jubatus::core::framework::linear_function_mixer Class Reference
#include <linear_function_mixer.hpp>
Public Types
typedef jubatus::util::lang::shared_ptr< model_type > model_ptr
typedef storage::storage_base model_type
Public Member Functions
diff_object convert_diff_object (const msgpack::object &) const
void get_diff (diffv &) const
void get_diff (packer &) const
model_ptr get_model () const
jubatus::util::lang::shared_ptr< unlearner::unlearner_base > get_unlearner () const
linear_function_mixer (model_ptr model)
void mix (const diffv &lhs, diffv &mixed) const
void mix (const msgpack::object &obj, diff_object) const
bool put_diff (const diffv &v)
bool put_diff (const diff_object &obj)
void set_label_unlearner (jubatus::util::lang::shared_ptr< unlearner::unlearner_base > label_unlearner)
Public Member Functions inherited from jubatus::core::framework::linear_mixable
linear_mixable ()
virtual ~linear_mixable ()
Public Member Functions inherited from jubatus::core::framework::mixable
virtual storage::version get_version () const
mixable ()
mixable (const std::string &name)
virtual std::set< std::string > mixables () const
virtual ~mixable ()
Private Attributes
jubatus::util::lang::shared_ptr< unlearner::unlearner_base > label_unlearner_
model_ptr model_
Additional Inherited Members
Protected Attributes inherited from jubatus::core::framework::mixable
std::set< std::string > mixables_
Detailed Description
Definition at line 33 of file linear_function_mixer.hpp.
Member Typedef Documentation
typedef jubatus::util::lang::shared_ptr<model_type> jubatus::core::framework::linear_function_mixer::model_ptr
Definition at line 36 of file linear_function_mixer.hpp.
typedef storage::storage_base jubatus::core::framework::linear_function_mixer::model_type
Definition at line 35 of file linear_function_mixer.hpp.
Constructor & Destructor Documentation
jubatus::core::framework::linear_function_mixer::linear_function_mixer (model_ptr model) inline explicit
Definition at line 38 of file linear_function_mixer.hpp.
References JUBATUS_EXCEPTION.
     : model_(model) {
     if (!model) {
       throw JUBATUS_EXCEPTION(common::config_not_set());
     }
   }
Member Function Documentation
diff_object jubatus::core::framework::linear_function_mixer::convert_diff_object (const msgpack::object & obj) const virtual
Implements jubatus::core::framework::linear_mixable.
Definition at line 123 of file linear_function_mixer.cpp.
{
   internal_diff_object* diff = new internal_diff_object;
   diff_object diff_obj(diff);
   obj.convert(&diff->diff_);
   return diff_obj;
 }
void jubatus::core::framework::linear_function_mixer::get_diff (diffv & diff) const
Definition at line 82 of file linear_function_mixer.cpp.
References jubatus::core::framework::diffv::count, get_model(), and jubatus::core::framework::diffv::v.
Referenced by get_diff().
{
   diff.count = 1;  // TODO(kuenishi) mixer_->get_count();
   get_model()->get_diff(diff.v);
 }
void jubatus::core::framework::linear_function_mixer::get_diff (packer & pk) const virtual
Implements jubatus::core::framework::linear_mixable.
Definition at line 145 of file linear_function_mixer.cpp.
References get_diff().
{
   diffv diff;
   get_diff(diff);
   pk.pack(diff);
 }
model_ptr jubatus::core::framework::linear_function_mixer::get_model () const inline
Definition at line 51 of file linear_function_mixer.hpp.
References model_.
Referenced by get_diff(), and put_diff().
{
     return model_;
   }
jubatus::util::lang::shared_ptr<unlearner::unlearner_base> jubatus::core::framework::linear_function_mixer::get_unlearner () const inline
Definition at line 66 of file linear_function_mixer.hpp.
References label_unlearner_.
{
     return label_unlearner_;
   }
void jubatus::core::framework::linear_function_mixer::mix (const diffv & lhs, diffv & mixed) const
Definition at line 67 of file linear_function_mixer.cpp.
References jubatus::core::storage::detail::binop(), jubatus::core::framework::diffv::count, jubatus::core::storage::diff_t::diff, jubatus::core::storage::diff_t::expect_version, and jubatus::core::framework::diffv::v.
Referenced by mix().
{
   if (lhs.v.expect_version == mixed.v.expect_version) {
     features3_t l(lhs.v.diff);
     const features3_t& r(mixed.v.diff);
     storage::detail::binop(
         l,
         r,
         bind(mix_feature, lhs.count, mixed.count, _1, _2));
     mixed.v.diff.swap(l);
     mixed.count = lhs.count + mixed.count;
   } else if (lhs.v.expect_version > mixed.v.expect_version) {
     mixed = lhs;
   }
 }
void jubatus::core::framework::linear_function_mixer::mix (const msgpack::object & obj, diff_object ptr) const virtual
Implements jubatus::core::framework::linear_mixable.
Definition at line 131 of file linear_function_mixer.cpp.
References JUBATUS_EXCEPTION, and mix().
{
   diffv diff;
   internal_diff_object* diff_obj =
     dynamic_cast<internal_diff_object*>(ptr.get());
   if (!diff_obj) {
     throw JUBATUS_EXCEPTION(
         core::common::exception::runtime_error("bad diff_object"));
   }
   obj.convert(&diff);
   mix(diff, diff_obj->diff_);
 }
bool jubatus::core::framework::linear_function_mixer::put_diff (const diffv & v)
Definition at line 87 of file linear_function_mixer.cpp.
References jubatus::core::storage::diff_t::diff, jubatus::core::storage::diff_t::expect_version, get_model(), label_unlearner_, jubatus::core::clustering::swap(), and jubatus::core::framework::diffv::v.
Referenced by put_diff().
{
   if (label_unlearner_) {
     for (size_t i = 0; i < v.v.diff.size(); ++i) {
       const feature_val3_t& classes = v.v.diff[i].second;
       for (size_t j = 0; j < classes.size(); ++j) {
         // ignore error returned by touch
         label_unlearner_->touch(classes[j].first);
       }
     }
     features3_t parameters(v.v.diff.size());
     for (size_t i = 0; i < v.v.diff.size(); ++i) {
       parameters[i].first = v.v.diff[i].first;
       // Copy weights of classes except unlearned classes.
       const feature_val3_t& source_classes = v.v.diff[i].second;
       feature_val3_t& target_classes = parameters[i].second;
       target_classes.reserve(source_classes.size());
       for (size_t j = 0; j < source_classes.size(); ++j) {
         if (label_unlearner_->exists_in_memory(source_classes[j].first)) {
           target_classes.push_back(source_classes[j]);
         }
       }
     }
     storage::diff_t unlearned_diff;
     std::swap(unlearned_diff.diff, parameters);
     unlearned_diff.expect_version = v.v.expect_version;
     return get_model()->set_average_and_clear_diff(unlearned_diff);
   } else {
     return get_model()->set_average_and_clear_diff(v.v);
   }
 }
bool jubatus::core::framework::linear_function_mixer::put_diff (const diff_object & obj) virtual
Implements jubatus::core::framework::linear_mixable.
Definition at line 151 of file linear_function_mixer.cpp.
References JUBATUS_EXCEPTION, and put_diff().
{
   internal_diff_object* diff_obj =
     dynamic_cast<internal_diff_object*>(ptr.get());
   if (!diff_obj) {
     throw JUBATUS_EXCEPTION(
         core::common::exception::runtime_error("bad diff_object"));
   }
   return put_diff(diff_obj->diff_);
 }
void jubatus::core::framework::linear_function_mixer::set_label_unlearner (jubatus::util::lang::shared_ptr< unlearner::unlearner_base > label_unlearner) inline
Definition at line 45 of file linear_function_mixer.hpp.
References label_unlearner_.
Referenced by jubatus::core::classifier::linear_classifier::set_label_unlearner().
{
     label_unlearner_ = label_unlearner;
   }
Member Data Documentation
jubatus::util::lang::shared_ptr<unlearner::unlearner_base> jubatus::core::framework::linear_function_mixer::label_unlearner_ private
Definition at line 72 of file linear_function_mixer.hpp.
Referenced by get_unlearner(), put_diff(), and set_label_unlearner().
model_ptr jubatus::core::framework::linear_function_mixer::model_ private
Definition at line 71 of file linear_function_mixer.hpp.
Referenced by get_model().
The documentation for this class was generated from the following files:
jubatus/core/framework/linear_function_mixer.hpp
jubatus/core/framework/linear_function_mixer.cpp