jubatus_core: jubatus/core/driver/test_util.hpp File Reference
test_util.hpp File Reference
#include <string>
#include <sstream>
#include <vector>
#include "jubatus/util/math/random.h"
#include "../fv_converter/converter_config.hpp"
#include "../fv_converter/datum_to_fv_converter.hpp"
#include "../fv_converter/datum.hpp"
#include "../framework/mixable.hpp"
Functions
jubatus::core::fv_converter::datum generate_random_datum (jubatus::util::math::random::mtrand &rand, int datum_length)
std::string generate_random_string (jubatus::util::math::random::mtrand &rand, int length)
jubatus::util::lang::shared_ptr< jubatus::core::fv_converter::datum_to_fv_converter > make_fv_converter ()
jubatus::util::lang::shared_ptr< jubatus::core::fv_converter::datum_to_fv_converter > make_tf_idf_fv_converter ()
Function Documentation
jubatus::core::fv_converter::datum generate_random_datum (jubatus::util::math::random::mtrand & rand, int datum_length)
Definition at line 68 of file test_util.hpp.
References generate_random_string(), and jubatus::core::fv_converter::datum::string_values_.
                       {
   jubatus::core::fv_converter::datum d;
   std::string value = generate_random_string(rand, datum_length);
   d.string_values_.push_back(std::make_pair("key", value));
   return d;
 }
std::string generate_random_string (jubatus::util::math::random::mtrand & rand, int length)
Definition at line 56 of file test_util.hpp.
Referenced by generate_random_datum().
{
   static const std::string alphabets =
       "abcdefghijklmnopqrstuvwxyz"
       "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
   std::string ret(length, 'a');
   for (int i = 0; i < length; ++i) {
     ret[i] = alphabets[rand.next_int(alphabets.length())];
   }
   return ret;
 }
jubatus::util::lang::shared_ptr<jubatus::core::fv_converter::datum_to_fv_converter> make_fv_converter ()
Definition at line 32 of file test_util.hpp.
References jubatus::core::fv_converter::string_rule::global_weight, jubatus::core::fv_converter::initialize_converter(), jubatus::core::fv_converter::string_rule::key, jubatus::core::fv_converter::num_rule::key, jubatus::core::fv_converter::converter_config::num_rules, jubatus::core::fv_converter::string_rule::sample_weight, jubatus::core::fv_converter::converter_config::string_rules, jubatus::core::fv_converter::string_rule::type, and jubatus::core::fv_converter::num_rule::type.
                       {
   jubatus::util::lang::shared_ptr<jubatus::core::fv_converter::datum_to_fv_converter>  // NOLINT
     converter(
         new jubatus::core::fv_converter::datum_to_fv_converter);
   jubatus::core::fv_converter::string_rule str_rule;
   str_rule.key = "*";
   str_rule.type = "str";
   str_rule.sample_weight = "bin";
   str_rule.global_weight = "bin";
   jubatus::core::fv_converter::num_rule num_rule;
   num_rule.key = "*";
   num_rule.type = "num";
   jubatus::core::fv_converter::converter_config c;
   c.string_rules = std::vector<jubatus::core::fv_converter::string_rule>();
   c.string_rules->push_back(str_rule);
   c.num_rules = std::vector<jubatus::core::fv_converter::num_rule>();
   c.num_rules->push_back(num_rule);
   jubatus::core::fv_converter::initialize_converter(c, *converter);
   return converter;
 }
jubatus::util::lang::shared_ptr<jubatus::core::fv_converter::datum_to_fv_converter> make_tf_idf_fv_converter ()
Definition at line 78 of file test_util.hpp.
References jubatus::core::fv_converter::string_rule::global_weight, jubatus::core::fv_converter::initialize_converter(), jubatus::core::fv_converter::string_rule::key, jubatus::core::fv_converter::string_rule::sample_weight, jubatus::core::fv_converter::converter_config::string_rules, and jubatus::core::fv_converter::string_rule::type.
{
   jubatus::util::lang::shared_ptr<jubatus::core::fv_converter::datum_to_fv_converter>  // NOLINT
     converter(
         new jubatus::core::fv_converter::datum_to_fv_converter);
   jubatus::core::fv_converter::string_rule str_rule;
   str_rule.key = "*";
   str_rule.type = "space";
   str_rule.sample_weight = "tf";
   str_rule.global_weight = "idf";
   jubatus::core::fv_converter::converter_config c;
   c.string_rules = std::vector<jubatus::core::fv_converter::string_rule>();
   c.string_rules->push_back(str_rule);
   jubatus::core::fv_converter::initialize_converter(c, *converter);
   return converter;
 }