jubatus_core: jubatus::core::common::exception Namespace Reference
jubatus::core::common::exception Namespace Reference
Namespaces
detail
Classes
class error_info
class error_info< struct error_splitter_, void >
class error_info_base
class exception_thrower_base
struct exception_thrower_binder_type
class exception_thrower_impl
class jubaexception
class jubatus_exception
class runtime_error
class unknown_exception
Typedefs
typedef error_info< struct error_api_func_, std::string > error_api_func
typedef error_info< struct error_at_file_, std::string > error_at_file
typedef error_info< struct error_at_func_, std::string > error_at_func
typedef error_info< struct error_at_line_, int > error_at_line
typedef error_info< struct error_errno_, int > error_errno
typedef error_info< struct error_file_name_, std::string > error_file_name
typedef std::vector< jubatus::util::lang::shared_ptr< error_info_base > > error_info_list_t
typedef error_info< struct error_message_, std::string > error_message
typedef error_info< struct error_splitter_, void > error_splitter
typedef jubatus::util::lang::shared_ptr< exception_thrower_base > exception_thrower_ptr
Functions
template<class Exception >
const Exception & add_info (const Exception &e, jubatus::util::lang::shared_ptr< error_info_base > info)
exception_thrower_ptr get_current_exception ()
template<class Exception , class Tag , class V >
const Exception & operator<< (const Exception &e, const error_info< Tag, V > &info)
template<class Exception >
const Exception & operator<< (const Exception &e, jubatus::util::lang::shared_ptr< error_info_base > info)
template<class Exception >
const Exception & operator<< (const Exception &e, const exception_thrower_binder_type &)
std::string to_string (const error_errno &info)
template<class Tag , class V >
std::string to_string (const error_info< Tag, V > &info)
Typedef Documentation
typedef error_info<struct error_api_func_, std::string> jubatus::core::common::exception::error_api_func
Definition at line 58 of file exception.hpp.
typedef error_info<struct error_at_file_, std::string> jubatus::core::common::exception::error_at_file
Definition at line 38 of file exception.hpp.
typedef error_info<struct error_at_func_, std::string> jubatus::core::common::exception::error_at_func
Definition at line 39 of file exception.hpp.
typedef error_info<struct error_at_line_, int> jubatus::core::common::exception::error_at_line
Definition at line 40 of file exception.hpp.
typedef error_info<struct error_errno_, int> jubatus::core::common::exception::error_errno
Definition at line 41 of file exception.hpp.
typedef error_info<struct error_file_name_, std::string> jubatus::core::common::exception::error_file_name
Definition at line 57 of file exception.hpp.
typedef std::vector<jubatus::util::lang::shared_ptr<error_info_base> > jubatus::core::common::exception::error_info_list_t
Definition at line 88 of file exception.hpp.
typedef error_info<struct error_message_, std::string> jubatus::core::common::exception::error_message
Definition at line 59 of file exception.hpp.
typedef error_info<struct error_splitter_, void> jubatus::core::common::exception::error_splitter
Definition at line 61 of file exception.hpp.
typedef jubatus::util::lang::shared_ptr<exception_thrower_base> jubatus::core::common::exception::exception_thrower_ptr
Definition at line 83 of file exception.hpp.
Function Documentation
template<class Exception > const Exception& jubatus::core::common::exception::add_info (const Exception & e, jubatus::util::lang::shared_ptr< error_info_base > info) inline
Definition at line 128 of file exception.hpp.
Referenced by operator<<().
{
   e.info_list_.push_back(info);
   return e;
 }
exception_thrower_ptr jubatus::core::common::exception::get_current_exception () inline
Definition at line 255 of file exception.hpp.
References jubatus::core::common::exception::detail::current_std_exception(), jubatus::core::common::exception::jubatus_exception::thrower(), and jubatus::core::common::exception::jubaexception< Exception >::thrower().
{
   exception_thrower_ptr ptr;
   try {
     throw;
   } catch (const std::bad_alloc& e) {  // exception
     ptr = detail::current_std_exception(e);
   } catch (const std::bad_cast& e) {  // exception
     ptr = detail::current_std_exception(e);
   } catch (const std::bad_exception& e) {  // exception
     ptr = detail::current_std_exception(e);
   } catch (const std::bad_typeid& e) {  // exception
     ptr = detail::current_std_exception(e);
   } catch (const std::domain_error& e) {  // logic_error
     ptr = detail::current_std_exception(e);
   } catch (const std::invalid_argument& e) {  // logic_error
     ptr = detail::current_std_exception(e);
   } catch (const std::length_error& e) {  // logic_error
     ptr = detail::current_std_exception(e);
   } catch (const std::out_of_range& e) {  // logic_error
     ptr = detail::current_std_exception(e);
   } catch (const std::logic_error& e) {  // exception
     ptr = detail::current_std_exception(e);
   } catch (const std::range_error& e) {  // runtime_error
     ptr = detail::current_std_exception(e);
   } catch (const std::overflow_error& e) {  // runtime_error
     ptr = detail::current_std_exception(e);
   } catch (const std::underflow_error& e) {  // runtime_error
     ptr = detail::current_std_exception(e);
   } catch (const std::ios_base::failure& e) {  // exception
     ptr = detail::current_std_exception(e);
   } catch (const std::runtime_error& e) {  // exception
     ptr = detail::current_std_exception(e);
   } catch (const jubatus_exception& e) {
     ptr = e.thrower();
   } catch (const std::exception& e) {
     ptr = detail::current_std_exception(e);
   } catch (...) {
     ptr = unknown_exception().thrower();
   }
   return ptr;
 }
template<class Exception , class Tag , class V > const Exception& jubatus::core::common::exception::operator<< (const Exception & e, const error_info< Tag, V > & info) inline
Definition at line 136 of file exception.hpp.
References add_info().
{
   return add_info(
       e,
       jubatus::util::lang::shared_ptr<error_info_base>(
           new error_info<Tag, V>(info)));
 }
template<class Exception > const Exception& jubatus::core::common::exception::operator<< (const Exception & e, jubatus::util::lang::shared_ptr< error_info_base > info) inline
Definition at line 146 of file exception.hpp.
References add_info().
{
   return add_info(e, info);
 }
template<class Exception > const Exception& jubatus::core::common::exception::operator<< (const Exception & e, const exception_thrower_binder_type &) inline
Definition at line 211 of file exception.hpp.
{
   e.bind_thrower(
       exception_thrower_ptr(new exception_thrower_impl<Exception>(e)));
   return e;
 }
std::string jubatus::core::common::exception::to_string (const error_errno & info) inline
Definition at line 42 of file exception.hpp.
References jubatus::core::common::exception::error_info< Tag, V >::value().
Referenced by jubatus::core::common::exception::error_info< Tag, V >::as_string().
{
   char buf[1024];
 #if defined(__linux__)
   std::string msg(strerror_r(info.value(), buf, sizeof(buf)));
 #elif defined(__sparcv8) || defined(__sparcv9) || defined(__APPLE__)
   strerror_r(info.value(), buf, sizeof(buf));
   std::string msg(buf);
 #else
 #error cpp_strerror_r
 #endif
   msg += " (" +
     jubatus::util::lang::lexical_cast<std::string>(info.value()) + ")";
   return msg;
 }
template<class Tag , class V > std::string jubatus::core::common::exception::to_string (const error_info< Tag, V > & info) inline
Definition at line 49 of file exception_info.hpp.
References jubatus::core::common::exception::error_info< Tag, V >::value().
{
   return jubatus::util::lang::lexical_cast<std::string, V>(info.value());
 }