jubatus_core: msgpack Namespace Reference
msgpack Namespace Reference
Classes
class packer
Functions
template<typename Stream , typename K , typename V , typename H , typename E , typename A >
packer< Stream > & operator<< (packer< Stream > &o, const jubatus::util::data::unordered_map< K, V, H, E, A > &v)
template<typename Stream >
packer< Stream > & operator<< (packer< Stream > &o, const jubatus::core::common::byte_buffer &b)
void operator<< (object::with_zone &o, const jubatus::core::common::byte_buffer &b)
void operator<< (object &o, const jubatus::core::common::byte_buffer &b)
template<typename K , typename V , typename H , typename E , typename A >
jubatus::util::data::unordered_map< K, V, H, E, A > operator>> (object o, jubatus::util::data::unordered_map< K, V, H, E, A > &v)
jubatus::core::common::byte_buffer & operator>> (object o, jubatus::core::common::byte_buffer &b)
Function Documentation
template<typename Stream , typename K , typename V , typename H , typename E , typename A > packer<Stream>& msgpack::operator<< (packer< Stream > & o, const jubatus::util::data::unordered_map< K, V, H, E, A > & v) inline
Definition at line 49 of file unordered_map.hpp.
{
   o.pack_map(v.size());
   typedef typename
     jubatus::util::data::unordered_map<K, V, H, E, A>::const_iterator
     iter_t;
   for (iter_t it = v.begin(); it != v.end(); ++it) {
     o.pack(it->first);
     o.pack(it->second);
   }
   return o;
 }
template<typename Stream > packer<Stream>& msgpack::operator<< (packer< Stream > & o, const jubatus::core::common::byte_buffer & b) inline
Definition at line 117 of file byte_buffer.hpp.
References jubatus::core::common::byte_buffer::ptr(), and jubatus::core::common::byte_buffer::size().
{
   o.pack_raw(b.size());
   o.pack_raw_body(b.ptr(), b.size());
   return o;
 }
void msgpack::operator<< (object::with_zone & o, const jubatus::core::common::byte_buffer & b) inline
Definition at line 125 of file byte_buffer.hpp.
References jubatus::core::common::byte_buffer::ptr(), and jubatus::core::common::byte_buffer::size().
{
   o.type = type::RAW;
   char* ptr = static_cast<char*>(o.zone->malloc(b.size()));
   o.via.raw.ptr = ptr;
   o.via.raw.size = static_cast<uint32_t>(b.size());
   std::memcpy(ptr, b.ptr(), b.size());
 }
void msgpack::operator<< (object & o, const jubatus::core::common::byte_buffer & b) inline
Definition at line 135 of file byte_buffer.hpp.
References jubatus::core::common::byte_buffer::ptr(), and jubatus::core::common::byte_buffer::size().
{
   o.type = type::RAW;
   o.via.raw.ptr = b.ptr();
   o.via.raw.size = static_cast<uint32_t>(b.size());
 }
template<typename K , typename V , typename H , typename E , typename A > jubatus::util::data::unordered_map<K, V, H, E, A> msgpack::operator>> (object o, jubatus::util::data::unordered_map< K, V, H, E, A > & v) inline
Definition at line 28 of file unordered_map.hpp.
References jubatus::core::common::jsonconfig::v().
{
   if (o.type != type::MAP) {
     throw type_error();
   }
   object_kv* const p_end = o.via.map.ptr + o.via.map.size;
   for (object_kv* p = o.via.map.ptr; p != p_end; ++p) {
     K key;
     p->key.convert(&key);
     p->val.convert(&v[key]);
   }
   return v;
 }
jubatus::core::common::byte_buffer& msgpack::operator>> (object o, jubatus::core::common::byte_buffer & b) inline
Definition at line 105 of file byte_buffer.hpp.
References jubatus::core::common::byte_buffer::assign().
{
   if (o.type != type::RAW) {
     throw type_error();
   }
   b.assign(o.via.raw.ptr, o.via.raw.size);
   return b;
 }