jubatus_core: jubatus::core::common::jsonconfig Namespace Reference
jubatus::core::common::jsonconfig Namespace Reference
Namespaces
detail
Classes
class cast_check_error
class config
class config_error
class json_config_iarchive_cast
class member_collector
class not_found
class out_of_range
class redundant_key
class type_error
Typedefs
typedef std::vector< jubatus::util::lang::shared_ptr< config_error > > config_error_list
Functions
template<class T >
T config_cast (const config &c)
template<class T >
T config_cast (const config &c, config_error_list &errors)
template<class T >
T config_cast_check (const config &c)
for (size_t i=0;i< size;++i)
GENERATE_CONFIG_SERIALIZE_FLOAT_DEF (float) GENERATE_CONFIG_SERIALIZE_FLOAT_DEF(double) template< typename T > inline void serialize(json_config_iarchive_cast &js
template<typename T >
void json_from_config (const config &conf, T &v)
template<typename T >
void json_from_config (const config &conf, T &v, json_config_iarchive_cast &js)
template<typename T >
void json_from_config (const config &conf, T &v, config_error_list *errors)
template<typename T >
void serialize (member_collector &mem, jubatus::util::data::serialization::named_value< T > &v)
template<typename T >
void serialize (json_config_iarchive_cast &js, T &v)
template<typename K , typename V >
void serialize (json_config_iarchive_cast &js, std::map< K, V > &m)
template<typename K , typename V >
void serialize (json_config_iarchive_cast &js, jubatus::util::data::unordered_map< K, V > &m)
template<typename T >
void serialize (json_config_iarchive_cast &js, jubatus::util::data::serialization::named_value< jubatus::util::data::optional< T > > &v)
template<typename T >
void serialize (json_config_iarchive_cast &js, jubatus::util::data::serialization::named_value< T > &v)
template<>
void serialize (json_config_iarchive_cast &js, jubatus::util::text::json::json &v)
template<>
void serialize (json_config_iarchive_cast &js, config &v)
vs swap (v)
std::vector< T > v (size)
Variables
std::vector< T > & vs
Typedef Documentation
typedef std::vector<jubatus::util::lang::shared_ptr<config_error> > jubatus::core::common::jsonconfig::config_error_list
Definition at line 37 of file cast.hpp.
Function Documentation
template<class T > T jubatus::core::common::jsonconfig::config_cast (const config & c)
Definition at line 296 of file cast.hpp.
References json_from_config().
Referenced by jubatus::core::common::jsonconfig::config::As().
{
   T value;
   json_from_config(c, value);
   return value;
 }
template<class T > T jubatus::core::common::jsonconfig::config_cast (const config & c, config_error_list & errors)
Definition at line 303 of file cast.hpp.
References serialize().
{
   T value;
   json_config_iarchive_cast cast(c, &errors);
   serialize(cast, value);
   return value;
 }
template<class T > T jubatus::core::common::jsonconfig::config_cast_check (const config & c)
Definition at line 311 of file cast.hpp.
References JUBATUS_EXCEPTION, and serialize().
Referenced by jubatus::core::nearest_neighbor::create_nearest_neighbor(), and jubatus::core::unlearner::create_unlearner().
{
   config_error_list errors;
   T value;
   json_config_iarchive_cast cast(c, &errors);
   serialize(cast, value);
   if (!errors.empty()) {
     throw JUBATUS_EXCEPTION(cast_check_error(errors));
   }
   return value;
 }
jubatus::core::common::jsonconfig::for ()
Definition at line 197 of file cast.hpp.
References json_from_config().
{
     json_from_config(js.get_config()[i], v[i], js.errors());
   }
jubatus::core::common::jsonconfig::GENERATE_CONFIG_SERIALIZE_FLOAT_DEF (float)
template<typename T > void jubatus::core::common::jsonconfig::json_from_config (const config & conf, T & v)
Definition at line 284 of file cast.hpp.
References serialize().
Referenced by config_cast(), for(), and serialize().
{
   json_config_iarchive_cast cast(conf);
   serialize(cast, v);
 }
template<typename T > void jubatus::core::common::jsonconfig::json_from_config (const config & conf, T & v, json_config_iarchive_cast & js)
template<typename T > void jubatus::core::common::jsonconfig::json_from_config (const config & conf, T & v, config_error_list * errors)
Definition at line 290 of file cast.hpp.
References serialize().
{
   json_config_iarchive_cast cast(conf, errors);
   serialize(cast, v);
 }
template<typename T > void jubatus::core::common::jsonconfig::serialize (member_collector & mem, jubatus::util::data::serialization::named_value< T > & v) inline
Definition at line 54 of file cast.hpp.
References jubatus::core::common::jsonconfig::member_collector::append().
Referenced by config_cast(), config_cast_check(), and json_from_config().
{
   mem.append(v.name);
 }
template<typename T > void jubatus::core::common::jsonconfig::serialize (json_config_iarchive_cast & js, T & v) inline
Definition at line 106 of file cast.hpp.
References jubatus::core::common::jsonconfig::json_config_iarchive_cast::get(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::get_config(), jubatus::core::common::jsonconfig::member_collector::get_members(), JUBATUS_EXCEPTION, jubatus::core::common::jsonconfig::config::path(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::push_error(), serialize(), and jubatus::core::common::jsonconfig::json_config_iarchive_cast::trace_error().
{
   if (js.get().type() == jubatus::util::text::json::json::Object) {
     member_collector collector;
     jubatus::util::data::serialization::access::serialize(collector, v);
     std::set<std::string> members(collector.get_members().begin(),
         collector.get_members().end());
     for (jubatus::util::text::json::json::const_iterator it = js.get().begin();
          it != js.get().end(); ++it) {
       const std::string& key = it->first;
       if (members.count(key) == 0) {
         redundant_key e(js.get_config().path(), key);
         if (js.trace_error()) {
           js.push_error(e);
         } else {
           throw JUBATUS_EXCEPTION(e);
         }
       }
     }
   }
   jubatus::util::data::serialization::access::serialize(js, v);
 }
template<typename K , typename V > void jubatus::core::common::jsonconfig::serialize (json_config_iarchive_cast & js, std::map< K, V > & m) inline
Definition at line 204 of file cast.hpp.
References jubatus::core::common::jsonconfig::config::begin(), jubatus::core::common::jsonconfig::detail::check_json_type(), jubatus::core::common::jsonconfig::config::end(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::errors(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::get_config(), and json_from_config().
{
   if (!detail::check_json_type(js, jubatus::util::text::json::json::Object)) {
     return;
   }
   std::map<K, V> tmp;
   typedef config::iterator iter_t;
   for (iter_t it = js.get_config().begin(), end = js.get_config().end();
       it != end; ++it) {
     V value;
     json_from_config(it.value(), value, js.errors());
     tmp[it.key()] = value;
   }
   tmp.swap(m);
 }
template<typename K , typename V > void jubatus::core::common::jsonconfig::serialize (json_config_iarchive_cast & js, jubatus::util::data::unordered_map< K, V > & m) inline
Definition at line 221 of file cast.hpp.
References jubatus::core::common::jsonconfig::config::begin(), jubatus::core::common::jsonconfig::detail::check_json_type(), jubatus::core::common::jsonconfig::config::end(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::errors(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::get_config(), and json_from_config().
{
   if (!detail::check_json_type(js, jubatus::util::text::json::json::Object)) {
     return;
   }
   jubatus::util::data::unordered_map<K, V> tmp;
   typedef config::iterator iter_t;
   for (iter_t it = js.get_config().begin(), end = js.get_config().end();
       it != end; ++it) {
     V value;
     json_from_config(it.value(), value, js.errors());
     tmp[it.key()] = value;
   }
   tmp.swap(m);
 }
template<typename T > void jubatus::core::common::jsonconfig::serialize (json_config_iarchive_cast & js, jubatus::util::data::serialization::named_value< jubatus::util::data::optional< T > > & v) inline
Definition at line 240 of file cast.hpp.
References jubatus::core::common::jsonconfig::config::contain(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::errors(), jubatus::core::common::jsonconfig::config::get(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::get_config(), and json_from_config().
{
   using jubatus::util::text::json::json;
   if (js.get_config().contain(v.name)
       && (js.get_config()[v.name].get().type() != json::Null)) {
     T value;
     json_from_config(js.get_config()[v.name], value, js.errors());
     v.v = value;
   } else {
     // optional can be null
     v.v = jubatus::util::data::optional<T>();
   }
 }
template<typename T > void jubatus::core::common::jsonconfig::serialize (json_config_iarchive_cast & js, jubatus::util::data::serialization::named_value< T > & v) inline
Definition at line 257 of file cast.hpp.
References jubatus::core::common::jsonconfig::config::contain(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::errors(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::get_config(), json_from_config(), JUBATUS_EXCEPTION, jubatus::core::common::jsonconfig::config::path(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::push_error(), and jubatus::core::common::jsonconfig::json_config_iarchive_cast::trace_error().
{
   if (js.get_config().contain(v.name)) {
     json_from_config(js.get_config()[v.name], v.v, js.errors());
   } else {
     not_found e(js.get_config().path(), v.name);
     if (js.trace_error()) {
       js.push_error(e);
     } else {
       throw JUBATUS_EXCEPTION(e);
     }
   }
 }
template<> void jubatus::core::common::jsonconfig::serialize (json_config_iarchive_cast & js, jubatus::util::text::json::json & v) inline
Definition at line 272 of file cast.hpp.
References jubatus::core::common::jsonconfig::json_config_iarchive_cast::get().
{
   v = js.get();
 }
template<> void jubatus::core::common::jsonconfig::serialize (json_config_iarchive_cast & js, config & v) inline
Definition at line 279 of file cast.hpp.
References jubatus::core::common::jsonconfig::json_config_iarchive_cast::get(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::get_config(), and jubatus::core::common::jsonconfig::config::path().
Referenced by serialize().
{
   v = config(js.get(), js.get_config().path());
 }
vs jubatus::core::common::jsonconfig::swap (v)
std::vector<T> jubatus::core::common::jsonconfig::v (size)
Referenced by jubatus::core::driver::anomaly::calc_score(), jubatus::core::driver::classifier::classify(), jubatus::core::driver::recommender::complete_row_from_datum(), jubatus::core::driver::recommender::complete_row_from_id(), jubatus::core::clustering::eigen_feature_mapper::convert(), jubatus::core::driver::recommender::decode_row(), jubatus::core::driver::regression::estimate(), jubatus::core::recommender::generate_random_vector(), jubatus::core::fv_converter::datum_to_fv_converter_impl::make_string_features(), jubatus::core::driver::nearest_neighbor::neighbor_row_from_datum(), msgpack::operator>>(), jubatus::core::driver::anomaly::overwrite(), jubatus::core::recommender::prod_invert_and_vector(), jubatus::core::storage::fixed_size_heap< T, Comp >::push(), jubatus::core::storage::inverted_index_storage::put_diff(), jubatus::core::storage::local_storage_mixture::set3(), jubatus::core::storage::sparse_matrix_storage::set_row(), jubatus::core::driver::nearest_neighbor::set_row(), jubatus::core::driver::nearest_neighbor::similar_row(), jubatus::core::driver::recommender::similar_row_from_datum(), jubatus::core::driver::classifier::train(), jubatus::core::driver::regression::train(), jubatus::core::driver::anomaly::update(), jubatus::core::storage::local_storage_mixture::update(), jubatus::core::storage::local_storage::update(), and jubatus::core::driver::recommender::update_row().
Variable Documentation
std::vector<T>& jubatus::core::common::jsonconfig::vs
Initial value:
{
  if (!detail::check_json_type(js, jubatus::util::text::json::json::Array)) {
    return;
  }
  size_t size = js.get_config().size()
Definition at line 189 of file cast.hpp.