jubatus_core: jubatus::core::nearest_neighbor Namespace Reference
jubatus::core::nearest_neighbor Namespace Reference
Classes
class bit_vector_nearest_neighbor_base
class euclid_lsh
class lsh
class minhash
class nearest_neighbor_base
class nearest_neighbor_exception
class unimplemented_exception
Functions
storage::bit_vector binarize (const std::vector< float > &proj)
bit_vector binarize (const vector< float > &proj)
bit_vector cosine_lsh (const common::sfv_t &sfv, uint32_t hash_num)
shared_ptr< nearest_neighbor_base > create_nearest_neighbor (const std::string &name, const common::jsonconfig::config &config, shared_ptr< storage::column_table > table, const std::string &id)
jubatus::util::lang::shared_ptr< nearest_neighbor_base > create_nearest_neighbor (const std::string &name, const common::jsonconfig::config &config, jubatus::util::lang::shared_ptr< storage::column_table > table, const std::string &id)
vector< float > random_projection (const common::sfv_t &sfv, uint32_t hash_num)
void ranking_hamming_bit_vectors (const bit_vector &query, const const_bit_vector_column &bvs, vector< pair< uint64_t, float > > &ret, uint64_t ret_num)
void ranking_hamming_bit_vectors (const storage::bit_vector &query, const storage::const_bit_vector_column &bvs, std::vector< std::pair< uint64_t, float > > &ret, uint64_t ret_num)
Function Documentation
storage::bit_vector jubatus::core::nearest_neighbor::binarize (const std::vector< float > & proj)
bit_vector jubatus::core::nearest_neighbor::binarize (const vector< float > & proj)
Definition at line 43 of file lsh_function.cpp.
References jubatus::core::storage::bit_vector_base< bit_base >::set_bit().
Referenced by cosine_lsh(), and jubatus::core::storage::lsh_index_storage::make_entry().
{
   bit_vector bv(proj.size());
   for (size_t i = 0; i < proj.size(); ++i) {
     if (proj[i] > 0) {
       bv.set_bit(i);
     }
   }
   return bv;
 }
storage::bit_vector jubatus::core::nearest_neighbor::cosine_lsh (const common::sfv_t & sfv, uint32_t hash_num)
Definition at line 53 of file lsh_function.cpp.
References binarize(), and random_projection().
Referenced by jubatus::core::nearest_neighbor::lsh::hash(), and jubatus::core::nearest_neighbor::euclid_lsh::set_row().
{
   return binarize(random_projection(sfv, hash_num));
 }
shared_ptr<nearest_neighbor_base> jubatus::core::nearest_neighbor::create_nearest_neighbor (const std::string & name, const common::jsonconfig::config & config, shared_ptr< storage::column_table > table, const std::string & id)
Definition at line 32 of file nearest_neighbor_factory.cpp.
References jubatus::core::common::jsonconfig::config_cast_check(), and JUBATUS_EXCEPTION.
Referenced by jubatus::core::anomaly::anomaly_factory::create_anomaly(), jubatus::core::classifier::classifier_factory::create_classifier(), and jubatus::core::recommender::recommender_factory::create_recommender().
{
   using common::jsonconfig::config_cast_check;
   if (name == "euclid_lsh") {
     return shared_ptr<nearest_neighbor_base>(
         new euclid_lsh(config_cast_check<euclid_lsh::config>(config),
                        table,
                        id));
   } else if (name == "lsh") {
     return shared_ptr<nearest_neighbor_base>(
         new lsh(config_cast_check<lsh::config>(config), table, id));
   } else if (name == "minhash") {
     return shared_ptr<nearest_neighbor_base>(
         new minhash(config_cast_check<minhash::config>(config), table, id));
   } else {
     throw JUBATUS_EXCEPTION(common::unsupported_method(name));
   }
 }
jubatus::util::lang::shared_ptr<nearest_neighbor_base> jubatus::core::nearest_neighbor::create_nearest_neighbor (const std::string & name, const common::jsonconfig::config & config, jubatus::util::lang::shared_ptr< storage::column_table > table, const std::string & id)
std::vector< float > jubatus::core::nearest_neighbor::random_projection (const common::sfv_t & sfv, uint32_t hash_num)
Definition at line 31 of file lsh_function.cpp.
References jubatus::core::common::hash_util::calc_string_hash().
Referenced by cosine_lsh().
{
   vector<float> proj(hash_num);
   for (size_t i = 0; i < sfv.size(); ++i) {
     const uint32_t seed = common::hash_util::calc_string_hash(sfv[i].first);
     jubatus::util::math::random::mtrand rnd(seed);
     for (uint32_t j = 0; j < hash_num; ++j) {
       proj[j] += sfv[i].second * rnd.next_gaussian();
     }
   }
   return proj;
 }
void jubatus::core::nearest_neighbor::ranking_hamming_bit_vectors (const bit_vector & query, const const_bit_vector_column & bvs, vector< pair< uint64_t, float > > & ret, uint64_t ret_num)
Definition at line 34 of file bit_vector_ranking.cpp.
References jubatus::core::clustering::dist(), jubatus::core::storage::fixed_size_heap< T, Comp >::get_sorted(), and jubatus::core::storage::fixed_size_heap< T, Comp >::push().
Referenced by jubatus::core::nearest_neighbor::bit_vector_nearest_neighbor_base::neighbor_row_from_hash().
                       {
   storage::fixed_size_heap<pair<uint32_t, uint64_t> > heap(ret_num);
   for (uint64_t i = 0; i < bvs.size(); ++i) {
     const size_t dist = query.calc_hamming_distance(bvs[i]);
     heap.push(make_pair(dist, i));
   }
   vector<pair<uint32_t, uint64_t> > sorted;
   heap.get_sorted(sorted);
   ret.clear();
   const float denom = query.bit_num();
   for (size_t i = 0; i < sorted.size(); ++i) {
     ret.push_back(make_pair(sorted[i].second, sorted[i].first / denom));
   }
 }
void jubatus::core::nearest_neighbor::ranking_hamming_bit_vectors (const storage::bit_vector & query, const storage::const_bit_vector_column & bvs, std::vector< std::pair< uint64_t, float > > & ret, uint64_t ret_num)