jubatus_core: jubatus::core::storage::detail Namespace Reference
jubatus::core::storage::detail Namespace Reference
Classes
class abstract_column
class abstract_column_base
struct bitcount_impl
struct bitcount_impl< T, 1 >
struct bitcount_impl< T, 2 >
struct bitcount_impl< T, 4 >
struct bitcount_impl< T, 8 >
Functions
template<class E , class F >
std::vector< std::pair< std::string, E > > & binop (std::vector< std::pair< std::string, E > > &lhs, std::vector< std::pair< std::string, E > > rhs, F f, E default_value=E())
int bitcount (unsigned bits)
int bitcount (unsigned long bits)
int bitcount (unsigned long long bits)
template<class T >
int bitcount (T)
template<class T >
int bitcount_dispatcher (T bits)
template<class E >
std::vector< std::pair< std::string, E > > & mult_scalar (std::vector< std::pair< std::string, E > > &lhs, double d)
Function Documentation
template<class E , class F > std::vector<std::pair<std::string, E> >& jubatus::core::storage::detail::binop (std::vector< std::pair< std::string, E > > & lhs, std::vector< std::pair< std::string, E > > rhs, F f, E default_value = E())
Definition at line 233 of file storage_type.hpp.
Referenced by jubatus::core::framework::linear_function_mixer::mix(), jubatus::core::storage::operator*=(), jubatus::core::storage::operator+=(), jubatus::core::storage::operator-=(), and jubatus::core::storage::operator/=().
{
   std::sort(lhs.begin(), lhs.end());
   std::sort(rhs.begin(), rhs.end());
   size_t li = 0;
   size_t lsize = lhs.size();
   for (size_t ri = 0; ri < rhs.size(); ++ri) {
     while (li < lsize && lhs[li].first < rhs[ri].first) {
       lhs[li].second = f(lhs[li].second, default_value);
       ++li;
     }
     if (li < lsize && lhs[li].first == rhs[ri].first) {
       lhs[li].second = f(lhs[li].second, rhs[ri].second);
       ++li;
     } else {
       lhs.push_back(make_pair(rhs[ri].first, f(default_value, rhs[ri].second)));
     }
   }
   while (li < lsize) {
     lhs[li].second = f(lhs[li].second, default_value);
     ++li;
   }
   return lhs;
 }
int jubatus::core::storage::detail::bitcount (unsigned bits) inline
Definition at line 102 of file bit_vector.hpp.
References bitcount_dispatcher().
Referenced by jubatus::core::storage::bit_vector_base< uint64_t >::bit_count(), and jubatus::core::storage::bit_vector_base< uint64_t >::calc_hamming_distance().
{
   return bitcount_dispatcher(bits);
 }
int jubatus::core::storage::detail::bitcount (unsigned long bits) inline
Definition at line 106 of file bit_vector.hpp.
References bitcount_dispatcher().
{
   return bitcount_dispatcher(bits);
 }
int jubatus::core::storage::detail::bitcount (unsigned long long bits) inline
Definition at line 110 of file bit_vector.hpp.
References bitcount_dispatcher().
{
   return bitcount_dispatcher(bits);
 }
template<class T > int jubatus::core::storage::detail::bitcount (T) inline
template<class T > int jubatus::core::storage::detail::bitcount_dispatcher (T bits) inline
Definition at line 94 of file bit_vector.hpp.
Referenced by bitcount().
{
 #ifdef __GNUG__
   return fast_bitcount(bits);
 #else
   return bitcount_impl<T, sizeof(T)>::call(bits);
 #endif
 }
template<class E > std::vector<std::pair<std::string, E> >& jubatus::core::storage::detail::mult_scalar (std::vector< std::pair< std::string, E > > & lhs, double d)
Definition at line 265 of file storage_type.hpp.
Referenced by jubatus::core::storage::operator*=(), and jubatus::core::storage::operator/=().
               {
   for (size_t i = 0; i < lhs.size(); ++i) {
     lhs[i].second = lhs[i].second * d;
   }
   return lhs;
 }