jubatus_core: jubatus::core::storage Namespace Reference
jubatus::core::storage Namespace Reference
Namespaces
detail
Classes
class argument_unmatch_exception
class array_range_exception
class bit_index_storage
struct bit_vector_base
class bit_vector_unmatch_exception
class column_table
class column_type
struct diff_t
class fixed_size_heap
class invalid_row_set
class inverted_index_storage
class length_unmatch_exception
class local_storage
class local_storage_mixture
struct lsh_entry
class lsh_index_storage
class lsh_probe_generator
class lsh_vector
struct owner
class recommender_storage_base
class row_deleter
class sparse_matrix_storage
class storage_base
class storage_exception
class storage_factory
class type_unmatch_exception
class typed_column
class typed_column< bit_vector >
struct val2_t
struct val3_t
class version
Typedefs
typedef jubatus::util::data::unordered_map< std::string, bit_vector > bit_table_t
typedef bit_vector_base< uint64_t > bit_vector
typedef typed_column< bit_vector > bit_vector_column
typedef const bit_vector_column const_bit_vector_column
typedef const typed_column< double > const_double_column
typedef const typed_column< float > const_float_column
typedef const typed_column< int16_t > const_int16_column
typedef const typed_column< int32_t > const_int32_column
typedef const typed_column< int64_t > const_int64_column
typedef const typed_column< int8_t > const_int8_column
typedef const typed_column< std::string > const_string_column
typedef const typed_column< uint16_t > const_uint16_column
typedef const typed_column< uint32_t > const_uint32_column
typedef const typed_column< uint64_t > const_uint64_column
typedef const typed_column< uint8_t > const_uint8_column
typedef typed_column< double > double_column
typedef std::vector< std::pair< std::string, val1_t > > feature_val1_t
typedef std::vector< std::pair< std::string, val2_t > > feature_val2_t
typedef std::vector< std::pair< std::string, val3_t > > feature_val3_t
typedef std::vector< std::pair< std::string, feature_val1_t > > features1_t
typedef std::vector< std::pair< std::string, feature_val2_t > > features2_t
typedef std::vector< std::pair< std::string, feature_val3_t > > features3_t
typedef typed_column< float > float_column
typedef fixed_size_heap< pair< uint64_t, string >, greater< pair< uint64_t, string > > > heap_type
typedef jubatus::util::data::unordered_map< uint64_t, val3_t > id_feature_val3_t
typedef jubatus::util::data::unordered_map< std::string, id_feature_val3_t > id_features3_t
typedef jubatus::util::data::unordered_map< uint64_t, float > imap_float_t
typedef typed_column< int16_t > int16_column
typedef typed_column< int32_t > int32_column
typedef typed_column< int64_t > int64_column
typedef typed_column< int8_t > int8_column
typedef jubatus::util::data::unordered_map< std::string, lsh_entry > lsh_master_table_t
typedef jubatus::util::data::unordered_map< uint64_t, std::vector< uint64_t > > lsh_table_t
typedef jubatus::util::data::unordered_map< std::string, val1_t > map_feature_val1_t
typedef jubatus::util::data::unordered_map< std::string, val3_t > map_feature_val3_t
typedef jubatus::util::data::unordered_map< std::string, map_feature_val3_t > map_features3_t
typedef jubatus::util::data::unordered_map< std::string, float > map_float_t
typedef framework::linear_mixable_helper< bit_index_storage, bit_table_t > mixable_bit_index_storage
typedef framework::linear_mixable_helper< inverted_index_storage, inverted_index_storage::diff_type > mixable_inverted_index_storage
typedef framework::linear_mixable_helper< lsh_index_storage, lsh_master_table_t > mixable_lsh_index_storage
typedef jubatus::core::common::assoc_vector< uint64_t, float > row_t
typedef typed_column< std::string > string_column
typedef jubatus::util::data::unordered_map< std::string, row_t > tbl_t
typedef typed_column< uint16_t > uint16_column
typedef typed_column< uint32_t > uint32_column
typedef typed_column< uint64_t > uint64_column
typedef typed_column< uint8_t > uint8_column
typedef double val1_t
Functions
float feature_fabssum (const id_feature_val3_t &f)
template<class E >
std::vector< std::pair< std::string, E > > operator* (std::vector< std::pair< std::string, E > > lhs, const std::vector< std::pair< std::string, E > > &rhs)
template<class E >
std::vector< std::pair< std::string, E > > operator* (std::vector< std::pair< std::string, E > > lhs, double d)
template<class E >
std::vector< std::pair< std::string, E > > & operator*= (std::vector< std::pair< std::string, E > > &lhs, const std::vector< std::pair< std::string, E > > &rhs)
template<class E >
std::vector< std::pair< std::string, E > > & operator*= (std::vector< std::pair< std::string, E > > &lhs, double d)
template<class E >
std::vector< std::pair< std::string, E > > operator+ (std::vector< std::pair< std::string, E > > lhs, const std::vector< std::pair< std::string, E > > &rhs)
template<class E >
std::vector< std::pair< std::string, E > > & operator+= (std::vector< std::pair< std::string, E > > &lhs, const std::vector< std::pair< std::string, E > > &rhs)
template<class E >
std::vector< std::pair< std::string, E > > operator- (std::vector< std::pair< std::string, E > > lhs, const std::vector< std::pair< std::string, E > > &rhs)
template<class E >
std::vector< std::pair< std::string, E > > & operator-= (std::vector< std::pair< std::string, E > > &lhs, const std::vector< std::pair< std::string, E > > &rhs)
template<class E >
std::vector< std::pair< std::string, E > > operator/ (std::vector< std::pair< std::string, E > > lhs, const std::vector< std::pair< std::string, E > > &rhs)
template<class E >
std::vector< std::pair< std::string, E > > operator/ (std::vector< std::pair< std::string, E > > lhs, double d)
template<class E >
std::vector< std::pair< std::string, E > > & operator/= (std::vector< std::pair< std::string, E > > &lhs, const std::vector< std::pair< std::string, E > > &rhs)
template<class E >
std::vector< std::pair< std::string, E > > & operator/= (std::vector< std::pair< std::string, E > > &lhs, double d)
std::ostream & operator<< (std::ostream &os, const version &v)
std::ostream & operator<< (std::ostream &os, const lsh_vector &lv)
static void similar_row_one (const bit_vector &x, const pair< string, bit_vector > &y, heap_type &heap)
void swap (lsh_vector &l, lsh_vector &r)
Typedef Documentation
typedef jubatus::util::data::unordered_map<std::string, bit_vector> jubatus::core::storage::bit_table_t
Definition at line 39 of file storage_type.hpp.
typedef bit_vector_base< uint64_t > jubatus::core::storage::bit_vector
Definition at line 27 of file bit_vector_ranking.hpp.
typedef typed_column< bit_vector > jubatus::core::storage::bit_vector_column
Definition at line 31 of file bit_vector_ranking.hpp.
typedef const bit_vector_column jubatus::core::storage::const_bit_vector_column
Definition at line 33 of file bit_vector_ranking.hpp.
typedef const typed_column<double> jubatus::core::storage::const_double_column
Definition at line 382 of file abstract_column.hpp.
typedef const typed_column<float> jubatus::core::storage::const_float_column
Definition at line 381 of file abstract_column.hpp.
typedef const typed_column<int16_t> jubatus::core::storage::const_int16_column
Definition at line 378 of file abstract_column.hpp.
typedef const typed_column<int32_t> jubatus::core::storage::const_int32_column
Definition at line 379 of file abstract_column.hpp.
typedef const typed_column<int64_t> jubatus::core::storage::const_int64_column
Definition at line 380 of file abstract_column.hpp.
typedef const typed_column<int8_t> jubatus::core::storage::const_int8_column
Definition at line 377 of file abstract_column.hpp.
typedef const typed_column<std::string> jubatus::core::storage::const_string_column
Definition at line 383 of file abstract_column.hpp.
typedef const typed_column<uint16_t> jubatus::core::storage::const_uint16_column
Definition at line 374 of file abstract_column.hpp.
typedef const typed_column<uint32_t> jubatus::core::storage::const_uint32_column
Definition at line 375 of file abstract_column.hpp.
typedef const typed_column<uint64_t> jubatus::core::storage::const_uint64_column
Definition at line 376 of file abstract_column.hpp.
typedef const typed_column<uint8_t> jubatus::core::storage::const_uint8_column
Definition at line 373 of file abstract_column.hpp.
typedef typed_column<double> jubatus::core::storage::double_column
Definition at line 369 of file abstract_column.hpp.
typedef std::vector<std::pair<std::string, val1_t> > jubatus::core::storage::feature_val1_t
Definition at line 209 of file storage_type.hpp.
typedef std::vector<std::pair<std::string, val2_t> > jubatus::core::storage::feature_val2_t
Definition at line 210 of file storage_type.hpp.
typedef std::vector<std::pair<std::string, val3_t> > jubatus::core::storage::feature_val3_t
Definition at line 211 of file storage_type.hpp.
typedef std::vector<std::pair<std::string, feature_val1_t> > jubatus::core::storage::features1_t
Definition at line 213 of file storage_type.hpp.
typedef std::vector<std::pair<std::string, feature_val2_t> > jubatus::core::storage::features2_t
Definition at line 214 of file storage_type.hpp.
typedef std::vector<std::pair<std::string, feature_val3_t> > jubatus::core::storage::features3_t
Definition at line 215 of file storage_type.hpp.
typedef typed_column<float> jubatus::core::storage::float_column
Definition at line 368 of file abstract_column.hpp.
typedef fixed_size_heap<pair<uint64_t, string>, greater<pair<uint64_t, string> > > jubatus::core::storage::heap_type
Definition at line 122 of file bit_index_storage.cpp.
typedef jubatus::util::data::unordered_map<uint64_t, val3_t> jubatus::core::storage::id_feature_val3_t
Definition at line 34 of file local_storage.hpp.
typedef jubatus::util::data::unordered_map<std::string, id_feature_val3_t> jubatus::core::storage::id_features3_t
Definition at line 36 of file local_storage.hpp.
typedef jubatus::util::data::unordered_map<uint64_t, float> jubatus::core::storage::imap_float_t
Definition at line 42 of file storage_type.hpp.
typedef typed_column<int16_t> jubatus::core::storage::int16_column
Definition at line 365 of file abstract_column.hpp.
typedef typed_column<int32_t> jubatus::core::storage::int32_column
Definition at line 366 of file abstract_column.hpp.
typedef typed_column<int64_t> jubatus::core::storage::int64_column
Definition at line 367 of file abstract_column.hpp.
typedef typed_column<int8_t> jubatus::core::storage::int8_column
Definition at line 364 of file abstract_column.hpp.
typedef jubatus::util::data::unordered_map< std::string, lsh_entry > jubatus::core::storage::lsh_master_table_t
Definition at line 39 of file euclid_lsh.hpp.
typedef jubatus::util::data::unordered_map<uint64_t, std::vector<uint64_t> > jubatus::core::storage::lsh_table_t
Definition at line 49 of file lsh_index_storage.hpp.
typedef jubatus::util::data::unordered_map<std::string, val1_t> jubatus::core::storage::map_feature_val1_t
Definition at line 218 of file storage_type.hpp.
typedef jubatus::util::data::unordered_map<std::string, val3_t> jubatus::core::storage::map_feature_val3_t
Definition at line 220 of file storage_type.hpp.
typedef jubatus::util::data::unordered_map<std::string, map_feature_val3_t> jubatus::core::storage::map_features3_t
Definition at line 222 of file storage_type.hpp.
typedef jubatus::util::data::unordered_map<std::string, float> jubatus::core::storage::map_float_t
Definition at line 41 of file storage_type.hpp.
typedef framework::linear_mixable_helper< bit_index_storage, bit_table_t > jubatus::core::storage::mixable_bit_index_storage
Definition at line 34 of file lsh.hpp.
typedef framework::linear_mixable_helper< inverted_index_storage, inverted_index_storage::diff_type> jubatus::core::storage::mixable_inverted_index_storage
Definition at line 98 of file inverted_index_storage.hpp.
typedef framework::linear_mixable_helper< lsh_index_storage, lsh_master_table_t > jubatus::core::storage::mixable_lsh_index_storage
Definition at line 43 of file euclid_lsh.hpp.
typedef jubatus::core::common::assoc_vector<uint64_t, float> jubatus::core::storage::row_t
Definition at line 36 of file storage_type.hpp.
typedef typed_column<std::string> jubatus::core::storage::string_column
Definition at line 370 of file abstract_column.hpp.
typedef jubatus::util::data::unordered_map<std::string, row_t> jubatus::core::storage::tbl_t
Definition at line 37 of file storage_type.hpp.
typedef typed_column<uint16_t> jubatus::core::storage::uint16_column
Definition at line 361 of file abstract_column.hpp.
typedef typed_column<uint32_t> jubatus::core::storage::uint32_column
Definition at line 362 of file abstract_column.hpp.
typedef typed_column<uint64_t> jubatus::core::storage::uint64_column
Definition at line 363 of file abstract_column.hpp.
typedef typed_column<uint8_t> jubatus::core::storage::uint8_column
Definition at line 360 of file abstract_column.hpp.
typedef double jubatus::core::storage::val1_t
Definition at line 44 of file storage_type.hpp.
Function Documentation
float jubatus::core::storage::feature_fabssum (const id_feature_val3_t & f)
Definition at line 183 of file local_storage.cpp.
References jubatus::core::clustering::sum().
{
   float sum = 0.f;
   for (id_feature_val3_t::const_iterator it = f.begin(); it != f.end(); ++it) {
     sum += std::fabs(it->second.v1);
   }
   return sum;
 }
template<class E > std::vector<std::pair<std::string, E> > jubatus::core::storage::operator* (std::vector< std::pair< std::string, E > > lhs, const std::vector< std::pair< std::string, E > > & rhs) inline
Definition at line 305 of file storage_type.hpp.
{
   return lhs *= rhs;
 }
template<class E > std::vector<std::pair<std::string, E> > jubatus::core::storage::operator* (std::vector< std::pair< std::string, E > > lhs, double d) inline
Definition at line 333 of file storage_type.hpp.
               {
   return lhs *= d;
 }
template<class E > std::vector<std::pair<std::string, E> >& jubatus::core::storage::operator*= (std::vector< std::pair< std::string, E > > & lhs, const std::vector< std::pair< std::string, E > > & rhs) inline
Definition at line 313 of file storage_type.hpp.
References jubatus::core::storage::detail::binop().
{
   return detail::binop(lhs, rhs, std::multiplies<E>());
 }
template<class E > std::vector<std::pair<std::string, E> >& jubatus::core::storage::operator*= (std::vector< std::pair< std::string, E > > & lhs, double d) inline
Definition at line 340 of file storage_type.hpp.
References jubatus::core::storage::detail::mult_scalar().
               {
   return detail::mult_scalar(lhs, d);
 }
template<class E > std::vector<std::pair<std::string, E> > jubatus::core::storage::operator+ (std::vector< std::pair< std::string, E > > lhs, const std::vector< std::pair< std::string, E > > & rhs) inline
Definition at line 277 of file storage_type.hpp.
{
   return lhs += rhs;
 }
template<class E > std::vector<std::pair<std::string, E> >& jubatus::core::storage::operator+= (std::vector< std::pair< std::string, E > > & lhs, const std::vector< std::pair< std::string, E > > & rhs) inline
Definition at line 285 of file storage_type.hpp.
References jubatus::core::storage::detail::binop().
{
   return detail::binop(lhs, rhs, std::plus<E>());
 }
template<class E > std::vector<std::pair<std::string, E> > jubatus::core::storage::operator- (std::vector< std::pair< std::string, E > > lhs, const std::vector< std::pair< std::string, E > > & rhs) inline
Definition at line 291 of file storage_type.hpp.
{
   return lhs -= rhs;
 }
template<class E > std::vector<std::pair<std::string, E> >& jubatus::core::storage::operator-= (std::vector< std::pair< std::string, E > > & lhs, const std::vector< std::pair< std::string, E > > & rhs) inline
Definition at line 299 of file storage_type.hpp.
References jubatus::core::storage::detail::binop().
{
   return detail::binop(lhs, rhs, std::minus<E>());
 }
template<class E > std::vector<std::pair<std::string, E> > jubatus::core::storage::operator/ (std::vector< std::pair< std::string, E > > lhs, const std::vector< std::pair< std::string, E > > & rhs) inline
Definition at line 319 of file storage_type.hpp.
{
   return lhs /= rhs;
 }
template<class E > std::vector<std::pair<std::string, E> > jubatus::core::storage::operator/ (std::vector< std::pair< std::string, E > > lhs, double d) inline
Definition at line 347 of file storage_type.hpp.
               {
   return lhs /= d;
 }
template<class E > std::vector<std::pair<std::string, E> >& jubatus::core::storage::operator/= (std::vector< std::pair< std::string, E > > & lhs, const std::vector< std::pair< std::string, E > > & rhs) inline
Definition at line 326 of file storage_type.hpp.
References jubatus::core::storage::detail::binop().
{
   return detail::binop(lhs, rhs, std::divides<E>());
 }
template<class E > std::vector<std::pair<std::string, E> >& jubatus::core::storage::operator/= (std::vector< std::pair< std::string, E > > & lhs, double d) inline
Definition at line 354 of file storage_type.hpp.
References jubatus::core::storage::detail::mult_scalar().
               {
   return detail::mult_scalar(lhs, 1.0 / d);
 }
std::ostream& jubatus::core::storage::operator<< (std::ostream & os, const version & v)
Definition at line 24 of file version.cpp.
References jubatus::core::storage::version::version_number_.
{
   os << v.version_number_;
   // cardinal number output
   if ((v.version_number_ % 10) == 1
       && ((v.version_number_ % 100) != 11)) {
     os << "st";
   } else if ((v.version_number_ % 10) == 2
              && ((v.version_number_ % 100) != 12)) {
     os << "nd";
   } else if ((v.version_number_ % 10) == 3
              && ((v.version_number_ % 100) != 13)) {
     os << "rd";
   } else {
     os << "th";
   }
   return os;
 }
std::ostream& jubatus::core::storage::operator<< (std::ostream & os, const lsh_vector & lv) inline
Definition at line 65 of file lsh_vector.hpp.
References jubatus::core::storage::lsh_vector::debug_print().
{
   lv.debug_print(os);
   return os;
 }
static void jubatus::core::storage::similar_row_one (const bit_vector & x, const pair< string, bit_vector > & y, heap_type & heap) static
Definition at line 124 of file bit_index_storage.cpp.
References jubatus::core::storage::bit_vector_base< bit_base >::calc_hamming_similarity(), and jubatus::core::storage::fixed_size_heap< T, Comp >::push().
Referenced by jubatus::core::storage::bit_index_storage::similar_row().
                      {
   uint64_t match_num = x.calc_hamming_similarity(y.second);
   heap.push(make_pair(match_num, y.first));
 }
void jubatus::core::storage::swap (lsh_vector & l, lsh_vector & r) inline
Definition at line 61 of file lsh_vector.hpp.
References jubatus::core::storage::lsh_vector::swap().
Referenced by jubatus::core::storage::typed_column< T >::remove().
                                                {  // NOLINT
   l.swap(r);
 }