jubatus_core: jubatus::core::unlearner Namespace Reference
jubatus::core::unlearner Namespace Reference
Classes
class lru_unlearner
class mock_callback
class random_unlearner
class unlearner_base
Typedefs
typedef jubatus::util::lang::function< void(std::string)> unlearning_callback
Functions
shared_ptr< unlearner_base > create_unlearner (const std::string &name, const common::jsonconfig::config &config)
Typedef Documentation
typedef jubatus::util::lang::function<void (std::string)> jubatus::core::unlearner::unlearning_callback
Definition at line 27 of file unlearner_base.hpp.
Function Documentation
util::lang::shared_ptr< unlearner_base > jubatus::core::unlearner::create_unlearner (const std::string & name, const common::jsonconfig::config & config)
Definition at line 31 of file unlearner_factory.cpp.
References jubatus::core::common::jsonconfig::config_cast_check(), and JUBATUS_EXCEPTION.
Referenced by jubatus::core::anomaly::anomaly_factory::create_anomaly(), jubatus::core::classifier::classifier_factory::create_classifier(), and jubatus::core::recommender::recommender_factory::create_recommender().
{
   if (name == "lru") {
     return shared_ptr<unlearner_base>(
         new lru_unlearner(common::jsonconfig::config_cast_check<
                           lru_unlearner::config>(config)));
   } else if (name == "random") {
     return shared_ptr<unlearner_base>(
         new random_unlearner(common::jsonconfig::config_cast_check<
                              random_unlearner::config>(config)));
   } else {
     throw JUBATUS_EXCEPTION(common::unsupported_method(
                                 "unlearner(" + name + ')'));
   }
 }