jubatus_core: jubatus::core::common::jsonconfig::detail Namespace Reference
jubatus::core::common::jsonconfig::detail Namespace Reference
Functions
bool check_json_float (json_config_iarchive_cast &js)
bool check_json_type (json_config_iarchive_cast &js, jubatus::util::text::json::json::json_type_t t)
Function Documentation
bool jubatus::core::common::jsonconfig::detail::check_json_float (json_config_iarchive_cast & js) inline
Definition at line 145 of file cast.hpp.
References jubatus::core::common::jsonconfig::json_config_iarchive_cast::get(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::get_config(), JUBATUS_EXCEPTION, jubatus::core::common::jsonconfig::config::path(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::push_error(), and jubatus::core::common::jsonconfig::json_config_iarchive_cast::trace_error().
{
   if (js.get().type() != jubatus::util::text::json::json::Float
       && js.get().type() != jubatus::util::text::json::json::Integer) {
     type_error e(
         js.get_config().path(),
         jubatus::util::text::json::json::Float,
         js.get().type());
     if (js.trace_error()) {
       js.push_error(e);
     } else {
       throw JUBATUS_EXCEPTION(e);
     }
     return false;
   }
   return true;
 }
bool jubatus::core::common::jsonconfig::detail::check_json_type (json_config_iarchive_cast & js, jubatus::util::text::json::json::json_type_t t) inline
Definition at line 130 of file cast.hpp.
References jubatus::core::common::jsonconfig::json_config_iarchive_cast::get(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::get_config(), JUBATUS_EXCEPTION, jubatus::core::common::jsonconfig::config::path(), jubatus::core::common::jsonconfig::json_config_iarchive_cast::push_error(), and jubatus::core::common::jsonconfig::json_config_iarchive_cast::trace_error().
Referenced by jubatus::core::common::jsonconfig::serialize().
{
   if (js.get().type() != t) {
     type_error e(js.get_config().path(), t, js.get().type());
     if (js.trace_error()) {
       js.push_error(e);
     } else {
       throw JUBATUS_EXCEPTION(e);
     }
     return false;
   }
   return true;
 }