jubatus_core: jubatus::core::clustering Namespace Reference
jubatus::core::clustering Namespace Reference
Namespaces
compressor
Classes
class clustering
struct clustering_config
class clustering_error
class clustering_method
class clustering_method_factory
class compressive_storage
class discrete_distribution
class eigen_feature_mapper
struct eigen_wsvec_t
class event_dispatcher
class gmm
class gmm_clustering_method
class kmeans_clustering_method
class simple_storage
class storage
class storage_factory
struct weighted_point
Typedefs
typedef std::vector< cluster_unit > cluster_set
typedef std::vector< std::pair< cluster_weight, jubatus::core::fv_converter::datum > > cluster_unit
typedef double cluster_weight
typedef std::vector< std::pair< std::string, wplist > > diff_t
typedef std::vector< eigen_smat_t > eigen_smat_list_t
typedef Eigen::SparseMatrix< double > eigen_smat_t
typedef std::vector< jubatus::util::lang::shared_ptr< eigen_solver_t > > eigen_solver_list_t
typedef Eigen::SimplicialCholesky< eigen_smat_t > eigen_solver_t
typedef std::vector< eigen_svec_t > eigen_svec_list_t
typedef Eigen::SparseVector< double > eigen_svec_t
typedef std::vector< eigen_wsvec_t > eigen_wsvec_list_t
typedef framework::linear_mixable_helper< storage, diff_t > mixable_storage
typedef std::vector< common::sfv_t > plist
typedef std::vector< weighted_point > wplist
Enumerations
enum storage_event_type { REVISION_CHANGE, UPDATE }
Functions
common::sfv_t add (const common::sfv_t &p1, const common::sfv_t &p2)
void concat (const wplist &src, wplist &dst)
char digit (int num, int r, int n)
double dist (const common::sfv_t &p1, const common::sfv_t &p2)
double dist (const weighted_point &d1, const weighted_point &d2)
void dump_wplist (const wplist &src)
weighted_point get_point (size_t d)
weighted_point get_point (size_t d, const std::vector< double > &c)
std::vector< weighted_point > get_points (size_t n, size_t d)
std::vector< weighted_point > get_points (size_t n, size_t d, const std::vector< double > &c)
std::pair< size_t, double > min_dist (const common::sfv_t &p, const std::vector< common::sfv_t > &P)
pair< size_t, double > min_dist (const common::sfv_t &p, const vector< common::sfv_t > &P)
std::pair< size_t, double > min_dist (const weighted_point &d1, const wplist &P)
common::sfv_t scalar_dot (const common::sfv_t &p, double s)
void scalar_mul_and_add (const common::sfv_t &left, float s, common::sfv_t &right)
common::sfv_t sub (const common::sfv_t &p1, const common::sfv_t &p2)
double sum (const common::sfv_t &p)
double sum2 (const common::sfv_t &p)
void swap (weighted_point &p1, weighted_point &p2)
Typedef Documentation
typedef std::vector<cluster_unit> jubatus::core::clustering::cluster_set
Definition at line 37 of file types.hpp.
typedef std::vector<std::pair<cluster_weight, jubatus::core::fv_converter::datum> > jubatus::core::clustering::cluster_unit
Definition at line 36 of file types.hpp.
typedef double jubatus::core::clustering::cluster_weight
Definition at line 34 of file types.hpp.
typedef std::vector<std::pair<std::string, wplist> > jubatus::core::clustering::diff_t
Definition at line 57 of file types.hpp.
typedef std::vector<eigen_smat_t> jubatus::core::clustering::eigen_smat_list_t
Definition at line 33 of file gmm_types.hpp.
typedef Eigen::SparseMatrix<double> jubatus::core::clustering::eigen_smat_t
Definition at line 30 of file gmm_types.hpp.
typedef std::vector<jubatus::util::lang::shared_ptr<eigen_solver_t> > jubatus::core::clustering::eigen_solver_list_t
Definition at line 35 of file gmm_types.hpp.
typedef Eigen::SimplicialCholesky<eigen_smat_t> jubatus::core::clustering::eigen_solver_t
Definition at line 31 of file gmm_types.hpp.
typedef std::vector<eigen_svec_t> jubatus::core::clustering::eigen_svec_list_t
Definition at line 32 of file gmm_types.hpp.
typedef Eigen::SparseVector<double> jubatus::core::clustering::eigen_svec_t
Definition at line 29 of file gmm_types.hpp.
typedef std::vector<eigen_wsvec_t> jubatus::core::clustering::eigen_wsvec_list_t
Definition at line 42 of file gmm_types.hpp.
typedef framework::linear_mixable_helper<storage, diff_t> jubatus::core::clustering::mixable_storage
Definition at line 81 of file storage.hpp.
typedef std::vector<common::sfv_t> jubatus::core::clustering::plist
Definition at line 56 of file types.hpp.
typedef std::vector<weighted_point> jubatus::core::clustering::wplist
Definition at line 55 of file types.hpp.
Enumeration Type Documentation
enum jubatus::core::clustering::storage_event_type
Enumerator
REVISION_CHANGE
UPDATE
Definition at line 36 of file storage.hpp.
{
   REVISION_CHANGE,
   UPDATE
 };
Function Documentation
common::sfv_t jubatus::core::clustering::add (const common::sfv_t & p1, const common::sfv_t & p2)
Definition at line 89 of file util.cpp.
{
   common::sfv_t ret;
   common::sfv_t::const_iterator it1 = p1.begin();
   common::sfv_t::const_iterator it2 = p2.begin();
   while (it1 != p1.end() && it2 != p2.end()) {
     if ((*it1).first < (*it2).first) {
       ret.push_back((*it1));
       ++it1;
     } else if ((*it1).first > (*it2).first) {
       ret.push_back((*it2));
       ++it2;
     } else {
       ret.push_back(make_pair((*it1).first, (*it1).second + (*it2).second));
       ++it1;
       ++it2;
     }
   }
   for (; it1 != p1.end(); ++it1) {
     ret.push_back((*it1));
   }
   for (; it2 != p2.end(); ++it2) {
     ret.push_back((*it2));
   }
   return ret;
 }
void jubatus::core::clustering::concat (const wplist & src, wplist & dst)
Definition at line 33 of file util.cpp.
Referenced by jubatus::core::clustering::compressive_storage::carry_up(), jubatus::core::clustering::compressor::kmeans_compressor::compress(), jubatus::core::clustering::storage::get_all(), jubatus::core::clustering::storage::get_common(), and jubatus::core::clustering::compressive_storage::get_mine().
{
   dst.insert(dst.end(), src.begin(), src.end());
 }
char jubatus::core::clustering::digit (int num, int r, int n)
Definition at line 37 of file util.cpp.
Referenced by jubatus::core::clustering::compressive_storage::is_next_bucket_full().
{
   if (r < 0) {
     return 0;
   }
   for (int i = 0; i < r; ++i) {
     num /= n;
   }
   return num % n;
 }
double jubatus::core::clustering::dist (const common::sfv_t & p1, const common::sfv_t & p2)
Definition at line 151 of file util.cpp.
Referenced by dist(), jubatus::core::clustering::kmeans_clustering_method::do_batch_update(), jubatus::core::graph::graph_wo_index::get_diff_eigen_score(), jubatus::core::storage::lsh_index_storage::get_sorted_similar_rows(), jubatus::core::storage::lsh_probe_generator::init(), min_dist(), jubatus::core::nearest_neighbor::ranking_hamming_bit_vectors(), and jubatus::core::graph::graph_wo_index::update_spt_node().
{
   double ret = 0;
   common::sfv_t::const_iterator it1 = p1.begin();
   common::sfv_t::const_iterator it2 = p2.begin();
   while (it1 != p1.end() && it2 != p2.end()) {
     int cmp = strcmp(it1->first.c_str(), it2->first.c_str());
     if (cmp < 0) {
       ret += it1->second * it1->second;
       ++it1;
     } else if (cmp > 0) {
       ret += it2->second * it2->second;
       ++it2;
     } else {
       ret += (it1->second  - it2->second) * (it1->second - it2->second);
       ++it1;
       ++it2;
     }
   }
   for (; it1 != p1.end(); ++it1) {
     ret += std::pow(it1->second, 2);
   }
   for (; it2 != p2.end(); ++it2) {
     ret += std::pow(it2->second, 2);
   }
   return std::sqrt(ret);
 }
double jubatus::core::clustering::dist (const weighted_point & d1, const weighted_point & d2)
Definition at line 178 of file util.cpp.
References jubatus::core::clustering::weighted_point::data, and dist().
{
   return dist(d1.data, d2.data);
 }
void jubatus::core::clustering::dump_wplist (const wplist & src)
weighted_point jubatus::core::clustering::get_point (size_t d) inline
Definition at line 38 of file testutil.hpp.
References jubatus::core::clustering::weighted_point::data, and jubatus::core::clustering::weighted_point::weight.
Referenced by get_points().
{
   static mtrand r_(0);
   weighted_point ret;
   for (size_t i = 0; i < d; ++i) {
     ret.data.push_back(make_pair(
         lexical_cast<string, int>(i), r_.next_gaussian(0, 10)));
   }
   ret.weight = 1;
   return ret;
 }
weighted_point jubatus::core::clustering::get_point (size_t d, const std::vector< double > & c) inline
Definition at line 49 of file testutil.hpp.
References jubatus::core::clustering::weighted_point::data, and jubatus::core::clustering::weighted_point::weight.
{
   static mtrand r_(0);
   weighted_point ret;
   for (size_t i = 0; i < d; ++i) {
     ret.data.push_back(std::make_pair(
         "#test_" + lexical_cast<string, int>(i),
         c[i] + r_.next_gaussian(0, 10)));
   }
   ret.weight = 1;
   return ret;
 }
std::vector<weighted_point> jubatus::core::clustering::get_points (size_t n, size_t d) inline
Definition at line 61 of file testutil.hpp.
References get_point().
{
   std::vector<weighted_point> ret;
   for (size_t i = 0; i < n; ++i) {
     ret.push_back(get_point(d));
   }
   return ret;
 }
std::vector<weighted_point> jubatus::core::clustering::get_points (size_t n, size_t d, const std::vector< double > & c) inline
Definition at line 69 of file testutil.hpp.
References get_point().
{
   std::vector<weighted_point> ret;
   for (size_t i = 0; i < n; ++i) {
     ret.push_back(get_point(d, c));
   }
   return ret;
 }
std::pair<size_t, double> jubatus::core::clustering::min_dist (const common::sfv_t & p, const std::vector< common::sfv_t > & P)
pair<size_t, double> jubatus::core::clustering::min_dist (const common::sfv_t & p, const vector< common::sfv_t > & P)
Definition at line 182 of file util.cpp.
References dist().
Referenced by jubatus::core::clustering::compressor::kmeans_compressor::bicriteria_to_coreset(), jubatus::core::clustering::kmeans_clustering_method::do_batch_update(), jubatus::core::clustering::compressor::kmeans_compressor::get_bicriteria(), jubatus::core::clustering::kmeans_clustering_method::get_clusters(), jubatus::core::clustering::kmeans_clustering_method::get_nearest_center_index(), and jubatus::core::clustering::kmeans_clustering_method::initialize_centers().
{
   size_t idx = 0;
   double mindist = DBL_MAX;
   for (vector<common::sfv_t>::const_iterator it = P.begin();
        it != P.end(); ++it) {
     double d = dist(p, *it);
     if (mindist > d) {
       idx = it - P.begin();
       mindist = d;
     }
   }
   return std::make_pair(idx, mindist);
 }
std::pair< size_t, double > jubatus::core::clustering::min_dist (const weighted_point & d1, const wplist & P)
Definition at line 198 of file util.cpp.
References dist().
{
   double md = DBL_MAX;
   size_t midx = 0;
   for (wplist::const_iterator it = P.begin(); it != P.end(); ++it) {
     double d = dist((*it), d1);
     if (md > d) {
       midx = it - P.begin();
       md = d;
     }
   }
   return std::make_pair(midx, md);
 }
common::sfv_t jubatus::core::clustering::scalar_dot (const common::sfv_t & p, double s)
Definition at line 143 of file util.cpp.
Referenced by jubatus::core::clustering::kmeans_clustering_method::do_batch_update().
{
   common::sfv_t ret;
   for (common::sfv_t::const_iterator it = p.begin(); it != p.end(); ++it)  {
     ret.push_back(make_pair((*it).first, (*it).second*s));
   }
   return ret;
 }
void jubatus::core::clustering::scalar_mul_and_add (const common::sfv_t & left, float s, common::sfv_t & right)
Definition at line 62 of file util.cpp.
Referenced by jubatus::core::clustering::kmeans_clustering_method::do_batch_update().
{
   common::sfv_t::const_iterator l = left.begin();
   common::sfv_t::iterator r = right.begin();
   while (l != left.end() && r != right.end()) {
     if (l->first < r->first) {
       std::pair<std::string, float> p = *l;
       p.second *= s;
       r = right.insert(r, p);
       ++l;
     } else if (l->first > r->first) {
       ++r;
     } else {
       r->second += l->second * s;
       ++l;
       ++r;
     }
   }
   for (; l != left.end(); ++l) {
     std::pair<std::string, float> p = *l;
     p.second *= s;
     right.push_back(p);
   }
 }
common::sfv_t jubatus::core::clustering::sub (const common::sfv_t & p1, const common::sfv_t & p2)
Definition at line 116 of file util.cpp.
{
   common::sfv_t ret;
   common::sfv_t::const_iterator it1 = p1.begin();
   common::sfv_t::const_iterator it2 = p2.begin();
   while (it1 != p1.end() && it2 != p2.end()) {
     if ((*it1).first < (*it2).first) {
       ret.push_back((*it1));
       ++it1;
     } else if ((*it1).first > (*it2).first) {
       ret.push_back(make_pair((*it2).first, -(*it2).second));
       ++it2;
     } else {
       ret.push_back(make_pair((*it1).first, (*it1).second - (*it2).second));
       ++it1;
       ++it2;
     }
   }
   for (; it1 != p1.end(); ++it1) {
     ret.push_back((*it1));
   }
   for (; it2 != p2.end(); ++it2) {
     ret.push_back(make_pair((*it2).first, -(*it2).second));
   }
   return ret;
 }
double jubatus::core::clustering::sum (const common::sfv_t & p)
Definition at line 47 of file util.cpp.
Referenced by jubatus::core::clustering::gmm::cluster_probs(), and jubatus::core::storage::feature_fabssum().
{
   double s = 0;
   for (common::sfv_t::const_iterator it = p.begin(); it != p.end(); ++it) {
     s += (*it).second;
   }
   return s;
 }
double jubatus::core::clustering::sum2 (const common::sfv_t & p)
Definition at line 54 of file util.cpp.
{
   double s = 0;
   for (common::sfv_t::const_iterator it = p.begin(); it != p.end(); ++it) {
     s += std::pow((*it).second, 2);
   }
   return s;
 }
void jubatus::core::clustering::swap (weighted_point & p1, weighted_point & p2) inline
Definition at line 47 of file types.hpp.
References jubatus::core::clustering::weighted_point::data, jubatus::core::fv_converter::datum::num_values_, jubatus::core::clustering::weighted_point::original, jubatus::core::fv_converter::datum::string_values_, and jubatus::core::clustering::weighted_point::weight.
Referenced by jubatus::core::recommender::lsh::clear(), jubatus::core::fv_converter::counter< std::string >::clear(), jubatus::core::recommender::euclid_lsh::clear(), jubatus::core::anomaly::light_lof::collect_lrds(), jubatus::core::table::column_table::delete_row_(), jubatus::core::framework::linear_function_mixer::put_diff(), jubatus::core::table::typed_column< T >::remove(), jubatus::core::graph::graph_wo_index::remove_by_swap(), jubatus::core::storage::bit_vector::swap(), jubatus::core::burst::basic_window< batch_result >::swap(), jubatus::core::table::column_type::swap(), and jubatus::core::table::bit_vector_base< bit_base >::swap().
{
   using std::swap;
   swap(p1.weight, p2.weight);
   swap(p1.data, p2.data);
   swap(p1.original.string_values_, p2.original.string_values_);
   swap(p1.original.num_values_, p2.original.num_values_);
 }