jubatus_core: jubatus::core::recommender Namespace Reference
jubatus::core::recommender Namespace Reference
Classes
class euclid_lsh
class inverted_index
class lsh
class minhash
class nearest_neighbor_recommender
class recommender_base
class recommender_factory
class recommender_mock
class recommender_mock_storage
Typedefs
typedef storage::lsh_index_storage lsh_index_storage
typedef framework::linear_mixable_helper< recommender_mock_storage, recommender_mock_storage > mixable_recommender_mock_storage
typedef storage::mixable_lsh_index_storage::model_ptr model_ptr
typedef core::common::sfv_t sfv_diff_t
Functions
void generate_random_vector (size_t dim, uint32_t seed, std::vector< float > &v)
void generate_random_vector (size_t dim, uint32_t seed, vector< float > &ret)
std::vector< std::pair< std::string, float > > make_ids (const std::string &repr)
vector< pair< string, float > > make_ids (const string &repr)
common::sfv_t make_sfv (const std::string &repr)
common::sfv_t make_sfv (const string &repr)
void prod_invert_and_vector (const jubatus::util::data::unordered_map< std::string, std::vector< float > > &matrix, const common::sfv_t &vec, size_t dim, std::vector< float > &ret)
void prod_invert_and_vector (const unordered_map< string, vector< float > > &matrix, const common::sfv_t &vec, size_t dim, vector< float > &ret)
void set_bit_vector (const std::vector< float > &vec, jubatus::core::storage::bit_vector &bit_vec)
void set_bit_vector (const std::vector< float > &vec, bit_vector &bit_vec)
Variables
static const uint64_t DEFAULT_HASH_NUM = 64
Typedef Documentation
typedef storage::lsh_index_storage jubatus::core::recommender::lsh_index_storage
Definition at line 91 of file euclid_lsh.cpp.
typedef framework::linear_mixable_helper< recommender_mock_storage, recommender_mock_storage> jubatus::core::recommender::mixable_recommender_mock_storage
Definition at line 97 of file recommender_mock_storage.hpp.
typedef mixable_recommender_mock_storage::model_ptr jubatus::core::recommender::model_ptr
Definition at line 90 of file euclid_lsh.cpp.
typedef core::common::sfv_t jubatus::core::recommender::sfv_diff_t
Definition at line 26 of file recommender_type.hpp.
Function Documentation
void jubatus::core::recommender::generate_random_vector (size_t dim, uint32_t seed, std::vector< float > & v)
void jubatus::core::recommender::generate_random_vector (size_t dim, uint32_t seed, vector< float > & ret)
Definition at line 35 of file lsh_util.cpp.
References jubatus::core::common::jsonconfig::v().
Referenced by jubatus::core::recommender::lsh::generate_column_base().
{
   jubatus::util::math::random::mtrand rnd(seed);
   vector<float> v(dim);
   for (uint64_t i = 0; i < dim; ++i) {
     v[i] = rnd.next_gaussian();
   }
   ret.swap(v);
 }
std::vector<std::pair<std::string, float> > jubatus::core::recommender::make_ids (const std::string & repr)
vector<pair<string, float> > jubatus::core::recommender::make_ids (const string & repr)
Definition at line 45 of file recommender_mock_util.cpp.
References make_sfv().
{
   return make_sfv(repr);
 }
common::sfv_t jubatus::core::recommender::make_sfv (const std::string & repr)
common::sfv_t jubatus::core::recommender::make_sfv (const string & repr)
Definition at line 33 of file recommender_mock_util.cpp.
Referenced by make_ids().
{
   vector<string> elems = split(repr, ' ');
   common::sfv_t sfv(elems.size());
   for (size_t i = 0; i < elems.size(); ++i) {
     vector<string> parts = split(elems[i], ':');
     sfv[i] = make_pair(
         parts[0],
         jubatus::util::lang::lexical_cast<float>(parts[1]));
   }
   return sfv;
 }
void jubatus::core::recommender::prod_invert_and_vector (const jubatus::util::data::unordered_map< std::string, std::vector< float > > & matrix, const common::sfv_t & vec, size_t dim, std::vector< float > & ret)
void jubatus::core::recommender::prod_invert_and_vector (const unordered_map< string, vector< float > > & matrix, const common::sfv_t & vec, size_t dim, vector< float > & ret)
Definition at line 55 of file lsh_util.cpp.
References JUBATUS_ASSERT_EQ, and jubatus::core::common::jsonconfig::v().
Referenced by jubatus::core::recommender::lsh::calc_lsh_values().
{
   vector<float> r(dim);
   for (size_t i = 0; i < vec.size(); ++i) {
     const string& column = vec[i].first;
     float val = vec[i].second;
     unordered_map<string, vector<float> >::const_iterator it =
         matrix.find(column);
     if (it == matrix.end()) {
       continue;
     }
     const vector<float>& v = it->second;
     JUBATUS_ASSERT_EQ(v.size(), r.size(), "");
     for (size_t j = 0; j < v.size(); ++j) {
       r[j] += v[j] * val;
     }
   }
   ret.swap(r);
 }
void jubatus::core::recommender::set_bit_vector (const std::vector< float > & vec, jubatus::core::storage::bit_vector & bit_vec)
void jubatus::core::recommender::set_bit_vector (const std::vector< float > & vec, bit_vector & bit_vec)
Definition at line 44 of file lsh_util.cpp.
References jubatus::core::storage::bit_vector_base< bit_base >::resize_and_clear().
Referenced by jubatus::core::recommender::lsh::calc_lsh_values().
{
   bit_vector bv;
   bv.resize_and_clear(vec.size());
   for (size_t i = 0; i < vec.size(); ++i) {
     if (vec[i] >= 0.f) {
       bv.set_bit(i);
     }
   }
   bit_vec.swap(bv);
 }
Variable Documentation
const uint64_t jubatus::core::recommender::DEFAULT_HASH_NUM = 64 static
Definition at line 38 of file lsh.cpp.