jubatus_core: jubatus/core/regression/regression_test_util.hpp File Reference
regression_test_util.hpp File Reference
#include <cstdlib>
#include <cmath>
#include <cfloat>
#include <utility>
#include <vector>
#include <string>
#include <algorithm>
#include "jubatus/util/math/random.h"
Functions
std::pair< float, std::vector< double > > gen_random_data (float mu, float sigma, size_t dim)
void make_gaussian_random (float mu, float sigma, size_t dim, std::vector< double > &v)
void make_random (size_t dim, std::vector< double > &v)
Function Documentation
std::pair<float, std::vector<double> > gen_random_data (float mu, float sigma, size_t dim)
Definition at line 49 of file regression_test_util.hpp.
References make_gaussian_random(), and make_random().
                 {
   std::pair<float, std::vector<double> > p;
   std::vector<double> coef;
   make_random(dim, coef);
   make_gaussian_random(mu, sigma, dim , p.second);
   for (size_t i = 0; i < dim; i++) {
     p.first += p.second[i] * coef[i];
   }
   return p;
 }
void make_gaussian_random (float mu, float sigma, size_t dim, std::vector< double > & v)
Definition at line 29 of file regression_test_util.hpp.
Referenced by gen_random_data().
{
   jubatus::util::math::random::mtrand rand(0);
   for (size_t i = 0; i < dim; i++) {
     float value = rand.next_gaussian(mu, sigma);
     v.push_back(value);
   }
 }
void make_random (size_t dim, std::vector< double > & v)
Definition at line 41 of file regression_test_util.hpp.
Referenced by gen_random_data().
{
   jubatus::util::math::random::mtrand rand(0);
   for (size_t i = 0; i < dim; i++) {
     double value = rand.next_double();
     v.push_back(value);
   }
 }