jubatus_core: jubatus::core::table::bit_vector_base< bit_base > Struct Template Reference
jubatus::core::table::bit_vector_base< bit_base > Struct Template Reference
#include <bit_vector.hpp>
Public Member Functions
void alloc_memory ()
size_t bit_count () const
size_t bit_num () const
bit_vector_base (const bit_base *bits, size_t bit_num)
bit_vector_base (int bit_num)
bit_vector_base (const bit_vector_base &orig)
uint64_t calc_hamming_distance (const bit_vector_base &bv) const
uint64_t calc_hamming_similarity (const bit_vector_base &bv) const
void clear ()
void clear_bit (size_t pos)
void debug_print (std::ostream &os) const
bool get_bit (size_t pos) const
bool is_empty () const
template<typename Buffer >
void msgpack_pack (msgpack::packer< Buffer > &packer) const
void msgpack_unpack (msgpack::object o)
bool operator!= (const bit_vector_base &rhs) const
bit_vector_base & operator= (const bit_vector_base &orig)
bool operator== (const bit_vector_base &rhs) const
template<typename packable >
void pack (packable &buffer) const
bit_base * raw_data_unsafe ()
const bit_base * raw_data_unsafe () const
void reverse_bit (size_t pos)
void set_bit (size_t pos)
void status (std::ostream &os) const
void swap (bit_vector_base &x)
size_t used_bytes () const
~bit_vector_base ()
Static Public Member Functions
static size_t memory_size (size_t bit_width)
static uint64_t pop_count (uint64_t r)
static size_t pop_count (uint8_t r)
Static Public Attributes
static const size_t BASE_BITS = sizeof(bit_base) * 8
static const size_t BLOCKSIZE = sizeof(bit_base)
Private Member Functions
void duplicate (const bit_vector_base &orig)
bool release ()
Private Attributes
const size_t bit_num_
bit_base * bits_
bool own_
Friends
std::ostream & operator<< (std::ostream &os, const bit_vector_base &bv)
void swap (bit_vector_base &l, bit_vector_base &r)
Detailed Description
template<typename bit_base>
struct jubatus::core::table::bit_vector_base< bit_base >
Definition at line 100 of file bit_vector.hpp.
Constructor & Destructor Documentation
template<typename bit_base > jubatus::core::table::bit_vector_base< bit_base >::bit_vector_base (const bit_base * bits, size_t bit_num) inline
Definition at line 104 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::alloc_memory(), jubatus::core::table::bit_vector_base< bit_base >::bits_, and jubatus::core::table::bit_vector_base< bit_base >::used_bytes().
Referenced by jubatus::core::table::bit_vector_base< bit_base >::msgpack_unpack().
       : bits_(NULL),
         bit_num_(bit_num),
         own_(false) {
     alloc_memory();
     memcpy(bits_, bits, used_bytes());
   }
template<typename bit_base > jubatus::core::table::bit_vector_base< bit_base >::bit_vector_base (int bit_num) inline explicit
Definition at line 111 of file bit_vector.hpp.
       : bits_(NULL),
         bit_num_(bit_num),
         own_(false) {
   }
template<typename bit_base > jubatus::core::table::bit_vector_base< bit_base >::bit_vector_base (const bit_vector_base< bit_base > & orig) inline
Definition at line 117 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::alloc_memory(), jubatus::core::table::bit_vector_base< bit_base >::bits_, and jubatus::core::table::bit_vector_base< bit_base >::used_bytes().
       : bits_(NULL),
         bit_num_(orig.bit_num_),
         own_(false) {
     if (orig.bits_ == NULL) {
       return;
     }
     alloc_memory();
     memcpy(bits_, orig.bits_, used_bytes());
   }
template<typename bit_base > jubatus::core::table::bit_vector_base< bit_base >::~bit_vector_base () inline
Definition at line 128 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bits_, jubatus::core::table::bit_vector_base< bit_base >::own_, and jubatus::core::table::bit_vector_base< bit_base >::release().
                      {
     if (bits_ && own_) {
       release();
       return;
     }
   }
Member Function Documentation
template<typename bit_base > void jubatus::core::table::bit_vector_base< bit_base >::alloc_memory () inline
Definition at line 380 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bits_, JUBATUS_ASSERT, jubatus::core::table::bit_vector_base< bit_base >::own_, and jubatus::core::table::bit_vector_base< bit_base >::used_bytes().
Referenced by jubatus::core::table::bit_vector_base< bit_base >::bit_vector_base(), jubatus::core::table::bit_vector_base< bit_base >::duplicate(), jubatus::core::table::bit_vector_base< bit_base >::operator=(), jubatus::core::table::bit_vector_base< bit_base >::reverse_bit(), and jubatus::core::table::bit_vector_base< bit_base >::set_bit().
                       {
     JUBATUS_ASSERT(!own_);
     bits_ = new bit_base[used_bytes()];
     own_ = true;
     memset(bits_, 0, used_bytes());
   }
template<typename bit_base > size_t jubatus::core::table::bit_vector_base< bit_base >::bit_count () const inline
Definition at line 261 of file bit_vector.hpp.
References jubatus::core::table::detail::bitcount(), jubatus::core::table::bit_vector_base< bit_base >::bits_, and jubatus::core::table::bit_vector_base< bit_base >::used_bytes().
Referenced by jubatus::core::table::bit_vector_base< bit_base >::calc_hamming_distance(), and jubatus::core::table::bit_vector_base< bit_base >::is_empty().
{
     if (bits_ == NULL) {
       return 0;
     }
     size_t result = 0;
     for (int64_t i = (used_bytes() / sizeof(bit_base)) - 1; i >= 0; --i) {
       result += detail::bitcount(bits_[i]);
     }
     return result;
   }
template<typename bit_base > size_t jubatus::core::table::bit_vector_base< bit_base >::bit_num () const inline
Definition at line 297 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bit_num_.
Referenced by jubatus::core::table::bit_vector_base< bit_base >::calc_hamming_distance(), jubatus::core::table::bit_vector_base< bit_base >::calc_hamming_similarity(), jubatus::core::table::typed_column< bit_vector >::check_bit_vector_(), and jubatus::core::table::bit_vector_base< bit_base >::msgpack_unpack().
{
     return bit_num_;
   }
template<typename bit_base > uint64_t jubatus::core::table::bit_vector_base< bit_base >::calc_hamming_distance (const bit_vector_base< bit_base > & bv) const inline
Definition at line 241 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bit_count(), jubatus::core::table::bit_vector_base< bit_base >::bit_num(), jubatus::core::table::detail::bitcount(), jubatus::core::table::bit_vector_base< bit_base >::bits_, jubatus::core::table::bit_vector_base< bit_base >::is_empty(), and jubatus::core::table::bit_vector_base< bit_base >::used_bytes().
Referenced by jubatus::core::table::bit_vector_base< bit_base >::calc_hamming_similarity().
{
     if (bit_num() != bv.bit_num()) {
       throw bit_vector_unmatch_exception(
           "calc_hamming_similarity(): bit_vector length unmatch! " +
           jubatus::util::lang::lexical_cast<std::string>(bit_num()) + " with " +
           jubatus::util::lang::lexical_cast<std::string>(bv.bit_num()));
     }
     if (is_empty() && bv.is_empty()) {
       return 0;
     } else if (is_empty()) {
       return bv.bit_count();
     } else if (bv.is_empty()) {
       return bit_count();
     }
     size_t match_num = 0;
     for (size_t i = 0; i < used_bytes() / sizeof(bit_base); ++i) {
       match_num += detail::bitcount(bits_[i] ^ bv.bits_[i]);
     }
     return match_num;
   }
template<typename bit_base > uint64_t jubatus::core::table::bit_vector_base< bit_base >::calc_hamming_similarity (const bit_vector_base< bit_base > & bv) const inline
Definition at line 238 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bit_num(), and jubatus::core::table::bit_vector_base< bit_base >::calc_hamming_distance().
{
     return bit_num() - calc_hamming_distance(bv);
   }
template<typename bit_base > void jubatus::core::table::bit_vector_base< bit_base >::clear () inline
Definition at line 233 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bit_num_, and jubatus::core::table::bit_vector_base< bit_base >::clear_bit().
                {
     for (size_t i = 0; i < bit_num_; ++i) {
       clear_bit(i);
     }
   }
template<typename bit_base > void jubatus::core::table::bit_vector_base< bit_base >::clear_bit (size_t pos) inline
Definition at line 190 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::BASE_BITS, and jubatus::core::table::bit_vector_base< bit_base >::bits_.
Referenced by jubatus::core::table::bit_vector_base< bit_base >::clear().
{
     if (bits_ == NULL) {
       return;
     }
     bits_[pos / BASE_BITS] &= ~(1LLU << (pos % BASE_BITS));
   }
template<typename bit_base > void jubatus::core::table::bit_vector_base< bit_base >::debug_print (std::ostream & os) const inline
Definition at line 307 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bits_, and jubatus::core::table::bit_vector_base< bit_base >::used_bytes().
{
     if (bits_ == NULL) {
       os << "(unallocated)";
       return;
     }
     for (uint64_t i = 0; i < used_bytes() * 8; ++i) {
       if ((bits_[i / (sizeof(bit_base) * 8)] >> (i % (sizeof(bit_base) * 8))) &
           1LLU) {
         os << "1";
       } else {
         os << "0";
       }
     }
   }
template<typename bit_base > void jubatus::core::table::bit_vector_base< bit_base >::duplicate (const bit_vector_base< bit_base > & orig) inline private
Definition at line 399 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::alloc_memory(), jubatus::core::table::bit_vector_base< bit_base >::bit_num_, jubatus::core::table::bit_vector_base< bit_base >::bits_, jubatus::core::table::bit_vector_base< bit_base >::own_, and jubatus::core::table::bit_vector_base< bit_base >::used_bytes().
{
     if (bit_num_ != orig.bit_num_) {
       throw bit_vector_unmatch_exception(
           "failed copy bit vector from " +
           jubatus::util::lang::lexical_cast<std::string>(orig.bit_num_) +
           " to " +
           jubatus::util::lang::lexical_cast<std::string>(bit_num_));
     }
     if (!own_) {
       alloc_memory();
     }
     memcpy(bits_, orig.bits_, used_bytes());
   }
template<typename bit_base > bool jubatus::core::table::bit_vector_base< bit_base >::get_bit (size_t pos) const inline
Definition at line 223 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::BASE_BITS, and jubatus::core::table::bit_vector_base< bit_base >::bits_.
{
     if (bits_ == NULL) {
       return false;
     }
     return bits_[pos / BASE_BITS] & (1LLU << (pos % BASE_BITS));
   }
template<typename bit_base > bool jubatus::core::table::bit_vector_base< bit_base >::is_empty () const inline
Definition at line 229 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bit_count().
Referenced by jubatus::core::table::bit_vector_base< bit_base >::calc_hamming_distance(), and jubatus::core::table::bit_vector_base< bit_base >::operator==().
{
     return bit_count() == 0;
   }
template<typename bit_base > static size_t jubatus::core::table::bit_vector_base< bit_base >::memory_size (size_t bit_width) inline static
Definition at line 303 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::BLOCKSIZE.
Referenced by jubatus::core::table::typed_column< bit_vector >::bytes_per_value_(), jubatus::core::table::bit_vector_base< bit_base >::msgpack_unpack(), jubatus::core::table::column_type::size(), and jubatus::core::table::bit_vector_base< bit_base >::used_bytes().
{
     return ((((bit_width + 7) / 8) + BLOCKSIZE - 1) / BLOCKSIZE) * BLOCKSIZE;
   }
template<typename bit_base > template<typename Buffer > void jubatus::core::table::bit_vector_base< bit_base >::msgpack_pack (msgpack::packer< Buffer > & packer) const inline
Definition at line 339 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bit_num_, jubatus::core::table::bit_vector_base< bit_base >::bits_, jubatus::core::table::bit_vector_base< bit_base >::BLOCKSIZE, jubatus::core::table::bit_vector_base< bit_base >::used_bytes(), and jubatus::core::common::write_big_endian().
{
     packer.pack_array(2);
     packer.pack(static_cast<uint64_t>(bit_num_));
     packer.pack_raw(used_bytes());
     if (bits_) {
       const size_t n = used_bytes() / BLOCKSIZE;
       for (size_t i = 0; i < n; ++i) {
         char buf[BLOCKSIZE];
         common::write_big_endian(bits_[i], buf);
         packer.pack_raw_body(buf, BLOCKSIZE);
       }
     } else {
       const char c = 0;
       for (size_t i = 0; i < used_bytes(); ++i) {
         packer.pack_raw_body(&c, 1);
       }
     }
   }
template<typename bit_base > void jubatus::core::table::bit_vector_base< bit_base >::msgpack_unpack (msgpack::object o) inline
Definition at line 357 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bit_num(), jubatus::core::table::bit_vector_base< bit_base >::bit_num_, jubatus::core::table::bit_vector_base< bit_base >::bit_vector_base(), jubatus::core::table::bit_vector_base< bit_base >::bits_, jubatus::core::table::bit_vector_base< bit_base >::BLOCKSIZE, JUBATUS_ASSERT, jubatus::core::table::bit_vector_base< bit_base >::memory_size(), objs, and jubatus::core::table::bit_vector_base< bit_base >::own_.
{
     if (o.type != msgpack::type::ARRAY || o.via.array.size != 2) {
       throw msgpack::type_error();  // like MSGPACK_DEFINE
     }
     const msgpack::object* objs = o.via.array.ptr;
     const uint64_t bit_num = objs[0].as<uint64_t>();
     const msgpack::type::raw_ref data = objs[1].as<msgpack::type::raw_ref>();
     if (data.size != memory_size(bit_num)) {
       throw bit_vector_unmatch_exception(
           "msgpack_unpack(): invalid length of packed data: "
           "expected: " +
           jubatus::util::lang::lexical_cast<std::string>(bit_num_) +
           ", got: " +
           jubatus::util::lang::lexical_cast<std::string>(data.size));
     }
     std::vector<bit_base> buf;
     for (size_t i = 0; i < data.size; i += BLOCKSIZE) {
       buf.push_back(common::read_big_endian<bit_base>(&data.ptr[i]));
     }
     bit_vector_base(&buf[0], bit_num).swap(*this);
     JUBATUS_ASSERT(own_ || bits_ == NULL);
   }
template<typename bit_base > bool jubatus::core::table::bit_vector_base< bit_base >::operator!= (const bit_vector_base< bit_base > & rhs) const inline
Definition at line 150 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::operator==().
{
     return !this->operator==(rhs);
   }
template<typename bit_base > bit_vector_base& jubatus::core::table::bit_vector_base< bit_base >::operator= (const bit_vector_base< bit_base > & orig) inline
Definition at line 155 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::alloc_memory(), jubatus::core::table::bit_vector_base< bit_base >::bit_num_, jubatus::core::table::bit_vector_base< bit_base >::bits_, and jubatus::core::table::bit_vector_base< bit_base >::used_bytes().
{
     if (&orig != this) {
       if (bit_num_ != orig.bit_num_) {
         throw bit_vector_unmatch_exception(
             "failed copy bit vector from " +
             jubatus::util::lang::lexical_cast<std::string>(orig.bit_num_) +
             " to " +
             jubatus::util::lang::lexical_cast<std::string>(bit_num_));
       }
       if (bits_ == NULL) {
         alloc_memory();
       }
       if (orig.bits_ == NULL) {
         memset(bits_, 0, used_bytes());
       } else {
         memcpy(bits_, orig.bits_, used_bytes());
       }
     }
     return *this;
   }
template<typename bit_base > bool jubatus::core::table::bit_vector_base< bit_base >::operator== (const bit_vector_base< bit_base > & rhs) const inline
Definition at line 135 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bit_num_, jubatus::core::table::bit_vector_base< bit_base >::bits_, jubatus::core::table::bit_vector_base< bit_base >::is_empty(), and jubatus::core::table::bit_vector_base< bit_base >::used_bytes().
Referenced by jubatus::core::table::bit_vector_base< bit_base >::operator!=().
{
     if (bit_num_ != rhs.bit_num_) {
       return false;
     }
     if (is_empty() && rhs.is_empty()) {
       return true;
     }
     if (is_empty() && !rhs.is_empty()) {
       return false;
     }
     if (!is_empty() && rhs.is_empty()) {
       return false;
     }
     return memcmp(bits_, rhs.bits_, used_bytes()) == 0;
   }
template<typename bit_base > template<typename packable > void jubatus::core::table::bit_vector_base< bit_base >::pack (packable & buffer) const inline
Definition at line 335 of file bit_vector.hpp.
{
     msgpack::pack(buffer, *this);
   }
template<typename bit_base > static uint64_t jubatus::core::table::bit_vector_base< bit_base >::pop_count (uint64_t r) inline static
Definition at line 271 of file bit_vector.hpp.
{
     r = (r & 0x5555555555555555ULL) +
       ((r >> 1) & 0x5555555555555555ULL);
     r = (r & 0x3333333333333333ULL) +
       ((r >> 2) & 0x3333333333333333ULL);
     r = (r + (r >> 4)) & 0x0f0f0f0f0f0f0f0fULL;
     r = r + (r >>  8);
     r = r + (r >> 16);
     r = r + (r >> 32);
     return static_cast<uint64_t>(r & 0x7f);
   }
template<typename bit_base > static size_t jubatus::core::table::bit_vector_base< bit_base >::pop_count (uint8_t r) inline static
Definition at line 282 of file bit_vector.hpp.
{
     r = (r & 0x55U) +
       ((r >> 1) & 0x55U);
     r = (r & 0x33U) +
       ((r >> 2) & 0x33U);
     r = (r + (r >> 4)) & 0x0fU;
     return static_cast<size_t>(r & 0x7f);
   }
template<typename bit_base > bit_base* jubatus::core::table::bit_vector_base< bit_base >::raw_data_unsafe () inline
Definition at line 291 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bits_.
Referenced by jubatus::core::table::typed_column< bit_vector >::insert(), jubatus::core::table::typed_column< bit_vector >::push_back(), and jubatus::core::table::typed_column< bit_vector >::update().
{
     return bits_;
   }
template<typename bit_base > const bit_base* jubatus::core::table::bit_vector_base< bit_base >::raw_data_unsafe () const inline
Definition at line 294 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bits_.
{
     return bits_;
   }
template<typename bit_base > bool jubatus::core::table::bit_vector_base< bit_base >::release () inline private
Definition at line 388 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bits_, and jubatus::core::table::bit_vector_base< bit_base >::own_.
Referenced by jubatus::core::table::bit_vector_base< bit_base >::~bit_vector_base().
                  {
     if (bits_ && own_) {
       delete[] bits_;
       own_ = false;
       bits_ = NULL;
       return true;
     }
     return false;
   }
template<typename bit_base > void jubatus::core::table::bit_vector_base< bit_base >::reverse_bit (size_t pos) inline
Definition at line 209 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::alloc_memory(), jubatus::core::table::bit_vector_base< bit_base >::BASE_BITS, jubatus::core::table::bit_vector_base< bit_base >::bit_num_, and jubatus::core::table::bit_vector_base< bit_base >::bits_.
{
     if (bits_ == NULL) {
       alloc_memory();
     }
     if (bit_num_ < pos) {
       throw bit_vector_unmatch_exception(
           "reverse_bit(): invalid posison " +
           jubatus::util::lang::lexical_cast<std::string>(pos) +
           " for length: " +
           jubatus::util::lang::lexical_cast<std::string>(bit_num_));
     }
     bits_[pos / BASE_BITS] ^= (1LLU << (pos % BASE_BITS));
   }
template<typename bit_base > void jubatus::core::table::bit_vector_base< bit_base >::set_bit (size_t pos) inline
Definition at line 196 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::alloc_memory(), jubatus::core::table::bit_vector_base< bit_base >::BASE_BITS, jubatus::core::table::bit_vector_base< bit_base >::bit_num_, and jubatus::core::table::bit_vector_base< bit_base >::bits_.
{
     if (bits_ == NULL) {
       alloc_memory();
     }
     if (static_cast<size_t>(bit_num_) < pos) {
       throw bit_vector_unmatch_exception(
           "set_bit(): invalid posison " +
           jubatus::util::lang::lexical_cast<std::string>(pos) +
           " for length: " +
           jubatus::util::lang::lexical_cast<std::string>(bit_num_));
     }
     bits_[pos / BASE_BITS] |= (1LLU << (pos % BASE_BITS));
   }
template<typename bit_base > void jubatus::core::table::bit_vector_base< bit_base >::status (std::ostream & os) const inline
Definition at line 325 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bits_, and jubatus::core::table::bit_vector_base< bit_base >::own_.
{
     os << "status():";
     if (bits_ == NULL) {
       os << "(unallocated)" << " owns_" << own_;
       return;
     }
     os << (own_ ? "[own]" : "[other]") << std::endl;
   }
template<typename bit_base > void jubatus::core::table::bit_vector_base< bit_base >::swap (bit_vector_base< bit_base > & x) inline
Definition at line 175 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bit_num_, jubatus::core::table::bit_vector_base< bit_base >::bits_, jubatus::core::table::bit_vector_base< bit_base >::own_, and jubatus::core::clustering::swap().
{
     if (bit_num_ != x.bit_num_) {
       throw bit_vector_unmatch_exception(
           "failed to swap bit vectors " +
           jubatus::util::lang::lexical_cast<std::string>(bit_num_) + " and " +
           jubatus::util::lang::lexical_cast<std::string>(x.bit_num_));
     }
     using std::swap;
     swap(bits_, x.bits_);
     swap(own_, x.own_);
   }
template<typename bit_base > size_t jubatus::core::table::bit_vector_base< bit_base >::used_bytes () const inline
Definition at line 300 of file bit_vector.hpp.
References jubatus::core::table::bit_vector_base< bit_base >::bit_num_, and jubatus::core::table::bit_vector_base< bit_base >::memory_size().
Referenced by jubatus::core::table::bit_vector_base< bit_base >::alloc_memory(), jubatus::core::table::bit_vector_base< bit_base >::bit_count(), jubatus::core::table::bit_vector_base< bit_base >::bit_vector_base(), jubatus::core::table::bit_vector_base< bit_base >::calc_hamming_distance(), jubatus::core::table::bit_vector_base< bit_base >::debug_print(), jubatus::core::table::bit_vector_base< bit_base >::duplicate(), jubatus::core::table::bit_vector_base< bit_base >::msgpack_pack(), jubatus::core::table::bit_vector_base< bit_base >::operator=(), and jubatus::core::table::bit_vector_base< bit_base >::operator==().
{
     return memory_size(bit_num_);
   }
Friends And Related Function Documentation
template<typename bit_base > std::ostream& operator<< (std::ostream & os, const bit_vector_base< bit_base > & bv) friend
Definition at line 321 of file bit_vector.hpp.
{
     bv.debug_print(os);
     return os;
   }
template<typename bit_base > void swap (bit_vector_base< bit_base > & l, bit_vector_base< bit_base > & r) friend
Definition at line 186 of file bit_vector.hpp.
{
     l.swap(r);
   }
Member Data Documentation
template<typename bit_base > const size_t jubatus::core::table::bit_vector_base< bit_base >::BASE_BITS = sizeof(bit_base) * 8 static
Definition at line 101 of file bit_vector.hpp.
Referenced by jubatus::core::table::bit_vector_base< bit_base >::clear_bit(), jubatus::core::table::bit_vector_base< bit_base >::get_bit(), jubatus::core::table::bit_vector_base< bit_base >::reverse_bit(), and jubatus::core::table::bit_vector_base< bit_base >::set_bit().
template<typename bit_base > const size_t jubatus::core::table::bit_vector_base< bit_base >::bit_num_ private
Definition at line 414 of file bit_vector.hpp.
Referenced by jubatus::core::table::bit_vector_base< bit_base >::bit_num(), jubatus::core::table::bit_vector_base< bit_base >::clear(), jubatus::core::table::bit_vector_base< bit_base >::duplicate(), jubatus::core::table::bit_vector_base< bit_base >::msgpack_pack(), jubatus::core::table::bit_vector_base< bit_base >::msgpack_unpack(), jubatus::core::table::bit_vector_base< bit_base >::operator=(), jubatus::core::table::bit_vector_base< bit_base >::operator==(), jubatus::core::table::bit_vector_base< bit_base >::reverse_bit(), jubatus::core::table::bit_vector_base< bit_base >::set_bit(), jubatus::core::table::bit_vector_base< bit_base >::swap(), and jubatus::core::table::bit_vector_base< bit_base >::used_bytes().
template<typename bit_base > bit_base* jubatus::core::table::bit_vector_base< bit_base >::bits_ private
Definition at line 413 of file bit_vector.hpp.
Referenced by jubatus::core::table::bit_vector_base< bit_base >::alloc_memory(), jubatus::core::table::bit_vector_base< bit_base >::bit_count(), jubatus::core::table::bit_vector_base< bit_base >::bit_vector_base(), jubatus::core::table::bit_vector_base< bit_base >::calc_hamming_distance(), jubatus::core::table::bit_vector_base< bit_base >::clear_bit(), jubatus::core::table::bit_vector_base< bit_base >::debug_print(), jubatus::core::table::bit_vector_base< bit_base >::duplicate(), jubatus::core::table::bit_vector_base< bit_base >::get_bit(), jubatus::core::table::bit_vector_base< bit_base >::msgpack_pack(), jubatus::core::table::bit_vector_base< bit_base >::msgpack_unpack(), jubatus::core::table::bit_vector_base< bit_base >::operator=(), jubatus::core::table::bit_vector_base< bit_base >::operator==(), jubatus::core::table::bit_vector_base< bit_base >::raw_data_unsafe(), jubatus::core::table::bit_vector_base< bit_base >::release(), jubatus::core::table::bit_vector_base< bit_base >::reverse_bit(), jubatus::core::table::bit_vector_base< bit_base >::set_bit(), jubatus::core::table::bit_vector_base< bit_base >::status(), jubatus::core::table::bit_vector_base< bit_base >::swap(), and jubatus::core::table::bit_vector_base< bit_base >::~bit_vector_base().
template<typename bit_base > const size_t jubatus::core::table::bit_vector_base< bit_base >::BLOCKSIZE = sizeof(bit_base) static
Definition at line 102 of file bit_vector.hpp.
Referenced by jubatus::core::table::bit_vector_base< bit_base >::memory_size(), jubatus::core::table::bit_vector_base< bit_base >::msgpack_pack(), and jubatus::core::table::bit_vector_base< bit_base >::msgpack_unpack().
template<typename bit_base > bool jubatus::core::table::bit_vector_base< bit_base >::own_ private
Definition at line 415 of file bit_vector.hpp.
Referenced by jubatus::core::table::bit_vector_base< bit_base >::alloc_memory(), jubatus::core::table::bit_vector_base< bit_base >::duplicate(), jubatus::core::table::bit_vector_base< bit_base >::msgpack_unpack(), jubatus::core::table::bit_vector_base< bit_base >::release(), jubatus::core::table::bit_vector_base< bit_base >::status(), jubatus::core::table::bit_vector_base< bit_base >::swap(), and jubatus::core::table::bit_vector_base< bit_base >::~bit_vector_base().
The documentation for this struct was generated from the following file:
jubatus/core/table/column/bit_vector.hpp