var searchData=
[
  ['bad_5fstorage_5ftype',['bad_storage_type',['../classjubatus_1_1core_1_1common_1_1bad__storage__type.html',1,'jubatus::core::common']]],
  ['bandit',['bandit',['../classjubatus_1_1core_1_1driver_1_1bandit.html',1,'jubatus::core::driver']]],
  ['bandit_5fbase',['bandit_base',['../classjubatus_1_1core_1_1bandit_1_1bandit__base.html',1,'jubatus::core::bandit']]],
  ['bandit_5ffactory',['bandit_factory',['../classjubatus_1_1core_1_1bandit_1_1bandit__factory.html',1,'jubatus::core::bandit']]],
  ['basic_5fwindow',['basic_window',['../classjubatus_1_1core_1_1burst_1_1basic__window.html',1,'jubatus::core::burst']]],
  ['basic_5fwindow_3c_20batch_5finput_20_3e',['basic_window&lt; batch_input &gt;',['../classjubatus_1_1core_1_1burst_1_1basic__window.html',1,'jubatus::core::burst']]],
  ['basic_5fwindow_3c_20batch_5fresult_20_3e',['basic_window&lt; batch_result &gt;',['../classjubatus_1_1core_1_1burst_1_1basic__window.html',1,'jubatus::core::burst']]],
  ['batch_5finput',['batch_input',['../structjubatus_1_1core_1_1burst_1_1batch__input.html',1,'jubatus::core::burst']]],
  ['batch_5fresult',['batch_result',['../structjubatus_1_1core_1_1burst_1_1batch__result.html',1,'jubatus::core::burst']]],
  ['binary_5ffeature',['binary_feature',['../classjubatus_1_1core_1_1fv__converter_1_1binary__feature.html',1,'jubatus::core::fv_converter']]],
  ['binary_5ffeature_5ffactory',['binary_feature_factory',['../classjubatus_1_1core_1_1fv__converter_1_1binary__feature__factory.html',1,'jubatus::core::fv_converter']]],
  ['binary_5ffeature_5frule',['binary_feature_rule',['../structjubatus_1_1core_1_1fv__converter_1_1datum__to__fv__converter__impl_1_1binary__feature__rule.html',1,'jubatus::core::fv_converter::datum_to_fv_converter_impl']]],
  ['binary_5frule',['binary_rule',['../structjubatus_1_1core_1_1fv__converter_1_1binary__rule.html',1,'jubatus::core::fv_converter']]],
  ['bit_5findex_5fstorage',['bit_index_storage',['../classjubatus_1_1core_1_1storage_1_1bit__index__storage.html',1,'jubatus::core::storage']]],
  ['bit_5fvector_5fbase',['bit_vector_base',['../classjubatus_1_1core_1_1storage_1_1bit__vector__base.html',1,'jubatus::core::storage']]],
  ['bit_5fvector_5fbase_3c_20uint64_5ft_20_3e',['bit_vector_base&lt; uint64_t &gt;',['../classjubatus_1_1core_1_1storage_1_1bit__vector__base.html',1,'jubatus::core::storage']]],
  ['bit_5fvector_5fnearest_5fneighbor_5fbase',['bit_vector_nearest_neighbor_base',['../classjubatus_1_1core_1_1nearest__neighbor_1_1bit__vector__nearest__neighbor__base.html',1,'jubatus::core::nearest_neighbor']]],
  ['bit_5fvector_5funmatch_5fexception',['bit_vector_unmatch_exception',['../classjubatus_1_1core_1_1storage_1_1bit__vector__unmatch__exception.html',1,'jubatus::core::storage']]],
  ['bitcount_5fimpl',['bitcount_impl',['../structjubatus_1_1core_1_1storage_1_1detail_1_1bitcount__impl.html',1,'jubatus::core::storage::detail']]],
  ['bitcount_5fimpl_3c_20t_2c_201_20_3e',['bitcount_impl&lt; T, 1 &gt;',['../structjubatus_1_1core_1_1storage_1_1detail_1_1bitcount__impl_3_01_t_00_011_01_4.html',1,'jubatus::core::storage::detail']]],
  ['bitcount_5fimpl_3c_20t_2c_202_20_3e',['bitcount_impl&lt; T, 2 &gt;',['../structjubatus_1_1core_1_1storage_1_1detail_1_1bitcount__impl_3_01_t_00_012_01_4.html',1,'jubatus::core::storage::detail']]],
  ['bitcount_5fimpl_3c_20t_2c_204_20_3e',['bitcount_impl&lt; T, 4 &gt;',['../structjubatus_1_1core_1_1storage_1_1detail_1_1bitcount__impl_3_01_t_00_014_01_4.html',1,'jubatus::core::storage::detail']]],
  ['bitcount_5fimpl_3c_20t_2c_208_20_3e',['bitcount_impl&lt; T, 8 &gt;',['../structjubatus_1_1core_1_1storage_1_1detail_1_1bitcount__impl_3_01_t_00_018_01_4.html',1,'jubatus::core::storage::detail']]],
  ['burst',['burst',['../classjubatus_1_1core_1_1driver_1_1burst.html',1,'jubatus::core::driver']]],
  ['burst',['burst',['../classjubatus_1_1core_1_1burst_1_1burst.html',1,'jubatus::core::burst']]],
  ['burst_5foptions',['burst_options',['../structjubatus_1_1core_1_1burst_1_1burst__options.html',1,'jubatus::core::burst']]],
  ['burst_5fresult',['burst_result',['../classjubatus_1_1core_1_1burst_1_1burst__result.html',1,'jubatus::core::burst']]],
  ['byte_5fbuffer',['byte_buffer',['../classjubatus_1_1core_1_1common_1_1byte__buffer.html',1,'jubatus::core::common']]]
];
