var searchData=
[
  ['random_5funlearner',['random_unlearner',['../classjubatus_1_1core_1_1unlearner_1_1random__unlearner.html',1,'jubatus::core::unlearner']]],
  ['recommender',['recommender',['../classjubatus_1_1core_1_1driver_1_1recommender.html',1,'jubatus::core::driver']]],
  ['recommender_5fbase',['recommender_base',['../classjubatus_1_1core_1_1recommender_1_1recommender__base.html',1,'jubatus::core::recommender']]],
  ['recommender_5ffactory',['recommender_factory',['../classjubatus_1_1core_1_1recommender_1_1recommender__factory.html',1,'jubatus::core::recommender']]],
  ['recommender_5fmock',['recommender_mock',['../classjubatus_1_1core_1_1recommender_1_1recommender__mock.html',1,'jubatus::core::recommender']]],
  ['recommender_5fmock_5fstorage',['recommender_mock_storage',['../classjubatus_1_1core_1_1recommender_1_1recommender__mock__storage.html',1,'jubatus::core::recommender']]],
  ['recommender_5fstorage_5fbase',['recommender_storage_base',['../classjubatus_1_1core_1_1storage_1_1recommender__storage__base.html',1,'jubatus::core::storage']]],
  ['redundant_5fkey',['redundant_key',['../classjubatus_1_1core_1_1common_1_1jsonconfig_1_1redundant__key.html',1,'jubatus::core::common::jsonconfig']]],
  ['regexp_5ffilter',['regexp_filter',['../classjubatus_1_1core_1_1fv__converter_1_1regexp__filter.html',1,'jubatus::core::fv_converter']]],
  ['regexp_5fmatch',['regexp_match',['../classjubatus_1_1core_1_1fv__converter_1_1regexp__match.html',1,'jubatus::core::fv_converter']]],
  ['regexp_5fsplitter',['regexp_splitter',['../classjubatus_1_1core_1_1fv__converter_1_1regexp__splitter.html',1,'jubatus::core::fv_converter']]],
  ['regression',['regression',['../classjubatus_1_1core_1_1driver_1_1regression.html',1,'jubatus::core::driver']]],
  ['regression_5fbase',['regression_base',['../classjubatus_1_1core_1_1regression_1_1regression__base.html',1,'jubatus::core::regression']]],
  ['regression_5ffactory',['regression_factory',['../classjubatus_1_1core_1_1regression_1_1regression__factory.html',1,'jubatus::core::regression']]],
  ['result_5fstorage',['result_storage',['../classjubatus_1_1core_1_1burst_1_1result__storage.html',1,'jubatus::core::burst']]],
  ['result_5fwindow',['result_window',['../classjubatus_1_1core_1_1burst_1_1result__window.html',1,'jubatus::core::burst']]],
  ['row_5fdeleter',['row_deleter',['../classjubatus_1_1core_1_1storage_1_1row__deleter.html',1,'jubatus::core::storage']]],
  ['runtime_5ferror',['runtime_error',['../classjubatus_1_1core_1_1common_1_1exception_1_1runtime__error.html',1,'jubatus::core::common::exception']]]
];
